/* Generated by opensource COBOL 4J 1.1.16 */
import java.io.UnsupportedEncodingException;
import jp.osscons.opensourcecobol.libcobj.*;
import jp.osscons.opensourcecobol.libcobj.common.*;
import jp.osscons.opensourcecobol.libcobj.data.*;
import jp.osscons.opensourcecobol.libcobj.exceptions.*;
import jp.osscons.opensourcecobol.libcobj.termio.*;
import jp.osscons.opensourcecobol.libcobj.call.*;
import jp.osscons.opensourcecobol.libcobj.file.*;
import jp.osscons.opensourcecobol.libcobj.ui.*;
import java.util.Optional;

public class ABC_099_C implements CobolRunnable {

  private boolean initialized = false;
  private CobolModule module;
  private int entry;

  private CobolRunnable cob_unifunc;


  @Override
  public int run(CobolDataStorage... argStorages) {
    return ABC_099_C_(0, argStorages);
  }

  @Override
  public void cancel() {
    ABC_099_C_(-1);
  }

  @Override
  public boolean isActive() {
    return false;
  }

  public CobolResultSet execute () {
    int returnCode = run_module(0);
    return new CobolResultSet(returnCode);
  }

  public int ABC_099_C_ (int entry, CobolDataStorage ...argStorages) {
    this.entry = entry;
    return this.run_module(entry);
  }

  int run_module (int entry) {
    this.module = new CobolModule(null, null, null, null, 0, '.', '$', ',', 1, 1, 1, 0, null );

    /* Start of function code */

    /* CANCEL callback handling */
    if (entry < 0) {
    	if (!this.initialized) {
    		CobolDecimal.cobInitNumeric();
    		return 0;
    	}
    	d0.clear();
    	d0.setScale(0);
    	d1.clear();
    	d1.setScale(0);
    	this.initialized = false;
    	return 0;
    }

    /* Push module stack */
    CobolModule.push (module);
    CobolResolve.pushCallStackList ("ABC_099_C");

    /* Initialize program */
    if (!this.initialized) {
      module.setProgramId("ABC_099_C");

      /* Initialize decimal numbers */
      d0.decimalInit();
      d1.decimalInit();

      b_RETURN_CODE.set((int)0);
      b_N.fillBytes('0', 6);
      b_ans.fillBytes(' ', 6);
      f_ZS.moveFrom (CobolConstant.zero);
      b_DUMMY.setByte(' ');
      b_i.fillBytes(0, 4);
      b_r.setByte('0');
      b_sumr.fillBytes('0', 7);
      b_t.fillBytes('0', 6);
      b_res.fillBytes('0', 6);
      this.initialized = true;
    }
    /* PROCEDURE DIVISION */
    try{
      /* Entry dispatch */
      execEntry(l_ABC_099_C);

    } catch(CobolStopRunException e) {
      CobolStopRunException.stopRun();
      System.exit(e.getReturnCode());
    }
    /* Pop module stack */
    CobolResolve.popCallStackList();
    CobolModule.pop();

    /* Program return */
    return b_RETURN_CODE.intValue();
  }
  public CobolControl[] contList = {
    new CobolControl(0, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_ABC_099_C]);
      }
    },
    /* Entry ABC_099_C */
    new CobolControl(l_ABC_099_C, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN]);
      }
    },
    /* MAIN SECTION */
    new CobolControl(l_MAIN, CobolControl.LabelType.section) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION__DEFAULT_PARAGRAPH]);
      }
    },
    /* MAIN_SECTION__DEFAULT_PARAGRAPH */
    new CobolControl(l_MAIN_SECTION__DEFAULT_PARAGRAPH, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* /content/temp_cobol/ABC_099_C_fixed.cob:20: ACCEPT */
        {
          CobolTerminal.accept (f_N);
        }
        /* /content/temp_cobol/ABC_099_C_fixed.cob:22: MOVE */
        {
          b_res.setBytes (b_N, 6);
        }
        /* /content/temp_cobol/ABC_099_C_fixed.cob:24: PERFORM */
        b_i.setSwpU32Binary (1);
        for(;;b_i.addSwpU32Binary (1))
        {
          if (((long)f_N.cmpInteger ((int)(b_i.bswap_32())) <  0L))
            break;
          {
            /* /content/temp_cobol/ABC_099_C_fixed.cob:26: MOVE */
            {
              f_t.moveFrom (f_i);
            }
            /* /content/temp_cobol/ABC_099_C_fixed.cob:27: MOVE */
            {
              b_sumr.fillBytes (48, 7);
            }
            /* /content/temp_cobol/ABC_099_C_fixed.cob:29: PERFORM */
            for (;;)
            {
              if (((long)b_t.cmpNumdisp (6, 0) <= 0L))
                break;
              {
                /* /content/temp_cobol/ABC_099_C_fixed.cob:30: DIVIDE */
                {
                  f_t.divQuotient (c_1_6, f_t, 4);
                  f_r.divRemainder (4);
                }
                /* /content/temp_cobol/ABC_099_C_fixed.cob:31: ADD */
                {
                  f_sumr.add (f_r, 4);
                }
              }
            }
            /* /content/temp_cobol/ABC_099_C_fixed.cob:34: SUBTRACT */
            {
              {
                {
                  d0.set (b_N.getNumdisp(6));
                  d1.set ((int)(b_i.bswap_32()));
                  d0.sub (d1);
                  d0.getField (f_t, 4);
                }
              }
            }
            /* /content/temp_cobol/ABC_099_C_fixed.cob:36: PERFORM */
            for (;;)
            {
              if (((long)b_t.cmpNumdisp (6, 0) <= 0L))
                break;
              {
                /* /content/temp_cobol/ABC_099_C_fixed.cob:37: DIVIDE */
                {
                  f_t.divQuotient (c_2_9, f_t, 4);
                  f_r.divRemainder (4);
                }
                /* /content/temp_cobol/ABC_099_C_fixed.cob:38: ADD */
                {
                  f_sumr.add (f_r, 4);
                }
              }
            }
            /* /content/temp_cobol/ABC_099_C_fixed.cob:41: COMPUTE */
            {
              {
                {
                  d0.setField (CobolIntrinsic.funcMin (2, f_res, f_sumr));
                  d0.getField (f_res, 4);
                }
              }
            }
          }
        }
        /* /content/temp_cobol/ABC_099_C_fixed.cob:45: MOVE */
        {
          f_ZS.moveFrom (f_res);
        }
        /* /content/temp_cobol/ABC_099_C_fixed.cob:47: PERFORM */
        /* PERFORM UNANS */
        CobolControl.perform(contList, l_UNANS).run();
        /* /content/temp_cobol/ABC_099_C_fixed.cob:49: DISPLAY */
        {
          CobolTerminal.display (0, 1, 1, CobolFieldFactory.makeCobolField(CobolIntrinsic.funcStoredCharLength (f_ans).getInt(), b_ans.getSubDataStorage(0), a_6_Alphanumeric));
        }
        /* /content/temp_cobol/ABC_099_C_fixed.cob:50: STOP */
        {
          CobolStopRunException.throwException (b_RETURN_CODE.intValue());
        }

        return Optional.of(contList[l_UNANS]);
      }
    },
    /* UNANS SECTION */
    new CobolControl(l_UNANS, CobolControl.LabelType.section) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_UNANS_SECTION__DEFAULT_PARAGRAPH]);
      }
    },
    /* UNANS_SECTION__DEFAULT_PARAGRAPH */
    new CobolControl(l_UNANS_SECTION__DEFAULT_PARAGRAPH, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* /content/temp_cobol/ABC_099_C_fixed.cob:53: UNSTRING */
        {
          CobolString.unstringInit (f_ZS, 0, 1);
          CobolString.unstringDelimited (CobolConstant.space, 1);
          CobolString.unstringInto (f_DUMMY, 0, 0);
          CobolString.unstringInto (f_ans, 0, 0);
          CobolString.unstringFinish ();
        }
        return Optional.of(CobolControl.pure());
      }
    },
    CobolControl.pure()
  };
  public void execEntry(int start) throws CobolRuntimeException, CobolStopRunException {
    Optional<CobolControl> nextLabel = Optional.of(contList[start]);
    while(nextLabel.isPresent()) {
      CobolControl section = nextLabel.get();
      nextLabel = section.run();
    }
  }

  public static void main(String[] args)
  {
    CobolUtil.cob_init(args, false);
    CobolDecimal.cobInitNumeric();
    new ABC_099_C().ABC_099_C_(0);
    CobolStopRunException.stopRun();
  }

  public ABC_099_C()
  {
    init();
  }

  public void init() 
  {
    /* Decimal structures */

    d0 = new CobolDecimal();
    d1 = new CobolDecimal();

    /* Data storage */

    cob_unifunc = null;

    /* PROGRAM-ID : ABC_099_C */
    b_RETURN_CODE = new CobolDataStorage(4);	/* RETURN-CODE */
    b_N = new CobolDataStorage(6);	/* N */
    b_ans = new CobolDataStorage(6);	/* ans */
    b_ZS = new CobolDataStorage(7);	/* ZS */
    b_DUMMY = new CobolDataStorage(1);	/* DUMMY */
    b_i = new CobolDataStorage(4);	/* i */
    b_r = new CobolDataStorage(1);	/* r */
    b_sumr = new CobolDataStorage(7);	/* sumr */
    b_t = new CobolDataStorage(6);	/* t */
    b_res = new CobolDataStorage(6);	/* res */

    /* End of data storage */


    initAttr();

    /* Fields */

    /* PROGRAM-ID : ABC_099_C */
    f_N	= CobolFieldFactory.makeCobolField(6, b_N, a_2_NumericDisplay_Digits6_Scale0);	/* N */
    f_ans	= CobolFieldFactory.makeCobolField(6, b_ans, a_6_Alphanumeric);	/* ans */
    f_ZS	= CobolFieldFactory.makeCobolField(7, b_ZS, a_1_NumericEdited_Digits7_Scale0);	/* ZS */
    f_DUMMY	= CobolFieldFactory.makeCobolField(1, b_DUMMY, a_6_Alphanumeric);	/* DUMMY */
    f_i	= CobolFieldFactory.makeCobolField(4, b_i, a_3_NumericBinary_Digits6_Scale0_BinarySwap);	/* i */
    f_r	= CobolFieldFactory.makeCobolField(1, b_r, a_4_NumericDisplay_Digits1_Scale0);	/* r */
    f_sumr	= CobolFieldFactory.makeCobolField(7, b_sumr, a_5_NumericDisplay_Digits7_Scale0);	/* sumr */
    f_t	= CobolFieldFactory.makeCobolField(6, b_t, a_2_NumericDisplay_Digits6_Scale0);	/* t */
    f_res	= CobolFieldFactory.makeCobolField(6, b_res, a_2_NumericDisplay_Digits6_Scale0);	/* res */

    /* End of fields */


    /* Constants */

    c_1_6	= CobolFieldFactory.makeCobolField(1, "6", a_4_NumericDisplay_Digits1_Scale0);
    c_2_9	= CobolFieldFactory.makeCobolField(1, "9", a_4_NumericDisplay_Digits1_Scale0);

  }

  private void initAttr() {
    /* Attributes */

    a_1_NumericEdited_Digits7_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_EDITED,
      /* digits= */ 7,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ "Z\007\000\000\000");
    a_2_NumericDisplay_Digits6_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 6,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_3_NumericBinary_Digits6_Scale0_BinarySwap = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_BINARY,
      /* digits= */ 6,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_BINARY_SWAP,
      /* pic= */ null);
    a_4_NumericDisplay_Digits1_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 1,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_5_NumericDisplay_Digits7_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 7,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_6_Alphanumeric = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_ALPHANUMERIC,
      /* digits= */ 0,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);

  }

  /* Decimal structures */

  private CobolDecimal d0;
  private CobolDecimal d1;

  /* Data storage */

  /* PROGRAM-ID : ABC_099_C */
  public CobolDataStorage b_RETURN_CODE;	/* RETURN-CODE */
  private CobolDataStorage b_N;	/* N */
  private CobolDataStorage b_ans;	/* ans */
  private CobolDataStorage b_ZS;	/* ZS */
  private CobolDataStorage b_DUMMY;	/* DUMMY */
  private CobolDataStorage b_i;	/* i */
  private CobolDataStorage b_r;	/* r */
  private CobolDataStorage b_sumr;	/* sumr */
  private CobolDataStorage b_t;	/* t */
  private CobolDataStorage b_res;	/* res */

  /* End of data storage */


  /* Fields */

  /* PROGRAM-ID : ABC_099_C */
  private AbstractCobolField f_N;	/* N */
  private AbstractCobolField f_ans;	/* ans */
  private AbstractCobolField f_ZS;	/* ZS */
  private AbstractCobolField f_DUMMY;	/* DUMMY */
  private AbstractCobolField f_i;	/* i */
  private AbstractCobolField f_r;	/* r */
  private AbstractCobolField f_sumr;	/* sumr */
  private AbstractCobolField f_t;	/* t */
  private AbstractCobolField f_res;	/* res */

  /* End of fields */


  private static AbstractCobolField f_native;

  /* Constants */

  private AbstractCobolField c_2_9;
  private AbstractCobolField c_1_6;

  /* Attributes */

  private CobolFieldAttribute a_6_Alphanumeric;
  private CobolFieldAttribute a_5_NumericDisplay_Digits7_Scale0;
  private CobolFieldAttribute a_4_NumericDisplay_Digits1_Scale0;
  private CobolFieldAttribute a_3_NumericBinary_Digits6_Scale0_BinarySwap;
  private CobolFieldAttribute a_2_NumericDisplay_Digits6_Scale0;
  private CobolFieldAttribute a_1_NumericEdited_Digits7_Scale0;




  /* Sections and Labels */
  private final static int l_ABC_099_C = 1;
  private final static int l_MAIN = 2;
  private final static int l_MAIN_SECTION__DEFAULT_PARAGRAPH = 3;
  private final static int l_UNANS = 4;
  private final static int l_UNANS_SECTION__DEFAULT_PARAGRAPH = 5;
  private final static int l_Default_Error_Handler = 6;

}
