/* Generated by opensource COBOL 4J 1.1.16 */
import java.io.UnsupportedEncodingException;
import jp.osscons.opensourcecobol.libcobj.*;
import jp.osscons.opensourcecobol.libcobj.common.*;
import jp.osscons.opensourcecobol.libcobj.data.*;
import jp.osscons.opensourcecobol.libcobj.exceptions.*;
import jp.osscons.opensourcecobol.libcobj.termio.*;
import jp.osscons.opensourcecobol.libcobj.call.*;
import jp.osscons.opensourcecobol.libcobj.file.*;
import jp.osscons.opensourcecobol.libcobj.ui.*;
import java.util.Optional;

public class PROGRAM_ID implements CobolRunnable {

  private boolean initialized = false;
  private CobolModule module;
  private int entry;

  private CobolRunnable cob_unifunc;


  @Override
  public int run(CobolDataStorage... argStorages) {
    return PROGRAM_ID_(0, argStorages);
  }

  @Override
  public void cancel() {
    PROGRAM_ID_(-1);
  }

  @Override
  public boolean isActive() {
    return false;
  }

  public CobolResultSet execute () {
    int returnCode = run_module(0);
    return new CobolResultSet(returnCode);
  }

  public int PROGRAM_ID_ (int entry, CobolDataStorage ...argStorages) {
    this.entry = entry;
    return this.run_module(entry);
  }

  int run_module (int entry) {
    this.module = new CobolModule(null, null, null, null, 0, '.', '$', ',', 1, 1, 1, 0, null );

    /* Start of function code */

    /* CANCEL callback handling */
    if (entry < 0) {
    	if (!this.initialized) {
    		CobolDecimal.cobInitNumeric();
    		return 0;
    	}
    	d0.clear();
    	d0.setScale(0);
    	d1.clear();
    	d1.setScale(0);
    	d2.clear();
    	d2.setScale(0);
    	d3.clear();
    	d3.setScale(0);
    	this.initialized = false;
    	return 0;
    }

    /* Push module stack */
    CobolModule.push (module);
    CobolResolve.pushCallStackList ("PROGRAM_ID");

    /* Initialize program */
    if (!this.initialized) {
      module.setProgramId("PROGRAM_ID");

      /* Initialize decimal numbers */
      d0.decimalInit();
      d1.decimalInit();
      d2.decimalInit();
      d3.decimalInit();

      b_RETURN_CODE.set((int)0);
      b_ln.fillBytes(' ', 15);
      b_A.fillBytes('0', 10);
      b_B.fillBytes('0', 10);
      b_C.fillBytes('0', 10);
      b_D.fillBytes('0', 10);
      b_TK.fillBytes('0', 10);
      b_AO.fillBytes('0', 10);
      this.initialized = true;
    }
    /* PROCEDURE DIVISION */
    try{
      /* Entry dispatch */
      execEntry(l_PROGRAM_ID);

    } catch(CobolStopRunException e) {
      CobolStopRunException.stopRun();
      System.exit(e.getReturnCode());
    }
    /* Pop module stack */
    CobolResolve.popCallStackList();
    CobolModule.pop();

    /* Program return */
    return b_RETURN_CODE.intValue();
  }
  public CobolControl[] contList = {
    new CobolControl(0, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_PROGRAM_ID]);
      }
    },
    /* Entry PROGRAM_ID */
    new CobolControl(l_PROGRAM_ID, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN]);
      }
    },
    /* MAIN SECTION */
    new CobolControl(l_MAIN, CobolControl.LabelType.section) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION__DEFAULT_PARAGRAPH]);
      }
    },
    /* MAIN_SECTION__DEFAULT_PARAGRAPH */
    new CobolControl(l_MAIN_SECTION__DEFAULT_PARAGRAPH, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* /content/temp_cobol/PROGRAM_ID_fixed.cob:15: ACCEPT */
        {
          CobolTerminal.accept (f_ln);
        }
        /* /content/temp_cobol/PROGRAM_ID_fixed.cob:16: UNSTRING */
        {
          CobolString.unstringInit (f_ln, 0, 1);
          CobolString.unstringDelimited (CobolConstant.space, 0);
          CobolString.unstringInto (f_A, 0, 0);
          CobolString.unstringInto (f_B, 0, 0);
          CobolString.unstringInto (f_C, 0, 0);
          CobolString.unstringInto (f_D, 0, 0);
          CobolString.unstringFinish ();
        }
        /* /content/temp_cobol/PROGRAM_ID_fixed.cob:17: COMPUTE */
        {
          {
            {
              d0.setField (f_C);
              d3.setField (f_B);
              d0.add (d3);
              d2.set (1);
              d0.sub (d2);
              d1.setField (f_B);
              d0.div (d1);
              d0.getField (f_TK, 4);
            }
          }
        }
        /* /content/temp_cobol/PROGRAM_ID_fixed.cob:18: COMPUTE */
        {
          {
            {
              d0.setField (f_A);
              d3.setField (f_D);
              d0.add (d3);
              d2.set (1);
              d0.sub (d2);
              d1.setField (f_D);
              d0.div (d1);
              d0.getField (f_AO, 4);
            }
          }
        }
        /* /content/temp_cobol/PROGRAM_ID_fixed.cob:19: IF */
        {
          if (((long)b_TK.memcmp (b_AO, 10) <= 0L))
            {
              /* /content/temp_cobol/PROGRAM_ID_fixed.cob:20: DISPLAY */
              {
                CobolTerminal.display (0, 1, 1, c_1_Yes);
              }
            }
          else
            {
              /* /content/temp_cobol/PROGRAM_ID_fixed.cob:22: DISPLAY */
              {
                CobolTerminal.display (0, 1, 1, c_2_No);
              }
            }
        }
        /* /content/temp_cobol/PROGRAM_ID_fixed.cob:24: STOP */
        {
          CobolStopRunException.throwException (b_RETURN_CODE.intValue());
        }
        return Optional.of(CobolControl.pure());
      }
    },
    CobolControl.pure()
  };
  public void execEntry(int start) throws CobolRuntimeException, CobolStopRunException {
    Optional<CobolControl> nextLabel = Optional.of(contList[start]);
    while(nextLabel.isPresent()) {
      CobolControl section = nextLabel.get();
      nextLabel = section.run();
    }
  }

  public static void main(String[] args)
  {
    CobolUtil.cob_init(args, false);
    CobolDecimal.cobInitNumeric();
    new PROGRAM_ID().PROGRAM_ID_(0);
    CobolStopRunException.stopRun();
  }

  public PROGRAM_ID()
  {
    init();
  }

  public void init() 
  {
    /* Decimal structures */

    d0 = new CobolDecimal();
    d1 = new CobolDecimal();
    d2 = new CobolDecimal();
    d3 = new CobolDecimal();

    /* Data storage */

    cob_unifunc = null;

    /* PROGRAM-ID : PROGRAM_ID */
    b_RETURN_CODE = new CobolDataStorage(4);	/* RETURN-CODE */
    b_ln = new CobolDataStorage(15);	/* ln */
    b_A = new CobolDataStorage(10);	/* A */
    b_B = new CobolDataStorage(10);	/* B */
    b_C = new CobolDataStorage(10);	/* C */
    b_D = new CobolDataStorage(10);	/* D */
    b_TK = new CobolDataStorage(10);	/* TK */
    b_AO = new CobolDataStorage(10);	/* AO */

    /* End of data storage */


    initAttr();

    /* Fields */

    /* PROGRAM-ID : PROGRAM_ID */
    f_ln	= CobolFieldFactory.makeCobolField(15, b_ln, a_1_Alphanumeric);	/* ln */
    f_A	= CobolFieldFactory.makeCobolField(10, b_A, a_2_NumericDisplay_Digits10_Scale0);	/* A */
    f_B	= CobolFieldFactory.makeCobolField(10, b_B, a_2_NumericDisplay_Digits10_Scale0);	/* B */
    f_C	= CobolFieldFactory.makeCobolField(10, b_C, a_2_NumericDisplay_Digits10_Scale0);	/* C */
    f_D	= CobolFieldFactory.makeCobolField(10, b_D, a_2_NumericDisplay_Digits10_Scale0);	/* D */
    f_TK	= CobolFieldFactory.makeCobolField(10, b_TK, a_2_NumericDisplay_Digits10_Scale0);	/* TK */
    f_AO	= CobolFieldFactory.makeCobolField(10, b_AO, a_2_NumericDisplay_Digits10_Scale0);	/* AO */

    /* End of fields */


    /* Constants */

    c_1_Yes	= CobolFieldFactory.makeCobolField(str_0_Yes, a_1_Alphanumeric);
    c_2_No	= CobolFieldFactory.makeCobolField(str_1_No, a_1_Alphanumeric);

  }

  private void initAttr() {
    /* Attributes */

    a_1_Alphanumeric = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_ALPHANUMERIC,
      /* digits= */ 0,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_2_NumericDisplay_Digits10_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 10,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);

  }

  /* Decimal structures */

  private CobolDecimal d0;
  private CobolDecimal d1;
  private CobolDecimal d2;
  private CobolDecimal d3;

  /* Data storage */

  /* PROGRAM-ID : PROGRAM_ID */
  public CobolDataStorage b_RETURN_CODE;	/* RETURN-CODE */
  private CobolDataStorage b_ln;	/* ln */
  private CobolDataStorage b_A;	/* A */
  private CobolDataStorage b_B;	/* B */
  private CobolDataStorage b_C;	/* C */
  private CobolDataStorage b_D;	/* D */
  private CobolDataStorage b_TK;	/* TK */
  private CobolDataStorage b_AO;	/* AO */

  /* End of data storage */


  /* Fields */

  /* PROGRAM-ID : PROGRAM_ID */
  private AbstractCobolField f_ln;	/* ln */
  private AbstractCobolField f_A;	/* A */
  private AbstractCobolField f_B;	/* B */
  private AbstractCobolField f_C;	/* C */
  private AbstractCobolField f_D;	/* D */
  private AbstractCobolField f_TK;	/* TK */
  private AbstractCobolField f_AO;	/* AO */

  /* End of fields */


  private static AbstractCobolField f_native;

  /* Constants */

  private AbstractCobolField c_2_No;
  private AbstractCobolField c_1_Yes;

  /* Attributes */

  private CobolFieldAttribute a_2_NumericDisplay_Digits10_Scale0;
  private CobolFieldAttribute a_1_Alphanumeric;



  /* String literals */
  public static final byte[] str_1_No = CobolUtil.stringToBytes("No");
  public static final byte[] str_0_Yes = CobolUtil.stringToBytes("Yes");

  /* Sections and Labels */
  private final static int l_PROGRAM_ID = 1;
  private final static int l_MAIN = 2;
  private final static int l_MAIN_SECTION__DEFAULT_PARAGRAPH = 3;
  private final static int l_Default_Error_Handler = 4;

}
