/* Generated by opensource COBOL 4J 1.1.16 */
import java.io.UnsupportedEncodingException;
import jp.osscons.opensourcecobol.libcobj.*;
import jp.osscons.opensourcecobol.libcobj.common.*;
import jp.osscons.opensourcecobol.libcobj.data.*;
import jp.osscons.opensourcecobol.libcobj.exceptions.*;
import jp.osscons.opensourcecobol.libcobj.termio.*;
import jp.osscons.opensourcecobol.libcobj.call.*;
import jp.osscons.opensourcecobol.libcobj.file.*;
import jp.osscons.opensourcecobol.libcobj.ui.*;
import java.util.Optional;

public class _3158A implements CobolRunnable {

  private boolean initialized = false;
  private CobolModule module;
  private int entry;

  private CobolRunnable cob_unifunc;


  @Override
  public int run(CobolDataStorage... argStorages) {
    return _3158A_(0, argStorages);
  }

  @Override
  public void cancel() {
    _3158A_(-1);
  }

  @Override
  public boolean isActive() {
    return false;
  }

  public CobolResultSet execute () {
    int returnCode = run_module(0);
    return new CobolResultSet(returnCode);
  }

  public int _3158A_ (int entry, CobolDataStorage ...argStorages) {
    this.entry = entry;
    return this.run_module(entry);
  }

  int run_module (int entry) {
    this.module = new CobolModule(null, null, null, null, 0, '.', '$', ',', 1, 1, 1, 0, null );

    /* Start of function code */

    /* CANCEL callback handling */
    if (entry < 0) {
    	if (!this.initialized) {
    		CobolDecimal.cobInitNumeric();
    		return 0;
    	}
    	this.initialized = false;
    	return 0;
    }

    /* Push module stack */
    CobolModule.push (module);
    CobolResolve.pushCallStackList ("_3158A");

    /* Initialize program */
    if (!this.initialized) {
      module.setProgramId("_3158A");

      b_RETURN_CODE.set((int)0);
      b_INP.fillBytes(' ', 3);
      this.initialized = true;
    }
    /* PROCEDURE DIVISION */
    try{
      /* Entry dispatch */
      execEntry(l__3158A);

    } catch(CobolStopRunException e) {
      CobolStopRunException.stopRun();
      System.exit(e.getReturnCode());
    }
    /* Pop module stack */
    CobolResolve.popCallStackList();
    CobolModule.pop();

    /* Program return */
    return b_RETURN_CODE.intValue();
  }
  public CobolControl[] contList = {
    new CobolControl(0, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l__3158A]);
      }
    },
    /* Entry 158A */
    new CobolControl(l__3158A, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION]);
      }
    },
    /* MAIN SECTION */
    new CobolControl(l_MAIN_SECTION, CobolControl.LabelType.section) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION__MAIN_001]);
      }
    },
    /* MAIN-001 */
    new CobolControl(l_MAIN_SECTION__MAIN_001, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* /content/temp_cobol/158A_fixed.cob:13: ACCEPT */
        {
          CobolTerminal.accept (f_INP);
        }
        /* /content/temp_cobol/158A_fixed.cob:15: IF */
        {
          if ((((long)(Byte.toUnsignedInt(b_S1__INP.getByte(0)) - Byte.toUnsignedInt(b_S2__INP.getByte(0))) == 0L) && ((long)(Byte.toUnsignedInt(b_S1__INP.getByte(0)) - Byte.toUnsignedInt(b_S3__INP.getByte(0))) == 0L)))
            {
              /* /content/temp_cobol/158A_fixed.cob:16: DISPLAY */
              {
                CobolTerminal.display (0, 1, 1, c_1_No);
              }
            }
          else
            {
              /* /content/temp_cobol/158A_fixed.cob:18: DISPLAY */
              {
                CobolTerminal.display (0, 1, 1, c_2_Yes);
              }
            }
        }

        return Optional.of(contList[l_MAIN_SECTION__MAIN_EXIT]);
      }
    },
    /* MAIN-EXIT */
    new CobolControl(l_MAIN_SECTION__MAIN_EXIT, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* /content/temp_cobol/158A_fixed.cob:21: STOP */
        {
          CobolStopRunException.throwException (b_RETURN_CODE.intValue());
        }
        return Optional.of(CobolControl.pure());
      }
    },
    CobolControl.pure()
  };
  public void execEntry(int start) throws CobolRuntimeException, CobolStopRunException {
    Optional<CobolControl> nextLabel = Optional.of(contList[start]);
    while(nextLabel.isPresent()) {
      CobolControl section = nextLabel.get();
      nextLabel = section.run();
    }
  }

  public static void main(String[] args)
  {
    CobolUtil.cob_init(args, false);
    CobolDecimal.cobInitNumeric();
    new _3158A()._3158A_(0);
    CobolStopRunException.stopRun();
  }

  public _3158A()
  {
    init();
  }

  public void init() 
  {
    /* Data storage */

    cob_unifunc = null;

    /* PROGRAM-ID : 158A */
    b_RETURN_CODE = new CobolDataStorage(4);	/* RETURN-CODE */
    b_INP = new CobolDataStorage(3);	/* INP */
    b_S1__INP = b_INP;
    b_S2__INP = b_INP.getSubDataStorage(1);
    b_S3__INP = b_INP.getSubDataStorage(2);

    /* End of data storage */


    initAttr();

    /* Fields */

    /* PROGRAM-ID : 158A */
    f_INP	= CobolFieldFactory.makeCobolField(3, b_INP, a_1_Group);	/* INP */

    /* End of fields */


    /* Constants */

    c_1_No	= CobolFieldFactory.makeCobolField(str_0_No, a_2_Alphanumeric);
    c_2_Yes	= CobolFieldFactory.makeCobolField(str_1_Yes, a_2_Alphanumeric);

  }

  private void initAttr() {
    /* Attributes */

    a_1_Group = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_GROUP,
      /* digits= */ 0,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_2_Alphanumeric = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_ALPHANUMERIC,
      /* digits= */ 0,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);

  }

  /* Data storage */

  /* PROGRAM-ID : 158A */
  public CobolDataStorage b_RETURN_CODE;	/* RETURN-CODE */
  private CobolDataStorage b_INP;	/* INP */
  private CobolDataStorage b_S1__INP;
  private CobolDataStorage b_S2__INP;
  private CobolDataStorage b_S3__INP;

  /* End of data storage */


  /* Fields */

  /* PROGRAM-ID : 158A */
  private AbstractCobolField f_INP;	/* INP */

  /* End of fields */


  private static AbstractCobolField f_native;

  /* Constants */

  private AbstractCobolField c_2_Yes;
  private AbstractCobolField c_1_No;

  /* Attributes */

  private CobolFieldAttribute a_2_Alphanumeric;
  private CobolFieldAttribute a_1_Group;



  /* String literals */
  public static final byte[] str_1_Yes = CobolUtil.stringToBytes("Yes");
  public static final byte[] str_0_No = CobolUtil.stringToBytes("No");

  /* Sections and Labels */
  private final static int l__3158A = 1;
  private final static int l_MAIN_SECTION = 2;
  private final static int l_MAIN_SECTION__MAIN_001 = 3;
  private final static int l_MAIN_SECTION__MAIN_EXIT = 4;
  private final static int l_Default_Error_Handler = 5;

}
