/* Generated by opensource COBOL 4J 1.1.16 */
import java.io.UnsupportedEncodingException;
import jp.osscons.opensourcecobol.libcobj.*;
import jp.osscons.opensourcecobol.libcobj.common.*;
import jp.osscons.opensourcecobol.libcobj.data.*;
import jp.osscons.opensourcecobol.libcobj.exceptions.*;
import jp.osscons.opensourcecobol.libcobj.termio.*;
import jp.osscons.opensourcecobol.libcobj.call.*;
import jp.osscons.opensourcecobol.libcobj.file.*;
import jp.osscons.opensourcecobol.libcobj.ui.*;
import java.util.Optional;

public class _3154B implements CobolRunnable {

  private boolean initialized = false;
  private CobolModule module;
  private int entry;

  private CobolRunnable cob_unifunc;


  @Override
  public int run(CobolDataStorage... argStorages) {
    return _3154B_(0, argStorages);
  }

  @Override
  public void cancel() {
    _3154B_(-1);
  }

  @Override
  public boolean isActive() {
    return false;
  }

  public CobolResultSet execute () {
    int returnCode = run_module(0);
    return new CobolResultSet(returnCode);
  }

  public int _3154B_ (int entry, CobolDataStorage ...argStorages) {
    this.entry = entry;
    return this.run_module(entry);
  }

  int run_module (int entry) {
    this.module = new CobolModule(null, null, null, null, 0, '.', '$', ',', 1, 1, 1, 0, null );

    /* Start of function code */

    /* CANCEL callback handling */
    if (entry < 0) {
    	if (!this.initialized) {
    		CobolDecimal.cobInitNumeric();
    		return 0;
    	}
    	this.initialized = false;
    	return 0;
    }

    /* Push module stack */
    CobolModule.push (module);
    CobolResolve.pushCallStackList ("_3154B");

    /* Initialize program */
    if (!this.initialized) {
      module.setProgramId("_3154B");

      b_RETURN_CODE.set((int)0);
      b_INP.fillBytes(' ', 100);
      b_S.fillBytes(' ', 100);
      b_CNT.fillBytes('0', 3);
      b_I.fillBytes('0', 3);
      this.initialized = true;
    }
    /* PROCEDURE DIVISION */
    try{
      /* Entry dispatch */
      execEntry(l__3154B);

    } catch(CobolStopRunException e) {
      CobolStopRunException.stopRun();
      System.exit(e.getReturnCode());
    }
    /* Pop module stack */
    CobolResolve.popCallStackList();
    CobolModule.pop();

    /* Program return */
    return b_RETURN_CODE.intValue();
  }
  public CobolControl[] contList = {
    new CobolControl(0, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l__3154B]);
      }
    },
    /* Entry 154B */
    new CobolControl(l__3154B, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN]);
      }
    },
    /* MAIN SECTION */
    new CobolControl(l_MAIN, CobolControl.LabelType.section) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION__DEFAULT_PARAGRAPH]);
      }
    },
    /* MAIN_SECTION__DEFAULT_PARAGRAPH */
    new CobolControl(l_MAIN_SECTION__DEFAULT_PARAGRAPH, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* /content/temp_cobol/154B_fixed.cob:11: ACCEPT */
        {
          CobolTerminal.accept (f_INP);
        }
        /* /content/temp_cobol/154B_fixed.cob:12: UNSTRING */
        {
          CobolString.unstringInit (f_INP, 0, 1);
          CobolString.unstringDelimited (c_1, 0);
          CobolString.unstringInto (f_S, 0, f_CNT);
          CobolString.unstringFinish ();
        }
        /* /content/temp_cobol/154B_fixed.cob:14: MOVE */
        {
          CobolFieldFactory.makeCobolField(b_CNT.getNumdisp(3), b_S.getSubDataStorage(0), a_1_Alphanumeric).moveFrom (c_2_x);
        }
        /* /content/temp_cobol/154B_fixed.cob:15: DISPLAY */
        {
          CobolTerminal.display (0, 1, 1, CobolFieldFactory.makeCobolField(b_CNT.getNumdisp(3), b_S.getSubDataStorage(0), a_1_Alphanumeric));
        }
        /* /content/temp_cobol/154B_fixed.cob:17: STOP */
        {
          CobolStopRunException.throwException (b_RETURN_CODE.intValue());
        }
        return Optional.of(CobolControl.pure());
      }
    },
    CobolControl.pure()
  };
  public void execEntry(int start) throws CobolRuntimeException, CobolStopRunException {
    Optional<CobolControl> nextLabel = Optional.of(contList[start]);
    while(nextLabel.isPresent()) {
      CobolControl section = nextLabel.get();
      nextLabel = section.run();
    }
  }

  public static void main(String[] args)
  {
    CobolUtil.cob_init(args, false);
    CobolDecimal.cobInitNumeric();
    new _3154B()._3154B_(0);
    CobolStopRunException.stopRun();
  }

  public _3154B()
  {
    init();
  }

  public void init() 
  {
    /* Data storage */

    cob_unifunc = null;

    /* PROGRAM-ID : 154B */
    b_RETURN_CODE = new CobolDataStorage(4);	/* RETURN-CODE */
    b_INP = new CobolDataStorage(100);	/* INP */
    b_S = new CobolDataStorage(100);	/* S */
    b_CNT = new CobolDataStorage(3);	/* CNT */
    b_I = new CobolDataStorage(3);	/* I */

    /* End of data storage */


    initAttr();

    /* Fields */

    /* PROGRAM-ID : 154B */
    f_INP	= CobolFieldFactory.makeCobolField(100, b_INP, a_1_Alphanumeric);	/* INP */
    f_S	= CobolFieldFactory.makeCobolField(100, b_S, a_1_Alphanumeric);	/* S */
    f_CNT	= CobolFieldFactory.makeCobolField(3, b_CNT, a_2_NumericDisplay_Digits3_Scale0);	/* CNT */

    /* End of fields */


    /* Constants */

    c_1	= CobolFieldFactory.makeCobolField(str_0, a_1_Alphanumeric);
    c_2_x	= CobolFieldFactory.makeCobolField(str_1_x, a_3_AlphanumericAll);

  }

  private void initAttr() {
    /* Attributes */

    a_1_Alphanumeric = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_ALPHANUMERIC,
      /* digits= */ 0,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_2_NumericDisplay_Digits3_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 3,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_3_AlphanumericAll = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_ALPHANUMERIC_ALL,
      /* digits= */ 0,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);

  }

  /* Data storage */

  /* PROGRAM-ID : 154B */
  public CobolDataStorage b_RETURN_CODE;	/* RETURN-CODE */
  private CobolDataStorage b_INP;	/* INP */
  private CobolDataStorage b_S;	/* S */
  private CobolDataStorage b_CNT;	/* CNT */
  private CobolDataStorage b_I;	/* I */

  /* End of data storage */


  /* Fields */

  /* PROGRAM-ID : 154B */
  private AbstractCobolField f_INP;	/* INP */
  private AbstractCobolField f_S;	/* S */
  private AbstractCobolField f_CNT;	/* CNT */

  /* End of fields */


  private static AbstractCobolField f_native;

  /* Constants */

  private AbstractCobolField c_2_x;
  private AbstractCobolField c_1;

  /* Attributes */

  private CobolFieldAttribute a_3_AlphanumericAll;
  private CobolFieldAttribute a_2_NumericDisplay_Digits3_Scale0;
  private CobolFieldAttribute a_1_Alphanumeric;



  /* String literals */
  public static final byte[] str_1_x = CobolUtil.stringToBytes("x");
  public static final byte[] str_0 = CobolUtil.stringToBytes(" ");

  /* Sections and Labels */
  private final static int l__3154B = 1;
  private final static int l_MAIN = 2;
  private final static int l_MAIN_SECTION__DEFAULT_PARAGRAPH = 3;
  private final static int l_Default_Error_Handler = 4;

}
