/* Generated by opensource COBOL 4J 1.1.16 */
import java.io.UnsupportedEncodingException;
import jp.osscons.opensourcecobol.libcobj.*;
import jp.osscons.opensourcecobol.libcobj.common.*;
import jp.osscons.opensourcecobol.libcobj.data.*;
import jp.osscons.opensourcecobol.libcobj.exceptions.*;
import jp.osscons.opensourcecobol.libcobj.termio.*;
import jp.osscons.opensourcecobol.libcobj.call.*;
import jp.osscons.opensourcecobol.libcobj.file.*;
import jp.osscons.opensourcecobol.libcobj.ui.*;
import java.util.Optional;

public class PROGRAM_ID implements CobolRunnable {

  private boolean initialized = false;
  private CobolModule module;
  private int entry;

  private CobolRunnable cob_unifunc;


  @Override
  public int run(CobolDataStorage... argStorages) {
    return PROGRAM_ID_(0, argStorages);
  }

  @Override
  public void cancel() {
    PROGRAM_ID_(-1);
  }

  @Override
  public boolean isActive() {
    return false;
  }

  public CobolResultSet execute () {
    int returnCode = run_module(0);
    return new CobolResultSet(returnCode);
  }

  public int PROGRAM_ID_ (int entry, CobolDataStorage ...argStorages) {
    this.entry = entry;
    return this.run_module(entry);
  }

  int run_module (int entry) {
    this.module = new CobolModule(null, null, null, null, 0, '.', '$', ',', 1, 1, 1, 0, null );

    /* Start of function code */

    /* CANCEL callback handling */
    if (entry < 0) {
    	if (!this.initialized) {
    		CobolDecimal.cobInitNumeric();
    		return 0;
    	}
    	d0.clear();
    	d0.setScale(0);
    	d1.clear();
    	d1.setScale(0);
    	this.initialized = false;
    	return 0;
    }

    /* Push module stack */
    CobolModule.push (module);
    CobolResolve.pushCallStackList ("PROGRAM_ID");

    /* Initialize program */
    if (!this.initialized) {
      module.setProgramId("PROGRAM_ID");

      /* Initialize decimal numbers */
      d0.decimalInit();
      d1.decimalInit();

      b_RETURN_CODE.set((int)0);
      b_S.fillBytes(' ', 100);
      b_X.fillBytes(' ', 100);
      b_cur.fillBytes(' ', 100);
      b_pre.fillBytes(' ', 100);
      b_n.fillBytes('0', 10);
      b_m.fillBytes('0', 10);
      b_i.fillBytes('0', 10);
      this.initialized = true;
    }
    /* PROCEDURE DIVISION */
    try{
      /* Entry dispatch */
      execEntry(l_PROGRAM_ID);

    } catch(CobolStopRunException e) {
      CobolStopRunException.stopRun();
      System.exit(e.getReturnCode());
    }
    /* Pop module stack */
    CobolResolve.popCallStackList();
    CobolModule.pop();

    /* Program return */
    return b_RETURN_CODE.intValue();
  }
  public CobolControl[] contList = {
    new CobolControl(0, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_PROGRAM_ID]);
      }
    },
    /* Entry PROGRAM_ID */
    new CobolControl(l_PROGRAM_ID, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN]);
      }
    },
    /* MAIN SECTION */
    new CobolControl(l_MAIN, CobolControl.LabelType.section) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION__DEFAULT_PARAGRAPH]);
      }
    },
    /* MAIN_SECTION__DEFAULT_PARAGRAPH */
    new CobolControl(l_MAIN_SECTION__DEFAULT_PARAGRAPH, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* /content/temp_cobol/PROGRAM_ID_fixed.cob:16: ACCEPT */
        {
          CobolTerminal.accept (f_S);
        }
        /* /content/temp_cobol/PROGRAM_ID_fixed.cob:17: COMPUTE */
        {
          {
            {
              d0.setField (CobolIntrinsic.funcStoredCharLength (f_S));
              d0.getField (f_n, 4);
            }
          }
        }
        /* /content/temp_cobol/PROGRAM_ID_fixed.cob:18: MOVE */
        {
          b_m.setBytes (b_n, 10);
        }
        /* /content/temp_cobol/PROGRAM_ID_fixed.cob:19: PERFORM */
        /* PERFORM REVERSESTR */
        CobolControl.perform(contList, l_REVERSESTR).run();
        /* /content/temp_cobol/PROGRAM_ID_fixed.cob:20: IF */
        {
          if (((long)b_S.memcmp (b_cur, 100) == 0L))
            {
              /* /content/temp_cobol/PROGRAM_ID_fixed.cob:21: MOVE */
              {
                b_cur.fillBytes (32, 100);
              }
              /* /content/temp_cobol/PROGRAM_ID_fixed.cob:22: DIVIDE */
              {
                {
                  {
                    d0.setField (f_n);
                    d1.set (2);
                    d0.div (d1);
                    d0.getField (f_m, 4);
                  }
                }
              }
              /* /content/temp_cobol/PROGRAM_ID_fixed.cob:23: MOVE */
              {
                f_X.moveFrom (CobolFieldFactory.makeCobolField(f_m.getInt(), b_S.getSubDataStorage(0), a_1_Alphanumeric));
              }
              /* /content/temp_cobol/PROGRAM_ID_fixed.cob:24: PERFORM */
              /* PERFORM REVERSESTR */
              CobolControl.perform(contList, l_REVERSESTR).run();
              /* /content/temp_cobol/PROGRAM_ID_fixed.cob:25: IF */
              {
                if (((long)b_X.memcmp (b_cur, 100) == 0L))
                  {
                    /* /content/temp_cobol/PROGRAM_ID_fixed.cob:26: DISPLAY */
                    {
                      CobolTerminal.display (0, 1, 1, c_1_Yes);
                    }
                  }
                else
                  {
                    /* /content/temp_cobol/PROGRAM_ID_fixed.cob:28: DISPLAY */
                    {
                      CobolTerminal.display (0, 1, 1, c_2_No);
                    }
                  }
              }
            }
          else
            {
              /* /content/temp_cobol/PROGRAM_ID_fixed.cob:31: DISPLAY */
              {
                CobolTerminal.display (0, 1, 1, c_2_No);
              }
            }
        }
        /* /content/temp_cobol/PROGRAM_ID_fixed.cob:33: STOP */
        {
          CobolStopRunException.throwException (b_RETURN_CODE.intValue());
        }

        return Optional.of(contList[l_REVERSESTR]);
      }
    },
    /* REVERSESTR SECTION */
    new CobolControl(l_REVERSESTR, CobolControl.LabelType.section) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_REVERSESTR_SECTION__DEFAULT_PARAGRAPH]);
      }
    },
    /* REVERSESTR_SECTION__DEFAULT_PARAGRAPH */
    new CobolControl(l_REVERSESTR_SECTION__DEFAULT_PARAGRAPH, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* /content/temp_cobol/PROGRAM_ID_fixed.cob:36: PERFORM */
        b_i.setBytes (str_0_0000000001, 10);
        for(;;f_i.addInt (1))
        {
          if (((long)b_m.memcmp (b_i, 10) <  0L))
            break;
          {
            /* /content/temp_cobol/PROGRAM_ID_fixed.cob:37: MOVE */
            {
              b_cur.getSubDataStorage((f_i.getInt() - 1)).setByte(b_S.getSubDataStorage((((f_m.getInt() - f_i.getInt()) + 1) - 1)).getByte(0));
            }
          }
        }
        return Optional.of(CobolControl.pure());
      }
    },
    CobolControl.pure()
  };
  public void execEntry(int start) throws CobolRuntimeException, CobolStopRunException {
    Optional<CobolControl> nextLabel = Optional.of(contList[start]);
    while(nextLabel.isPresent()) {
      CobolControl section = nextLabel.get();
      nextLabel = section.run();
    }
  }

  public static void main(String[] args)
  {
    CobolUtil.cob_init(args, false);
    CobolDecimal.cobInitNumeric();
    new PROGRAM_ID().PROGRAM_ID_(0);
    CobolStopRunException.stopRun();
  }

  public PROGRAM_ID()
  {
    init();
  }

  public void init() 
  {
    /* Decimal structures */

    d0 = new CobolDecimal();
    d1 = new CobolDecimal();

    /* Data storage */

    cob_unifunc = null;

    /* PROGRAM-ID : PROGRAM_ID */
    b_RETURN_CODE = new CobolDataStorage(4);	/* RETURN-CODE */
    b_S = new CobolDataStorage(100);	/* S */
    b_X = new CobolDataStorage(100);	/* X */
    b_cur = new CobolDataStorage(100);	/* cur */
    b_pre = new CobolDataStorage(100);	/* pre */
    b_n = new CobolDataStorage(10);	/* n */
    b_m = new CobolDataStorage(10);	/* m */
    b_i = new CobolDataStorage(10);	/* i */

    /* End of data storage */


    initAttr();

    /* Fields */

    /* PROGRAM-ID : PROGRAM_ID */
    f_S	= CobolFieldFactory.makeCobolField(100, b_S, a_1_Alphanumeric);	/* S */
    f_X	= CobolFieldFactory.makeCobolField(100, b_X, a_1_Alphanumeric);	/* X */
    f_n	= CobolFieldFactory.makeCobolField(10, b_n, a_2_NumericDisplay_Digits10_Scale0);	/* n */
    f_m	= CobolFieldFactory.makeCobolField(10, b_m, a_2_NumericDisplay_Digits10_Scale0);	/* m */
    f_i	= CobolFieldFactory.makeCobolField(10, b_i, a_2_NumericDisplay_Digits10_Scale0);	/* i */

    /* End of fields */


    /* Constants */

    c_1_Yes	= CobolFieldFactory.makeCobolField(str_1_Yes, a_1_Alphanumeric);
    c_2_No	= CobolFieldFactory.makeCobolField(str_2_No, a_1_Alphanumeric);

  }

  private void initAttr() {
    /* Attributes */

    a_1_Alphanumeric = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_ALPHANUMERIC,
      /* digits= */ 0,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_2_NumericDisplay_Digits10_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 10,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);

  }

  /* Decimal structures */

  private CobolDecimal d0;
  private CobolDecimal d1;

  /* Data storage */

  /* PROGRAM-ID : PROGRAM_ID */
  public CobolDataStorage b_RETURN_CODE;	/* RETURN-CODE */
  private CobolDataStorage b_S;	/* S */
  private CobolDataStorage b_X;	/* X */
  private CobolDataStorage b_cur;	/* cur */
  private CobolDataStorage b_pre;	/* pre */
  private CobolDataStorage b_n;	/* n */
  private CobolDataStorage b_m;	/* m */
  private CobolDataStorage b_i;	/* i */

  /* End of data storage */


  /* Fields */

  /* PROGRAM-ID : PROGRAM_ID */
  private AbstractCobolField f_S;	/* S */
  private AbstractCobolField f_X;	/* X */
  private AbstractCobolField f_n;	/* n */
  private AbstractCobolField f_m;	/* m */
  private AbstractCobolField f_i;	/* i */

  /* End of fields */


  private static AbstractCobolField f_native;

  /* Constants */

  private AbstractCobolField c_2_No;
  private AbstractCobolField c_1_Yes;

  /* Attributes */

  private CobolFieldAttribute a_2_NumericDisplay_Digits10_Scale0;
  private CobolFieldAttribute a_1_Alphanumeric;



  /* String literals */
  public static final byte[] str_2_No = CobolUtil.stringToBytes("No");
  public static final byte[] str_1_Yes = CobolUtil.stringToBytes("Yes");
  public static final byte[] str_0_0000000001 = CobolUtil.stringToBytes("0000000001");

  /* Sections and Labels */
  private final static int l_PROGRAM_ID = 1;
  private final static int l_MAIN = 2;
  private final static int l_MAIN_SECTION__DEFAULT_PARAGRAPH = 3;
  private final static int l_REVERSESTR = 4;
  private final static int l_REVERSESTR_SECTION__DEFAULT_PARAGRAPH = 5;
  private final static int l_Default_Error_Handler = 6;

}
