/* Generated by opensource COBOL 4J 1.1.16 */
import java.io.UnsupportedEncodingException;
import jp.osscons.opensourcecobol.libcobj.*;
import jp.osscons.opensourcecobol.libcobj.common.*;
import jp.osscons.opensourcecobol.libcobj.data.*;
import jp.osscons.opensourcecobol.libcobj.exceptions.*;
import jp.osscons.opensourcecobol.libcobj.termio.*;
import jp.osscons.opensourcecobol.libcobj.call.*;
import jp.osscons.opensourcecobol.libcobj.file.*;
import jp.osscons.opensourcecobol.libcobj.ui.*;
import java.util.Optional;

public class _3174A implements CobolRunnable {

  private boolean initialized = false;
  private CobolModule module;
  private int entry;

  private CobolRunnable cob_unifunc;


  @Override
  public int run(CobolDataStorage... argStorages) {
    return _3174A_(0, argStorages);
  }

  @Override
  public void cancel() {
    _3174A_(-1);
  }

  @Override
  public boolean isActive() {
    return false;
  }

  public CobolResultSet execute () {
    int returnCode = run_module(0);
    return new CobolResultSet(returnCode);
  }

  public int _3174A_ (int entry, CobolDataStorage ...argStorages) {
    this.entry = entry;
    return this.run_module(entry);
  }

  int run_module (int entry) {
    this.module = new CobolModule(null, null, null, null, 0, '.', '$', ',', 1, 1, 1, 0, null );

    /* Start of function code */

    /* CANCEL callback handling */
    if (entry < 0) {
    	if (!this.initialized) {
    		CobolDecimal.cobInitNumeric();
    		return 0;
    	}
    	this.initialized = false;
    	return 0;
    }

    /* Push module stack */
    CobolModule.push (module);
    CobolResolve.pushCallStackList ("_3174A");

    /* Initialize program */
    if (!this.initialized) {
      module.setProgramId("_3174A");

      b_RETURN_CODE.set((int)0);
      b_X.fillBytes('0', 2);
      CobolFieldFactory.makeCobolField(3, b_OUT, a_1_NumericEdited_Digits3_Scale0).moveFrom (CobolConstant.zero);
      this.initialized = true;
    }
    /* PROCEDURE DIVISION */
    try{
      /* Entry dispatch */
      execEntry(l__3174A);

    } catch(CobolStopRunException e) {
      CobolStopRunException.stopRun();
      System.exit(e.getReturnCode());
    }
    /* Pop module stack */
    CobolResolve.popCallStackList();
    CobolModule.pop();

    /* Program return */
    return b_RETURN_CODE.intValue();
  }
  public CobolControl[] contList = {
    new CobolControl(0, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l__3174A]);
      }
    },
    /* Entry 174A */
    new CobolControl(l__3174A, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN]);
      }
    },
    /* MAIN SECTION */
    new CobolControl(l_MAIN, CobolControl.LabelType.section) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION__DEFAULT_PARAGRAPH]);
      }
    },
    /* MAIN_SECTION__DEFAULT_PARAGRAPH */
    new CobolControl(l_MAIN_SECTION__DEFAULT_PARAGRAPH, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* /content/temp_cobol/174A_fixed.cob:9: ACCEPT */
        {
          CobolTerminal.accept (f_X);
        }
        /* /content/temp_cobol/174A_fixed.cob:11: IF */
        {
          if (((long)b_X.cmpSignNumdisp (2, 30) >= 0L))
            {
              /* /content/temp_cobol/174A_fixed.cob:12: DISPLAY */
              {
                CobolTerminal.display (0, 1, 1, c_1_Yes);
              }
            }
          else
            {
              /* /content/temp_cobol/174A_fixed.cob:14: DISPLAY */
              {
                CobolTerminal.display (0, 1, 1, c_2_No);
              }
            }
        }
        /* /content/temp_cobol/174A_fixed.cob:17: STOP */
        {
          CobolStopRunException.throwException (b_RETURN_CODE.intValue());
        }
        return Optional.of(CobolControl.pure());
      }
    },
    CobolControl.pure()
  };
  public void execEntry(int start) throws CobolRuntimeException, CobolStopRunException {
    Optional<CobolControl> nextLabel = Optional.of(contList[start]);
    while(nextLabel.isPresent()) {
      CobolControl section = nextLabel.get();
      nextLabel = section.run();
    }
  }

  public static void main(String[] args)
  {
    CobolUtil.cob_init(args, false);
    CobolDecimal.cobInitNumeric();
    new _3174A()._3174A_(0);
    CobolStopRunException.stopRun();
  }

  public _3174A()
  {
    init();
  }

  public void init() 
  {
    /* Data storage */

    cob_unifunc = null;

    /* PROGRAM-ID : 174A */
    b_RETURN_CODE = new CobolDataStorage(4);	/* RETURN-CODE */
    b_X = new CobolDataStorage(2);	/* X */
    b_OUT = new CobolDataStorage(3);	/* OUT */

    /* End of data storage */


    initAttr();

    /* Fields */

    /* PROGRAM-ID : 174A */
    f_X	= CobolFieldFactory.makeCobolField(2, b_X, a_2_NumericDisplay_Digits2_Scale0_HaveSign);	/* X */

    /* End of fields */


    /* Constants */

    c_1_Yes	= CobolFieldFactory.makeCobolField(str_0_Yes, a_3_Alphanumeric);
    c_2_No	= CobolFieldFactory.makeCobolField(str_1_No, a_3_Alphanumeric);

  }

  private void initAttr() {
    /* Attributes */

    a_1_NumericEdited_Digits3_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_EDITED,
      /* digits= */ 3,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ "Z\002\000\000\0009\001\000\000\000");
    a_2_NumericDisplay_Digits2_Scale0_HaveSign = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 2,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_HAVE_SIGN,
      /* pic= */ null);
    a_3_Alphanumeric = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_ALPHANUMERIC,
      /* digits= */ 0,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);

  }

  /* Data storage */

  /* PROGRAM-ID : 174A */
  public CobolDataStorage b_RETURN_CODE;	/* RETURN-CODE */
  private CobolDataStorage b_X;	/* X */
  private CobolDataStorage b_OUT;	/* OUT */

  /* End of data storage */


  /* Fields */

  /* PROGRAM-ID : 174A */
  private AbstractCobolField f_X;	/* X */

  /* End of fields */


  private static AbstractCobolField f_native;

  /* Constants */

  private AbstractCobolField c_2_No;
  private AbstractCobolField c_1_Yes;

  /* Attributes */

  private CobolFieldAttribute a_3_Alphanumeric;
  private CobolFieldAttribute a_2_NumericDisplay_Digits2_Scale0_HaveSign;
  private CobolFieldAttribute a_1_NumericEdited_Digits3_Scale0;



  /* String literals */
  public static final byte[] str_1_No = CobolUtil.stringToBytes("No");
  public static final byte[] str_0_Yes = CobolUtil.stringToBytes("Yes");

  /* Sections and Labels */
  private final static int l__3174A = 1;
  private final static int l_MAIN = 2;
  private final static int l_MAIN_SECTION__DEFAULT_PARAGRAPH = 3;
  private final static int l_Default_Error_Handler = 4;

}
