/* Generated by opensource COBOL 4J 1.1.16 */
import java.io.UnsupportedEncodingException;
import jp.osscons.opensourcecobol.libcobj.*;
import jp.osscons.opensourcecobol.libcobj.common.*;
import jp.osscons.opensourcecobol.libcobj.data.*;
import jp.osscons.opensourcecobol.libcobj.exceptions.*;
import jp.osscons.opensourcecobol.libcobj.termio.*;
import jp.osscons.opensourcecobol.libcobj.call.*;
import jp.osscons.opensourcecobol.libcobj.file.*;
import jp.osscons.opensourcecobol.libcobj.ui.*;
import java.util.Optional;

public class ABC111A implements CobolRunnable {

  private boolean initialized = false;
  private CobolModule module;
  private int entry;

  private CobolRunnable cob_unifunc;


  @Override
  public int run(CobolDataStorage... argStorages) {
    return ABC111A_(0, argStorages);
  }

  @Override
  public void cancel() {
    ABC111A_(-1);
  }

  @Override
  public boolean isActive() {
    return false;
  }

  public CobolResultSet execute () {
    int returnCode = run_module(0);
    return new CobolResultSet(returnCode);
  }

  public int ABC111A_ (int entry, CobolDataStorage ...argStorages) {
    this.entry = entry;
    return this.run_module(entry);
  }

  int run_module (int entry) {
    this.module = new CobolModule(null, null, null, null, 0, '.', '$', ',', 1, 1, 1, 0, null );

    /* Start of function code */

    /* CANCEL callback handling */
    if (entry < 0) {
    	if (!this.initialized) {
    		CobolDecimal.cobInitNumeric();
    		return 0;
    	}
    	this.initialized = false;
    	return 0;
    }

    /* Push module stack */
    CobolModule.push (module);
    CobolResolve.pushCallStackList ("ABC111A");

    /* Initialize program */
    if (!this.initialized) {
      module.setProgramId("ABC111A");

      b_RETURN_CODE.set((int)0);
      b_N.fillBytes('0', 3);
      this.initialized = true;
    }
    /* PROCEDURE DIVISION */
    try{
      /* Entry dispatch */
      execEntry(l_ABC111A);

    } catch(CobolStopRunException e) {
      CobolStopRunException.stopRun();
      System.exit(e.getReturnCode());
    }
    /* Pop module stack */
    CobolResolve.popCallStackList();
    CobolModule.pop();

    /* Program return */
    return b_RETURN_CODE.intValue();
  }
  public CobolControl[] contList = {
    new CobolControl(0, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_ABC111A]);
      }
    },
    /* Entry ABC111A */
    new CobolControl(l_ABC111A, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN]);
      }
    },
    /* MAIN SECTION */
    new CobolControl(l_MAIN, CobolControl.LabelType.section) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION__DEFAULT_PARAGRAPH]);
      }
    },
    /* MAIN_SECTION__DEFAULT_PARAGRAPH */
    new CobolControl(l_MAIN_SECTION__DEFAULT_PARAGRAPH, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* /content/temp_cobol/ABC111A_fixed.cob:9: ACCEPT */
        {
          CobolTerminal.accept (f_N);
        }
        /* /content/temp_cobol/ABC111A_fixed.cob:10: INSPECT */
        {
          CobolInspect.init (f_N, 0);
          CobolInspect.start ();
          CobolInspect.converting (c_1_19, c_2_91);
          CobolInspect.finish ();
        }
        /* /content/temp_cobol/ABC111A_fixed.cob:11: DISPLAY */
        {
          CobolTerminal.display (0, 1, 1, f_N);
        }
        /* /content/temp_cobol/ABC111A_fixed.cob:12: STOP */
        {
          CobolStopRunException.throwException (b_RETURN_CODE.intValue());
        }
        return Optional.of(CobolControl.pure());
      }
    },
    CobolControl.pure()
  };
  public void execEntry(int start) throws CobolRuntimeException, CobolStopRunException {
    Optional<CobolControl> nextLabel = Optional.of(contList[start]);
    while(nextLabel.isPresent()) {
      CobolControl section = nextLabel.get();
      nextLabel = section.run();
    }
  }

  public static void main(String[] args)
  {
    CobolUtil.cob_init(args, false);
    CobolDecimal.cobInitNumeric();
    new ABC111A().ABC111A_(0);
    CobolStopRunException.stopRun();
  }

  public ABC111A()
  {
    init();
  }

  public void init() 
  {
    /* Data storage */

    cob_unifunc = null;

    /* PROGRAM-ID : ABC111A */
    b_RETURN_CODE = new CobolDataStorage(4);	/* RETURN-CODE */
    b_N = new CobolDataStorage(3);	/* N */

    /* End of data storage */


    initAttr();

    /* Fields */

    /* PROGRAM-ID : ABC111A */
    f_N	= CobolFieldFactory.makeCobolField(3, b_N, a_1_NumericDisplay_Digits3_Scale0);	/* N */

    /* End of fields */


    /* Constants */

    c_1_19	= CobolFieldFactory.makeCobolField(str_0_19, a_2_Alphanumeric);
    c_2_91	= CobolFieldFactory.makeCobolField(str_1_91, a_2_Alphanumeric);

  }

  private void initAttr() {
    /* Attributes */

    a_1_NumericDisplay_Digits3_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 3,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_2_Alphanumeric = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_ALPHANUMERIC,
      /* digits= */ 0,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);

  }

  /* Data storage */

  /* PROGRAM-ID : ABC111A */
  public CobolDataStorage b_RETURN_CODE;	/* RETURN-CODE */
  private CobolDataStorage b_N;	/* N */

  /* End of data storage */


  /* Fields */

  /* PROGRAM-ID : ABC111A */
  private AbstractCobolField f_N;	/* N */

  /* End of fields */


  private static AbstractCobolField f_native;

  /* Constants */

  private AbstractCobolField c_2_91;
  private AbstractCobolField c_1_19;

  /* Attributes */

  private CobolFieldAttribute a_2_Alphanumeric;
  private CobolFieldAttribute a_1_NumericDisplay_Digits3_Scale0;



  /* String literals */
  public static final byte[] str_1_91 = CobolUtil.stringToBytes("91");
  public static final byte[] str_0_19 = CobolUtil.stringToBytes("19");

  /* Sections and Labels */
  private final static int l_ABC111A = 1;
  private final static int l_MAIN = 2;
  private final static int l_MAIN_SECTION__DEFAULT_PARAGRAPH = 3;
  private final static int l_Default_Error_Handler = 4;

}
