/* Generated by opensource COBOL 4J 1.1.16 */
import java.io.UnsupportedEncodingException;
import jp.osscons.opensourcecobol.libcobj.*;
import jp.osscons.opensourcecobol.libcobj.common.*;
import jp.osscons.opensourcecobol.libcobj.data.*;
import jp.osscons.opensourcecobol.libcobj.exceptions.*;
import jp.osscons.opensourcecobol.libcobj.termio.*;
import jp.osscons.opensourcecobol.libcobj.call.*;
import jp.osscons.opensourcecobol.libcobj.file.*;
import jp.osscons.opensourcecobol.libcobj.ui.*;
import java.util.Optional;

public class Main implements CobolRunnable {

  private boolean initialized = false;
  private CobolModule module;
  private int entry;

  private CobolRunnable cob_unifunc;


  @Override
  public int run(CobolDataStorage... argStorages) {
    return Main_(0, argStorages);
  }

  @Override
  public void cancel() {
    Main_(-1);
  }

  @Override
  public boolean isActive() {
    return false;
  }

  public CobolResultSet execute () {
    int returnCode = run_module(0);
    return new CobolResultSet(returnCode);
  }

  public int Main_ (int entry, CobolDataStorage ...argStorages) {
    this.entry = entry;
    return this.run_module(entry);
  }

  int run_module (int entry) {
    this.module = new CobolModule(null, null, null, null, 0, '.', '$', ',', 1, 1, 1, 0, null );

    /* Start of function code */

    /* CANCEL callback handling */
    if (entry < 0) {
    	if (!this.initialized) {
    		CobolDecimal.cobInitNumeric();
    		return 0;
    	}
    	d0.clear();
    	d0.setScale(0);
    	d1.clear();
    	d1.setScale(0);
    	this.initialized = false;
    	return 0;
    }

    /* Push module stack */
    CobolModule.push (module);
    CobolResolve.pushCallStackList ("Main");

    /* Initialize program */
    if (!this.initialized) {
      module.setProgramId("Main");

      /* Initialize decimal numbers */
      d0.decimalInit();
      d1.decimalInit();

      b_RETURN_CODE.set((int)0);
      b_N.setByte('0');
      b_A.setByte(0, ' ');
      b_B.setByte(0, ' ');
      b_C.fillBytes (32, 2);
      b_A_9.setByte('0');
      b_B_9.setByte('0');
      b_C_9.fillBytes('0', 2);
      b_D_9.setByte('0');
      this.initialized = true;
    }
    /* PROCEDURE DIVISION */
    try{
      /* Entry dispatch */
      execEntry(l_Main);

    } catch(CobolStopRunException e) {
      CobolStopRunException.stopRun();
      System.exit(e.getReturnCode());
    }
    /* Pop module stack */
    CobolResolve.popCallStackList();
    CobolModule.pop();

    /* Program return */
    return b_RETURN_CODE.intValue();
  }
  public CobolControl[] contList = {
    new CobolControl(0, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_Main]);
      }
    },
    /* Entry Main */
    new CobolControl(l_Main, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN]);
      }
    },
    /* MAIN SECTION */
    new CobolControl(l_MAIN, CobolControl.LabelType.section) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION__DEFAULT_PARAGRAPH]);
      }
    },
    /* MAIN_SECTION__DEFAULT_PARAGRAPH */
    new CobolControl(l_MAIN_SECTION__DEFAULT_PARAGRAPH, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* /content/temp_cobol/Main_fixed.cob:14: ACCEPT */
        {
          CobolTerminal.accept (f_N);
        }
        /* /content/temp_cobol/Main_fixed.cob:15: IF */
        {
          if (((long)b_N.cmpNumdisp (1, 1) == 0L))
            {
              /* /content/temp_cobol/Main_fixed.cob:17: DISPLAY */
              {
                CobolTerminal.display (0, 1, 1, c_1_Hello);
              }
            }
          else
            {
              /* /content/temp_cobol/Main_fixed.cob:19: IF */
              {
                if (((long)f_N.compareTo (c_2_2) == 0L))
                  {
                    /* /content/temp_cobol/Main_fixed.cob:21: ACCEPT */
                    {
                      CobolTerminal.accept (f_A);
                    }
                    /* /content/temp_cobol/Main_fixed.cob:22: ACCEPT */
                    {
                      CobolTerminal.accept (f_B);
                    }
                    /* /content/temp_cobol/Main_fixed.cob:23: MOVE */
                    {
                      f_A_9.moveFrom (f_A);
                    }
                    /* /content/temp_cobol/Main_fixed.cob:24: MOVE */
                    {
                      f_B_9.moveFrom (f_B);
                    }
                    /* /content/temp_cobol/Main_fixed.cob:25: COMPUTE */
                    {
                      {
                        {
                          d0.set (b_A_9.getNumdisp(1));
                          d1.set (b_B_9.getNumdisp(1));
                          d0.add (d1);
                          d0.getField (f_C_9, 4);
                        }
                      }
                    }
                    /* /content/temp_cobol/Main_fixed.cob:26: IF */
                    {
                      if (((long)b_C_9.cmpNumdisp (2, 9) >  0L))
                        {
                          /* /content/temp_cobol/Main_fixed.cob:28: DISPLAY */
                          {
                            CobolTerminal.display (0, 1, 1, f_C_9);
                          }
                        }
                      else
                        {
                          /* /content/temp_cobol/Main_fixed.cob:30: MOVE */
                          {
                            f_D_9.moveFrom (f_C_9);
                          }
                          /* /content/temp_cobol/Main_fixed.cob:31: DISPLAY */
                          {
                            CobolTerminal.display (0, 1, 1, f_D_9);
                          }
                        }
                    }
                  }
                else
                  {
                    /* /content/temp_cobol/Main_fixed.cob:35: DISPLAY */
                    {
                      CobolTerminal.display (0, 1, 1, c_3_ERR);
                    }
                  }
              }
            }
        }
        /* /content/temp_cobol/Main_fixed.cob:38: STOP */
        {
          CobolStopRunException.throwException (b_RETURN_CODE.intValue());
        }
        return Optional.of(CobolControl.pure());
      }
    },
    CobolControl.pure()
  };
  public void execEntry(int start) throws CobolRuntimeException, CobolStopRunException {
    Optional<CobolControl> nextLabel = Optional.of(contList[start]);
    while(nextLabel.isPresent()) {
      CobolControl section = nextLabel.get();
      nextLabel = section.run();
    }
  }

  public static void main(String[] args)
  {
    CobolUtil.cob_init(args, false);
    CobolDecimal.cobInitNumeric();
    new Main().Main_(0);
    CobolStopRunException.stopRun();
  }

  public Main()
  {
    init();
  }

  public void init() 
  {
    /* Decimal structures */

    d0 = new CobolDecimal();
    d1 = new CobolDecimal();

    /* Data storage */

    cob_unifunc = null;

    /* PROGRAM-ID : Main */
    b_RETURN_CODE = new CobolDataStorage(4);	/* RETURN-CODE */
    b_N = new CobolDataStorage(1);	/* N */
    b_A = new CobolDataStorage(1);	/* A */
    b_B = new CobolDataStorage(1);	/* B */
    b_C = new CobolDataStorage(2);	/* C */
    b_A_9 = new CobolDataStorage(1);	/* A-9 */
    b_B_9 = new CobolDataStorage(1);	/* B-9 */
    b_C_9 = new CobolDataStorage(2);	/* C-9 */
    b_D_9 = new CobolDataStorage(1);	/* D-9 */

    /* End of data storage */


    initAttr();

    /* Fields */

    /* PROGRAM-ID : Main */
    f_N	= CobolFieldFactory.makeCobolField(1, b_N, a_1_NumericDisplay_Digits1_Scale0);	/* N */
    f_A	= CobolFieldFactory.makeCobolField(1, b_A, a_2_Alphanumeric);	/* A */
    f_B	= CobolFieldFactory.makeCobolField(1, b_B, a_2_Alphanumeric);	/* B */
    f_A_9	= CobolFieldFactory.makeCobolField(1, b_A_9, a_1_NumericDisplay_Digits1_Scale0);	/* A-9 */
    f_B_9	= CobolFieldFactory.makeCobolField(1, b_B_9, a_1_NumericDisplay_Digits1_Scale0);	/* B-9 */
    f_C_9	= CobolFieldFactory.makeCobolField(2, b_C_9, a_3_NumericDisplay_Digits2_Scale0);	/* C-9 */
    f_D_9	= CobolFieldFactory.makeCobolField(1, b_D_9, a_1_NumericDisplay_Digits1_Scale0);	/* D-9 */

    /* End of fields */


    /* Constants */

    c_1_Hello	= CobolFieldFactory.makeCobolField(str_0_Hello, a_2_Alphanumeric);
    c_2_2	= CobolFieldFactory.makeCobolField(str_1_2, a_2_Alphanumeric);
    c_3_ERR	= CobolFieldFactory.makeCobolField(str_2_ERR, a_2_Alphanumeric);

  }

  private void initAttr() {
    /* Attributes */

    a_1_NumericDisplay_Digits1_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 1,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_2_Alphanumeric = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_ALPHANUMERIC,
      /* digits= */ 0,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_3_NumericDisplay_Digits2_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 2,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);

  }

  /* Decimal structures */

  private CobolDecimal d0;
  private CobolDecimal d1;

  /* Data storage */

  /* PROGRAM-ID : Main */
  public CobolDataStorage b_RETURN_CODE;	/* RETURN-CODE */
  private CobolDataStorage b_N;	/* N */
  private CobolDataStorage b_A;	/* A */
  private CobolDataStorage b_B;	/* B */
  private CobolDataStorage b_C;	/* C */
  private CobolDataStorage b_A_9;	/* A-9 */
  private CobolDataStorage b_B_9;	/* B-9 */
  private CobolDataStorage b_C_9;	/* C-9 */
  private CobolDataStorage b_D_9;	/* D-9 */

  /* End of data storage */


  /* Fields */

  /* PROGRAM-ID : Main */
  private AbstractCobolField f_N;	/* N */
  private AbstractCobolField f_A;	/* A */
  private AbstractCobolField f_B;	/* B */
  private AbstractCobolField f_A_9;	/* A-9 */
  private AbstractCobolField f_B_9;	/* B-9 */
  private AbstractCobolField f_C_9;	/* C-9 */
  private AbstractCobolField f_D_9;	/* D-9 */

  /* End of fields */


  private static AbstractCobolField f_native;

  /* Constants */

  private AbstractCobolField c_3_ERR;
  private AbstractCobolField c_2_2;
  private AbstractCobolField c_1_Hello;

  /* Attributes */

  private CobolFieldAttribute a_3_NumericDisplay_Digits2_Scale0;
  private CobolFieldAttribute a_2_Alphanumeric;
  private CobolFieldAttribute a_1_NumericDisplay_Digits1_Scale0;



  /* String literals */
  public static final byte[] str_2_ERR = CobolUtil.stringToBytes("ERR!");
  public static final byte[] str_1_2 = CobolUtil.stringToBytes("2");
  public static final byte[] str_0_Hello = CobolUtil.stringToBytes("Hello World");

  /* Sections and Labels */
  private final static int l_Main = 1;
  private final static int l_MAIN = 2;
  private final static int l_MAIN_SECTION__DEFAULT_PARAGRAPH = 3;
  private final static int l_Default_Error_Handler = 4;

}
