/* Generated by opensource COBOL 4J 1.1.16 */
import java.io.UnsupportedEncodingException;
import jp.osscons.opensourcecobol.libcobj.*;
import jp.osscons.opensourcecobol.libcobj.common.*;
import jp.osscons.opensourcecobol.libcobj.data.*;
import jp.osscons.opensourcecobol.libcobj.exceptions.*;
import jp.osscons.opensourcecobol.libcobj.termio.*;
import jp.osscons.opensourcecobol.libcobj.call.*;
import jp.osscons.opensourcecobol.libcobj.file.*;
import jp.osscons.opensourcecobol.libcobj.ui.*;
import java.util.Optional;

public class ABC_042_B implements CobolRunnable {

  private boolean initialized = false;
  private CobolModule module;
  private int entry;

  private CobolRunnable cob_unifunc;


  @Override
  public int run(CobolDataStorage... argStorages) {
    return ABC_042_B_(0, argStorages);
  }

  @Override
  public void cancel() {
    ABC_042_B_(-1);
  }

  @Override
  public boolean isActive() {
    return false;
  }

  public CobolResultSet execute () {
    int returnCode = run_module(0);
    return new CobolResultSet(returnCode);
  }

  public int ABC_042_B_ (int entry, CobolDataStorage ...argStorages) {
    this.entry = entry;
    return this.run_module(entry);
  }

  int run_module (int entry) {
    this.module = new CobolModule(null, null, null, null, 0, '.', '$', ',', 1, 1, 1, 0, null );

    /* Start of function code */

    /* CANCEL callback handling */
    if (entry < 0) {
    	if (!this.initialized) {
    		CobolDecimal.cobInitNumeric();
    		return 0;
    	}
    	d0.clear();
    	d0.setScale(0);
    	d1.clear();
    	d1.setScale(0);
    	d2.clear();
    	d2.setScale(0);
    	d3.clear();
    	d3.setScale(0);
    	this.initialized = false;
    	return 0;
    }

    /* Push module stack */
    CobolModule.push (module);
    CobolResolve.pushCallStackList ("ABC_042_B");

    /* Initialize program */
    if (!this.initialized) {
      module.setProgramId("ABC_042_B");

      /* Initialize decimal numbers */
      d0.decimalInit();
      d1.decimalInit();
      d2.decimalInit();
      d3.decimalInit();

      b_RETURN_CODE.set((int)0);
      b_INP.fillBytes(' ', 7);
      b_N.fillBytes('0', 3);
      b_L.fillBytes('0', 3);
      b_S1.fillBytes(' ', 10000);
      b_ans.fillBytes(' ', 10000);
      b_tmp.fillBytes(' ', 100);
      b_i.fillBytes('0', 3);
      b_j.fillBytes('0', 3);
      b_st.fillBytes('0', 3);
      b_p.fillBytes('0', 5);
      this.initialized = true;
    }
    /* PROCEDURE DIVISION */
    try{
      /* Entry dispatch */
      execEntry(l_ABC_042_B);

    } catch(CobolStopRunException e) {
      CobolStopRunException.stopRun();
      System.exit(e.getReturnCode());
    }
    /* Pop module stack */
    CobolResolve.popCallStackList();
    CobolModule.pop();

    /* Program return */
    return b_RETURN_CODE.intValue();
  }
  public CobolControl[] contList = {
    new CobolControl(0, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_ABC_042_B]);
      }
    },
    /* Entry ABC_042_B */
    new CobolControl(l_ABC_042_B, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION]);
      }
    },
    /* MAIN SECTION */
    new CobolControl(l_MAIN_SECTION, CobolControl.LabelType.section) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION__MAIN]);
      }
    },
    /* MAIN */
    new CobolControl(l_MAIN_SECTION__MAIN, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* /content/temp_cobol/ABC_042_B_fixed.cob:19: ACCEPT */
        {
          CobolTerminal.accept (f_INP);
        }
        /* /content/temp_cobol/ABC_042_B_fixed.cob:21: UNSTRING */
        {
          CobolString.unstringInit (f_INP, 0, 1);
          CobolString.unstringDelimited (CobolConstant.space, 0);
          CobolString.unstringInto (f_N, 0, 0);
          CobolString.unstringInto (f_L, 0, 0);
          CobolString.unstringFinish ();
        }
        /* /content/temp_cobol/ABC_042_B_fixed.cob:25: PERFORM */
        b_i.setBytes (str_0_001, 3);
        for(;;f_i.addInt (1))
        {
          if (((long)b_N.memcmp (b_i, 3) <  0L))
            break;
          {
            /* /content/temp_cobol/ABC_042_B_fixed.cob:26: ACCEPT */
            {
              CobolTerminal.accept (CobolFieldFactory.makeCobolField(100, b_S__S11__S1.getSubDataStorage(100 * (b_i.getNumdisp(3) - 1)), a_1_Alphanumeric));
            }
          }
        }
        /* /content/temp_cobol/ABC_042_B_fixed.cob:29: SORT */
        {
          CobolFileSort.sortTableInit (1, 0);
          CobolFileSort.sortTableInitKey (0, f_S__S11__S1, 0);
          CobolFileSort.sortTable (f_S11__S1, b_N.getNumdisp(3));
        }
        /* /content/temp_cobol/ABC_042_B_fixed.cob:31: PERFORM */
        b_i.setBytes (str_1_001, 3);
        for(;;f_i.addInt (1))
        {
          if (((long)b_N.memcmp (b_i, 3) <  0L))
            break;
          {
            /* /content/temp_cobol/ABC_042_B_fixed.cob:32: COMPUTE */
            {
              {
                {
                  d0.set (b_L.getNumdisp(3));
                  d2.set (b_i.getNumdisp(3));
                  d3.set (1);
                  d2.sub (d3);
                  d0.mul (d2);
                  d1.set (1);
                  d0.add (d1);
                  d0.getField (f_p, 4);
                }
              }
            }
            /* /content/temp_cobol/ABC_042_B_fixed.cob:34: STRING */
            {
              CobolString.stringInit (f_ans, f_p);
              CobolString.stringDelimited (0);
              CobolString.stringAppend (CobolFieldFactory.makeCobolField(b_L.getNumdisp(3), b_S__S11__S1.getSubDataStorage(100 * (b_i.getNumdisp(3) - 1)+ (0)), a_1_Alphanumeric));
              CobolString.stringFinish ();
            }
          }
        }
        /* /content/temp_cobol/ABC_042_B_fixed.cob:40: DISPLAY */
        {
          CobolTerminal.display (0, 1, 1, CobolFieldFactory.makeCobolField(CobolIntrinsic.funcStoredCharLength (f_ans).getInt(), b_ans.getSubDataStorage(0), a_1_Alphanumeric));
        }
        /* /content/temp_cobol/ABC_042_B_fixed.cob:42: STOP */
        {
          CobolStopRunException.throwException (b_RETURN_CODE.intValue());
        }
        return Optional.of(CobolControl.pure());
      }
    },
    CobolControl.pure()
  };
  public void execEntry(int start) throws CobolRuntimeException, CobolStopRunException {
    Optional<CobolControl> nextLabel = Optional.of(contList[start]);
    while(nextLabel.isPresent()) {
      CobolControl section = nextLabel.get();
      nextLabel = section.run();
    }
  }

  public static void main(String[] args)
  {
    CobolUtil.cob_init(args, false);
    CobolDecimal.cobInitNumeric();
    new ABC_042_B().ABC_042_B_(0);
    CobolStopRunException.stopRun();
  }

  public ABC_042_B()
  {
    init();
  }

  public void init() 
  {
    /* Decimal structures */

    d0 = new CobolDecimal();
    d1 = new CobolDecimal();
    d2 = new CobolDecimal();
    d3 = new CobolDecimal();

    /* Data storage */

    cob_unifunc = null;

    /* PROGRAM-ID : ABC_042_B */
    b_RETURN_CODE = new CobolDataStorage(4);	/* RETURN-CODE */
    b_INP = new CobolDataStorage(7);	/* INP */
    b_N = new CobolDataStorage(3);	/* N */
    b_L = new CobolDataStorage(3);	/* L */
    b_S1 = new CobolDataStorage(10000);	/* S1 */
    b_ans = new CobolDataStorage(10000);	/* ans */
    b_tmp = new CobolDataStorage(100);	/* tmp */
    b_i = new CobolDataStorage(3);	/* i */
    b_j = new CobolDataStorage(3);	/* j */
    b_st = new CobolDataStorage(3);	/* st */
    b_p = new CobolDataStorage(5);	/* p */
    b_S__S11__S1 = b_S1;
    b_S11__S1 = b_S1;

    /* End of data storage */


    initAttr();

    /* Fields */

    /* PROGRAM-ID : ABC_042_B */
    f_INP	= CobolFieldFactory.makeCobolField(7, b_INP, a_1_Alphanumeric);	/* INP */
    f_N	= CobolFieldFactory.makeCobolField(3, b_N, a_2_NumericDisplay_Digits3_Scale0);	/* N */
    f_L	= CobolFieldFactory.makeCobolField(3, b_L, a_2_NumericDisplay_Digits3_Scale0);	/* L */
    f_S11__S1	= CobolFieldFactory.makeCobolField(100, b_S11__S1, a_3_Group);	/* S11 */
    f_S__S11__S1	= CobolFieldFactory.makeCobolField(100, b_S__S11__S1, a_1_Alphanumeric);	/* S */
    f_ans	= CobolFieldFactory.makeCobolField(10000, b_ans, a_1_Alphanumeric);	/* ans */
    f_i	= CobolFieldFactory.makeCobolField(3, b_i, a_2_NumericDisplay_Digits3_Scale0);	/* i */
    f_p	= CobolFieldFactory.makeCobolField(5, b_p, a_4_NumericDisplay_Digits5_Scale0);	/* p */

    /* End of fields */


  }

  private void initAttr() {
    /* Attributes */

    a_1_Alphanumeric = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_ALPHANUMERIC,
      /* digits= */ 0,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_2_NumericDisplay_Digits3_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 3,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_3_Group = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_GROUP,
      /* digits= */ 0,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_4_NumericDisplay_Digits5_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 5,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);

  }

  /* Decimal structures */

  private CobolDecimal d0;
  private CobolDecimal d1;
  private CobolDecimal d2;
  private CobolDecimal d3;

  /* Data storage */

  /* PROGRAM-ID : ABC_042_B */
  public CobolDataStorage b_RETURN_CODE;	/* RETURN-CODE */
  private CobolDataStorage b_INP;	/* INP */
  private CobolDataStorage b_N;	/* N */
  private CobolDataStorage b_L;	/* L */
  private CobolDataStorage b_S1;	/* S1 */
  private CobolDataStorage b_ans;	/* ans */
  private CobolDataStorage b_tmp;	/* tmp */
  private CobolDataStorage b_i;	/* i */
  private CobolDataStorage b_j;	/* j */
  private CobolDataStorage b_st;	/* st */
  private CobolDataStorage b_p;	/* p */
  private CobolDataStorage b_S__S11__S1;
  private CobolDataStorage b_S11__S1;

  /* End of data storage */


  /* Fields */

  /* PROGRAM-ID : ABC_042_B */
  private AbstractCobolField f_INP;	/* INP */
  private AbstractCobolField f_N;	/* N */
  private AbstractCobolField f_L;	/* L */
  private AbstractCobolField f_S11__S1;	/* S11 */
  private AbstractCobolField f_S__S11__S1;	/* S */
  private AbstractCobolField f_ans;	/* ans */
  private AbstractCobolField f_i;	/* i */
  private AbstractCobolField f_p;	/* p */

  /* End of fields */


  private static AbstractCobolField f_native;

  /* Attributes */

  private CobolFieldAttribute a_4_NumericDisplay_Digits5_Scale0;
  private CobolFieldAttribute a_3_Group;
  private CobolFieldAttribute a_2_NumericDisplay_Digits3_Scale0;
  private CobolFieldAttribute a_1_Alphanumeric;



  /* String literals */
  public static final byte[] str_1_001 = CobolUtil.stringToBytes("001");
  public static final byte[] str_0_001 = CobolUtil.stringToBytes("001");

  /* Sections and Labels */
  private final static int l_ABC_042_B = 1;
  private final static int l_MAIN_SECTION = 2;
  private final static int l_MAIN_SECTION__MAIN = 3;
  private final static int l_Default_Error_Handler = 4;

}
