/* Generated by opensource COBOL 4J 1.1.16 */
import java.io.UnsupportedEncodingException;
import jp.osscons.opensourcecobol.libcobj.*;
import jp.osscons.opensourcecobol.libcobj.common.*;
import jp.osscons.opensourcecobol.libcobj.data.*;
import jp.osscons.opensourcecobol.libcobj.exceptions.*;
import jp.osscons.opensourcecobol.libcobj.termio.*;
import jp.osscons.opensourcecobol.libcobj.call.*;
import jp.osscons.opensourcecobol.libcobj.file.*;
import jp.osscons.opensourcecobol.libcobj.ui.*;
import java.util.Optional;

public class ABC_059_A implements CobolRunnable {

  private boolean initialized = false;
  private CobolModule module;
  private int entry;

  private CobolRunnable cob_unifunc;


  @Override
  public int run(CobolDataStorage... argStorages) {
    return ABC_059_A_(0, argStorages);
  }

  @Override
  public void cancel() {
    ABC_059_A_(-1);
  }

  @Override
  public boolean isActive() {
    return false;
  }

  public CobolResultSet execute () {
    int returnCode = run_module(0);
    return new CobolResultSet(returnCode);
  }

  public int ABC_059_A_ (int entry, CobolDataStorage ...argStorages) {
    this.entry = entry;
    return this.run_module(entry);
  }

  int run_module (int entry) {
    this.module = new CobolModule(null, null, null, null, 0, '.', '$', ',', 1, 1, 1, 0, null );

    /* Start of function code */

    /* CANCEL callback handling */
    if (entry < 0) {
    	if (!this.initialized) {
    		CobolDecimal.cobInitNumeric();
    		return 0;
    	}
    	this.initialized = false;
    	return 0;
    }

    /* Push module stack */
    CobolModule.push (module);
    CobolResolve.pushCallStackList ("ABC_059_A");

    /* Initialize program */
    if (!this.initialized) {
      module.setProgramId("ABC_059_A");

      b_RETURN_CODE.set((int)0);
      b_INP.fillBytes(' ', 32);
      b_s1.fillBytes(' ', 10);
      b_s2.fillBytes(' ', 10);
      b_s3.fillBytes(' ', 10);
      this.initialized = true;
    }
    /* PROCEDURE DIVISION */
    try{
      /* Entry dispatch */
      execEntry(l_ABC_059_A);

    } catch(CobolStopRunException e) {
      CobolStopRunException.stopRun();
      System.exit(e.getReturnCode());
    }
    /* Pop module stack */
    CobolResolve.popCallStackList();
    CobolModule.pop();

    /* Program return */
    return b_RETURN_CODE.intValue();
  }
  public CobolControl[] contList = {
    new CobolControl(0, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_ABC_059_A]);
      }
    },
    /* Entry ABC_059_A */
    new CobolControl(l_ABC_059_A, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION]);
      }
    },
    /* MAIN SECTION */
    new CobolControl(l_MAIN_SECTION, CobolControl.LabelType.section) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION__MAIN]);
      }
    },
    /* MAIN */
    new CobolControl(l_MAIN_SECTION__MAIN, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* /content/temp_translate/s387540551.cob:12: ACCEPT */
        {
          CobolTerminal.accept (f_INP);
        }
        /* /content/temp_translate/s387540551.cob:14: UNSTRING */
        {
          CobolString.unstringInit (f_INP, 0, 1);
          CobolString.unstringDelimited (CobolConstant.space, 0);
          CobolString.unstringInto (f_s1, 0, 0);
          CobolString.unstringInto (f_s2, 0, 0);
          CobolString.unstringInto (f_s3, 0, 0);
          CobolString.unstringFinish ();
        }
        /* /content/temp_translate/s387540551.cob:18: MOVE */
        {
          f_s1.moveFrom (CobolIntrinsic.funcUpperCase (0, 0, f_s1));
        }
        /* /content/temp_translate/s387540551.cob:19: MOVE */
        {
          f_s2.moveFrom (CobolIntrinsic.funcUpperCase (0, 0, f_s2));
        }
        /* /content/temp_translate/s387540551.cob:20: MOVE */
        {
          f_s3.moveFrom (CobolIntrinsic.funcUpperCase (0, 0, f_s3));
        }
        /* /content/temp_translate/s387540551.cob:22: DISPLAY */
        {
          CobolTerminal.display (0, 1, 3, CobolFieldFactory.makeCobolField(1, b_s1.getSubDataStorage(0), a_1_Alphanumeric), CobolFieldFactory.makeCobolField(1, b_s2.getSubDataStorage(0), a_1_Alphanumeric), CobolFieldFactory.makeCobolField(1, b_s3.getSubDataStorage(0), a_1_Alphanumeric));
        }
        /* /content/temp_translate/s387540551.cob:24: STOP */
        {
          CobolStopRunException.throwException (b_RETURN_CODE.intValue());
        }
        return Optional.of(CobolControl.pure());
      }
    },
    CobolControl.pure()
  };
  public void execEntry(int start) throws CobolRuntimeException, CobolStopRunException {
    Optional<CobolControl> nextLabel = Optional.of(contList[start]);
    while(nextLabel.isPresent()) {
      CobolControl section = nextLabel.get();
      nextLabel = section.run();
    }
  }

  public static void main(String[] args)
  {
    CobolUtil.cob_init(args, false);
    CobolDecimal.cobInitNumeric();
    new ABC_059_A().ABC_059_A_(0);
    CobolStopRunException.stopRun();
  }

  public ABC_059_A()
  {
    init();
  }

  public void init() 
  {
    /* Data storage */

    cob_unifunc = null;

    /* PROGRAM-ID : ABC_059_A */
    b_RETURN_CODE = new CobolDataStorage(4);	/* RETURN-CODE */
    b_INP = new CobolDataStorage(32);	/* INP */
    b_s1 = new CobolDataStorage(10);	/* s1 */
    b_s2 = new CobolDataStorage(10);	/* s2 */
    b_s3 = new CobolDataStorage(10);	/* s3 */

    /* End of data storage */


    initAttr();

    /* Fields */

    /* PROGRAM-ID : ABC_059_A */
    f_INP	= CobolFieldFactory.makeCobolField(32, b_INP, a_1_Alphanumeric);	/* INP */
    f_s1	= CobolFieldFactory.makeCobolField(10, b_s1, a_1_Alphanumeric);	/* s1 */
    f_s2	= CobolFieldFactory.makeCobolField(10, b_s2, a_1_Alphanumeric);	/* s2 */
    f_s3	= CobolFieldFactory.makeCobolField(10, b_s3, a_1_Alphanumeric);	/* s3 */

    /* End of fields */


  }

  private void initAttr() {
    /* Attributes */

    a_1_Alphanumeric = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_ALPHANUMERIC,
      /* digits= */ 0,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);

  }

  /* Data storage */

  /* PROGRAM-ID : ABC_059_A */
  public CobolDataStorage b_RETURN_CODE;	/* RETURN-CODE */
  private CobolDataStorage b_INP;	/* INP */
  private CobolDataStorage b_s1;	/* s1 */
  private CobolDataStorage b_s2;	/* s2 */
  private CobolDataStorage b_s3;	/* s3 */

  /* End of data storage */


  /* Fields */

  /* PROGRAM-ID : ABC_059_A */
  private AbstractCobolField f_INP;	/* INP */
  private AbstractCobolField f_s1;	/* s1 */
  private AbstractCobolField f_s2;	/* s2 */
  private AbstractCobolField f_s3;	/* s3 */

  /* End of fields */


  private static AbstractCobolField f_native;

  /* Attributes */

  private CobolFieldAttribute a_1_Alphanumeric;




  /* Sections and Labels */
  private final static int l_ABC_059_A = 1;
  private final static int l_MAIN_SECTION = 2;
  private final static int l_MAIN_SECTION__MAIN = 3;
  private final static int l_Default_Error_Handler = 4;

}
