/* Generated by opensource COBOL 4J 1.1.16 */
import java.io.UnsupportedEncodingException;
import jp.osscons.opensourcecobol.libcobj.*;
import jp.osscons.opensourcecobol.libcobj.common.*;
import jp.osscons.opensourcecobol.libcobj.data.*;
import jp.osscons.opensourcecobol.libcobj.exceptions.*;
import jp.osscons.opensourcecobol.libcobj.termio.*;
import jp.osscons.opensourcecobol.libcobj.call.*;
import jp.osscons.opensourcecobol.libcobj.file.*;
import jp.osscons.opensourcecobol.libcobj.ui.*;
import java.util.Optional;

public class ATCODER implements CobolRunnable {

  private boolean initialized = false;
  private CobolModule module;
  private int entry;

  private CobolRunnable cob_unifunc;


  @Override
  public int run(CobolDataStorage... argStorages) {
    return ATCODER_(0, argStorages);
  }

  @Override
  public void cancel() {
    ATCODER_(-1);
  }

  @Override
  public boolean isActive() {
    return false;
  }

  public CobolResultSet execute () {
    int returnCode = run_module(0);
    return new CobolResultSet(returnCode);
  }

  public int ATCODER_ (int entry, CobolDataStorage ...argStorages) {
    this.entry = entry;
    return this.run_module(entry);
  }

  int run_module (int entry) {
    this.module = new CobolModule(null, null, null, null, 0, '.', '$', ',', 1, 1, 1, 0, null );

    /* Start of function code */

    /* CANCEL callback handling */
    if (entry < 0) {
    	if (!this.initialized) {
    		CobolDecimal.cobInitNumeric();
    		return 0;
    	}
    	this.initialized = false;
    	return 0;
    }

    /* Push module stack */
    CobolModule.push (module);
    CobolResolve.pushCallStackList ("ATCODER");

    /* Initialize program */
    if (!this.initialized) {
      module.setProgramId("ATCODER");

      b_RETURN_CODE.set((int)0);
      b_indata.fillBytes(' ', 100);
      b_a1.fillBytes('0', 8);
      b_a2.fillBytes('0', 8);
      b_a3.fillBytes('0', 8);
      b_r.fillBytes('0', 8);
      b_g.fillBytes('0', 8);
      b_r2.fillBytes('0', 8);
      CobolFieldFactory.makeCobolField(21, b_disp, a_1_NumericEdited_Digits21_Scale0).moveFrom (CobolConstant.zero);
      this.initialized = true;
    }
    /* PROCEDURE DIVISION */
    try{
      /* Entry dispatch */
      execEntry(l_ATCODER);

    } catch(CobolStopRunException e) {
      CobolStopRunException.stopRun();
      System.exit(e.getReturnCode());
    }
    /* Pop module stack */
    CobolResolve.popCallStackList();
    CobolModule.pop();

    /* Program return */
    return b_RETURN_CODE.intValue();
  }
  public CobolControl[] contList = {
    new CobolControl(0, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_ATCODER]);
      }
    },
    /* Entry ATCODER */
    new CobolControl(l_ATCODER, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN]);
      }
    },
    /* MAIN SECTION */
    new CobolControl(l_MAIN, CobolControl.LabelType.section) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION__DEFAULT_PARAGRAPH]);
      }
    },
    /* MAIN_SECTION__DEFAULT_PARAGRAPH */
    new CobolControl(l_MAIN_SECTION__DEFAULT_PARAGRAPH, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* /content/temp_cobol/ATCODER_fixed.cob:14: ACCEPT */
        {
          CobolTerminal.accept (f_indata);
        }
        /* /content/temp_cobol/ATCODER_fixed.cob:16: UNSTRING */
        {
          CobolString.unstringInit (f_indata, 0, 1);
          CobolString.unstringDelimited (CobolConstant.space, 0);
          CobolString.unstringInto (f_a1, 0, 0);
          CobolString.unstringFinish ();
        }
        /* /content/temp_cobol/ATCODER_fixed.cob:17: IF */
        {
          if (((((long)b_a1.cmpNumdisp (8, 3) == 0L) || ((long)b_a1.cmpNumdisp (8, 5) == 0L)) || ((long)b_a1.cmpNumdisp (8, 7) == 0L)))
            {
              /* /content/temp_cobol/ATCODER_fixed.cob:18: DISPLAY */
              {
                CobolTerminal.display (0, 1, 1, c_1_YES);
              }
            }
          else
            {
              /* /content/temp_cobol/ATCODER_fixed.cob:20: DISPLAY */
              {
                CobolTerminal.display (0, 1, 1, c_2_NO);
              }
            }
        }
        /* /content/temp_cobol/ATCODER_fixed.cob:23: STOP */
        {
          CobolStopRunException.throwException (b_RETURN_CODE.intValue());
        }
        return Optional.of(CobolControl.pure());
      }
    },
    CobolControl.pure()
  };
  public void execEntry(int start) throws CobolRuntimeException, CobolStopRunException {
    Optional<CobolControl> nextLabel = Optional.of(contList[start]);
    while(nextLabel.isPresent()) {
      CobolControl section = nextLabel.get();
      nextLabel = section.run();
    }
  }

  public static void main(String[] args)
  {
    CobolUtil.cob_init(args, false);
    CobolDecimal.cobInitNumeric();
    new ATCODER().ATCODER_(0);
    CobolStopRunException.stopRun();
  }

  public ATCODER()
  {
    init();
  }

  public void init() 
  {
    /* Data storage */

    cob_unifunc = null;

    /* PROGRAM-ID : ATCODER */
    b_RETURN_CODE = new CobolDataStorage(4);	/* RETURN-CODE */
    b_indata = new CobolDataStorage(100);	/* indata */
    b_a1 = new CobolDataStorage(8);	/* a1 */
    b_a2 = new CobolDataStorage(8);	/* a2 */
    b_a3 = new CobolDataStorage(8);	/* a3 */
    b_r = new CobolDataStorage(8);	/* r */
    b_g = new CobolDataStorage(8);	/* g */
    b_r2 = new CobolDataStorage(8);	/* r2 */
    b_disp = new CobolDataStorage(21);	/* disp */

    /* End of data storage */


    initAttr();

    /* Fields */

    /* PROGRAM-ID : ATCODER */
    f_indata	= CobolFieldFactory.makeCobolField(100, b_indata, a_2_Alphanumeric);	/* indata */
    f_a1	= CobolFieldFactory.makeCobolField(8, b_a1, a_3_NumericDisplay_Digits8_Scale0);	/* a1 */

    /* End of fields */


    /* Constants */

    c_1_YES	= CobolFieldFactory.makeCobolField(str_0_YES, a_2_Alphanumeric);
    c_2_NO	= CobolFieldFactory.makeCobolField(str_1_NO, a_2_Alphanumeric);

  }

  private void initAttr() {
    /* Attributes */

    a_1_NumericEdited_Digits21_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_EDITED,
      /* digits= */ 21,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ "Z\024\000\000\0009\001\000\000\000");
    a_2_Alphanumeric = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_ALPHANUMERIC,
      /* digits= */ 0,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_3_NumericDisplay_Digits8_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 8,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);

  }

  /* Data storage */

  /* PROGRAM-ID : ATCODER */
  public CobolDataStorage b_RETURN_CODE;	/* RETURN-CODE */
  private CobolDataStorage b_indata;	/* indata */
  private CobolDataStorage b_a1;	/* a1 */
  private CobolDataStorage b_a2;	/* a2 */
  private CobolDataStorage b_a3;	/* a3 */
  private CobolDataStorage b_r;	/* r */
  private CobolDataStorage b_g;	/* g */
  private CobolDataStorage b_r2;	/* r2 */
  private CobolDataStorage b_disp;	/* disp */

  /* End of data storage */


  /* Fields */

  /* PROGRAM-ID : ATCODER */
  private AbstractCobolField f_indata;	/* indata */
  private AbstractCobolField f_a1;	/* a1 */

  /* End of fields */


  private static AbstractCobolField f_native;

  /* Constants */

  private AbstractCobolField c_2_NO;
  private AbstractCobolField c_1_YES;

  /* Attributes */

  private CobolFieldAttribute a_3_NumericDisplay_Digits8_Scale0;
  private CobolFieldAttribute a_2_Alphanumeric;
  private CobolFieldAttribute a_1_NumericEdited_Digits21_Scale0;



  /* String literals */
  public static final byte[] str_1_NO = CobolUtil.stringToBytes("NO");
  public static final byte[] str_0_YES = CobolUtil.stringToBytes("YES");

  /* Sections and Labels */
  private final static int l_ATCODER = 1;
  private final static int l_MAIN = 2;
  private final static int l_MAIN_SECTION__DEFAULT_PARAGRAPH = 3;
  private final static int l_Default_Error_Handler = 4;

}
