/* Generated by opensource COBOL 4J 1.1.16 */
import java.io.UnsupportedEncodingException;
import jp.osscons.opensourcecobol.libcobj.*;
import jp.osscons.opensourcecobol.libcobj.common.*;
import jp.osscons.opensourcecobol.libcobj.data.*;
import jp.osscons.opensourcecobol.libcobj.exceptions.*;
import jp.osscons.opensourcecobol.libcobj.termio.*;
import jp.osscons.opensourcecobol.libcobj.call.*;
import jp.osscons.opensourcecobol.libcobj.file.*;
import jp.osscons.opensourcecobol.libcobj.ui.*;
import java.util.Optional;

public class _3161C implements CobolRunnable {

  private boolean initialized = false;
  private CobolModule module;
  private int entry;

  private CobolRunnable cob_unifunc;


  @Override
  public int run(CobolDataStorage... argStorages) {
    return _3161C_(0, argStorages);
  }

  @Override
  public void cancel() {
    _3161C_(-1);
  }

  @Override
  public boolean isActive() {
    return false;
  }

  public CobolResultSet execute () {
    int returnCode = run_module(0);
    return new CobolResultSet(returnCode);
  }

  public int _3161C_ (int entry, CobolDataStorage ...argStorages) {
    this.entry = entry;
    return this.run_module(entry);
  }

  int run_module (int entry) {
    this.module = new CobolModule(null, null, null, null, 0, '.', '$', ',', 1, 1, 1, 0, null );

    /* Start of function code */

    /* CANCEL callback handling */
    if (entry < 0) {
    	if (!this.initialized) {
    		CobolDecimal.cobInitNumeric();
    		return 0;
    	}
    	d0.clear();
    	d0.setScale(0);
    	d1.clear();
    	d1.setScale(0);
    	d2.clear();
    	d2.setScale(0);
    	this.initialized = false;
    	return 0;
    }

    /* Push module stack */
    CobolModule.push (module);
    CobolResolve.pushCallStackList ("_3161C");

    /* Initialize program */
    if (!this.initialized) {
      module.setProgramId("_3161C");

      /* Initialize decimal numbers */
      d0.decimalInit();
      d1.decimalInit();
      d2.decimalInit();

      b_RETURN_CODE.set((int)0);
      b_INP.fillBytes(' ', 41);
      b_NX.fillBytes(' ', 19);
      b_KX.fillBytes(' ', 19);
      b_N.fillBytes(0, 8);
      b_K.fillBytes(0, 8);
      b_S.fillBytes(0, 8);
      b_A.fillBytes(0, 8);
      f_ANS.moveFrom (CobolConstant.zero);
      this.initialized = true;
    }
    /* PROCEDURE DIVISION */
    try{
      /* Entry dispatch */
      execEntry(l__3161C);

    } catch(CobolStopRunException e) {
      CobolStopRunException.stopRun();
      System.exit(e.getReturnCode());
    }
    /* Pop module stack */
    CobolResolve.popCallStackList();
    CobolModule.pop();

    /* Program return */
    return b_RETURN_CODE.intValue();
  }
  public CobolControl[] contList = {
    new CobolControl(0, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l__3161C]);
      }
    },
    /* Entry 161C */
    new CobolControl(l__3161C, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN]);
      }
    },
    /* MAIN SECTION */
    new CobolControl(l_MAIN, CobolControl.LabelType.section) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION__DEFAULT_PARAGRAPH]);
      }
    },
    /* MAIN_SECTION__DEFAULT_PARAGRAPH */
    new CobolControl(l_MAIN_SECTION__DEFAULT_PARAGRAPH, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* /content/temp_cobol/161C_fixed.cob:15: ACCEPT */
        {
          CobolTerminal.accept (f_INP);
        }
        /* /content/temp_cobol/161C_fixed.cob:16: UNSTRING */
        {
          CobolString.unstringInit (f_INP, 0, 1);
          CobolString.unstringDelimited (c_1, 0);
          CobolString.unstringInto (f_NX, 0, 0);
          CobolString.unstringInto (f_KX, 0, 0);
          CobolString.unstringFinish ();
        }
        /* /content/temp_cobol/161C_fixed.cob:19: EVALUATE */
        {
          if ((((long)b_NX.memcmp (str_0_1000000000000000000, 19) == 0L) && ((long)b_KX.memcmp (str_1_1000000000000000000, 19) == 0L)))
            {
              /* /content/temp_cobol/161C_fixed.cob:22: MOVE */
              {
                b_N.setSwpU64Binary (1);
              }
              /* /content/temp_cobol/161C_fixed.cob:23: MOVE */
              {
                b_N.setSwpU64Binary (1);
              }
            }
          else
            if (((long)b_NX.memcmp (str_2_1000000000000000000, 19) == 0L))
              {
                /* /content/temp_cobol/161C_fixed.cob:25: MOVE */
                {
                  f_K.moveFrom (f_KX);
                }
                /* /content/temp_cobol/161C_fixed.cob:26: COMPUTE */
                {
                  {
                    {
                      d0.setField (c_2_999999999999999999);
                      d2.setField (f_K);
                      d0.sub (d2);
                      d1.set (1);
                      d0.add (d1);
                      d0.getField (f_N, 4);
                    }
                  }
                }
              }
            else
              if (((long)b_KX.memcmp (str_3_1000000000000000000, 19) == 0L))
                {
                  /* /content/temp_cobol/161C_fixed.cob:28: MOVE */
                  {
                    f_N.moveFrom (f_NX);
                  }
                  /* /content/temp_cobol/161C_fixed.cob:29: COMPUTE */
                  {
                    {
                      {
                        d0.setField (c_2_999999999999999999);
                        d2.setField (f_N);
                        d0.sub (d2);
                        d1.set (1);
                        d0.add (d1);
                        d0.getField (f_K, 4);
                      }
                    }
                  }
                }
              else
                {
                  /* /content/temp_cobol/161C_fixed.cob:31: MOVE */
                  {
                    f_N.moveFrom (f_NX);
                  }
                  /* /content/temp_cobol/161C_fixed.cob:32: MOVE */
                  {
                    f_K.moveFrom (f_KX);
                  }
                }
        }
        /* /content/temp_cobol/161C_fixed.cob:35: DIVIDE */
        {
          f_N.divQuotient (f_K, f_S, 4);
          f_A.divRemainder (4);
        }
        /* /content/temp_cobol/161C_fixed.cob:36: EVALUATE */
        {
          if (((long)f_A.cmpInteger (0) == 0L))
            {
              /* /content/temp_cobol/161C_fixed.cob:38: MOVE */
              {
                f_ANS.moveFrom (c_3_0);
              }
            }
          else
            if (((long)            (new GetInt() {
              public int run() throws CobolStopRunException {
                d0.setField (f_A);
                d1.setField (f_K);
                d2.set (2);
                d1.div (d2);
                return 
                d0.compareTo (d1);
            }
          }).run() <= 0L))
            {
              /* /content/temp_cobol/161C_fixed.cob:40: MOVE */
              {
                f_ANS.moveFrom (f_A);
              }
            }
          else
            {
              /* /content/temp_cobol/161C_fixed.cob:42: COMPUTE */
              {
                {
                  {
                    d0.setField (f_K);
                    d1.setField (f_A);
                    d0.sub (d1);
                    d0.getField (f_ANS, 4);
                  }
                }
              }
            }
      }
      /* /content/temp_cobol/161C_fixed.cob:45: DISPLAY */
      {
        CobolTerminal.display (0, 1, 1, CobolIntrinsic.funcTrim (0, 0, f_ANS, 0));
      }
      /* /content/temp_cobol/161C_fixed.cob:46: STOP */
      {
        CobolStopRunException.throwException (b_RETURN_CODE.intValue());
      }
      return Optional.of(CobolControl.pure());
    }
  },
  CobolControl.pure()
};
public void execEntry(int start) throws CobolRuntimeException, CobolStopRunException {
  Optional<CobolControl> nextLabel = Optional.of(contList[start]);
  while(nextLabel.isPresent()) {
    CobolControl section = nextLabel.get();
    nextLabel = section.run();
  }
}

public static void main(String[] args)
{
  CobolUtil.cob_init(args, false);
  CobolDecimal.cobInitNumeric();
  new _3161C()._3161C_(0);
  CobolStopRunException.stopRun();
}

public _3161C()
{
  init();
}

public void init() 
{
  /* Decimal structures */

  d0 = new CobolDecimal();
  d1 = new CobolDecimal();
  d2 = new CobolDecimal();

  /* Data storage */

  cob_unifunc = null;

  /* PROGRAM-ID : 161C */
  b_RETURN_CODE = new CobolDataStorage(4);	/* RETURN-CODE */
  b_INP = new CobolDataStorage(41);	/* INP */
  b_NX = new CobolDataStorage(19);	/* NX */
  b_KX = new CobolDataStorage(19);	/* KX */
  b_N = new CobolDataStorage(8);	/* N */
  b_K = new CobolDataStorage(8);	/* K */
  b_S = new CobolDataStorage(8);	/* S */
  b_A = new CobolDataStorage(8);	/* A */
  b_ANS = new CobolDataStorage(18);	/* ANS */

  /* End of data storage */


  initAttr();

  /* Fields */

  /* PROGRAM-ID : 161C */
  f_INP	= CobolFieldFactory.makeCobolField(41, b_INP, a_2_Alphanumeric);	/* INP */
  f_NX	= CobolFieldFactory.makeCobolField(19, b_NX, a_2_Alphanumeric);	/* NX */
  f_KX	= CobolFieldFactory.makeCobolField(19, b_KX, a_2_Alphanumeric);	/* KX */
  f_N	= CobolFieldFactory.makeCobolField(8, b_N, a_3_NumericBinary_Digits18_Scale0_BinarySwap);	/* N */
  f_K	= CobolFieldFactory.makeCobolField(8, b_K, a_3_NumericBinary_Digits18_Scale0_BinarySwap);	/* K */
  f_S	= CobolFieldFactory.makeCobolField(8, b_S, a_3_NumericBinary_Digits18_Scale0_BinarySwap);	/* S */
  f_A	= CobolFieldFactory.makeCobolField(8, b_A, a_3_NumericBinary_Digits18_Scale0_BinarySwap);	/* A */
  f_ANS	= CobolFieldFactory.makeCobolField(18, b_ANS, a_1_NumericEdited_Digits18_Scale0);	/* ANS */

  /* End of fields */


  /* Constants */

  c_1	= CobolFieldFactory.makeCobolField(str_4, a_2_Alphanumeric);
  c_2_999999999999999999	= CobolFieldFactory.makeCobolField(18, "999999999999999999", a_4_NumericDisplay_Digits18_Scale0);
  c_3_0	= CobolFieldFactory.makeCobolField(1, "0", a_5_NumericDisplay_Digits1_Scale0);

}

private void initAttr() {
  /* Attributes */

  a_1_NumericEdited_Digits18_Scale0 = new CobolFieldAttribute(
    CobolFieldAttribute.COB_TYPE_NUMERIC_EDITED,
    /* digits= */ 18,
    /* scale= */ 0,
    CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
    /* pic= */ "Z\021\000\000\0009\001\000\000\000");
  a_2_Alphanumeric = new CobolFieldAttribute(
    CobolFieldAttribute.COB_TYPE_ALPHANUMERIC,
    /* digits= */ 0,
    /* scale= */ 0,
    CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
    /* pic= */ null);
  a_3_NumericBinary_Digits18_Scale0_BinarySwap = new CobolFieldAttribute(
    CobolFieldAttribute.COB_TYPE_NUMERIC_BINARY,
    /* digits= */ 18,
    /* scale= */ 0,
    CobolFieldAttribute.COB_FLAG_BINARY_SWAP,
    /* pic= */ null);
  a_4_NumericDisplay_Digits18_Scale0 = new CobolFieldAttribute(
    CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
    /* digits= */ 18,
    /* scale= */ 0,
    CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
    /* pic= */ null);
  a_5_NumericDisplay_Digits1_Scale0 = new CobolFieldAttribute(
    CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
    /* digits= */ 1,
    /* scale= */ 0,
    CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
    /* pic= */ null);

}

/* Decimal structures */

private CobolDecimal d0;
private CobolDecimal d1;
private CobolDecimal d2;

/* Data storage */

/* PROGRAM-ID : 161C */
public CobolDataStorage b_RETURN_CODE;	/* RETURN-CODE */
private CobolDataStorage b_INP;	/* INP */
private CobolDataStorage b_NX;	/* NX */
private CobolDataStorage b_KX;	/* KX */
private CobolDataStorage b_N;	/* N */
private CobolDataStorage b_K;	/* K */
private CobolDataStorage b_S;	/* S */
private CobolDataStorage b_A;	/* A */
private CobolDataStorage b_ANS;	/* ANS */

/* End of data storage */


/* Fields */

/* PROGRAM-ID : 161C */
private AbstractCobolField f_INP;	/* INP */
private AbstractCobolField f_NX;	/* NX */
private AbstractCobolField f_KX;	/* KX */
private AbstractCobolField f_N;	/* N */
private AbstractCobolField f_K;	/* K */
private AbstractCobolField f_S;	/* S */
private AbstractCobolField f_A;	/* A */
private AbstractCobolField f_ANS;	/* ANS */

/* End of fields */


private static AbstractCobolField f_native;

/* Constants */

private AbstractCobolField c_3_0;
private AbstractCobolField c_2_999999999999999999;
private AbstractCobolField c_1;

/* Attributes */

private CobolFieldAttribute a_5_NumericDisplay_Digits1_Scale0;
private CobolFieldAttribute a_4_NumericDisplay_Digits18_Scale0;
private CobolFieldAttribute a_3_NumericBinary_Digits18_Scale0_BinarySwap;
private CobolFieldAttribute a_2_Alphanumeric;
private CobolFieldAttribute a_1_NumericEdited_Digits18_Scale0;



/* String literals */
public static final byte[] str_4 = CobolUtil.stringToBytes(" ");
public static final byte[] str_3_1000000000000000000 = CobolUtil.stringToBytes("1000000000000000000");
public static final byte[] str_2_1000000000000000000 = CobolUtil.stringToBytes("1000000000000000000");
public static final byte[] str_1_1000000000000000000 = CobolUtil.stringToBytes("1000000000000000000");
public static final byte[] str_0_1000000000000000000 = CobolUtil.stringToBytes("1000000000000000000");

/* Sections and Labels */
private final static int l__3161C = 1;
private final static int l_MAIN = 2;
private final static int l_MAIN_SECTION__DEFAULT_PARAGRAPH = 3;
private final static int l_Default_Error_Handler = 4;

}
