/* Generated by opensource COBOL 4J 1.1.16 */
import java.io.UnsupportedEncodingException;
import jp.osscons.opensourcecobol.libcobj.*;
import jp.osscons.opensourcecobol.libcobj.common.*;
import jp.osscons.opensourcecobol.libcobj.data.*;
import jp.osscons.opensourcecobol.libcobj.exceptions.*;
import jp.osscons.opensourcecobol.libcobj.termio.*;
import jp.osscons.opensourcecobol.libcobj.call.*;
import jp.osscons.opensourcecobol.libcobj.file.*;
import jp.osscons.opensourcecobol.libcobj.ui.*;
import java.util.Optional;

public class _3175A implements CobolRunnable {

  private boolean initialized = false;
  private CobolModule module;
  private int entry;

  private CobolRunnable cob_unifunc;


  @Override
  public int run(CobolDataStorage... argStorages) {
    return _3175A_(0, argStorages);
  }

  @Override
  public void cancel() {
    _3175A_(-1);
  }

  @Override
  public boolean isActive() {
    return false;
  }

  public CobolResultSet execute () {
    int returnCode = run_module(0);
    return new CobolResultSet(returnCode);
  }

  public int _3175A_ (int entry, CobolDataStorage ...argStorages) {
    this.entry = entry;
    return this.run_module(entry);
  }

  int run_module (int entry) {
    this.module = new CobolModule(null, null, null, null, 0, '.', '$', ',', 1, 1, 1, 0, null );

    /* Start of function code */

    /* CANCEL callback handling */
    if (entry < 0) {
    	if (!this.initialized) {
    		CobolDecimal.cobInitNumeric();
    		return 0;
    	}
    	this.initialized = false;
    	return 0;
    }

    /* Push module stack */
    CobolModule.push (module);
    CobolResolve.pushCallStackList ("_3175A");

    /* Initialize program */
    if (!this.initialized) {
      module.setProgramId("_3175A");

      b_RETURN_CODE.set((int)0);
      b_S.fillBytes(' ', 3);
      b_OUT.setByte('0');
      this.initialized = true;
    }
    /* PROCEDURE DIVISION */
    try{
      /* Entry dispatch */
      execEntry(l__3175A);

    } catch(CobolStopRunException e) {
      CobolStopRunException.stopRun();
      System.exit(e.getReturnCode());
    }
    /* Pop module stack */
    CobolResolve.popCallStackList();
    CobolModule.pop();

    /* Program return */
    return b_RETURN_CODE.intValue();
  }
  public CobolControl[] contList = {
    new CobolControl(0, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l__3175A]);
      }
    },
    /* Entry 175A */
    new CobolControl(l__3175A, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN]);
      }
    },
    /* MAIN SECTION */
    new CobolControl(l_MAIN, CobolControl.LabelType.section) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION__DEFAULT_PARAGRAPH]);
      }
    },
    /* MAIN_SECTION__DEFAULT_PARAGRAPH */
    new CobolControl(l_MAIN_SECTION__DEFAULT_PARAGRAPH, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* /content/temp_cobol/175A_fixed.cob:9: ACCEPT */
        {
          CobolTerminal.accept (f_S);
        }
        /* /content/temp_cobol/175A_fixed.cob:11: EVALUATE */
        {
          if (((long)b_S.memcmp (str_0_RRR, 3) == 0L))
            {
              /* /content/temp_cobol/175A_fixed.cob:13: MOVE */
              {
                b_OUT.setByte(51);
              }
            }
          else
            if ((((long)b_S.getSubDataStorage(0).memcmp (str_1_RR, 2) == 0L) || ((long)b_S.getSubDataStorage(1).memcmp (str_2_RR, 2) == 0L)))
              {
                /* /content/temp_cobol/175A_fixed.cob:15: MOVE */
                {
                  b_OUT.setByte(50);
                }
              }
            else
              if (((((long)(Byte.toUnsignedInt(b_S.getSubDataStorage(0).getByte(0)) - (int)82) == 0L) || ((long)(Byte.toUnsignedInt(b_S.getSubDataStorage(1).getByte(0)) - (int)82) == 0L)) || ((long)(Byte.toUnsignedInt(b_S.getSubDataStorage(2).getByte(0)) - (int)82) == 0L)))
                {
                  /* /content/temp_cobol/175A_fixed.cob:17: MOVE */
                  {
                    b_OUT.setByte(49);
                  }
                }
              else
                {
                  /* /content/temp_cobol/175A_fixed.cob:19: MOVE */
                  {
                    b_OUT.setByte(48);
                  }
                }
        }
        /* /content/temp_cobol/175A_fixed.cob:22: DISPLAY */
        {
          CobolTerminal.display (0, 1, 1, f_OUT);
        }
        /* /content/temp_cobol/175A_fixed.cob:23: STOP */
        {
          CobolStopRunException.throwException (b_RETURN_CODE.intValue());
        }
        return Optional.of(CobolControl.pure());
      }
    },
    CobolControl.pure()
  };
  public void execEntry(int start) throws CobolRuntimeException, CobolStopRunException {
    Optional<CobolControl> nextLabel = Optional.of(contList[start]);
    while(nextLabel.isPresent()) {
      CobolControl section = nextLabel.get();
      nextLabel = section.run();
    }
  }

  public static void main(String[] args)
  {
    CobolUtil.cob_init(args, false);
    CobolDecimal.cobInitNumeric();
    new _3175A()._3175A_(0);
    CobolStopRunException.stopRun();
  }

  public _3175A()
  {
    init();
  }

  public void init() 
  {
    /* Data storage */

    cob_unifunc = null;

    /* PROGRAM-ID : 175A */
    b_RETURN_CODE = new CobolDataStorage(4);	/* RETURN-CODE */
    b_S = new CobolDataStorage(3);	/* S */
    b_OUT = new CobolDataStorage(1);	/* OUT */

    /* End of data storage */


    initAttr();

    /* Fields */

    /* PROGRAM-ID : 175A */
    f_S	= CobolFieldFactory.makeCobolField(3, b_S, a_1_Alphanumeric);	/* S */
    f_OUT	= CobolFieldFactory.makeCobolField(1, b_OUT, a_2_NumericDisplay_Digits1_Scale0);	/* OUT */

    /* End of fields */


  }

  private void initAttr() {
    /* Attributes */

    a_1_Alphanumeric = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_ALPHANUMERIC,
      /* digits= */ 0,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_2_NumericDisplay_Digits1_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 1,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);

  }

  /* Data storage */

  /* PROGRAM-ID : 175A */
  public CobolDataStorage b_RETURN_CODE;	/* RETURN-CODE */
  private CobolDataStorage b_S;	/* S */
  private CobolDataStorage b_OUT;	/* OUT */

  /* End of data storage */


  /* Fields */

  /* PROGRAM-ID : 175A */
  private AbstractCobolField f_S;	/* S */
  private AbstractCobolField f_OUT;	/* OUT */

  /* End of fields */


  private static AbstractCobolField f_native;

  /* Attributes */

  private CobolFieldAttribute a_2_NumericDisplay_Digits1_Scale0;
  private CobolFieldAttribute a_1_Alphanumeric;



  /* String literals */
  public static final byte[] str_2_RR = CobolUtil.stringToBytes("RR");
  public static final byte[] str_1_RR = CobolUtil.stringToBytes("RR");
  public static final byte[] str_0_RRR = CobolUtil.stringToBytes("RRR");

  /* Sections and Labels */
  private final static int l__3175A = 1;
  private final static int l_MAIN = 2;
  private final static int l_MAIN_SECTION__DEFAULT_PARAGRAPH = 3;
  private final static int l_Default_Error_Handler = 4;

}
