/* Generated by opensource COBOL 4J 1.1.16 */
import java.io.UnsupportedEncodingException;
import jp.osscons.opensourcecobol.libcobj.*;
import jp.osscons.opensourcecobol.libcobj.common.*;
import jp.osscons.opensourcecobol.libcobj.data.*;
import jp.osscons.opensourcecobol.libcobj.exceptions.*;
import jp.osscons.opensourcecobol.libcobj.termio.*;
import jp.osscons.opensourcecobol.libcobj.call.*;
import jp.osscons.opensourcecobol.libcobj.file.*;
import jp.osscons.opensourcecobol.libcobj.ui.*;
import java.util.Optional;

public class ABC_096_B implements CobolRunnable {

  private boolean initialized = false;
  private CobolModule module;
  private int entry;

  private CobolRunnable cob_unifunc;


  @Override
  public int run(CobolDataStorage... argStorages) {
    return ABC_096_B_(0, argStorages);
  }

  @Override
  public void cancel() {
    ABC_096_B_(-1);
  }

  @Override
  public boolean isActive() {
    return false;
  }

  public CobolResultSet execute () {
    int returnCode = run_module(0);
    return new CobolResultSet(returnCode);
  }

  public int ABC_096_B_ (int entry, CobolDataStorage ...argStorages) {
    this.entry = entry;
    return this.run_module(entry);
  }

  int run_module (int entry) {
    this.module = new CobolModule(null, null, null, null, 0, '.', '$', ',', 1, 1, 1, 0, null );

    /* Start of function code */

    /* CANCEL callback handling */
    if (entry < 0) {
    	if (!this.initialized) {
    		CobolDecimal.cobInitNumeric();
    		return 0;
    	}
    	d0.clear();
    	d0.setScale(0);
    	d1.clear();
    	d1.setScale(0);
    	d2.clear();
    	d2.setScale(0);
    	this.initialized = false;
    	return 0;
    }

    /* Push module stack */
    CobolModule.push (module);
    CobolResolve.pushCallStackList ("ABC_096_B");

    /* Initialize program */
    if (!this.initialized) {
      module.setProgramId("ABC_096_B");

      /* Initialize decimal numbers */
      d0.decimalInit();
      d1.decimalInit();
      d2.decimalInit();

      b_RETURN_CODE.set((int)0);
      b_INP.fillBytes(' ', 10);
      b_K.fillBytes('0', 2);
      b_maxlen.setByte(51);
      b_cur.setBytes (str_0_01, 2);
      b_i.setBytes (str_1_000000000000000001, 18);
      b_j.fillBytes('0', 18);
      b_len.fillBytes('0', 2);
      b_mx.fillBytes('0', 5);
      b_tmp.fillBytes('0', 5);
      b_ans.fillBytes(' ', 5);
      f_ZS.moveFrom (CobolConstant.zero);
      b_ABC1.fillBytes('0', 6);
      b_DUMMY.setByte(' ');
      this.initialized = true;
    }
    /* PROCEDURE DIVISION */
    try{
      /* Entry dispatch */
      execEntry(l_ABC_096_B);

    } catch(CobolStopRunException e) {
      CobolStopRunException.stopRun();
      System.exit(e.getReturnCode());
    }
    /* Pop module stack */
    CobolResolve.popCallStackList();
    CobolModule.pop();

    /* Program return */
    return b_RETURN_CODE.intValue();
  }
  public CobolControl[] contList = {
    new CobolControl(0, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_ABC_096_B]);
      }
    },
    /* Entry ABC_096_B */
    new CobolControl(l_ABC_096_B, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION]);
      }
    },
    /* MAIN SECTION */
    new CobolControl(l_MAIN_SECTION, CobolControl.LabelType.section) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION__MAIN]);
      }
    },
    /* MAIN */
    new CobolControl(l_MAIN_SECTION__MAIN, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* /content/temp_cobol/ABC_096_B_fixed.cob:27: ACCEPT */
        {
          CobolTerminal.accept (f_INP);
        }
        /* /content/temp_cobol/ABC_096_B_fixed.cob:29: ACCEPT */
        {
          CobolTerminal.accept (f_K);
        }
        /* /content/temp_cobol/ABC_096_B_fixed.cob:31: PERFORM */
        for (int n0 = b_maxlen.getNumdisp(1); n0 > 0; n0--)
        {
          {
            /* /content/temp_cobol/ABC_096_B_fixed.cob:33: PERFORM */
            f_j.moveFrom (f_cur);
            for(;;f_j.addInt (1))
            {
              if (((long)(Byte.toUnsignedInt(b_INP.getSubDataStorage((f_j.getInt() - 1)).getByte(0)) - (int)' ') == 0L))
                break;
              ;
            }
            /* /content/temp_cobol/ABC_096_B_fixed.cob:37: COMPUTE */
            {
              {
                {
                  d0.setField (f_j);
                  d1.set (b_cur.getNumdisp(2));
                  d0.sub (d1);
                  d0.getField (f_len, 4);
                }
              }
            }
            /* /content/temp_cobol/ABC_096_B_fixed.cob:39: MOVE */
            {
              CobolFieldFactory.makeCobolField(2, b_ABC__ABC11__ABC1.getSubDataStorage(2 * (f_i.getInt() - 1)), a_3_NumericDisplay_Digits2_Scale0).moveFrom (CobolFieldFactory.makeCobolField(b_len.getNumdisp(2), b_INP.getSubDataStorage((b_cur.getNumdisp(2) - 1)), a_2_Alphanumeric));
            }
            /* /content/temp_cobol/ABC_096_B_fixed.cob:41: COMPUTE */
            {
              {
                {
                  d0.setField (f_j);
                  d1.set (1);
                  d0.add (d1);
                  d0.getField (f_cur, 4);
                }
              }
            }
            /* /content/temp_cobol/ABC_096_B_fixed.cob:43: ADD */
            {
              f_i.add (c_1_1, 4);
            }
          }
        }
        /* /content/temp_cobol/ABC_096_B_fixed.cob:47: ADD */
        {
          {
            {
              d0.set (b_ABC__ABC11__ABC1.getSubDataStorage(2 * 0).getNumdisp(2));
              d2.set (b_ABC__ABC11__ABC1.getSubDataStorage(2 * 1).getNumdisp(2));
              d0.add (d2);
              d1.set (b_ABC__ABC11__ABC1.getSubDataStorage(2 * 2).getNumdisp(2));
              d0.add (d1);
              d1.set (b_tmp.getNumdisp(5));
              d1.add (d0);
              d1.getField (f_tmp, 4);
            }
          }
        }
        /* /content/temp_cobol/ABC_096_B_fixed.cob:48: COMPUTE */
        {
          {
            {
              d0.setField (CobolIntrinsic.funcMax (3, CobolFieldFactory.makeCobolField(2, b_ABC__ABC11__ABC1.getSubDataStorage(2 * 0), a_3_NumericDisplay_Digits2_Scale0), CobolFieldFactory.makeCobolField(2, b_ABC__ABC11__ABC1.getSubDataStorage(2 * 1), a_3_NumericDisplay_Digits2_Scale0), CobolFieldFactory.makeCobolField(2, b_ABC__ABC11__ABC1.getSubDataStorage(2 * 2), a_3_NumericDisplay_Digits2_Scale0)));
              d0.getField (f_mx, 4);
            }
          }
        }
        /* /content/temp_cobol/ABC_096_B_fixed.cob:50: SUBTRACT */
        {
          f_tmp.sub (f_mx, 4);
        }
        /* /content/temp_cobol/ABC_096_B_fixed.cob:51: COMPUTE */
        {
          {
            {
              d0.set (b_mx.getNumdisp(5));
              d1.set (2);
              d2.set (b_K.getNumdisp(2));
              d1.pow (d2);
              d0.mul (d1);
              d0.getField (f_mx, 4);
            }
          }
        }
        /* /content/temp_cobol/ABC_096_B_fixed.cob:52: ADD */
        {
          f_tmp.add (f_mx, 4);
        }
        /* /content/temp_cobol/ABC_096_B_fixed.cob:54: MOVE */
        {
          f_ZS.moveFrom (f_tmp);
        }
        /* /content/temp_cobol/ABC_096_B_fixed.cob:56: PERFORM */
        /* PERFORM UNANS */
        CobolControl.perform(contList, l_UNANS).run();
        /* /content/temp_cobol/ABC_096_B_fixed.cob:58: DISPLAY */
        {
          CobolTerminal.display (0, 1, 1, CobolFieldFactory.makeCobolField(CobolIntrinsic.funcStoredCharLength (f_ans).getInt(), b_ans.getSubDataStorage(0), a_2_Alphanumeric));
        }
        /* /content/temp_cobol/ABC_096_B_fixed.cob:59: STOP */
        {
          CobolStopRunException.throwException (b_RETURN_CODE.intValue());
        }

        return Optional.of(contList[l_UNANS]);
      }
    },
    /* UNANS SECTION */
    new CobolControl(l_UNANS, CobolControl.LabelType.section) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_UNANS_SECTION__DEFAULT_PARAGRAPH]);
      }
    },
    /* UNANS_SECTION__DEFAULT_PARAGRAPH */
    new CobolControl(l_UNANS_SECTION__DEFAULT_PARAGRAPH, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* /content/temp_cobol/ABC_096_B_fixed.cob:62: UNSTRING */
        {
          CobolString.unstringInit (f_ZS, 0, 1);
          CobolString.unstringDelimited (CobolConstant.space, 1);
          CobolString.unstringInto (f_DUMMY, 0, 0);
          CobolString.unstringInto (f_ans, 0, 0);
          CobolString.unstringFinish ();
        }
        return Optional.of(CobolControl.pure());
      }
    },
    CobolControl.pure()
  };
  public void execEntry(int start) throws CobolRuntimeException, CobolStopRunException {
    Optional<CobolControl> nextLabel = Optional.of(contList[start]);
    while(nextLabel.isPresent()) {
      CobolControl section = nextLabel.get();
      nextLabel = section.run();
    }
  }

  public static void main(String[] args)
  {
    CobolUtil.cob_init(args, false);
    CobolDecimal.cobInitNumeric();
    new ABC_096_B().ABC_096_B_(0);
    CobolStopRunException.stopRun();
  }

  public ABC_096_B()
  {
    init();
  }

  public void init() 
  {
    /* Decimal structures */

    d0 = new CobolDecimal();
    d1 = new CobolDecimal();
    d2 = new CobolDecimal();

    /* Data storage */

    cob_unifunc = null;

    /* PROGRAM-ID : ABC_096_B */
    b_RETURN_CODE = new CobolDataStorage(4);	/* RETURN-CODE */
    b_INP = new CobolDataStorage(10);	/* INP */
    b_K = new CobolDataStorage(2);	/* K */
    b_maxlen = new CobolDataStorage(1);	/* maxlen */
    b_cur = new CobolDataStorage(2);	/* cur */
    b_i = new CobolDataStorage(18);	/* i */
    b_j = new CobolDataStorage(18);	/* j */
    b_len = new CobolDataStorage(2);	/* len */
    b_mx = new CobolDataStorage(5);	/* mx */
    b_tmp = new CobolDataStorage(5);	/* tmp */
    b_ans = new CobolDataStorage(5);	/* ans */
    b_ZS = new CobolDataStorage(6);	/* ZS */
    b_ABC1 = new CobolDataStorage(6);	/* ABC1 */
    b_DUMMY = new CobolDataStorage(1);	/* DUMMY */
    b_ABC__ABC11__ABC1 = b_ABC1;

    /* End of data storage */


    initAttr();

    /* Fields */

    /* PROGRAM-ID : ABC_096_B */
    f_INP	= CobolFieldFactory.makeCobolField(10, b_INP, a_2_Alphanumeric);	/* INP */
    f_K	= CobolFieldFactory.makeCobolField(2, b_K, a_3_NumericDisplay_Digits2_Scale0);	/* K */
    f_cur	= CobolFieldFactory.makeCobolField(2, b_cur, a_3_NumericDisplay_Digits2_Scale0);	/* cur */
    f_i	= CobolFieldFactory.makeCobolField(18, b_i, a_4_NumericDisplay_Digits18_Scale0);	/* i */
    f_j	= CobolFieldFactory.makeCobolField(18, b_j, a_4_NumericDisplay_Digits18_Scale0);	/* j */
    f_len	= CobolFieldFactory.makeCobolField(2, b_len, a_3_NumericDisplay_Digits2_Scale0);	/* len */
    f_mx	= CobolFieldFactory.makeCobolField(5, b_mx, a_5_NumericDisplay_Digits5_Scale0);	/* mx */
    f_tmp	= CobolFieldFactory.makeCobolField(5, b_tmp, a_5_NumericDisplay_Digits5_Scale0);	/* tmp */
    f_ans	= CobolFieldFactory.makeCobolField(5, b_ans, a_2_Alphanumeric);	/* ans */
    f_ZS	= CobolFieldFactory.makeCobolField(6, b_ZS, a_1_NumericEdited_Digits6_Scale0);	/* ZS */
    f_DUMMY	= CobolFieldFactory.makeCobolField(1, b_DUMMY, a_2_Alphanumeric);	/* DUMMY */

    /* End of fields */


    /* Constants */

    c_1_1	= CobolFieldFactory.makeCobolField(1, "1", a_6_NumericDisplay_Digits1_Scale0);

  }

  private void initAttr() {
    /* Attributes */

    a_1_NumericEdited_Digits6_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_EDITED,
      /* digits= */ 6,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ "Z\006\000\000\000");
    a_2_Alphanumeric = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_ALPHANUMERIC,
      /* digits= */ 0,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_3_NumericDisplay_Digits2_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 2,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_4_NumericDisplay_Digits18_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 18,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_5_NumericDisplay_Digits5_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 5,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_6_NumericDisplay_Digits1_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 1,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);

  }

  /* Decimal structures */

  private CobolDecimal d0;
  private CobolDecimal d1;
  private CobolDecimal d2;

  /* Data storage */

  /* PROGRAM-ID : ABC_096_B */
  public CobolDataStorage b_RETURN_CODE;	/* RETURN-CODE */
  private CobolDataStorage b_INP;	/* INP */
  private CobolDataStorage b_K;	/* K */
  private CobolDataStorage b_maxlen;	/* maxlen */
  private CobolDataStorage b_cur;	/* cur */
  private CobolDataStorage b_i;	/* i */
  private CobolDataStorage b_j;	/* j */
  private CobolDataStorage b_len;	/* len */
  private CobolDataStorage b_mx;	/* mx */
  private CobolDataStorage b_tmp;	/* tmp */
  private CobolDataStorage b_ans;	/* ans */
  private CobolDataStorage b_ZS;	/* ZS */
  private CobolDataStorage b_ABC1;	/* ABC1 */
  private CobolDataStorage b_DUMMY;	/* DUMMY */
  private CobolDataStorage b_ABC__ABC11__ABC1;

  /* End of data storage */


  /* Fields */

  /* PROGRAM-ID : ABC_096_B */
  private AbstractCobolField f_INP;	/* INP */
  private AbstractCobolField f_K;	/* K */
  private AbstractCobolField f_cur;	/* cur */
  private AbstractCobolField f_i;	/* i */
  private AbstractCobolField f_j;	/* j */
  private AbstractCobolField f_len;	/* len */
  private AbstractCobolField f_mx;	/* mx */
  private AbstractCobolField f_tmp;	/* tmp */
  private AbstractCobolField f_ans;	/* ans */
  private AbstractCobolField f_ZS;	/* ZS */
  private AbstractCobolField f_DUMMY;	/* DUMMY */

  /* End of fields */


  private static AbstractCobolField f_native;

  /* Constants */

  private AbstractCobolField c_1_1;

  /* Attributes */

  private CobolFieldAttribute a_6_NumericDisplay_Digits1_Scale0;
  private CobolFieldAttribute a_5_NumericDisplay_Digits5_Scale0;
  private CobolFieldAttribute a_4_NumericDisplay_Digits18_Scale0;
  private CobolFieldAttribute a_3_NumericDisplay_Digits2_Scale0;
  private CobolFieldAttribute a_2_Alphanumeric;
  private CobolFieldAttribute a_1_NumericEdited_Digits6_Scale0;



  /* String literals */
  public static final byte[] str_1_000000000000000001 = CobolUtil.stringToBytes("000000000000000001");
  public static final byte[] str_0_01 = CobolUtil.stringToBytes("01");

  /* Sections and Labels */
  private final static int l_ABC_096_B = 1;
  private final static int l_MAIN_SECTION = 2;
  private final static int l_MAIN_SECTION__MAIN = 3;
  private final static int l_UNANS = 4;
  private final static int l_UNANS_SECTION__DEFAULT_PARAGRAPH = 5;
  private final static int l_Default_Error_Handler = 6;

}
