/* Generated by opensource COBOL 4J 1.1.16 */
import java.io.UnsupportedEncodingException;
import jp.osscons.opensourcecobol.libcobj.*;
import jp.osscons.opensourcecobol.libcobj.common.*;
import jp.osscons.opensourcecobol.libcobj.data.*;
import jp.osscons.opensourcecobol.libcobj.exceptions.*;
import jp.osscons.opensourcecobol.libcobj.termio.*;
import jp.osscons.opensourcecobol.libcobj.call.*;
import jp.osscons.opensourcecobol.libcobj.file.*;
import jp.osscons.opensourcecobol.libcobj.ui.*;
import java.util.Optional;

public class _3100C implements CobolRunnable {

  private boolean initialized = false;
  private CobolModule module;
  private int entry;

  private CobolRunnable cob_unifunc;


  @Override
  public int run(CobolDataStorage... argStorages) {
    return _3100C_(0, argStorages);
  }

  @Override
  public void cancel() {
    _3100C_(-1);
  }

  @Override
  public boolean isActive() {
    return false;
  }

  public CobolResultSet execute () {
    int returnCode = run_module(0);
    return new CobolResultSet(returnCode);
  }

  public int _3100C_ (int entry, CobolDataStorage ...argStorages) {
    this.entry = entry;
    return this.run_module(entry);
  }

  int run_module (int entry) {
    this.module = new CobolModule(null, null, null, null, 0, '.', '$', ',', 1, 1, 1, 0, null );

    /* Start of function code */

    /* CANCEL callback handling */
    if (entry < 0) {
    	if (!this.initialized) {
    		CobolDecimal.cobInitNumeric();
    		return 0;
    	}
    	h_STDIO.close (0, null);
    	d0.clear();
    	d0.setScale(0);
    	d1.clear();
    	d1.setScale(0);
    	d2.clear();
    	d2.setScale(0);
    	this.initialized = false;
    	return 0;
    }

    /* Push module stack */
    CobolModule.push (module);
    CobolResolve.pushCallStackList ("_3100C");

    /* Initialize program */
    if (!this.initialized) {
      module.setProgramId("_3100C");

      /* Initialize decimal numbers */
      d0.decimalInit();
      d1.decimalInit();
      d2.decimalInit();

      b_RETURN_CODE.set((int)0);
      b_N.fillBytes(0, 4);
      b_I.fillBytes(0, 4);
      b_W.fillBytes(0, 8);
      b_S.fillBytes(0, 8);
      b_AMR.setByte(0);
      b_P1.fillBytes(0, 4);
      b_P2.fillBytes(0, 4);
      b_TBL1.fillBytes('0', 2000000);
      b_TBL_SA.fillBytes('0', 2000000);
      b_CNT.fillBytes(0, 8);
      f_OUT.moveFrom (CobolConstant.zero);

      h_STDIO = CobolFileFactory.makeCobolFileInstance(
      /* select_name = */ "STDIO",
      /* file_status = */ h_STDIO_status,
      /* assign = */ null,
      /* record = */ f_STDIO_record,
      /* record_size = */ null,
      /* record_min = */ 0,
      /* record_max = */ 2200000,
      /* nkeys = */ 0,
      /* keys = */ null,
      /* organization = */ (char)1,
      /* access_mode = */ (char)1,
      /* lock_mode = */ (char)2,
      /* open_mode = */ (char)0,
      /* flag_optional = */ false,
      /* last_open_mode = */ (char)0,
      /* special = */ (char)1,
      /* flag_nonexistent = */ false,
      /* flag_end_of_file = */ false,
      /* flag_begin_of_file = */ false,
      /* flag_first_read = */ (char)0,
      /* flag_read_done = */ false,
      /* flag_select_features = */ (char)0,
      /* flag_needs_nl = */ false,
      /* flag_needs_top = */ false,
      /* file_version = */ (char)0
      );

      this.initialized = true;
    }
    /* PROCEDURE DIVISION */
    try{
      /* Entry dispatch */
      execEntry(l__3100C);

    } catch(CobolStopRunException e) {
      CobolStopRunException.stopRun();
      System.exit(e.getReturnCode());
    }
    /* Pop module stack */
    CobolResolve.popCallStackList();
    CobolModule.pop();

    /* Program return */
    return b_RETURN_CODE.intValue();
  }
  public CobolControl[] contList = {
    new CobolControl(0, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l__3100C]);
      }
    },
    /* Entry 100C */
    new CobolControl(l__3100C, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN]);
      }
    },
    /* MAIN SECTION */
    new CobolControl(l_MAIN, CobolControl.LabelType.section) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION__DEFAULT_PARAGRAPH]);
      }
    },
    /* MAIN_SECTION__DEFAULT_PARAGRAPH */
    new CobolControl(l_MAIN_SECTION__DEFAULT_PARAGRAPH, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* /content/temp_cobol/100C_fixed.cob:29: ACCEPT */
        {
          CobolTerminal.accept (f_N);
        }
        /* /content/temp_cobol/100C_fixed.cob:31: OPEN */
        {
          CobolRuntimeException.code = 0;
          {
            h_STDIO.open (1, 0, null);
          }
          if (CobolRuntimeException.code != 0)
          {
            /* PERFORM Default Error Handler */
            CobolControl.perform(contList, l_Default_Error_Handler).run();
          }
        }
        /* /content/temp_cobol/100C_fixed.cob:32: READ */
        CobolRuntimeException.code = 0;
        {
          h_STDIO.read (0, null, 1);
        }
        if (CobolRuntimeException.code != 0)
        {
          /* PERFORM Default Error Handler */
          CobolControl.perform(contList, l_Default_Error_Handler).run();
        }
        /* /content/temp_cobol/100C_fixed.cob:33: CLOSE */
        {
          CobolRuntimeException.code = 0;
          {
            h_STDIO.close (0, null);
          }
          if (CobolRuntimeException.code != 0)
          {
            /* PERFORM Default Error Handler */
            CobolControl.perform(contList, l_Default_Error_Handler).run();
          }
        }
        /* /content/temp_cobol/100C_fixed.cob:35: MOVE */
        {
          b_P1.setSwpU32Binary (1);
        }
        /* /content/temp_cobol/100C_fixed.cob:36: PERFORM */
        b_I.setSwpU32Binary (1);
        for(;;b_I.addSwpU32Binary (1))
        {
          if (((long)f_I.cmpInteger ((int)(b_N.bswap_32())) >  0L))
            break;
          {
            /* /content/temp_cobol/100C_fixed.cob:37: PERFORM */
            b_P2.setBytes (b_P1, 4);
            for(;;b_P2.addSwpU32Binary (1))
            {
              if (((long)(Byte.toUnsignedInt(b_INP.getSubDataStorage(((int)(b_P2.bswap_32()) - 1)).getByte(0)) - (int)32) == 0L))
                break;
              ;
            }
            /* /content/temp_cobol/100C_fixed.cob:39: MOVE */
            {
              CobolFieldFactory.makeCobolField(10, b_A__TBL1.getSubDataStorage(10 * ((int)(b_I.bswap_32()) - 1)), a_4_NumericDisplay_Digits10_Scale0).moveFrom (CobolFieldFactory.makeCobolField(((int)(b_P2.bswap_32()) - (int)(b_P1.bswap_32())), b_INP.getSubDataStorage(((int)(b_P1.bswap_32()) - 1)), a_2_Alphanumeric));
            }
            /* /content/temp_cobol/100C_fixed.cob:40: COMPUTE */
            {
              {
                {
                  d0.setField (CobolFieldFactory.makeCobolField(10, b_A__TBL1.getSubDataStorage(10 * ((int)(b_I.bswap_32()) - 1)), a_4_NumericDisplay_Digits10_Scale0));
                  d1.set ((int)(b_I.bswap_32()));
                  d0.sub (d1);
                  d0.getField (CobolFieldFactory.makeCobolField(10, b_SA__TBL_SA.getSubDataStorage(10 * ((int)(b_I.bswap_32()) - 1)), a_5_NumericDisplay_Digits10_Scale0_HaveSign), 4);
                }
              }
            }
            /* /content/temp_cobol/100C_fixed.cob:41: COMPUTE */
            {
              {
                {
                  d0.set ((int)(b_P2.bswap_32()));
                  d1.set (1);
                  d0.add (d1);
                  d0.getField (f_P1, 4);
                }
              }
            }
          }
        }
        /* /content/temp_cobol/100C_fixed.cob:44: SORT */
        {
          CobolFileSort.sortTableInit (1, 0);
          CobolFileSort.sortTableInitKey (0, f_SA__TBL_SA, 0);
          CobolFileSort.sortTable (f_SA__TBL_SA, (int)(b_N.bswap_32()));
        }
        /* /content/temp_cobol/100C_fixed.cob:45: DIVIDE */
        {
          f_N.divQuotient (c_1_2, f_S, 4);
          f_AMR.divRemainder (4);
        }
        /* /content/temp_cobol/100C_fixed.cob:46: IF */
        {
          if (((long)f_AMR.cmpInteger (1) == 0L))
            {
              /* /content/temp_cobol/100C_fixed.cob:47: MOVE */
              {
                f_W.moveFrom (CobolFieldFactory.makeCobolField(10, b_SA__TBL_SA.getSubDataStorage(10 * ((b_S.bswap_64() + 1) - 1)), a_5_NumericDisplay_Digits10_Scale0_HaveSign));
              }
            }
          else
            {
              /* /content/temp_cobol/100C_fixed.cob:49: COMPUTE */
              {
                {
                  {
                    d0.setField (CobolFieldFactory.makeCobolField(10, b_SA__TBL_SA.getSubDataStorage(10 * (b_S.bswap_64() - 1)), a_5_NumericDisplay_Digits10_Scale0_HaveSign));
                    d2.setField (CobolFieldFactory.makeCobolField(10, b_SA__TBL_SA.getSubDataStorage(10 * ((b_S.bswap_64() + 1) - 1)), a_5_NumericDisplay_Digits10_Scale0_HaveSign));
                    d0.add (d2);
                    d1.set (2);
                    d0.div (d1);
                    d0.getField (f_W, 5);
                  }
                }
              }
            }
        }
        /* /content/temp_cobol/100C_fixed.cob:52: MOVE */
        {
          b_CNT.fillBytes (0, 8);
        }
        /* /content/temp_cobol/100C_fixed.cob:53: PERFORM */
        b_I.setSwpU32Binary (1);
        for(;;b_I.addSwpU32Binary (1))
        {
          if (((long)f_I.cmpInteger ((int)(b_N.bswap_32())) >  0L))
            break;
          {
            /* /content/temp_cobol/100C_fixed.cob:54: COMPUTE */
            {
              {
                {
                  d0.setField (CobolFieldFactory.makeCobolField(10, b_A__TBL1.getSubDataStorage(10 * ((int)(b_I.bswap_32()) - 1)), a_4_NumericDisplay_Digits10_Scale0));
                  d1.setField (f_W);
                  d2.set ((int)(b_I.bswap_32()));
                  d1.add (d2);
                  d0.sub (d1);
                  d0.getField (f_S, 4);
                }
              }
            }
            /* /content/temp_cobol/100C_fixed.cob:55: COMPUTE */
            {
              {
                {
                  d0.setField (f_CNT);
                  d1.setField (f_S);
                  d0.add (d1);
                  d0.getField (f_CNT, 4);
                }
              }
            }
          }
        }
        /* /content/temp_cobol/100C_fixed.cob:58: MOVE */
        {
          f_OUT.moveFrom (f_CNT);
        }
        /* /content/temp_cobol/100C_fixed.cob:59: DISPLAY */
        {
          CobolTerminal.display (0, 1, 1, CobolIntrinsic.funcTrim (0, 0, f_OUT, 0));
        }
        /* /content/temp_cobol/100C_fixed.cob:60: STOP */
        {
          CobolStopRunException.throwException (b_RETURN_CODE.intValue());
        }


        return Optional.of(CobolControl.pure());
      }
    },
    /* Default Error Handler */
    new CobolControl(l_Default_Error_Handler, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        if ((CobolFile.errorFile.flag_select_features & CobolFile.COB_SELECT_FILE_STATUS) == 0) {
        	CobolFile.defaultErrorHandle ();
        	CobolStopRunException.stopRunAndThrow (1);
        }

        return Optional.of(CobolControl.pure());
      }
    },
    CobolControl.pure()
  };
  public void execEntry(int start) throws CobolRuntimeException, CobolStopRunException {
    Optional<CobolControl> nextLabel = Optional.of(contList[start]);
    while(nextLabel.isPresent()) {
      CobolControl section = nextLabel.get();
      nextLabel = section.run();
    }
  }

  public static void main(String[] args)
  {
    CobolUtil.cob_init(args, false);
    CobolDecimal.cobInitNumeric();
    new _3100C()._3100C_(0);
    CobolStopRunException.stopRun();
  }

  public _3100C()
  {
    init();
  }

  public void init() 
  {
    /* Decimal structures */

    d0 = new CobolDecimal();
    d1 = new CobolDecimal();
    d2 = new CobolDecimal();

    /* Data storage */

    cob_unifunc = null;

    /* PROGRAM-ID : 100C */
    b_RETURN_CODE = new CobolDataStorage(4);	/* RETURN-CODE */
    b_STDIO_record = new CobolDataStorage(2200000);	/* STDIO_record */
    b_N = new CobolDataStorage(4);	/* N */
    b_I = new CobolDataStorage(4);	/* I */
    b_W = new CobolDataStorage(8);	/* W */
    b_S = new CobolDataStorage(8);	/* S */
    b_AMR = new CobolDataStorage(1);	/* AMR */
    b_P1 = new CobolDataStorage(4);	/* P1 */
    b_P2 = new CobolDataStorage(4);	/* P2 */
    b_TBL1 = new CobolDataStorage(2000000);	/* TBL1 */
    b_TBL_SA = new CobolDataStorage(2000000);	/* TBL-SA */
    b_CNT = new CobolDataStorage(8);	/* CNT */
    b_OUT = new CobolDataStorage(15);	/* OUT */
    b_INP = b_STDIO_record;
    b_SA__TBL_SA = b_TBL_SA;
    b_A__TBL1 = b_TBL1;

    /* End of data storage */


    initAttr();

    /* Fields */

    /* PROGRAM-ID : 100C */
    f_STDIO_record	= CobolFieldFactory.makeCobolField(2200000, b_STDIO_record, a_2_Alphanumeric);	/* STDIO_record */
    f_N	= CobolFieldFactory.makeCobolField(4, b_N, a_3_NumericBinary_Digits6_Scale0_BinarySwap);	/* N */
    f_I	= CobolFieldFactory.makeCobolField(4, b_I, a_3_NumericBinary_Digits6_Scale0_BinarySwap);	/* I */
    f_W	= CobolFieldFactory.makeCobolField(8, b_W, a_9_NumericBinary_Digits10_Scale0_HaveSign_BinarySwap);	/* W */
    f_S	= CobolFieldFactory.makeCobolField(8, b_S, a_7_NumericBinary_Digits10_Scale0_BinarySwap);	/* S */
    f_AMR	= CobolFieldFactory.makeCobolField(1, b_AMR, a_8_NumericBinary_Digits1_Scale0_BinarySwap);	/* AMR */
    f_P1	= CobolFieldFactory.makeCobolField(4, b_P1, a_6_NumericBinary_Digits7_Scale0_BinarySwap);	/* P1 */
    f_SA__TBL_SA	= CobolFieldFactory.makeCobolField(10, b_SA__TBL_SA, a_5_NumericDisplay_Digits10_Scale0_HaveSign);	/* SA */
    f_CNT	= CobolFieldFactory.makeCobolField(8, b_CNT, a_10_NumericBinary_Digits15_Scale0_BinarySwap);	/* CNT */
    f_OUT	= CobolFieldFactory.makeCobolField(15, b_OUT, a_1_NumericEdited_Digits15_Scale0);	/* OUT */

    /* End of fields */


    /* Constants */

    c_1_2	= CobolFieldFactory.makeCobolField(1, "2", a_11_NumericDisplay_Digits1_Scale0);

  }

  private void initAttr() {
    /* Attributes */

    a_1_NumericEdited_Digits15_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_EDITED,
      /* digits= */ 15,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ "Z\016\000\000\0009\001\000\000\000");
    a_2_Alphanumeric = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_ALPHANUMERIC,
      /* digits= */ 0,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_3_NumericBinary_Digits6_Scale0_BinarySwap = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_BINARY,
      /* digits= */ 6,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_BINARY_SWAP,
      /* pic= */ null);
    a_4_NumericDisplay_Digits10_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 10,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_5_NumericDisplay_Digits10_Scale0_HaveSign = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 10,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_HAVE_SIGN,
      /* pic= */ null);
    a_6_NumericBinary_Digits7_Scale0_BinarySwap = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_BINARY,
      /* digits= */ 7,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_BINARY_SWAP,
      /* pic= */ null);
    a_7_NumericBinary_Digits10_Scale0_BinarySwap = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_BINARY,
      /* digits= */ 10,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_BINARY_SWAP,
      /* pic= */ null);
    a_8_NumericBinary_Digits1_Scale0_BinarySwap = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_BINARY,
      /* digits= */ 1,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_BINARY_SWAP,
      /* pic= */ null);
    a_9_NumericBinary_Digits10_Scale0_HaveSign_BinarySwap = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_BINARY,
      /* digits= */ 10,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_HAVE_SIGN
        | CobolFieldAttribute.COB_FLAG_BINARY_SWAP,
      /* pic= */ null);
    a_10_NumericBinary_Digits15_Scale0_BinarySwap = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_BINARY,
      /* digits= */ 15,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_BINARY_SWAP,
      /* pic= */ null);
    a_11_NumericDisplay_Digits1_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 1,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);

  }

  /* Decimal structures */

  private CobolDecimal d0;
  private CobolDecimal d1;
  private CobolDecimal d2;

  /* Data storage */

  /* PROGRAM-ID : 100C */
  public CobolDataStorage b_RETURN_CODE;	/* RETURN-CODE */
  private CobolDataStorage b_STDIO_record;	/* STDIO_record */
  private CobolDataStorage b_N;	/* N */
  private CobolDataStorage b_I;	/* I */
  private CobolDataStorage b_W;	/* W */
  private CobolDataStorage b_S;	/* S */
  private CobolDataStorage b_AMR;	/* AMR */
  private CobolDataStorage b_P1;	/* P1 */
  private CobolDataStorage b_P2;	/* P2 */
  private CobolDataStorage b_TBL1;	/* TBL1 */
  private CobolDataStorage b_TBL_SA;	/* TBL-SA */
  private CobolDataStorage b_CNT;	/* CNT */
  private CobolDataStorage b_OUT;	/* OUT */
  private CobolDataStorage b_INP;
  private CobolDataStorage b_SA__TBL_SA;
  private CobolDataStorage b_A__TBL1;

  /* End of data storage */


  /* Fields */

  /* PROGRAM-ID : 100C */
  private AbstractCobolField f_STDIO_record;	/* STDIO_record */
  private AbstractCobolField f_N;	/* N */
  private AbstractCobolField f_I;	/* I */
  private AbstractCobolField f_W;	/* W */
  private AbstractCobolField f_S;	/* S */
  private AbstractCobolField f_AMR;	/* AMR */
  private AbstractCobolField f_P1;	/* P1 */
  private AbstractCobolField f_SA__TBL_SA;	/* SA */
  private AbstractCobolField f_CNT;	/* CNT */
  private AbstractCobolField f_OUT;	/* OUT */

  /* End of fields */


  private static AbstractCobolField f_native;

  /* Constants */

  private AbstractCobolField c_1_2;

  /* Attributes */

  private CobolFieldAttribute a_11_NumericDisplay_Digits1_Scale0;
  private CobolFieldAttribute a_10_NumericBinary_Digits15_Scale0_BinarySwap;
  private CobolFieldAttribute a_9_NumericBinary_Digits10_Scale0_HaveSign_BinarySwap;
  private CobolFieldAttribute a_8_NumericBinary_Digits1_Scale0_BinarySwap;
  private CobolFieldAttribute a_7_NumericBinary_Digits10_Scale0_BinarySwap;
  private CobolFieldAttribute a_6_NumericBinary_Digits7_Scale0_BinarySwap;
  private CobolFieldAttribute a_5_NumericDisplay_Digits10_Scale0_HaveSign;
  private CobolFieldAttribute a_4_NumericDisplay_Digits10_Scale0;
  private CobolFieldAttribute a_3_NumericBinary_Digits6_Scale0_BinarySwap;
  private CobolFieldAttribute a_2_Alphanumeric;
  private CobolFieldAttribute a_1_NumericEdited_Digits15_Scale0;



  /* File STDIO */
  private CobolFile		h_STDIO = null;
  private byte[]	h_STDIO_status = new byte[4];

  /* Sections and Labels */
  private final static int l__3100C = 1;
  private final static int l_MAIN = 2;
  private final static int l_MAIN_SECTION__DEFAULT_PARAGRAPH = 3;
  private final static int l_Default_Error_Handler = 4;

}
