/* Generated by opensource COBOL 4J 1.1.16 */
import java.io.UnsupportedEncodingException;
import jp.osscons.opensourcecobol.libcobj.*;
import jp.osscons.opensourcecobol.libcobj.common.*;
import jp.osscons.opensourcecobol.libcobj.data.*;
import jp.osscons.opensourcecobol.libcobj.exceptions.*;
import jp.osscons.opensourcecobol.libcobj.termio.*;
import jp.osscons.opensourcecobol.libcobj.call.*;
import jp.osscons.opensourcecobol.libcobj.file.*;
import jp.osscons.opensourcecobol.libcobj.ui.*;
import java.util.Optional;

public class ABC046__B implements CobolRunnable {

  private boolean initialized = false;
  private CobolModule module;
  private int entry;

  private CobolRunnable cob_unifunc;


  @Override
  public int run(CobolDataStorage... argStorages) {
    return ABC046__B_(0, argStorages);
  }

  @Override
  public void cancel() {
    ABC046__B_(-1);
  }

  @Override
  public boolean isActive() {
    return false;
  }

  public CobolResultSet execute () {
    int returnCode = run_module(0);
    return new CobolResultSet(returnCode);
  }

  public int ABC046__B_ (int entry, CobolDataStorage ...argStorages) {
    this.entry = entry;
    return this.run_module(entry);
  }

  int run_module (int entry) {
    this.module = new CobolModule(null, null, null, null, 0, '.', '$', ',', 1, 1, 1, 0, null );

    /* Start of function code */

    /* CANCEL callback handling */
    if (entry < 0) {
    	if (!this.initialized) {
    		CobolDecimal.cobInitNumeric();
    		return 0;
    	}
    	d0.clear();
    	d0.setScale(0);
    	d1.clear();
    	d1.setScale(0);
    	d2.clear();
    	d2.setScale(0);
    	d3.clear();
    	d3.setScale(0);
    	this.initialized = false;
    	return 0;
    }

    /* Push module stack */
    CobolModule.push (module);
    CobolResolve.pushCallStackList ("ABC046__B");

    /* Initialize program */
    if (!this.initialized) {
      module.setProgramId("ABC046__B");

      /* Initialize decimal numbers */
      d0.decimalInit();
      d1.decimalInit();
      d2.decimalInit();
      d3.decimalInit();

      b_RETURN_CODE.set((int)0);
      b_STR.fillBytes(' ', 11);
      b_N.fillBytes('0', 4);
      b_K.fillBytes('0', 4);
      b_ANS.fillBytes('0', 10);
      f_ANSS.moveFrom (CobolConstant.zero);
      this.initialized = true;
    }
    /* PROCEDURE DIVISION */
    try{
      /* Entry dispatch */
      execEntry(l_ABC046__B);

    } catch(CobolStopRunException e) {
      CobolStopRunException.stopRun();
      System.exit(e.getReturnCode());
    }
    /* Pop module stack */
    CobolResolve.popCallStackList();
    CobolModule.pop();

    /* Program return */
    return b_RETURN_CODE.intValue();
  }
  public CobolControl[] contList = {
    new CobolControl(0, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_ABC046__B]);
      }
    },
    /* Entry ABC046-B */
    new CobolControl(l_ABC046__B, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION]);
      }
    },
    /* MAIN SECTION */
    new CobolControl(l_MAIN_SECTION, CobolControl.LabelType.section) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION__MAIN_PROCEDURE]);
      }
    },
    /* MAIN-PROCEDURE */
    new CobolControl(l_MAIN_SECTION__MAIN_PROCEDURE, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* /content/temp_cobol/ABC046-B_fixed.cob:14: ACCEPT */
        {
          CobolTerminal.accept (f_STR);
        }
        /* /content/temp_cobol/ABC046-B_fixed.cob:15: UNSTRING */
        {
          CobolString.unstringInit (f_STR, 0, 1);
          CobolString.unstringDelimited (c_1, 0);
          CobolString.unstringInto (f_N, 0, 0);
          CobolString.unstringInto (f_K, 0, 0);
          CobolString.unstringFinish ();
        }
        /* /content/temp_cobol/ABC046-B_fixed.cob:17: COMPUTE */
        {
          {
            {
              d0.set (b_K.getNumdisp(4));
              d1.set (b_K.getNumdisp(4));
              d3.set (1);
              d1.sub (d3);
              d2.set (b_N.getNumdisp(4));
              d3.set (1);
              d2.sub (d3);
              d1.pow (d2);
              d0.mul (d1);
              d0.getField (f_ANS, 4);
            }
          }
        }
        /* /content/temp_cobol/ABC046-B_fixed.cob:18: MOVE */
        {
          f_ANSS.moveFrom (f_ANS);
        }
        /* /content/temp_cobol/ABC046-B_fixed.cob:19: DISPLAY */
        {
          CobolTerminal.display (0, 1, 1, f_ANSS);
        }
        /* /content/temp_cobol/ABC046-B_fixed.cob:20: STOP */
        {
          CobolStopRunException.throwException (b_RETURN_CODE.intValue());
        }
        return Optional.of(CobolControl.pure());
      }
    },
    CobolControl.pure()
  };
  public void execEntry(int start) throws CobolRuntimeException, CobolStopRunException {
    Optional<CobolControl> nextLabel = Optional.of(contList[start]);
    while(nextLabel.isPresent()) {
      CobolControl section = nextLabel.get();
      nextLabel = section.run();
    }
  }

  public static void main(String[] args)
  {
    CobolUtil.cob_init(args, false);
    CobolDecimal.cobInitNumeric();
    new ABC046__B().ABC046__B_(0);
    CobolStopRunException.stopRun();
  }

  public ABC046__B()
  {
    init();
  }

  public void init() 
  {
    /* Decimal structures */

    d0 = new CobolDecimal();
    d1 = new CobolDecimal();
    d2 = new CobolDecimal();
    d3 = new CobolDecimal();

    /* Data storage */

    cob_unifunc = null;

    /* PROGRAM-ID : ABC046-B */
    b_RETURN_CODE = new CobolDataStorage(4);	/* RETURN-CODE */
    b_STR = new CobolDataStorage(11);	/* STR */
    b_N = new CobolDataStorage(4);	/* N */
    b_K = new CobolDataStorage(4);	/* K */
    b_ANS = new CobolDataStorage(10);	/* ANS */
    b_ANSS = new CobolDataStorage(10);	/* ANSS */

    /* End of data storage */


    initAttr();

    /* Fields */

    /* PROGRAM-ID : ABC046-B */
    f_STR	= CobolFieldFactory.makeCobolField(11, b_STR, a_2_Alphanumeric);	/* STR */
    f_N	= CobolFieldFactory.makeCobolField(4, b_N, a_3_NumericDisplay_Digits4_Scale0);	/* N */
    f_K	= CobolFieldFactory.makeCobolField(4, b_K, a_3_NumericDisplay_Digits4_Scale0);	/* K */
    f_ANS	= CobolFieldFactory.makeCobolField(10, b_ANS, a_4_NumericDisplay_Digits10_Scale0);	/* ANS */
    f_ANSS	= CobolFieldFactory.makeCobolField(10, b_ANSS, a_1_NumericEdited_Digits10_Scale0);	/* ANSS */

    /* End of fields */


    /* Constants */

    c_1	= CobolFieldFactory.makeCobolField(str_0, a_2_Alphanumeric);

  }

  private void initAttr() {
    /* Attributes */

    a_1_NumericEdited_Digits10_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_EDITED,
      /* digits= */ 10,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ "Z\011\000\000\0009\001\000\000\000");
    a_2_Alphanumeric = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_ALPHANUMERIC,
      /* digits= */ 0,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_3_NumericDisplay_Digits4_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 4,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_4_NumericDisplay_Digits10_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 10,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);

  }

  /* Decimal structures */

  private CobolDecimal d0;
  private CobolDecimal d1;
  private CobolDecimal d2;
  private CobolDecimal d3;

  /* Data storage */

  /* PROGRAM-ID : ABC046-B */
  public CobolDataStorage b_RETURN_CODE;	/* RETURN-CODE */
  private CobolDataStorage b_STR;	/* STR */
  private CobolDataStorage b_N;	/* N */
  private CobolDataStorage b_K;	/* K */
  private CobolDataStorage b_ANS;	/* ANS */
  private CobolDataStorage b_ANSS;	/* ANSS */

  /* End of data storage */


  /* Fields */

  /* PROGRAM-ID : ABC046-B */
  private AbstractCobolField f_STR;	/* STR */
  private AbstractCobolField f_N;	/* N */
  private AbstractCobolField f_K;	/* K */
  private AbstractCobolField f_ANS;	/* ANS */
  private AbstractCobolField f_ANSS;	/* ANSS */

  /* End of fields */


  private static AbstractCobolField f_native;

  /* Constants */

  private AbstractCobolField c_1;

  /* Attributes */

  private CobolFieldAttribute a_4_NumericDisplay_Digits10_Scale0;
  private CobolFieldAttribute a_3_NumericDisplay_Digits4_Scale0;
  private CobolFieldAttribute a_2_Alphanumeric;
  private CobolFieldAttribute a_1_NumericEdited_Digits10_Scale0;



  /* String literals */
  public static final byte[] str_0 = CobolUtil.stringToBytes(" ");

  /* Sections and Labels */
  private final static int l_ABC046__B = 1;
  private final static int l_MAIN_SECTION = 2;
  private final static int l_MAIN_SECTION__MAIN_PROCEDURE = 3;
  private final static int l_Default_Error_Handler = 4;

}
