/* Generated by opensource COBOL 4J 1.1.16 */
import java.io.UnsupportedEncodingException;
import jp.osscons.opensourcecobol.libcobj.*;
import jp.osscons.opensourcecobol.libcobj.common.*;
import jp.osscons.opensourcecobol.libcobj.data.*;
import jp.osscons.opensourcecobol.libcobj.exceptions.*;
import jp.osscons.opensourcecobol.libcobj.termio.*;
import jp.osscons.opensourcecobol.libcobj.call.*;
import jp.osscons.opensourcecobol.libcobj.file.*;
import jp.osscons.opensourcecobol.libcobj.ui.*;
import java.util.Optional;

public class ABC_097_B implements CobolRunnable {

  private boolean initialized = false;
  private CobolModule module;
  private int entry;

  private CobolRunnable cob_unifunc;


  @Override
  public int run(CobolDataStorage... argStorages) {
    return ABC_097_B_(0, argStorages);
  }

  @Override
  public void cancel() {
    ABC_097_B_(-1);
  }

  @Override
  public boolean isActive() {
    return false;
  }

  public CobolResultSet execute () {
    int returnCode = run_module(0);
    return new CobolResultSet(returnCode);
  }

  public int ABC_097_B_ (int entry, CobolDataStorage ...argStorages) {
    this.entry = entry;
    return this.run_module(entry);
  }

  int run_module (int entry) {
    this.module = new CobolModule(null, null, null, null, 0, '.', '$', ',', 1, 1, 1, 0, null );

    /* Start of function code */

    /* CANCEL callback handling */
    if (entry < 0) {
    	if (!this.initialized) {
    		CobolDecimal.cobInitNumeric();
    		return 0;
    	}
    	d0.clear();
    	d0.setScale(0);
    	d1.clear();
    	d1.setScale(0);
    	this.initialized = false;
    	return 0;
    }

    /* Push module stack */
    CobolModule.push (module);
    CobolResolve.pushCallStackList ("ABC_097_B");

    /* Initialize program */
    if (!this.initialized) {
      module.setProgramId("ABC_097_B");

      /* Initialize decimal numbers */
      d0.decimalInit();
      d1.decimalInit();

      b_RETURN_CODE.set((int)0);
      b_A.fillBytes('0', 18);
      b_b.fillBytes('0', 4);
      b_p.fillBytes('0', 4);
      b_tmp.fillBytes('0', 18);
      f_ans.moveFrom (CobolConstant.zero);
      this.initialized = true;
    }
    /* PROCEDURE DIVISION */
    try{
      /* Entry dispatch */
      execEntry(l_ABC_097_B);

    } catch(CobolStopRunException e) {
      CobolStopRunException.stopRun();
      System.exit(e.getReturnCode());
    }
    /* Pop module stack */
    CobolResolve.popCallStackList();
    CobolModule.pop();

    /* Program return */
    return b_RETURN_CODE.intValue();
  }
  public CobolControl[] contList = {
    new CobolControl(0, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_ABC_097_B]);
      }
    },
    /* Entry ABC_097_B */
    new CobolControl(l_ABC_097_B, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION]);
      }
    },
    /* MAIN SECTION */
    new CobolControl(l_MAIN_SECTION, CobolControl.LabelType.section) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION__MAIN]);
      }
    },
    /* MAIN */
    new CobolControl(l_MAIN_SECTION__MAIN, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* /content/temp_cobol/ABC_097_B_fixed.cob:15: ACCEPT */
        {
          CobolTerminal.accept (f_A);
        }
        /* /content/temp_cobol/ABC_097_B_fixed.cob:17: MOVE */
        {
          f_ans.moveFrom (c_1_1);
        }
        /* /content/temp_cobol/ABC_097_B_fixed.cob:19: PERFORM */
        b_b.setBytes (str_0_0002, 4);
        for(;;f_b.addInt (1))
        {
          if (((long)b_A.cmpLongNumdisp (18, b_b.getNumdisp(4)) <  0L))
            break;
          {
            /* /content/temp_cobol/ABC_097_B_fixed.cob:20: PERFORM */
            b_p.setBytes (str_1_0002, 4);
            for(;;f_p.addInt (1))
            {
              if (((long)b_A.cmpLongNumdisp (18, b_p.getNumdisp(4)) <  0L))
                break;
              {
                /* /content/temp_cobol/ABC_097_B_fixed.cob:21: COMPUTE */
                {
                  {
                    {
                      d0.set (b_b.getNumdisp(4));
                      d1.set (b_p.getNumdisp(4));
                      d0.pow (d1);
                      d0.getField (f_tmp, 4);
                    }
                  }
                }
                /* /content/temp_cobol/ABC_097_B_fixed.cob:23: IF */
                {
                  if (((long)b_A.memcmp (b_tmp, 18) <  0L))
                    {
                      /* /content/temp_cobol/ABC_097_B_fixed.cob:24: EXIT */
                      {
                        if(true) break;
                      }
                    }
                }
                /* /content/temp_cobol/ABC_097_B_fixed.cob:27: COMPUTE */
                {
                  {
                    {
                      d0.setField (CobolIntrinsic.funcMax (2, f_ans, f_tmp));
                      d0.getField (f_ans, 4);
                    }
                  }
                }
              }
            }
          }
        }
        /* /content/temp_cobol/ABC_097_B_fixed.cob:31: DISPLAY */
        {
          CobolTerminal.display (0, 1, 1, f_ans);
        }
        /* /content/temp_cobol/ABC_097_B_fixed.cob:32: STOP */
        {
          CobolStopRunException.throwException (b_RETURN_CODE.intValue());
        }
        return Optional.of(CobolControl.pure());
      }
    },
    CobolControl.pure()
  };
  public void execEntry(int start) throws CobolRuntimeException, CobolStopRunException {
    Optional<CobolControl> nextLabel = Optional.of(contList[start]);
    while(nextLabel.isPresent()) {
      CobolControl section = nextLabel.get();
      nextLabel = section.run();
    }
  }

  public static void main(String[] args)
  {
    CobolUtil.cob_init(args, false);
    CobolDecimal.cobInitNumeric();
    new ABC_097_B().ABC_097_B_(0);
    CobolStopRunException.stopRun();
  }

  public ABC_097_B()
  {
    init();
  }

  public void init() 
  {
    /* Decimal structures */

    d0 = new CobolDecimal();
    d1 = new CobolDecimal();

    /* Data storage */

    cob_unifunc = null;

    /* PROGRAM-ID : ABC_097_B */
    b_RETURN_CODE = new CobolDataStorage(4);	/* RETURN-CODE */
    b_A = new CobolDataStorage(18);	/* A */
    b_b = new CobolDataStorage(4);	/* b */
    b_p = new CobolDataStorage(4);	/* p */
    b_tmp = new CobolDataStorage(18);	/* tmp */
    b_ans = new CobolDataStorage(18);	/* ans */

    /* End of data storage */


    initAttr();

    /* Fields */

    /* PROGRAM-ID : ABC_097_B */
    f_A	= CobolFieldFactory.makeCobolField(18, b_A, a_2_NumericDisplay_Digits18_Scale0);	/* A */
    f_b	= CobolFieldFactory.makeCobolField(4, b_b, a_3_NumericDisplay_Digits4_Scale0);	/* b */
    f_p	= CobolFieldFactory.makeCobolField(4, b_p, a_3_NumericDisplay_Digits4_Scale0);	/* p */
    f_tmp	= CobolFieldFactory.makeCobolField(18, b_tmp, a_2_NumericDisplay_Digits18_Scale0);	/* tmp */
    f_ans	= CobolFieldFactory.makeCobolField(18, b_ans, a_1_NumericEdited_Digits18_Scale0);	/* ans */

    /* End of fields */


    /* Constants */

    c_1_1	= CobolFieldFactory.makeCobolField(1, "1", a_4_NumericDisplay_Digits1_Scale0);

  }

  private void initAttr() {
    /* Attributes */

    a_1_NumericEdited_Digits18_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_EDITED,
      /* digits= */ 18,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ "Z\022\000\000\000");
    a_2_NumericDisplay_Digits18_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 18,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_3_NumericDisplay_Digits4_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 4,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_4_NumericDisplay_Digits1_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 1,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);

  }

  /* Decimal structures */

  private CobolDecimal d0;
  private CobolDecimal d1;

  /* Data storage */

  /* PROGRAM-ID : ABC_097_B */
  public CobolDataStorage b_RETURN_CODE;	/* RETURN-CODE */
  private CobolDataStorage b_A;	/* A */
  private CobolDataStorage b_b;	/* b */
  private CobolDataStorage b_p;	/* p */
  private CobolDataStorage b_tmp;	/* tmp */
  private CobolDataStorage b_ans;	/* ans */

  /* End of data storage */


  /* Fields */

  /* PROGRAM-ID : ABC_097_B */
  private AbstractCobolField f_A;	/* A */
  private AbstractCobolField f_b;	/* b */
  private AbstractCobolField f_p;	/* p */
  private AbstractCobolField f_tmp;	/* tmp */
  private AbstractCobolField f_ans;	/* ans */

  /* End of fields */


  private static AbstractCobolField f_native;

  /* Constants */

  private AbstractCobolField c_1_1;

  /* Attributes */

  private CobolFieldAttribute a_4_NumericDisplay_Digits1_Scale0;
  private CobolFieldAttribute a_3_NumericDisplay_Digits4_Scale0;
  private CobolFieldAttribute a_2_NumericDisplay_Digits18_Scale0;
  private CobolFieldAttribute a_1_NumericEdited_Digits18_Scale0;



  /* String literals */
  public static final byte[] str_1_0002 = CobolUtil.stringToBytes("0002");
  public static final byte[] str_0_0002 = CobolUtil.stringToBytes("0002");

  /* Sections and Labels */
  private final static int l_ABC_097_B = 1;
  private final static int l_MAIN_SECTION = 2;
  private final static int l_MAIN_SECTION__MAIN = 3;
  private final static int l_Default_Error_Handler = 4;

}
