/* Generated by opensource COBOL 4J 1.1.16 */
import java.io.UnsupportedEncodingException;
import jp.osscons.opensourcecobol.libcobj.*;
import jp.osscons.opensourcecobol.libcobj.common.*;
import jp.osscons.opensourcecobol.libcobj.data.*;
import jp.osscons.opensourcecobol.libcobj.exceptions.*;
import jp.osscons.opensourcecobol.libcobj.termio.*;
import jp.osscons.opensourcecobol.libcobj.call.*;
import jp.osscons.opensourcecobol.libcobj.file.*;
import jp.osscons.opensourcecobol.libcobj.ui.*;
import java.util.Optional;

public class ABC_060_A implements CobolRunnable {

  private boolean initialized = false;
  private CobolModule module;
  private int entry;

  private CobolRunnable cob_unifunc;


  @Override
  public int run(CobolDataStorage... argStorages) {
    return ABC_060_A_(0, argStorages);
  }

  @Override
  public void cancel() {
    ABC_060_A_(-1);
  }

  @Override
  public boolean isActive() {
    return false;
  }

  public CobolResultSet execute () {
    int returnCode = run_module(0);
    return new CobolResultSet(returnCode);
  }

  public int ABC_060_A_ (int entry, CobolDataStorage ...argStorages) {
    this.entry = entry;
    return this.run_module(entry);
  }

  int run_module (int entry) {
    this.module = new CobolModule(null, null, null, null, 0, '.', '$', ',', 1, 1, 1, 0, null );

    /* Start of function code */

    /* CANCEL callback handling */
    if (entry < 0) {
    	if (!this.initialized) {
    		CobolDecimal.cobInitNumeric();
    		return 0;
    	}
    	this.initialized = false;
    	return 0;
    }

    /* Push module stack */
    CobolModule.push (module);
    CobolResolve.pushCallStackList ("ABC_060_A");

    /* Initialize program */
    if (!this.initialized) {
      module.setProgramId("ABC_060_A");

      b_RETURN_CODE.set((int)0);
      b_INP.fillBytes(' ', 32);
      b_A.fillBytes(' ', 10);
      b_B.fillBytes(' ', 10);
      b_C.fillBytes(' ', 10);
      this.initialized = true;
    }
    /* PROCEDURE DIVISION */
    try{
      /* Entry dispatch */
      execEntry(l_ABC_060_A);

    } catch(CobolStopRunException e) {
      CobolStopRunException.stopRun();
      System.exit(e.getReturnCode());
    }
    /* Pop module stack */
    CobolResolve.popCallStackList();
    CobolModule.pop();

    /* Program return */
    return b_RETURN_CODE.intValue();
  }
  public CobolControl[] contList = {
    new CobolControl(0, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_ABC_060_A]);
      }
    },
    /* Entry ABC_060_A */
    new CobolControl(l_ABC_060_A, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION]);
      }
    },
    /* MAIN SECTION */
    new CobolControl(l_MAIN_SECTION, CobolControl.LabelType.section) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION__MAIN]);
      }
    },
    /* MAIN */
    new CobolControl(l_MAIN_SECTION__MAIN, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* /content/temp_cobol/ABC_060_A_fixed.cob:13: ACCEPT */
        {
          CobolTerminal.accept (f_INP);
        }
        /* /content/temp_cobol/ABC_060_A_fixed.cob:15: UNSTRING */
        {
          CobolString.unstringInit (f_INP, 0, 1);
          CobolString.unstringDelimited (CobolConstant.space, 0);
          CobolString.unstringInto (f_A, 0, 0);
          CobolString.unstringInto (f_B, 0, 0);
          CobolString.unstringInto (f_C, 0, 0);
          CobolString.unstringFinish ();
        }
        /* /content/temp_cobol/ABC_060_A_fixed.cob:19: IF */
        {
          if ((((long)(Byte.toUnsignedInt(b_A.getSubDataStorage((CobolIntrinsic.funcStoredCharLength (f_A).getInt() - 1)).getByte(0)) - Byte.toUnsignedInt(b_B.getSubDataStorage(0).getByte(0))) == 0L) && ((long)(Byte.toUnsignedInt(b_B.getSubDataStorage((CobolIntrinsic.funcStoredCharLength (f_B).getInt() - 1)).getByte(0)) - Byte.toUnsignedInt(b_C.getSubDataStorage(0).getByte(0))) == 0L)))
            {
              /* /content/temp_cobol/ABC_060_A_fixed.cob:21: DISPLAY */
              {
                CobolTerminal.display (0, 1, 1, c_1_YES);
              }
            }
          else
            {
              /* /content/temp_cobol/ABC_060_A_fixed.cob:23: DISPLAY */
              {
                CobolTerminal.display (0, 1, 1, c_2_NO);
              }
            }
        }
        /* /content/temp_cobol/ABC_060_A_fixed.cob:26: STOP */
        {
          CobolStopRunException.throwException (b_RETURN_CODE.intValue());
        }
        return Optional.of(CobolControl.pure());
      }
    },
    CobolControl.pure()
  };
  public void execEntry(int start) throws CobolRuntimeException, CobolStopRunException {
    Optional<CobolControl> nextLabel = Optional.of(contList[start]);
    while(nextLabel.isPresent()) {
      CobolControl section = nextLabel.get();
      nextLabel = section.run();
    }
  }

  public static void main(String[] args)
  {
    CobolUtil.cob_init(args, false);
    CobolDecimal.cobInitNumeric();
    new ABC_060_A().ABC_060_A_(0);
    CobolStopRunException.stopRun();
  }

  public ABC_060_A()
  {
    init();
  }

  public void init() 
  {
    /* Data storage */

    cob_unifunc = null;

    /* PROGRAM-ID : ABC_060_A */
    b_RETURN_CODE = new CobolDataStorage(4);	/* RETURN-CODE */
    b_INP = new CobolDataStorage(32);	/* INP */
    b_A = new CobolDataStorage(10);	/* A */
    b_B = new CobolDataStorage(10);	/* B */
    b_C = new CobolDataStorage(10);	/* C */

    /* End of data storage */


    initAttr();

    /* Fields */

    /* PROGRAM-ID : ABC_060_A */
    f_INP	= CobolFieldFactory.makeCobolField(32, b_INP, a_1_Alphanumeric);	/* INP */
    f_A	= CobolFieldFactory.makeCobolField(10, b_A, a_1_Alphanumeric);	/* A */
    f_B	= CobolFieldFactory.makeCobolField(10, b_B, a_1_Alphanumeric);	/* B */
    f_C	= CobolFieldFactory.makeCobolField(10, b_C, a_1_Alphanumeric);	/* C */

    /* End of fields */


    /* Constants */

    c_1_YES	= CobolFieldFactory.makeCobolField(str_0_YES, a_1_Alphanumeric);
    c_2_NO	= CobolFieldFactory.makeCobolField(str_1_NO, a_1_Alphanumeric);

  }

  private void initAttr() {
    /* Attributes */

    a_1_Alphanumeric = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_ALPHANUMERIC,
      /* digits= */ 0,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);

  }

  /* Data storage */

  /* PROGRAM-ID : ABC_060_A */
  public CobolDataStorage b_RETURN_CODE;	/* RETURN-CODE */
  private CobolDataStorage b_INP;	/* INP */
  private CobolDataStorage b_A;	/* A */
  private CobolDataStorage b_B;	/* B */
  private CobolDataStorage b_C;	/* C */

  /* End of data storage */


  /* Fields */

  /* PROGRAM-ID : ABC_060_A */
  private AbstractCobolField f_INP;	/* INP */
  private AbstractCobolField f_A;	/* A */
  private AbstractCobolField f_B;	/* B */
  private AbstractCobolField f_C;	/* C */

  /* End of fields */


  private static AbstractCobolField f_native;

  /* Constants */

  private AbstractCobolField c_2_NO;
  private AbstractCobolField c_1_YES;

  /* Attributes */

  private CobolFieldAttribute a_1_Alphanumeric;



  /* String literals */
  public static final byte[] str_1_NO = CobolUtil.stringToBytes("NO");
  public static final byte[] str_0_YES = CobolUtil.stringToBytes("YES");

  /* Sections and Labels */
  private final static int l_ABC_060_A = 1;
  private final static int l_MAIN_SECTION = 2;
  private final static int l_MAIN_SECTION__MAIN = 3;
  private final static int l_Default_Error_Handler = 4;

}
