/* Generated by opensource COBOL 4J 1.1.16 */
import java.io.UnsupportedEncodingException;
import jp.osscons.opensourcecobol.libcobj.*;
import jp.osscons.opensourcecobol.libcobj.common.*;
import jp.osscons.opensourcecobol.libcobj.data.*;
import jp.osscons.opensourcecobol.libcobj.exceptions.*;
import jp.osscons.opensourcecobol.libcobj.termio.*;
import jp.osscons.opensourcecobol.libcobj.call.*;
import jp.osscons.opensourcecobol.libcobj.file.*;
import jp.osscons.opensourcecobol.libcobj.ui.*;
import java.util.Optional;

public class test1 implements CobolRunnable {

  private boolean initialized = false;
  private CobolModule module;
  private int entry;

  private CobolRunnable cob_unifunc;


  @Override
  public int run(CobolDataStorage... argStorages) {
    return test1_(0, argStorages);
  }

  @Override
  public void cancel() {
    test1_(-1);
  }

  @Override
  public boolean isActive() {
    return false;
  }

  public CobolResultSet execute () {
    int returnCode = run_module(0);
    return new CobolResultSet(returnCode);
  }

  public int test1_ (int entry, CobolDataStorage ...argStorages) {
    this.entry = entry;
    return this.run_module(entry);
  }

  int run_module (int entry) {
    this.module = new CobolModule(null, null, null, null, 0, '.', '$', ',', 1, 1, 1, 0, null );

    /* Start of function code */

    /* CANCEL callback handling */
    if (entry < 0) {
    	if (!this.initialized) {
    		CobolDecimal.cobInitNumeric();
    		return 0;
    	}
    	d0.clear();
    	d0.setScale(0);
    	d1.clear();
    	d1.setScale(0);
    	this.initialized = false;
    	return 0;
    }

    /* Push module stack */
    CobolModule.push (module);
    CobolResolve.pushCallStackList ("test1");

    /* Initialize program */
    if (!this.initialized) {
      module.setProgramId("test1");

      /* Initialize decimal numbers */
      d0.decimalInit();
      d1.decimalInit();

      b_RETURN_CODE.set((int)0);
      b_INP.fillBytes(' ', 100);
      b_A.fillBytes('0', 6);
      b_B.fillBytes('0', 6);
      b_C.fillBytes('0', 9);
      b_REN.fillBytes('0', 7);
      CobolFieldFactory.makeCobolField(7, b_RE, a_1_NumericEdited_Digits7_Scale0).moveFrom (CobolConstant.zero);
      b_temp1.fillBytes('0', 4);
      b_temp2.fillBytes('0', 4);
      b_N.fillBytes('0', 4);
      this.initialized = true;
    }
    /* PROCEDURE DIVISION */
    try{
      /* Entry dispatch */
      execEntry(l_test1);

    } catch(CobolStopRunException e) {
      CobolStopRunException.stopRun();
      System.exit(e.getReturnCode());
    }
    /* Pop module stack */
    CobolResolve.popCallStackList();
    CobolModule.pop();

    /* Program return */
    return b_RETURN_CODE.intValue();
  }
  public CobolControl[] contList = {
    new CobolControl(0, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_test1]);
      }
    },
    /* Entry test1 */
    new CobolControl(l_test1, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION]);
      }
    },
    /* MAIN SECTION */
    new CobolControl(l_MAIN_SECTION, CobolControl.LabelType.section) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION__MAIN]);
      }
    },
    /* MAIN */
    new CobolControl(l_MAIN_SECTION__MAIN, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* /content/temp_cobol/test1_fixed.cob:17: ACCEPT */
        {
          CobolTerminal.accept (f_INP);
        }
        /* /content/temp_cobol/test1_fixed.cob:18: PERFORM */
        b_temp1.setBytes (str_0_0001, 4);
        for(;;f_temp1.addInt (1))
        {
          if (((long)(Byte.toUnsignedInt(b_INP.getSubDataStorage((b_temp1.getNumdisp(4) - 1)).getByte(0)) - (int)' ') == 0L))
            break;
          ;
        }
        /* /content/temp_cobol/test1_fixed.cob:20: SUBTRACT */
        {
          f_temp1.sub (c_1_1, 4);
        }
        /* /content/temp_cobol/test1_fixed.cob:21: MOVE */
        {
          f_A.moveFrom (CobolFieldFactory.makeCobolField(b_temp1.getNumdisp(4), b_INP.getSubDataStorage(0), a_2_Alphanumeric));
        }
        /* /content/temp_cobol/test1_fixed.cob:22: ADD */
        {
          f_temp1.add (c_2_2, 4);
        }
        /* /content/temp_cobol/test1_fixed.cob:23: PERFORM */
        b_temp2.setBytes (b_temp1, 4);
        for(;;f_temp2.addInt (1))
        {
          if (((long)(Byte.toUnsignedInt(b_INP.getSubDataStorage((b_temp2.getNumdisp(4) - 1)).getByte(0)) - (int)' ') == 0L))
            break;
          ;
        }
        /* /content/temp_cobol/test1_fixed.cob:25: COMPUTE */
        {
          {
            {
              d0.set (b_temp2.getNumdisp(4));
              d1.set (b_temp1.getNumdisp(4));
              d0.sub (d1);
              d0.getField (f_N, 4);
            }
          }
        }
        /* /content/temp_cobol/test1_fixed.cob:26: MOVE */
        {
          f_B.moveFrom (CobolFieldFactory.makeCobolField(b_N.getNumdisp(4), b_INP.getSubDataStorage((b_temp1.getNumdisp(4) - 1)), a_2_Alphanumeric));
        }
        /* /content/temp_cobol/test1_fixed.cob:27: ADD */
        {
          f_temp2.add (c_1_1, 4);
        }
        /* /content/temp_cobol/test1_fixed.cob:28: PERFORM */
        b_temp1.setBytes (b_temp2, 4);
        for(;;f_temp1.addInt (1))
        {
          if (((long)(Byte.toUnsignedInt(b_INP.getSubDataStorage((b_temp1.getNumdisp(4) - 1)).getByte(0)) - (int)' ') == 0L))
            break;
          ;
        }
        /* /content/temp_cobol/test1_fixed.cob:30: COMPUTE */
        {
          {
            {
              d0.set (b_temp1.getNumdisp(4));
              d1.set (b_temp2.getNumdisp(4));
              d0.sub (d1);
              d0.getField (f_N, 4);
            }
          }
        }
        /* /content/temp_cobol/test1_fixed.cob:31: MOVE */
        {
          f_C.moveFrom (CobolFieldFactory.makeCobolField(b_N.getNumdisp(4), b_INP.getSubDataStorage((b_temp2.getNumdisp(4) - 1)), a_2_Alphanumeric));
        }
        /* /content/temp_cobol/test1_fixed.cob:32: IF */
        {
          if ((((long)b_A.memcmp (b_B, 6) == 0L) && ((long)b_B.cmpNumdisp (6, b_C.getNumdisp(9)) != 0L)))
            {
              /* /content/temp_cobol/test1_fixed.cob:33: DISPLAY */
              {
                CobolTerminal.display (0, 1, 1, c_2_2);
              }
            }
          else
            {
              /* /content/temp_cobol/test1_fixed.cob:34: IF */
              {
                if ((((long)b_A.memcmp (b_B, 6) != 0L) && ((long)b_B.cmpNumdisp (6, b_C.getNumdisp(9)) == 0L)))
                  {
                    /* /content/temp_cobol/test1_fixed.cob:35: DISPLAY */
                    {
                      CobolTerminal.display (0, 1, 1, c_2_2);
                    }
                  }
                else
                  {
                    /* /content/temp_cobol/test1_fixed.cob:36: IF */
                    {
                      if ((((long)b_A.cmpNumdisp (6, b_C.getNumdisp(9)) == 0L) && ((long)b_B.cmpNumdisp (6, b_C.getNumdisp(9)) != 0L)))
                        {
                          /* /content/temp_cobol/test1_fixed.cob:37: DISPLAY */
                          {
                            CobolTerminal.display (0, 1, 1, c_2_2);
                          }
                        }
                      else
                        {
                          /* /content/temp_cobol/test1_fixed.cob:38: IF */
                          {
                            if ((((long)b_A.cmpNumdisp (6, b_C.getNumdisp(9)) == 0L) && ((long)b_B.cmpNumdisp (6, b_C.getNumdisp(9)) == 0L)))
                              {
                                /* /content/temp_cobol/test1_fixed.cob:39: DISPLAY */
                                {
                                  CobolTerminal.display (0, 1, 1, c_1_1);
                                }
                              }
                            else
                              {
                                /* /content/temp_cobol/test1_fixed.cob:41: DISPLAY */
                                {
                                  CobolTerminal.display (0, 1, 1, c_3_3);
                                }
                              }
                          }
                        }
                    }
                  }
              }
            }
        }
        /* /content/temp_cobol/test1_fixed.cob:43: STOP */
        {
          CobolStopRunException.throwException (b_RETURN_CODE.intValue());
        }
        return Optional.of(CobolControl.pure());
      }
    },
    CobolControl.pure()
  };
  public void execEntry(int start) throws CobolRuntimeException, CobolStopRunException {
    Optional<CobolControl> nextLabel = Optional.of(contList[start]);
    while(nextLabel.isPresent()) {
      CobolControl section = nextLabel.get();
      nextLabel = section.run();
    }
  }

  public static void main(String[] args)
  {
    CobolUtil.cob_init(args, false);
    CobolDecimal.cobInitNumeric();
    new test1().test1_(0);
    CobolStopRunException.stopRun();
  }

  public test1()
  {
    init();
  }

  public void init() 
  {
    /* Decimal structures */

    d0 = new CobolDecimal();
    d1 = new CobolDecimal();

    /* Data storage */

    cob_unifunc = null;

    /* PROGRAM-ID : test1 */
    b_RETURN_CODE = new CobolDataStorage(4);	/* RETURN-CODE */
    b_INP = new CobolDataStorage(100);	/* INP */
    b_A = new CobolDataStorage(6);	/* A */
    b_B = new CobolDataStorage(6);	/* B */
    b_C = new CobolDataStorage(9);	/* C */
    b_REN = new CobolDataStorage(7);	/* REN */
    b_RE = new CobolDataStorage(7);	/* RE */
    b_temp1 = new CobolDataStorage(4);	/* temp1 */
    b_temp2 = new CobolDataStorage(4);	/* temp2 */
    b_N = new CobolDataStorage(4);	/* N */

    /* End of data storage */


    initAttr();

    /* Fields */

    /* PROGRAM-ID : test1 */
    f_INP	= CobolFieldFactory.makeCobolField(100, b_INP, a_2_Alphanumeric);	/* INP */
    f_A	= CobolFieldFactory.makeCobolField(6, b_A, a_4_NumericDisplay_Digits6_Scale0);	/* A */
    f_B	= CobolFieldFactory.makeCobolField(6, b_B, a_4_NumericDisplay_Digits6_Scale0);	/* B */
    f_C	= CobolFieldFactory.makeCobolField(9, b_C, a_5_NumericDisplay_Digits9_Scale0);	/* C */
    f_temp1	= CobolFieldFactory.makeCobolField(4, b_temp1, a_3_NumericDisplay_Digits4_Scale0);	/* temp1 */
    f_temp2	= CobolFieldFactory.makeCobolField(4, b_temp2, a_3_NumericDisplay_Digits4_Scale0);	/* temp2 */
    f_N	= CobolFieldFactory.makeCobolField(4, b_N, a_3_NumericDisplay_Digits4_Scale0);	/* N */

    /* End of fields */


    /* Constants */

    c_1_1	= CobolFieldFactory.makeCobolField(1, "1", a_6_NumericDisplay_Digits1_Scale0);
    c_2_2	= CobolFieldFactory.makeCobolField(1, "2", a_6_NumericDisplay_Digits1_Scale0);
    c_3_3	= CobolFieldFactory.makeCobolField(1, "3", a_6_NumericDisplay_Digits1_Scale0);

  }

  private void initAttr() {
    /* Attributes */

    a_1_NumericEdited_Digits7_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_EDITED,
      /* digits= */ 7,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ "Z\007\000\000\000");
    a_2_Alphanumeric = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_ALPHANUMERIC,
      /* digits= */ 0,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_3_NumericDisplay_Digits4_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 4,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_4_NumericDisplay_Digits6_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 6,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_5_NumericDisplay_Digits9_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 9,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_6_NumericDisplay_Digits1_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 1,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);

  }

  /* Decimal structures */

  private CobolDecimal d0;
  private CobolDecimal d1;

  /* Data storage */

  /* PROGRAM-ID : test1 */
  public CobolDataStorage b_RETURN_CODE;	/* RETURN-CODE */
  private CobolDataStorage b_INP;	/* INP */
  private CobolDataStorage b_A;	/* A */
  private CobolDataStorage b_B;	/* B */
  private CobolDataStorage b_C;	/* C */
  private CobolDataStorage b_REN;	/* REN */
  private CobolDataStorage b_RE;	/* RE */
  private CobolDataStorage b_temp1;	/* temp1 */
  private CobolDataStorage b_temp2;	/* temp2 */
  private CobolDataStorage b_N;	/* N */

  /* End of data storage */


  /* Fields */

  /* PROGRAM-ID : test1 */
  private AbstractCobolField f_INP;	/* INP */
  private AbstractCobolField f_A;	/* A */
  private AbstractCobolField f_B;	/* B */
  private AbstractCobolField f_C;	/* C */
  private AbstractCobolField f_temp1;	/* temp1 */
  private AbstractCobolField f_temp2;	/* temp2 */
  private AbstractCobolField f_N;	/* N */

  /* End of fields */


  private static AbstractCobolField f_native;

  /* Constants */

  private AbstractCobolField c_3_3;
  private AbstractCobolField c_2_2;
  private AbstractCobolField c_1_1;

  /* Attributes */

  private CobolFieldAttribute a_6_NumericDisplay_Digits1_Scale0;
  private CobolFieldAttribute a_5_NumericDisplay_Digits9_Scale0;
  private CobolFieldAttribute a_4_NumericDisplay_Digits6_Scale0;
  private CobolFieldAttribute a_3_NumericDisplay_Digits4_Scale0;
  private CobolFieldAttribute a_2_Alphanumeric;
  private CobolFieldAttribute a_1_NumericEdited_Digits7_Scale0;



  /* String literals */
  public static final byte[] str_0_0001 = CobolUtil.stringToBytes("0001");

  /* Sections and Labels */
  private final static int l_test1 = 1;
  private final static int l_MAIN_SECTION = 2;
  private final static int l_MAIN_SECTION__MAIN = 3;
  private final static int l_Default_Error_Handler = 4;

}
