/* Generated by opensource COBOL 4J 1.1.16 */
import java.io.UnsupportedEncodingException;
import jp.osscons.opensourcecobol.libcobj.*;
import jp.osscons.opensourcecobol.libcobj.common.*;
import jp.osscons.opensourcecobol.libcobj.data.*;
import jp.osscons.opensourcecobol.libcobj.exceptions.*;
import jp.osscons.opensourcecobol.libcobj.termio.*;
import jp.osscons.opensourcecobol.libcobj.call.*;
import jp.osscons.opensourcecobol.libcobj.file.*;
import jp.osscons.opensourcecobol.libcobj.ui.*;
import java.util.Optional;

public class PROGRAM_ID implements CobolRunnable {

  private boolean initialized = false;
  private CobolModule module;
  private int entry;

  private CobolRunnable cob_unifunc;


  @Override
  public int run(CobolDataStorage... argStorages) {
    return PROGRAM_ID_(0, argStorages);
  }

  @Override
  public void cancel() {
    PROGRAM_ID_(-1);
  }

  @Override
  public boolean isActive() {
    return false;
  }

  public CobolResultSet execute () {
    int returnCode = run_module(0);
    return new CobolResultSet(returnCode);
  }

  public int PROGRAM_ID_ (int entry, CobolDataStorage ...argStorages) {
    this.entry = entry;
    return this.run_module(entry);
  }

  int run_module (int entry) {
    this.module = new CobolModule(null, null, null, null, 0, '.', '$', ',', 1, 1, 1, 0, null );

    /* Start of function code */

    /* CANCEL callback handling */
    if (entry < 0) {
    	if (!this.initialized) {
    		CobolDecimal.cobInitNumeric();
    		return 0;
    	}
    	d0.clear();
    	d0.setScale(0);
    	d1.clear();
    	d1.setScale(0);
    	this.initialized = false;
    	return 0;
    }

    /* Push module stack */
    CobolModule.push (module);
    CobolResolve.pushCallStackList ("PROGRAM_ID");

    /* Initialize program */
    if (!this.initialized) {
      module.setProgramId("PROGRAM_ID");

      /* Initialize decimal numbers */
      d0.decimalInit();
      d1.decimalInit();

      b_RETURN_CODE.set((int)0);
      b_ln.fillBytes(' ', 42);
      b_A.fillBytes('0', 19);
      b_B.fillBytes('0', 19);
      b_K.fillBytes('0', 19);
      b_mna.fillBytes('0', 19);
      b_mnb.fillBytes('0', 19);
      b_ans.fillBytes(' ', 40);
      f_zsa.moveFrom (CobolConstant.zero);
      f_zsb.moveFrom (CobolConstant.zero);
      this.initialized = true;
    }
    /* PROCEDURE DIVISION */
    try{
      /* Entry dispatch */
      execEntry(l_PROGRAM_ID);

    } catch(CobolStopRunException e) {
      CobolStopRunException.stopRun();
      System.exit(e.getReturnCode());
    }
    /* Pop module stack */
    CobolResolve.popCallStackList();
    CobolModule.pop();

    /* Program return */
    return b_RETURN_CODE.intValue();
  }
  public CobolControl[] contList = {
    new CobolControl(0, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_PROGRAM_ID]);
      }
    },
    /* Entry PROGRAM_ID */
    new CobolControl(l_PROGRAM_ID, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN]);
      }
    },
    /* MAIN SECTION */
    new CobolControl(l_MAIN, CobolControl.LabelType.section) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION__DEFAULT_PARAGRAPH]);
      }
    },
    /* MAIN_SECTION__DEFAULT_PARAGRAPH */
    new CobolControl(l_MAIN_SECTION__DEFAULT_PARAGRAPH, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* /content/temp_cobol/PROGRAM_ID_fixed.cob:17: ACCEPT */
        {
          CobolTerminal.accept (f_ln);
        }
        /* /content/temp_cobol/PROGRAM_ID_fixed.cob:18: UNSTRING */
        {
          CobolString.unstringInit (f_ln, 0, 1);
          CobolString.unstringDelimited (CobolConstant.space, 0);
          CobolString.unstringInto (f_A, 0, 0);
          CobolString.unstringInto (f_B, 0, 0);
          CobolString.unstringInto (f_K, 0, 0);
          CobolString.unstringFinish ();
        }
        /* /content/temp_cobol/PROGRAM_ID_fixed.cob:19: COMPUTE */
        {
          {
            {
              d0.setField (CobolIntrinsic.funcMin (2, f_A, f_K));
              d0.getField (f_mna, 4);
            }
          }
        }
        /* /content/temp_cobol/PROGRAM_ID_fixed.cob:20: COMPUTE */
        {
          {
            {
              d0.setField (f_A);
              d1.setField (f_mna);
              d0.sub (d1);
              d0.getField (f_A, 4);
            }
          }
        }
        /* /content/temp_cobol/PROGRAM_ID_fixed.cob:21: COMPUTE */
        {
          {
            {
              d0.setField (f_K);
              d1.setField (f_mna);
              d0.sub (d1);
              d0.getField (f_mna, 4);
            }
          }
        }
        /* /content/temp_cobol/PROGRAM_ID_fixed.cob:22: COMPUTE */
        {
          {
            {
              d0.setField (CobolIntrinsic.funcMin (2, f_B, f_mna));
              d0.getField (f_mnb, 4);
            }
          }
        }
        /* /content/temp_cobol/PROGRAM_ID_fixed.cob:23: COMPUTE */
        {
          {
            {
              d0.setField (f_B);
              d1.setField (f_mnb);
              d0.sub (d1);
              d0.getField (f_B, 4);
            }
          }
        }
        /* /content/temp_cobol/PROGRAM_ID_fixed.cob:24: MOVE */
        {
          f_zsa.moveFrom (f_A);
        }
        /* /content/temp_cobol/PROGRAM_ID_fixed.cob:25: MOVE */
        {
          f_zsb.moveFrom (f_B);
        }
        /* /content/temp_cobol/PROGRAM_ID_fixed.cob:26: STRING */
        {
          CobolString.stringInit (f_ans, 0);
          CobolString.stringDelimited (0);
          CobolString.stringAppend (CobolIntrinsic.funcTrim (0, 0, f_zsa, 0));
          CobolString.stringAppend (CobolConstant.space);
          CobolString.stringAppend (CobolIntrinsic.funcTrim (0, 0, f_zsb, 0));
          CobolString.stringFinish ();
        }
        /* /content/temp_cobol/PROGRAM_ID_fixed.cob:27: DISPLAY */
        {
          CobolTerminal.display (0, 1, 1, CobolIntrinsic.funcTrim (0, 0, f_ans, 0));
        }
        /* /content/temp_cobol/PROGRAM_ID_fixed.cob:28: STOP */
        {
          CobolStopRunException.throwException (b_RETURN_CODE.intValue());
        }
        return Optional.of(CobolControl.pure());
      }
    },
    CobolControl.pure()
  };
  public void execEntry(int start) throws CobolRuntimeException, CobolStopRunException {
    Optional<CobolControl> nextLabel = Optional.of(contList[start]);
    while(nextLabel.isPresent()) {
      CobolControl section = nextLabel.get();
      nextLabel = section.run();
    }
  }

  public static void main(String[] args)
  {
    CobolUtil.cob_init(args, false);
    CobolDecimal.cobInitNumeric();
    new PROGRAM_ID().PROGRAM_ID_(0);
    CobolStopRunException.stopRun();
  }

  public PROGRAM_ID()
  {
    init();
  }

  public void init() 
  {
    /* Decimal structures */

    d0 = new CobolDecimal();
    d1 = new CobolDecimal();

    /* Data storage */

    cob_unifunc = null;

    /* PROGRAM-ID : PROGRAM_ID */
    b_RETURN_CODE = new CobolDataStorage(4);	/* RETURN-CODE */
    b_ln = new CobolDataStorage(42);	/* ln */
    b_A = new CobolDataStorage(19);	/* A */
    b_B = new CobolDataStorage(19);	/* B */
    b_K = new CobolDataStorage(19);	/* K */
    b_mna = new CobolDataStorage(19);	/* mna */
    b_mnb = new CobolDataStorage(19);	/* mnb */
    b_ans = new CobolDataStorage(40);	/* ans */
    b_zsa = new CobolDataStorage(19);	/* zsa */
    b_zsb = new CobolDataStorage(19);	/* zsb */

    /* End of data storage */


    initAttr();

    /* Fields */

    /* PROGRAM-ID : PROGRAM_ID */
    f_ln	= CobolFieldFactory.makeCobolField(42, b_ln, a_2_Alphanumeric);	/* ln */
    f_A	= CobolFieldFactory.makeCobolField(19, b_A, a_3_NumericDisplay_Digits19_Scale0);	/* A */
    f_B	= CobolFieldFactory.makeCobolField(19, b_B, a_3_NumericDisplay_Digits19_Scale0);	/* B */
    f_K	= CobolFieldFactory.makeCobolField(19, b_K, a_3_NumericDisplay_Digits19_Scale0);	/* K */
    f_mna	= CobolFieldFactory.makeCobolField(19, b_mna, a_3_NumericDisplay_Digits19_Scale0);	/* mna */
    f_mnb	= CobolFieldFactory.makeCobolField(19, b_mnb, a_3_NumericDisplay_Digits19_Scale0);	/* mnb */
    f_ans	= CobolFieldFactory.makeCobolField(40, b_ans, a_2_Alphanumeric);	/* ans */
    f_zsa	= CobolFieldFactory.makeCobolField(19, b_zsa, a_1_NumericEdited_Digits19_Scale0);	/* zsa */
    f_zsb	= CobolFieldFactory.makeCobolField(19, b_zsb, a_1_NumericEdited_Digits19_Scale0);	/* zsb */

    /* End of fields */


  }

  private void initAttr() {
    /* Attributes */

    a_1_NumericEdited_Digits19_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_EDITED,
      /* digits= */ 19,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ "Z\022\000\000\0009\001\000\000\000");
    a_2_Alphanumeric = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_ALPHANUMERIC,
      /* digits= */ 0,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_3_NumericDisplay_Digits19_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 19,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);

  }

  /* Decimal structures */

  private CobolDecimal d0;
  private CobolDecimal d1;

  /* Data storage */

  /* PROGRAM-ID : PROGRAM_ID */
  public CobolDataStorage b_RETURN_CODE;	/* RETURN-CODE */
  private CobolDataStorage b_ln;	/* ln */
  private CobolDataStorage b_A;	/* A */
  private CobolDataStorage b_B;	/* B */
  private CobolDataStorage b_K;	/* K */
  private CobolDataStorage b_mna;	/* mna */
  private CobolDataStorage b_mnb;	/* mnb */
  private CobolDataStorage b_ans;	/* ans */
  private CobolDataStorage b_zsa;	/* zsa */
  private CobolDataStorage b_zsb;	/* zsb */

  /* End of data storage */


  /* Fields */

  /* PROGRAM-ID : PROGRAM_ID */
  private AbstractCobolField f_ln;	/* ln */
  private AbstractCobolField f_A;	/* A */
  private AbstractCobolField f_B;	/* B */
  private AbstractCobolField f_K;	/* K */
  private AbstractCobolField f_mna;	/* mna */
  private AbstractCobolField f_mnb;	/* mnb */
  private AbstractCobolField f_ans;	/* ans */
  private AbstractCobolField f_zsa;	/* zsa */
  private AbstractCobolField f_zsb;	/* zsb */

  /* End of fields */


  private static AbstractCobolField f_native;

  /* Attributes */

  private CobolFieldAttribute a_3_NumericDisplay_Digits19_Scale0;
  private CobolFieldAttribute a_2_Alphanumeric;
  private CobolFieldAttribute a_1_NumericEdited_Digits19_Scale0;




  /* Sections and Labels */
  private final static int l_PROGRAM_ID = 1;
  private final static int l_MAIN = 2;
  private final static int l_MAIN_SECTION__DEFAULT_PARAGRAPH = 3;
  private final static int l_Default_Error_Handler = 4;

}
