/* Generated by opensource COBOL 4J 1.1.16 */
import java.io.UnsupportedEncodingException;
import jp.osscons.opensourcecobol.libcobj.*;
import jp.osscons.opensourcecobol.libcobj.common.*;
import jp.osscons.opensourcecobol.libcobj.data.*;
import jp.osscons.opensourcecobol.libcobj.exceptions.*;
import jp.osscons.opensourcecobol.libcobj.termio.*;
import jp.osscons.opensourcecobol.libcobj.call.*;
import jp.osscons.opensourcecobol.libcobj.file.*;
import jp.osscons.opensourcecobol.libcobj.ui.*;
import java.util.Optional;

public class aising__B implements CobolRunnable {

  private boolean initialized = false;
  private CobolModule module;
  private int entry;

  private CobolRunnable cob_unifunc;


  @Override
  public int run(CobolDataStorage... argStorages) {
    return aising__B_(0, argStorages);
  }

  @Override
  public void cancel() {
    aising__B_(-1);
  }

  @Override
  public boolean isActive() {
    return false;
  }

  public CobolResultSet execute () {
    int returnCode = run_module(0);
    return new CobolResultSet(returnCode);
  }

  public int aising__B_ (int entry, CobolDataStorage ...argStorages) {
    this.entry = entry;
    return this.run_module(entry);
  }

  int run_module (int entry) {
    this.module = new CobolModule(null, null, null, null, 0, '.', '$', ',', 1, 1, 1, 0, null );

    /* Start of function code */

    /* CANCEL callback handling */
    if (entry < 0) {
    	if (!this.initialized) {
    		CobolDecimal.cobInitNumeric();
    		return 0;
    	}
    	d0.clear();
    	d0.setScale(0);
    	d1.clear();
    	d1.setScale(0);
    	this.initialized = false;
    	return 0;
    }

    /* Push module stack */
    CobolModule.push (module);
    CobolResolve.pushCallStackList ("aising__B");

    /* Initialize program */
    if (!this.initialized) {
      module.setProgramId("aising__B");

      /* Initialize decimal numbers */
      d0.decimalInit();
      d1.decimalInit();

      b_RETURN_CODE.set((int)0);
      b_INP.fillBytes(' ', 400);
      b_N.fillBytes('0', 3);
      b_A.fillBytes('0', 3);
      b_I.fillBytes(0, 2);
      b_P1.fillBytes(0, 2);
      b_P2.fillBytes(0, 2);
      b_S.fillBytes('0', 2);
      b_AMR.setByte('0');
      b_SW_K.setByte('0');
      b_CNT.fillBytes('0', 3);
      f_OUT.moveFrom (CobolConstant.zero);
      this.initialized = true;
    }
    /* PROCEDURE DIVISION */
    try{
      /* Entry dispatch */
      execEntry(l_aising__B);

    } catch(CobolStopRunException e) {
      CobolStopRunException.stopRun();
      System.exit(e.getReturnCode());
    }
    /* Pop module stack */
    CobolResolve.popCallStackList();
    CobolModule.pop();

    /* Program return */
    return b_RETURN_CODE.intValue();
  }
  public CobolControl[] contList = {
    new CobolControl(0, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_aising__B]);
      }
    },
    /* Entry aising-B */
    new CobolControl(l_aising__B, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN]);
      }
    },
    /* MAIN SECTION */
    new CobolControl(l_MAIN, CobolControl.LabelType.section) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION__DEFAULT_PARAGRAPH]);
      }
    },
    /* MAIN_SECTION__DEFAULT_PARAGRAPH */
    new CobolControl(l_MAIN_SECTION__DEFAULT_PARAGRAPH, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* /content/temp_cobol/aising-B_fixed.cob:18: ACCEPT */
        {
          CobolTerminal.accept (f_N);
        }
        /* /content/temp_cobol/aising-B_fixed.cob:19: ACCEPT */
        {
          CobolTerminal.accept (f_INP);
        }
        /* /content/temp_cobol/aising-B_fixed.cob:21: MOVE */
        {
          b_CNT.fillBytes (48, 3);
        }
        /* /content/temp_cobol/aising-B_fixed.cob:22: MOVE */
        {
          b_P1.setSwpU16Binary (1);
          b_SW_K.setByte(49);
        }
        /* /content/temp_cobol/aising-B_fixed.cob:23: PERFORM */
        b_I.setSwpU16Binary (1);
        for(;;b_I.addSwpU16Binary (1))
        {
          if (((long)f_I.cmpInteger (b_N.getNumdisp(3)) >  0L))
            break;
          {
            /* /content/temp_cobol/aising-B_fixed.cob:24: PERFORM */
            b_P2.setBytes (b_P1, 2);
            for(;;b_P2.addSwpU16Binary (1))
            {
              if (((long)(Byte.toUnsignedInt(b_INP.getSubDataStorage(((short)(b_P2.bswap_16()) - 1)).getByte(0)) - (int)32) == 0L))
                break;
              ;
            }
            /* /content/temp_cobol/aising-B_fixed.cob:26: MOVE */
            {
              f_A.moveFrom (CobolFieldFactory.makeCobolField(((short)(b_P2.bswap_16()) - (short)(b_P1.bswap_16())), b_INP.getSubDataStorage(((short)(b_P1.bswap_16()) - 1)), a_3_Alphanumeric));
            }
            /* /content/temp_cobol/aising-B_fixed.cob:27: DIVIDE */
            {
              f_A.divQuotient (c_1_2, f_S, 4);
              f_AMR.divRemainder (4);
            }
            /* /content/temp_cobol/aising-B_fixed.cob:28: IF */
            {
              if ((((long)b_SW_K.cmpNumdisp (1, 1) == 0L) && ((long)b_AMR.cmpNumdisp (1, 1) == 0L)))
                {
                  /* /content/temp_cobol/aising-B_fixed.cob:29: ADD */
                  {
                    f_CNT.add (c_2_1, 4);
                  }
                }
            }
            /* /content/temp_cobol/aising-B_fixed.cob:31: COMPUTE */
            {
              {
                {
                  d0.set ((short)(b_P2.bswap_16()));
                  d1.set (1);
                  d0.add (d1);
                  d0.getField (f_P1, 4);
                }
              }
            }
            /* /content/temp_cobol/aising-B_fixed.cob:32: COMPUTE */
            {
              {
                {
                  d0.set (1);
                  d1.set (b_SW_K.getNumdisp(1));
                  d0.sub (d1);
                  d0.getField (f_SW_K, 4);
                }
              }
            }
          }
        }
        /* /content/temp_cobol/aising-B_fixed.cob:35: MOVE */
        {
          f_OUT.moveFrom (f_CNT);
        }
        /* /content/temp_cobol/aising-B_fixed.cob:36: DISPLAY */
        {
          CobolTerminal.display (0, 1, 1, CobolIntrinsic.funcTrim (0, 0, f_OUT, 0));
        }
        /* /content/temp_cobol/aising-B_fixed.cob:37: STOP */
        {
          CobolStopRunException.throwException (b_RETURN_CODE.intValue());
        }
        return Optional.of(CobolControl.pure());
      }
    },
    CobolControl.pure()
  };
  public void execEntry(int start) throws CobolRuntimeException, CobolStopRunException {
    Optional<CobolControl> nextLabel = Optional.of(contList[start]);
    while(nextLabel.isPresent()) {
      CobolControl section = nextLabel.get();
      nextLabel = section.run();
    }
  }

  public static void main(String[] args)
  {
    CobolUtil.cob_init(args, false);
    CobolDecimal.cobInitNumeric();
    new aising__B().aising__B_(0);
    CobolStopRunException.stopRun();
  }

  public aising__B()
  {
    init();
  }

  public void init() 
  {
    /* Decimal structures */

    d0 = new CobolDecimal();
    d1 = new CobolDecimal();

    /* Data storage */

    cob_unifunc = null;

    /* PROGRAM-ID : aising-B */
    b_RETURN_CODE = new CobolDataStorage(4);	/* RETURN-CODE */
    b_INP = new CobolDataStorage(400);	/* INP */
    b_N = new CobolDataStorage(3);	/* N */
    b_A = new CobolDataStorage(3);	/* A */
    b_I = new CobolDataStorage(2);	/* I */
    b_P1 = new CobolDataStorage(2);	/* P1 */
    b_P2 = new CobolDataStorage(2);	/* P2 */
    b_S = new CobolDataStorage(2);	/* S */
    b_AMR = new CobolDataStorage(1);	/* AMR */
    b_SW_K = new CobolDataStorage(1);	/* SW-K */
    b_CNT = new CobolDataStorage(3);	/* CNT */
    b_OUT = new CobolDataStorage(3);	/* OUT */

    /* End of data storage */


    initAttr();

    /* Fields */

    /* PROGRAM-ID : aising-B */
    f_INP	= CobolFieldFactory.makeCobolField(400, b_INP, a_3_Alphanumeric);	/* INP */
    f_N	= CobolFieldFactory.makeCobolField(3, b_N, a_2_NumericDisplay_Digits3_Scale0);	/* N */
    f_A	= CobolFieldFactory.makeCobolField(3, b_A, a_2_NumericDisplay_Digits3_Scale0);	/* A */
    f_I	= CobolFieldFactory.makeCobolField(2, b_I, a_4_NumericBinary_Digits4_Scale0_BinarySwap);	/* I */
    f_P1	= CobolFieldFactory.makeCobolField(2, b_P1, a_4_NumericBinary_Digits4_Scale0_BinarySwap);	/* P1 */
    f_S	= CobolFieldFactory.makeCobolField(2, b_S, a_5_NumericDisplay_Digits2_Scale0);	/* S */
    f_AMR	= CobolFieldFactory.makeCobolField(1, b_AMR, a_6_NumericDisplay_Digits1_Scale0);	/* AMR */
    f_SW_K	= CobolFieldFactory.makeCobolField(1, b_SW_K, a_6_NumericDisplay_Digits1_Scale0);	/* SW-K */
    f_CNT	= CobolFieldFactory.makeCobolField(3, b_CNT, a_2_NumericDisplay_Digits3_Scale0);	/* CNT */
    f_OUT	= CobolFieldFactory.makeCobolField(3, b_OUT, a_1_NumericEdited_Digits3_Scale0);	/* OUT */

    /* End of fields */


    /* Constants */

    c_1_2	= CobolFieldFactory.makeCobolField(1, "2", a_6_NumericDisplay_Digits1_Scale0);
    c_2_1	= CobolFieldFactory.makeCobolField(1, "1", a_6_NumericDisplay_Digits1_Scale0);

  }

  private void initAttr() {
    /* Attributes */

    a_1_NumericEdited_Digits3_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_EDITED,
      /* digits= */ 3,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ "Z\002\000\000\0009\001\000\000\000");
    a_2_NumericDisplay_Digits3_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 3,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_3_Alphanumeric = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_ALPHANUMERIC,
      /* digits= */ 0,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_4_NumericBinary_Digits4_Scale0_BinarySwap = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_BINARY,
      /* digits= */ 4,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_BINARY_SWAP,
      /* pic= */ null);
    a_5_NumericDisplay_Digits2_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 2,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_6_NumericDisplay_Digits1_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 1,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);

  }

  /* Decimal structures */

  private CobolDecimal d0;
  private CobolDecimal d1;

  /* Data storage */

  /* PROGRAM-ID : aising-B */
  public CobolDataStorage b_RETURN_CODE;	/* RETURN-CODE */
  private CobolDataStorage b_INP;	/* INP */
  private CobolDataStorage b_N;	/* N */
  private CobolDataStorage b_A;	/* A */
  private CobolDataStorage b_I;	/* I */
  private CobolDataStorage b_P1;	/* P1 */
  private CobolDataStorage b_P2;	/* P2 */
  private CobolDataStorage b_S;	/* S */
  private CobolDataStorage b_AMR;	/* AMR */
  private CobolDataStorage b_SW_K;	/* SW-K */
  private CobolDataStorage b_CNT;	/* CNT */
  private CobolDataStorage b_OUT;	/* OUT */

  /* End of data storage */


  /* Fields */

  /* PROGRAM-ID : aising-B */
  private AbstractCobolField f_INP;	/* INP */
  private AbstractCobolField f_N;	/* N */
  private AbstractCobolField f_A;	/* A */
  private AbstractCobolField f_I;	/* I */
  private AbstractCobolField f_P1;	/* P1 */
  private AbstractCobolField f_S;	/* S */
  private AbstractCobolField f_AMR;	/* AMR */
  private AbstractCobolField f_SW_K;	/* SW-K */
  private AbstractCobolField f_CNT;	/* CNT */
  private AbstractCobolField f_OUT;	/* OUT */

  /* End of fields */


  private static AbstractCobolField f_native;

  /* Constants */

  private AbstractCobolField c_2_1;
  private AbstractCobolField c_1_2;

  /* Attributes */

  private CobolFieldAttribute a_6_NumericDisplay_Digits1_Scale0;
  private CobolFieldAttribute a_5_NumericDisplay_Digits2_Scale0;
  private CobolFieldAttribute a_4_NumericBinary_Digits4_Scale0_BinarySwap;
  private CobolFieldAttribute a_3_Alphanumeric;
  private CobolFieldAttribute a_2_NumericDisplay_Digits3_Scale0;
  private CobolFieldAttribute a_1_NumericEdited_Digits3_Scale0;




  /* Sections and Labels */
  private final static int l_aising__B = 1;
  private final static int l_MAIN = 2;
  private final static int l_MAIN_SECTION__DEFAULT_PARAGRAPH = 3;
  private final static int l_Default_Error_Handler = 4;

}
