/* Generated by opensource COBOL 4J 1.1.16 */
import java.io.UnsupportedEncodingException;
import jp.osscons.opensourcecobol.libcobj.*;
import jp.osscons.opensourcecobol.libcobj.common.*;
import jp.osscons.opensourcecobol.libcobj.data.*;
import jp.osscons.opensourcecobol.libcobj.exceptions.*;
import jp.osscons.opensourcecobol.libcobj.termio.*;
import jp.osscons.opensourcecobol.libcobj.call.*;
import jp.osscons.opensourcecobol.libcobj.file.*;
import jp.osscons.opensourcecobol.libcobj.ui.*;
import java.util.Optional;

public class A__Birthday implements CobolRunnable {

  private boolean initialized = false;
  private CobolModule module;
  private int entry;

  private CobolRunnable cob_unifunc;


  @Override
  public int run(CobolDataStorage... argStorages) {
    return A__Birthday_(0, argStorages);
  }

  @Override
  public void cancel() {
    A__Birthday_(-1);
  }

  @Override
  public boolean isActive() {
    return false;
  }

  public CobolResultSet execute () {
    int returnCode = run_module(0);
    return new CobolResultSet(returnCode);
  }

  public int A__Birthday_ (int entry, CobolDataStorage ...argStorages) {
    this.entry = entry;
    return this.run_module(entry);
  }

  int run_module (int entry) {
    this.module = new CobolModule(null, null, null, null, 0, '.', '$', ',', 1, 1, 1, 0, null );

    /* Start of function code */

    /* CANCEL callback handling */
    if (entry < 0) {
    	if (!this.initialized) {
    		CobolDecimal.cobInitNumeric();
    		return 0;
    	}
    	this.initialized = false;
    	return 0;
    }

    /* Push module stack */
    CobolModule.push (module);
    CobolResolve.pushCallStackList ("A__Birthday");

    /* Initialize program */
    if (!this.initialized) {
      module.setProgramId("A__Birthday");

      b_RETURN_CODE.set((int)0);
      b_INP.fillBytes(' ', 100);
      b_IN_A.fillBytes('0', 2);
      b_IN_B.fillBytes('0', 2);
      this.initialized = true;
    }
    /* PROCEDURE DIVISION */
    try{
      /* Entry dispatch */
      execEntry(l_A__Birthday);

    } catch(CobolStopRunException e) {
      CobolStopRunException.stopRun();
      System.exit(e.getReturnCode());
    }
    /* Pop module stack */
    CobolResolve.popCallStackList();
    CobolModule.pop();

    /* Program return */
    return b_RETURN_CODE.intValue();
  }
  public CobolControl[] contList = {
    new CobolControl(0, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_A__Birthday]);
      }
    },
    /* Entry A-Birthday */
    new CobolControl(l_A__Birthday, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION]);
      }
    },
    /* MAIN SECTION */
    new CobolControl(l_MAIN_SECTION, CobolControl.LabelType.section) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION__MAIN_001]);
      }
    },
    /* MAIN-001 */
    new CobolControl(l_MAIN_SECTION__MAIN_001, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* /content/temp_cobol/A-Birthday_fixed.cob:12: ACCEPT */
        {
          CobolTerminal.accept (f_INP);
        }
        /* /content/temp_cobol/A-Birthday_fixed.cob:13: UNSTRING */
        {
          CobolString.unstringInit (f_INP, 0, 1);
          CobolString.unstringDelimited (c_1, 1);
          CobolString.unstringInto (f_IN_A, 0, 0);
          CobolString.unstringInto (f_IN_B, 0, 0);
          CobolString.unstringFinish ();
        }
        /* /content/temp_cobol/A-Birthday_fixed.cob:16: IF */
        {
          if ((((long)b_IN_A.cmpNumdisp (2, 8) <= 0L) && ((long)b_IN_B.cmpNumdisp (2, 8) <= 0L)))
            {
              /* /content/temp_cobol/A-Birthday_fixed.cob:17: DISPLAY */
              {
                CobolTerminal.display (0, 1, 1, c_2_Yay);
              }
            }
          else
            {
              /* /content/temp_cobol/A-Birthday_fixed.cob:19: DISPLAY */
              {
                CobolTerminal.display (0, 1, 1, c_3);
              }
            }
        }

        return Optional.of(contList[l_MAIN_SECTION__MAIN_EXIT]);
      }
    },
    /* MAIN-EXIT */
    new CobolControl(l_MAIN_SECTION__MAIN_EXIT, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* /content/temp_cobol/A-Birthday_fixed.cob:23: STOP */
        {
          CobolStopRunException.throwException (b_RETURN_CODE.intValue());
        }
        return Optional.of(CobolControl.pure());
      }
    },
    CobolControl.pure()
  };
  public void execEntry(int start) throws CobolRuntimeException, CobolStopRunException {
    Optional<CobolControl> nextLabel = Optional.of(contList[start]);
    while(nextLabel.isPresent()) {
      CobolControl section = nextLabel.get();
      nextLabel = section.run();
    }
  }

  public static void main(String[] args)
  {
    CobolUtil.cob_init(args, false);
    CobolDecimal.cobInitNumeric();
    new A__Birthday().A__Birthday_(0);
    CobolStopRunException.stopRun();
  }

  public A__Birthday()
  {
    init();
  }

  public void init() 
  {
    /* Data storage */

    cob_unifunc = null;

    /* PROGRAM-ID : A-Birthday */
    b_RETURN_CODE = new CobolDataStorage(4);	/* RETURN-CODE */
    b_INP = new CobolDataStorage(100);	/* INP */
    b_IN_A = new CobolDataStorage(2);	/* IN-A */
    b_IN_B = new CobolDataStorage(2);	/* IN-B */

    /* End of data storage */


    initAttr();

    /* Fields */

    /* PROGRAM-ID : A-Birthday */
    f_INP	= CobolFieldFactory.makeCobolField(100, b_INP, a_1_Alphanumeric);	/* INP */
    f_IN_A	= CobolFieldFactory.makeCobolField(2, b_IN_A, a_2_NumericDisplay_Digits2_Scale0);	/* IN-A */
    f_IN_B	= CobolFieldFactory.makeCobolField(2, b_IN_B, a_2_NumericDisplay_Digits2_Scale0);	/* IN-B */

    /* End of fields */


    /* Constants */

    c_1	= CobolFieldFactory.makeCobolField(str_0, a_1_Alphanumeric);
    c_2_Yay	= CobolFieldFactory.makeCobolField(str_1_Yay, a_1_Alphanumeric);
    c_3	= CobolFieldFactory.makeCobolField(str_2, a_1_Alphanumeric);

  }

  private void initAttr() {
    /* Attributes */

    a_1_Alphanumeric = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_ALPHANUMERIC,
      /* digits= */ 0,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_2_NumericDisplay_Digits2_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 2,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);

  }

  /* Data storage */

  /* PROGRAM-ID : A-Birthday */
  public CobolDataStorage b_RETURN_CODE;	/* RETURN-CODE */
  private CobolDataStorage b_INP;	/* INP */
  private CobolDataStorage b_IN_A;	/* IN-A */
  private CobolDataStorage b_IN_B;	/* IN-B */

  /* End of data storage */


  /* Fields */

  /* PROGRAM-ID : A-Birthday */
  private AbstractCobolField f_INP;	/* INP */
  private AbstractCobolField f_IN_A;	/* IN-A */
  private AbstractCobolField f_IN_B;	/* IN-B */

  /* End of fields */


  private static AbstractCobolField f_native;

  /* Constants */

  private AbstractCobolField c_3;
  private AbstractCobolField c_2_Yay;
  private AbstractCobolField c_1;

  /* Attributes */

  private CobolFieldAttribute a_2_NumericDisplay_Digits2_Scale0;
  private CobolFieldAttribute a_1_Alphanumeric;



  /* String literals */
  public static final byte[] str_2 = CobolUtil.stringToBytes(":(");
  public static final byte[] str_1_Yay = CobolUtil.stringToBytes("Yay!");
  public static final byte[] str_0 = CobolUtil.stringToBytes(" ");

  /* Sections and Labels */
  private final static int l_A__Birthday = 1;
  private final static int l_MAIN_SECTION = 2;
  private final static int l_MAIN_SECTION__MAIN_001 = 3;
  private final static int l_MAIN_SECTION__MAIN_EXIT = 4;
  private final static int l_Default_Error_Handler = 5;

}
