/* Generated by opensource COBOL 4J 1.1.16 */
import java.io.UnsupportedEncodingException;
import jp.osscons.opensourcecobol.libcobj.*;
import jp.osscons.opensourcecobol.libcobj.common.*;
import jp.osscons.opensourcecobol.libcobj.data.*;
import jp.osscons.opensourcecobol.libcobj.exceptions.*;
import jp.osscons.opensourcecobol.libcobj.termio.*;
import jp.osscons.opensourcecobol.libcobj.call.*;
import jp.osscons.opensourcecobol.libcobj.file.*;
import jp.osscons.opensourcecobol.libcobj.ui.*;
import java.util.Optional;

public class caddi2018a implements CobolRunnable {

  private boolean initialized = false;
  private CobolModule module;
  private int entry;

  private CobolRunnable cob_unifunc;


  @Override
  public int run(CobolDataStorage... argStorages) {
    return caddi2018a_(0, argStorages);
  }

  @Override
  public void cancel() {
    caddi2018a_(-1);
  }

  @Override
  public boolean isActive() {
    return false;
  }

  public CobolResultSet execute () {
    int returnCode = run_module(0);
    return new CobolResultSet(returnCode);
  }

  public int caddi2018a_ (int entry, CobolDataStorage ...argStorages) {
    this.entry = entry;
    return this.run_module(entry);
  }

  int run_module (int entry) {
    this.module = new CobolModule(null, null, null, null, 0, '.', '$', ',', 1, 1, 1, 0, null );

    /* Start of function code */

    /* CANCEL callback handling */
    if (entry < 0) {
    	if (!this.initialized) {
    		CobolDecimal.cobInitNumeric();
    		return 0;
    	}
    	this.initialized = false;
    	return 0;
    }

    /* Push module stack */
    CobolModule.push (module);
    CobolResolve.pushCallStackList ("caddi2018a");

    /* Initialize program */
    if (!this.initialized) {
      module.setProgramId("caddi2018a");

      b_RETURN_CODE.set((int)0);
      b_n.fillBytes('0', 4);
      b_c.setByte('0');
      this.initialized = true;
    }
    /* PROCEDURE DIVISION */
    try{
      /* Entry dispatch */
      execEntry(l_caddi2018a);

    } catch(CobolStopRunException e) {
      CobolStopRunException.stopRun();
      System.exit(e.getReturnCode());
    }
    /* Pop module stack */
    CobolResolve.popCallStackList();
    CobolModule.pop();

    /* Program return */
    return b_RETURN_CODE.intValue();
  }
  public CobolControl[] contList = {
    new CobolControl(0, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_caddi2018a]);
      }
    },
    /* Entry caddi2018a */
    new CobolControl(l_caddi2018a, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN]);
      }
    },
    /* MAIN SECTION */
    new CobolControl(l_MAIN, CobolControl.LabelType.section) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION__DEFAULT_PARAGRAPH]);
      }
    },
    /* MAIN_SECTION__DEFAULT_PARAGRAPH */
    new CobolControl(l_MAIN_SECTION__DEFAULT_PARAGRAPH, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* /content/temp_cobol/caddi2018a_fixed.cob:12: ACCEPT */
        {
          CobolTerminal.accept (f_n);
        }
        /* /content/temp_cobol/caddi2018a_fixed.cob:13: INSPECT */
        {
          CobolInspect.init (f_n, 0);
          CobolInspect.start ();
          CobolInspect.all (f_c, c_1_2);
          CobolInspect.finish ();
        }
        /* /content/temp_cobol/caddi2018a_fixed.cob:14: DISPLAY */
        {
          CobolTerminal.display (0, 1, 1, f_c);
        }
        /* /content/temp_cobol/caddi2018a_fixed.cob:15: STOP */
        {
          CobolStopRunException.throwException (b_RETURN_CODE.intValue());
        }
        return Optional.of(CobolControl.pure());
      }
    },
    CobolControl.pure()
  };
  public void execEntry(int start) throws CobolRuntimeException, CobolStopRunException {
    Optional<CobolControl> nextLabel = Optional.of(contList[start]);
    while(nextLabel.isPresent()) {
      CobolControl section = nextLabel.get();
      nextLabel = section.run();
    }
  }

  public static void main(String[] args)
  {
    CobolUtil.cob_init(args, false);
    CobolDecimal.cobInitNumeric();
    new caddi2018a().caddi2018a_(0);
    CobolStopRunException.stopRun();
  }

  public caddi2018a()
  {
    init();
  }

  public void init() 
  {
    /* Data storage */

    cob_unifunc = null;

    /* PROGRAM-ID : caddi2018a */
    b_RETURN_CODE = new CobolDataStorage(4);	/* RETURN-CODE */
    b_n = new CobolDataStorage(4);	/* n */
    b_c = new CobolDataStorage(1);	/* c */

    /* End of data storage */


    initAttr();

    /* Fields */

    /* PROGRAM-ID : caddi2018a */
    f_n	= CobolFieldFactory.makeCobolField(4, b_n, a_1_NumericDisplay_Digits4_Scale0);	/* n */
    f_c	= CobolFieldFactory.makeCobolField(1, b_c, a_2_NumericDisplay_Digits1_Scale0);	/* c */

    /* End of fields */


    /* Constants */

    c_1_2	= CobolFieldFactory.makeCobolField(str_0_2, a_3_Alphanumeric);

  }

  private void initAttr() {
    /* Attributes */

    a_1_NumericDisplay_Digits4_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 4,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_2_NumericDisplay_Digits1_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 1,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_3_Alphanumeric = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_ALPHANUMERIC,
      /* digits= */ 0,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);

  }

  /* Data storage */

  /* PROGRAM-ID : caddi2018a */
  public CobolDataStorage b_RETURN_CODE;	/* RETURN-CODE */
  private CobolDataStorage b_n;	/* n */
  private CobolDataStorage b_c;	/* c */

  /* End of data storage */


  /* Fields */

  /* PROGRAM-ID : caddi2018a */
  private AbstractCobolField f_n;	/* n */
  private AbstractCobolField f_c;	/* c */

  /* End of fields */


  private static AbstractCobolField f_native;

  /* Constants */

  private AbstractCobolField c_1_2;

  /* Attributes */

  private CobolFieldAttribute a_3_Alphanumeric;
  private CobolFieldAttribute a_2_NumericDisplay_Digits1_Scale0;
  private CobolFieldAttribute a_1_NumericDisplay_Digits4_Scale0;



  /* String literals */
  public static final byte[] str_0_2 = CobolUtil.stringToBytes("2");

  /* Sections and Labels */
  private final static int l_caddi2018a = 1;
  private final static int l_MAIN = 2;
  private final static int l_MAIN_SECTION__DEFAULT_PARAGRAPH = 3;
  private final static int l_Default_Error_Handler = 4;

}
