/* Generated by opensource COBOL 4J 1.1.16 */
import java.io.UnsupportedEncodingException;
import jp.osscons.opensourcecobol.libcobj.*;
import jp.osscons.opensourcecobol.libcobj.common.*;
import jp.osscons.opensourcecobol.libcobj.data.*;
import jp.osscons.opensourcecobol.libcobj.exceptions.*;
import jp.osscons.opensourcecobol.libcobj.termio.*;
import jp.osscons.opensourcecobol.libcobj.call.*;
import jp.osscons.opensourcecobol.libcobj.file.*;
import jp.osscons.opensourcecobol.libcobj.ui.*;
import java.util.Optional;

public class _3170D implements CobolRunnable {

  private boolean initialized = false;
  private CobolModule module;
  private int entry;

  private CobolRunnable cob_unifunc;


  @Override
  public int run(CobolDataStorage... argStorages) {
    return _3170D_(0, argStorages);
  }

  @Override
  public void cancel() {
    _3170D_(-1);
  }

  @Override
  public boolean isActive() {
    return false;
  }

  public CobolResultSet execute () {
    int returnCode = run_module(0);
    return new CobolResultSet(returnCode);
  }

  public int _3170D_ (int entry, CobolDataStorage ...argStorages) {
    this.entry = entry;
    return this.run_module(entry);
  }

  int run_module (int entry) {
    this.module = new CobolModule(null, null, null, null, 0, '.', '$', ',', 1, 1, 1, 0, null );

    /* Start of function code */

    /* CANCEL callback handling */
    if (entry < 0) {
    	if (!this.initialized) {
    		CobolDecimal.cobInitNumeric();
    		return 0;
    	}
    	h_STDIO.close (0, null);
    	d0.clear();
    	d0.setScale(0);
    	d1.clear();
    	d1.setScale(0);
    	d2.clear();
    	d2.setScale(0);
    	this.initialized = false;
    	return 0;
    }

    /* Push module stack */
    CobolModule.push (module);
    CobolResolve.pushCallStackList ("_3170D");

    /* Initialize program */
    if (!this.initialized) {
      module.setProgramId("_3170D");

      /* Initialize decimal numbers */
      d0.decimalInit();
      d1.decimalInit();
      d2.decimalInit();

      b_RETURN_CODE.set((int)0);
      b_N.fillBytes('0', 6);
      b_P1.fillBytes(0, 4);
      b_P2.fillBytes(0, 4);
      b_I.fillBytes(0, 4);
      b_J.fillBytes(0, 4);
      b_IDX.fillBytes(0, 4);
      b_TBL1.fillBytes(0, 800000);
      b_TBL2.fillBytes(0, 1000000);
      b_CNT.fillBytes('0', 6);
      f_OUT.moveFrom (CobolConstant.zero);

      h_STDIO = CobolFileFactory.makeCobolFileInstance(
      /* select_name = */ "STDIO",
      /* file_status = */ h_STDIO_status,
      /* assign = */ null,
      /* record = */ f_STDIO_record,
      /* record_size = */ null,
      /* record_min = */ 0,
      /* record_max = */ 1600000,
      /* nkeys = */ 0,
      /* keys = */ null,
      /* organization = */ (char)1,
      /* access_mode = */ (char)1,
      /* lock_mode = */ (char)2,
      /* open_mode = */ (char)0,
      /* flag_optional = */ false,
      /* last_open_mode = */ (char)0,
      /* special = */ (char)1,
      /* flag_nonexistent = */ false,
      /* flag_end_of_file = */ false,
      /* flag_begin_of_file = */ false,
      /* flag_first_read = */ (char)0,
      /* flag_read_done = */ false,
      /* flag_select_features = */ (char)0,
      /* flag_needs_nl = */ false,
      /* flag_needs_top = */ false,
      /* file_version = */ (char)0
      );

      this.initialized = true;
    }
    /* PROCEDURE DIVISION */
    try{
      /* Entry dispatch */
      execEntry(l__3170D);

    } catch(CobolStopRunException e) {
      CobolStopRunException.stopRun();
      System.exit(e.getReturnCode());
    }
    /* Pop module stack */
    CobolResolve.popCallStackList();
    CobolModule.pop();

    /* Program return */
    return b_RETURN_CODE.intValue();
  }
  public CobolControl[] contList = {
    new CobolControl(0, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l__3170D]);
      }
    },
    /* Entry 170D */
    new CobolControl(l__3170D, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN]);
      }
    },
    /* MAIN SECTION */
    new CobolControl(l_MAIN, CobolControl.LabelType.section) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION__DEFAULT_PARAGRAPH]);
      }
    },
    /* MAIN_SECTION__DEFAULT_PARAGRAPH */
    new CobolControl(l_MAIN_SECTION__DEFAULT_PARAGRAPH, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* /content/temp_cobol/170D_fixed.cob:30: ACCEPT */
        {
          CobolTerminal.accept (f_N);
        }
        /* /content/temp_cobol/170D_fixed.cob:32: OPEN */
        {
          CobolRuntimeException.code = 0;
          {
            h_STDIO.open (1, 0, null);
          }
          if (CobolRuntimeException.code != 0)
          {
            /* PERFORM Default Error Handler */
            CobolControl.perform(contList, l_Default_Error_Handler).run();
          }
        }
        /* /content/temp_cobol/170D_fixed.cob:33: READ */
        CobolRuntimeException.code = 0;
        {
          h_STDIO.read (0, null, 1);
        }
        if (CobolRuntimeException.code != 0)
        {
          /* PERFORM Default Error Handler */
          CobolControl.perform(contList, l_Default_Error_Handler).run();
        }
        /* /content/temp_cobol/170D_fixed.cob:34: CLOSE */
        {
          CobolRuntimeException.code = 0;
          {
            h_STDIO.close (0, null);
          }
          if (CobolRuntimeException.code != 0)
          {
            /* PERFORM Default Error Handler */
            CobolControl.perform(contList, l_Default_Error_Handler).run();
          }
        }
        /* /content/temp_cobol/170D_fixed.cob:37: MOVE */
        {
          b_P1.setSwpU32Binary (1);
        }
        /* /content/temp_cobol/170D_fixed.cob:38: PERFORM */
        b_I.setSwpU32Binary (1);
        for(;;b_I.addSwpU32Binary (1))
        {
          if (((long)f_I.cmpInteger (b_N.getNumdisp(6)) >  0L))
            break;
          {
            /* /content/temp_cobol/170D_fixed.cob:39: PERFORM */
            b_P2.setBytes (b_P1, 4);
            for(;;b_P2.addSwpU32Binary (1))
            {
              if (((long)(Byte.toUnsignedInt(b_INP.getSubDataStorage(((int)(b_P2.bswap_32()) - 1)).getByte(0)) - (int)32) == 0L))
                break;
              ;
            }
            /* /content/temp_cobol/170D_fixed.cob:41: MOVE */
            {
              CobolFieldFactory.makeCobolField(4, b_A__TBL1.getSubDataStorage(4 * ((int)(b_I.bswap_32()) - 1)), a_4_NumericBinary_Digits6_Scale0_BinarySwap).moveFrom (CobolFieldFactory.makeCobolField(((int)(b_P2.bswap_32()) - (int)(b_P1.bswap_32())), b_INP.getSubDataStorage(((int)(b_P1.bswap_32()) - 1)), a_2_Alphanumeric));
              f_IDX.moveFrom (CobolFieldFactory.makeCobolField(((int)(b_P2.bswap_32()) - (int)(b_P1.bswap_32())), b_INP.getSubDataStorage(((int)(b_P1.bswap_32()) - 1)), a_2_Alphanumeric));
            }
            /* /content/temp_cobol/170D_fixed.cob:42: ADD */
            {
              CobolFieldFactory.makeCobolField(4, b_B__TBL_M__TBL2.getSubDataStorage(5 * ((int)(b_IDX.bswap_32()) - 1)), a_5_NumericBinary_Digits7_Scale0_BinarySwap).add (c_1_1, 4);
            }
            /* /content/temp_cobol/170D_fixed.cob:43: COMPUTE */
            {
              {
                {
                  d0.set ((int)(b_P2.bswap_32()));
                  d1.set (1);
                  d0.add (d1);
                  d0.getField (f_P1, 4);
                }
              }
            }
          }
        }
        /* /content/temp_cobol/170D_fixed.cob:46: SORT */
        {
          CobolFileSort.sortTableInit (1, 0);
          CobolFileSort.sortTableInitKey (0, f_A__TBL1, 0);
          CobolFileSort.sortTable (f_A__TBL1, b_N.getNumdisp(6));
        }
        /* /content/temp_cobol/170D_fixed.cob:47: MOVE */
        {
          b_CNT.fillBytes (48, 6);
        }
        /* /content/temp_cobol/170D_fixed.cob:48: PERFORM */
        b_I.setSwpU32Binary (1);
        for(;;b_I.addSwpU32Binary (1))
        {
          if (((long)f_I.cmpInteger (b_N.getNumdisp(6)) >  0L))
            break;
          {
            /* /content/temp_cobol/170D_fixed.cob:49: IF */
            {
              if (((long)CobolFieldFactory.makeCobolField(1, b_C__TBL_M__TBL2.getSubDataStorage(5 * ((int)(b_A__TBL1.getSubDataStorage(4 * ((int)(b_I.bswap_32()) - 1)).bswap_32()) - 1)), a_6_NumericBinary_Digits1_Scale0_BinarySwap).cmpInteger (0) == 0L))
                {
                  /* /content/temp_cobol/170D_fixed.cob:50: IF */
                  {
                    if (((long)CobolFieldFactory.makeCobolField(4, b_B__TBL_M__TBL2.getSubDataStorage(5 * ((int)(b_A__TBL1.getSubDataStorage(4 * ((int)(b_I.bswap_32()) - 1)).bswap_32()) - 1)), a_5_NumericBinary_Digits7_Scale0_BinarySwap).cmpInteger (1) >  0L))
                      {
                        /* /content/temp_cobol/170D_fixed.cob:51: MOVE */
                        {
                          b_C__TBL_M__TBL2.getSubDataStorage(5 * (b_A__TBL1.getSubDataStorage(4 * (b_I - 1)) - 1)).set((byte)1);
                        }
                      }
                  }
                  /* /content/temp_cobol/170D_fixed.cob:54: PERFORM */
                  b_J.setSwpU32Binary (2);
                  for(;;b_J.addSwpU32Binary (1))
                  {
                    if (((long)                    (new GetInt() {
                      public int run() throws CobolStopRunException {
                        d0.set ((int)(b_A__TBL1.getSubDataStorage(4 * ((int)(b_I.bswap_32()) - 1)).bswap_32()));
                        d2.set ((int)(b_J.bswap_32()));
                        d0.mul (d2);
                        d1.set ((int)(b_A__TBL1.getSubDataStorage(4 * (b_N.getNumdisp(6) - 1)).bswap_32()));
                        return 
                        d0.compareTo (d1);
                    }
                  }).run() >  0L))
                    break;
                  {
                    /* /content/temp_cobol/170D_fixed.cob:55: MOVE */
                    {
                      b_C__TBL_M__TBL2.getSubDataStorage(5 * ((b_A__TBL1.getSubDataStorage(4 * (b_I - 1)) * b_J) - 1)).set((byte)1);
                    }
                  }
                }
              }
          }
        }
      }
      /* /content/temp_cobol/170D_fixed.cob:60: MOVE */
      {
        b_CNT.fillBytes (48, 6);
      }
      /* /content/temp_cobol/170D_fixed.cob:61: PERFORM */
      b_I.setSwpU32Binary (1);
      for(;;b_I.addSwpU32Binary (1))
      {
        if (((long)f_I.cmpInteger (b_N.getNumdisp(6)) >  0L))
          break;
        {
          /* /content/temp_cobol/170D_fixed.cob:62: IF */
          {
            if (((long)CobolFieldFactory.makeCobolField(1, b_C__TBL_M__TBL2.getSubDataStorage(5 * ((int)(b_A__TBL1.getSubDataStorage(4 * ((int)(b_I.bswap_32()) - 1)).bswap_32()) - 1)), a_6_NumericBinary_Digits1_Scale0_BinarySwap).cmpInteger (0) == 0L))
              {
                /* /content/temp_cobol/170D_fixed.cob:63: ADD */
                {
                  f_CNT.add (c_1_1, 4);
                }
              }
          }
        }
      }
      /* /content/temp_cobol/170D_fixed.cob:67: MOVE */
      {
        f_OUT.moveFrom (f_CNT);
      }
      /* /content/temp_cobol/170D_fixed.cob:68: DISPLAY */
      {
        CobolTerminal.display (0, 1, 1, CobolIntrinsic.funcTrim (0, 0, f_OUT, 0));
      }
      /* /content/temp_cobol/170D_fixed.cob:69: STOP */
      {
        CobolStopRunException.throwException (b_RETURN_CODE.intValue());
      }


      return Optional.of(CobolControl.pure());
    }
  },
  /* Default Error Handler */
  new CobolControl(l_Default_Error_Handler, CobolControl.LabelType.label) {
    public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

      if ((CobolFile.errorFile.flag_select_features & CobolFile.COB_SELECT_FILE_STATUS) == 0) {
      	CobolFile.defaultErrorHandle ();
      	CobolStopRunException.stopRunAndThrow (1);
      }

      return Optional.of(CobolControl.pure());
    }
  },
  CobolControl.pure()
};
public void execEntry(int start) throws CobolRuntimeException, CobolStopRunException {
  Optional<CobolControl> nextLabel = Optional.of(contList[start]);
  while(nextLabel.isPresent()) {
    CobolControl section = nextLabel.get();
    nextLabel = section.run();
  }
}

public static void main(String[] args)
{
  CobolUtil.cob_init(args, false);
  CobolDecimal.cobInitNumeric();
  new _3170D()._3170D_(0);
  CobolStopRunException.stopRun();
}

public _3170D()
{
  init();
}

public void init() 
{
  /* Decimal structures */

  d0 = new CobolDecimal();
  d1 = new CobolDecimal();
  d2 = new CobolDecimal();

  /* Data storage */

  cob_unifunc = null;

  /* PROGRAM-ID : 170D */
  b_RETURN_CODE = new CobolDataStorage(4);	/* RETURN-CODE */
  b_STDIO_record = new CobolDataStorage(1600000);	/* STDIO_record */
  b_N = new CobolDataStorage(6);	/* N */
  b_P1 = new CobolDataStorage(4);	/* P1 */
  b_P2 = new CobolDataStorage(4);	/* P2 */
  b_I = new CobolDataStorage(4);	/* I */
  b_J = new CobolDataStorage(4);	/* J */
  b_IDX = new CobolDataStorage(4);	/* IDX */
  b_TBL1 = new CobolDataStorage(800000);	/* TBL1 */
  b_TBL2 = new CobolDataStorage(1000000);	/* TBL2 */
  b_CNT = new CobolDataStorage(6);	/* CNT */
  b_OUT = new CobolDataStorage(6);	/* OUT */
  b_INP = b_STDIO_record;
  b_A__TBL1 = b_TBL1;
  b_B__TBL_M__TBL2 = b_TBL2;
  b_C__TBL_M__TBL2 = b_TBL2.getSubDataStorage(4);

  /* End of data storage */


  initAttr();

  /* Fields */

  /* PROGRAM-ID : 170D */
  f_STDIO_record	= CobolFieldFactory.makeCobolField(1600000, b_STDIO_record, a_2_Alphanumeric);	/* STDIO_record */
  f_N	= CobolFieldFactory.makeCobolField(6, b_N, a_3_NumericDisplay_Digits6_Scale0);	/* N */
  f_P1	= CobolFieldFactory.makeCobolField(4, b_P1, a_5_NumericBinary_Digits7_Scale0_BinarySwap);	/* P1 */
  f_I	= CobolFieldFactory.makeCobolField(4, b_I, a_4_NumericBinary_Digits6_Scale0_BinarySwap);	/* I */
  f_IDX	= CobolFieldFactory.makeCobolField(4, b_IDX, a_4_NumericBinary_Digits6_Scale0_BinarySwap);	/* IDX */
  f_A__TBL1	= CobolFieldFactory.makeCobolField(4, b_A__TBL1, a_4_NumericBinary_Digits6_Scale0_BinarySwap);	/* A */
  f_CNT	= CobolFieldFactory.makeCobolField(6, b_CNT, a_3_NumericDisplay_Digits6_Scale0);	/* CNT */
  f_OUT	= CobolFieldFactory.makeCobolField(6, b_OUT, a_1_NumericEdited_Digits6_Scale0);	/* OUT */

  /* End of fields */


  /* Constants */

  c_1_1	= CobolFieldFactory.makeCobolField(1, "1", a_7_NumericDisplay_Digits1_Scale0);

}

private void initAttr() {
  /* Attributes */

  a_1_NumericEdited_Digits6_Scale0 = new CobolFieldAttribute(
    CobolFieldAttribute.COB_TYPE_NUMERIC_EDITED,
    /* digits= */ 6,
    /* scale= */ 0,
    CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
    /* pic= */ "Z\005\000\000\0009\001\000\000\000");
  a_2_Alphanumeric = new CobolFieldAttribute(
    CobolFieldAttribute.COB_TYPE_ALPHANUMERIC,
    /* digits= */ 0,
    /* scale= */ 0,
    CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
    /* pic= */ null);
  a_3_NumericDisplay_Digits6_Scale0 = new CobolFieldAttribute(
    CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
    /* digits= */ 6,
    /* scale= */ 0,
    CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
    /* pic= */ null);
  a_4_NumericBinary_Digits6_Scale0_BinarySwap = new CobolFieldAttribute(
    CobolFieldAttribute.COB_TYPE_NUMERIC_BINARY,
    /* digits= */ 6,
    /* scale= */ 0,
    CobolFieldAttribute.COB_FLAG_BINARY_SWAP,
    /* pic= */ null);
  a_5_NumericBinary_Digits7_Scale0_BinarySwap = new CobolFieldAttribute(
    CobolFieldAttribute.COB_TYPE_NUMERIC_BINARY,
    /* digits= */ 7,
    /* scale= */ 0,
    CobolFieldAttribute.COB_FLAG_BINARY_SWAP,
    /* pic= */ null);
  a_6_NumericBinary_Digits1_Scale0_BinarySwap = new CobolFieldAttribute(
    CobolFieldAttribute.COB_TYPE_NUMERIC_BINARY,
    /* digits= */ 1,
    /* scale= */ 0,
    CobolFieldAttribute.COB_FLAG_BINARY_SWAP,
    /* pic= */ null);
  a_7_NumericDisplay_Digits1_Scale0 = new CobolFieldAttribute(
    CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
    /* digits= */ 1,
    /* scale= */ 0,
    CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
    /* pic= */ null);

}

/* Decimal structures */

private CobolDecimal d0;
private CobolDecimal d1;
private CobolDecimal d2;

/* Data storage */

/* PROGRAM-ID : 170D */
public CobolDataStorage b_RETURN_CODE;	/* RETURN-CODE */
private CobolDataStorage b_STDIO_record;	/* STDIO_record */
private CobolDataStorage b_N;	/* N */
private CobolDataStorage b_P1;	/* P1 */
private CobolDataStorage b_P2;	/* P2 */
private CobolDataStorage b_I;	/* I */
private CobolDataStorage b_J;	/* J */
private CobolDataStorage b_IDX;	/* IDX */
private CobolDataStorage b_TBL1;	/* TBL1 */
private CobolDataStorage b_TBL2;	/* TBL2 */
private CobolDataStorage b_CNT;	/* CNT */
private CobolDataStorage b_OUT;	/* OUT */
private CobolDataStorage b_INP;
private CobolDataStorage b_A__TBL1;
private CobolDataStorage b_B__TBL_M__TBL2;
private CobolDataStorage b_C__TBL_M__TBL2;

/* End of data storage */


/* Fields */

/* PROGRAM-ID : 170D */
private AbstractCobolField f_STDIO_record;	/* STDIO_record */
private AbstractCobolField f_N;	/* N */
private AbstractCobolField f_P1;	/* P1 */
private AbstractCobolField f_I;	/* I */
private AbstractCobolField f_IDX;	/* IDX */
private AbstractCobolField f_A__TBL1;	/* A */
private AbstractCobolField f_CNT;	/* CNT */
private AbstractCobolField f_OUT;	/* OUT */

/* End of fields */


private static AbstractCobolField f_native;

/* Constants */

private AbstractCobolField c_1_1;

/* Attributes */

private CobolFieldAttribute a_7_NumericDisplay_Digits1_Scale0;
private CobolFieldAttribute a_6_NumericBinary_Digits1_Scale0_BinarySwap;
private CobolFieldAttribute a_5_NumericBinary_Digits7_Scale0_BinarySwap;
private CobolFieldAttribute a_4_NumericBinary_Digits6_Scale0_BinarySwap;
private CobolFieldAttribute a_3_NumericDisplay_Digits6_Scale0;
private CobolFieldAttribute a_2_Alphanumeric;
private CobolFieldAttribute a_1_NumericEdited_Digits6_Scale0;



/* File STDIO */
private CobolFile		h_STDIO = null;
private byte[]	h_STDIO_status = new byte[4];

/* Sections and Labels */
private final static int l__3170D = 1;
private final static int l_MAIN = 2;
private final static int l_MAIN_SECTION__DEFAULT_PARAGRAPH = 3;
private final static int l_Default_Error_Handler = 4;

}
