/* Generated by opensource COBOL 4J 1.1.16 */
import java.io.UnsupportedEncodingException;
import jp.osscons.opensourcecobol.libcobj.*;
import jp.osscons.opensourcecobol.libcobj.common.*;
import jp.osscons.opensourcecobol.libcobj.data.*;
import jp.osscons.opensourcecobol.libcobj.exceptions.*;
import jp.osscons.opensourcecobol.libcobj.termio.*;
import jp.osscons.opensourcecobol.libcobj.call.*;
import jp.osscons.opensourcecobol.libcobj.file.*;
import jp.osscons.opensourcecobol.libcobj.ui.*;
import java.util.Optional;

public class test1 implements CobolRunnable {

  private boolean initialized = false;
  private CobolModule module;
  private int entry;

  private CobolRunnable cob_unifunc;


  @Override
  public int run(CobolDataStorage... argStorages) {
    return test1_(0, argStorages);
  }

  @Override
  public void cancel() {
    test1_(-1);
  }

  @Override
  public boolean isActive() {
    return false;
  }

  public CobolResultSet execute () {
    int returnCode = run_module(0);
    return new CobolResultSet(returnCode);
  }

  public int test1_ (int entry, CobolDataStorage ...argStorages) {
    this.entry = entry;
    return this.run_module(entry);
  }

  int run_module (int entry) {
    this.module = new CobolModule(null, null, null, null, 0, '.', '$', ',', 1, 1, 1, 0, null );

    /* Start of function code */

    /* CANCEL callback handling */
    if (entry < 0) {
    	if (!this.initialized) {
    		CobolDecimal.cobInitNumeric();
    		return 0;
    	}
    	this.initialized = false;
    	return 0;
    }

    /* Push module stack */
    CobolModule.push (module);
    CobolResolve.pushCallStackList ("test1");

    /* Initialize program */
    if (!this.initialized) {
      module.setProgramId("test1");

      b_RETURN_CODE.set((int)0);
      b_INP.fillBytes(' ', 11000);
      b_A_REC.fillBytes('0', 300);
      b_B.fillBytes('0', 3);
      b_C.fillBytes('0', 3);
      b_D.fillBytes('0', 3);
      b_ALICE.fillBytes('0', 6);
      b_BOB.fillBytes('0', 6);
      b_REN.fillBytes('0', 10);
      f_RE.moveFrom (CobolConstant.zero);
      b_temp1.fillBytes('0', 7);
      b_temp2.fillBytes('0', 7);
      b_temp3.fillBytes('0', 7);
      b_NOW.fillBytes('0', 7);
      b_N.fillBytes('0', 3);
      b_MAX.fillBytes('0', 3);
      this.initialized = true;
    }
    /* PROCEDURE DIVISION */
    try{
      /* Entry dispatch */
      execEntry(l_test1);

    } catch(CobolStopRunException e) {
      CobolStopRunException.stopRun();
      System.exit(e.getReturnCode());
    }
    /* Pop module stack */
    CobolResolve.popCallStackList();
    CobolModule.pop();

    /* Program return */
    return b_RETURN_CODE.intValue();
  }
  public CobolControl[] contList = {
    new CobolControl(0, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_test1]);
      }
    },
    /* Entry test1 */
    new CobolControl(l_test1, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION]);
      }
    },
    /* MAIN SECTION */
    new CobolControl(l_MAIN_SECTION, CobolControl.LabelType.section) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION__MAIN]);
      }
    },
    /* MAIN */
    new CobolControl(l_MAIN_SECTION__MAIN, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* /content/temp_translate/s107906750.cob:25: PERFORM */
        b_N.setBytes (str_0_001, 3);
        for(;;f_N.addInt (1))
        {
          if (((long)b_N.cmpNumdisp (3, 101) == 0L))
            break;
          {
            /* /content/temp_translate/s107906750.cob:26: MOVE */
            {
              b_A__A_DATA__A_REC.getSubDataStorage(3 * (b_N.getNumdisp(3) - 1)).fillBytes (48, 3);
            }
          }
        }
        /* /content/temp_translate/s107906750.cob:28: ACCEPT */
        {
          CobolTerminal.accept (f_B);
        }
        /* /content/temp_translate/s107906750.cob:29: ADD */
        {
          f_B.add (c_1_1, 4);
        }
        /* /content/temp_translate/s107906750.cob:30: PERFORM */
        b_N.setBytes (str_1_001, 3);
        for(;;f_N.addInt (1))
        {
          if (((long)b_N.memcmp (b_B, 3) == 0L))
            break;
          {
            /* /content/temp_translate/s107906750.cob:31: ACCEPT */
            {
              CobolTerminal.accept (f_C);
            }
            /* /content/temp_translate/s107906750.cob:32: ADD */
            {
              CobolFieldFactory.makeCobolField(3, b_A__A_DATA__A_REC.getSubDataStorage(3 * (b_C.getNumdisp(3) - 1)), a_2_NumericDisplay_Digits3_Scale0).add (c_1_1, 4);
            }
          }
        }
        /* /content/temp_translate/s107906750.cob:34: MOVE */
        {
          b_D.fillBytes (48, 3);
        }
        /* /content/temp_translate/s107906750.cob:35: PERFORM */
        b_N.setBytes (str_2_001, 3);
        for(;;f_N.addInt (1))
        {
          if (((long)b_N.cmpNumdisp (3, 101) == 0L))
            break;
          {
            /* /content/temp_translate/s107906750.cob:36: IF */
            {
              if (((long)b_A__A_DATA__A_REC.getSubDataStorage(3 * (b_N.getNumdisp(3) - 1)).cmpNumdisp (3, 0) >  0L))
                {
                  /* /content/temp_translate/s107906750.cob:37: ADD */
                  {
                    f_D.add (c_1_1, 4);
                  }
                }
            }
          }
        }
        /* /content/temp_translate/s107906750.cob:40: MOVE */
        {
          f_RE.moveFrom (f_D);
        }
        /* /content/temp_translate/s107906750.cob:41: DISPLAY */
        {
          CobolTerminal.display (0, 1, 1, f_RE);
        }
        /* /content/temp_translate/s107906750.cob:42: STOP */
        {
          CobolStopRunException.throwException (b_RETURN_CODE.intValue());
        }
        return Optional.of(CobolControl.pure());
      }
    },
    CobolControl.pure()
  };
  public void execEntry(int start) throws CobolRuntimeException, CobolStopRunException {
    Optional<CobolControl> nextLabel = Optional.of(contList[start]);
    while(nextLabel.isPresent()) {
      CobolControl section = nextLabel.get();
      nextLabel = section.run();
    }
  }

  public static void main(String[] args)
  {
    CobolUtil.cob_init(args, false);
    CobolDecimal.cobInitNumeric();
    new test1().test1_(0);
    CobolStopRunException.stopRun();
  }

  public test1()
  {
    init();
  }

  public void init() 
  {
    /* Data storage */

    cob_unifunc = null;

    /* PROGRAM-ID : test1 */
    b_RETURN_CODE = new CobolDataStorage(4);	/* RETURN-CODE */
    b_INP = new CobolDataStorage(11000);	/* INP */
    b_A_REC = new CobolDataStorage(300);	/* A-REC */
    b_B = new CobolDataStorage(3);	/* B */
    b_C = new CobolDataStorage(3);	/* C */
    b_D = new CobolDataStorage(3);	/* D */
    b_ALICE = new CobolDataStorage(6);	/* ALICE */
    b_BOB = new CobolDataStorage(6);	/* BOB */
    b_REN = new CobolDataStorage(10);	/* REN */
    b_RE = new CobolDataStorage(11);	/* RE */
    b_temp1 = new CobolDataStorage(7);	/* temp1 */
    b_temp2 = new CobolDataStorage(7);	/* temp2 */
    b_temp3 = new CobolDataStorage(7);	/* temp3 */
    b_NOW = new CobolDataStorage(7);	/* NOW */
    b_N = new CobolDataStorage(3);	/* N */
    b_MAX = new CobolDataStorage(3);	/* MAX */
    b_A__A_DATA__A_REC = b_A_REC;

    /* End of data storage */


    initAttr();

    /* Fields */

    /* PROGRAM-ID : test1 */
    f_B	= CobolFieldFactory.makeCobolField(3, b_B, a_2_NumericDisplay_Digits3_Scale0);	/* B */
    f_C	= CobolFieldFactory.makeCobolField(3, b_C, a_2_NumericDisplay_Digits3_Scale0);	/* C */
    f_D	= CobolFieldFactory.makeCobolField(3, b_D, a_2_NumericDisplay_Digits3_Scale0);	/* D */
    f_RE	= CobolFieldFactory.makeCobolField(11, b_RE, a_1_NumericEdited_Digits11_Scale0);	/* RE */
    f_N	= CobolFieldFactory.makeCobolField(3, b_N, a_2_NumericDisplay_Digits3_Scale0);	/* N */

    /* End of fields */


    /* Constants */

    c_1_1	= CobolFieldFactory.makeCobolField(1, "1", a_3_NumericDisplay_Digits1_Scale0);

  }

  private void initAttr() {
    /* Attributes */

    a_1_NumericEdited_Digits11_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_EDITED,
      /* digits= */ 11,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ "Z\012\000\000\0009\001\000\000\000");
    a_2_NumericDisplay_Digits3_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 3,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_3_NumericDisplay_Digits1_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 1,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);

  }

  /* Data storage */

  /* PROGRAM-ID : test1 */
  public CobolDataStorage b_RETURN_CODE;	/* RETURN-CODE */
  private CobolDataStorage b_INP;	/* INP */
  private CobolDataStorage b_A_REC;	/* A-REC */
  private CobolDataStorage b_B;	/* B */
  private CobolDataStorage b_C;	/* C */
  private CobolDataStorage b_D;	/* D */
  private CobolDataStorage b_ALICE;	/* ALICE */
  private CobolDataStorage b_BOB;	/* BOB */
  private CobolDataStorage b_REN;	/* REN */
  private CobolDataStorage b_RE;	/* RE */
  private CobolDataStorage b_temp1;	/* temp1 */
  private CobolDataStorage b_temp2;	/* temp2 */
  private CobolDataStorage b_temp3;	/* temp3 */
  private CobolDataStorage b_NOW;	/* NOW */
  private CobolDataStorage b_N;	/* N */
  private CobolDataStorage b_MAX;	/* MAX */
  private CobolDataStorage b_A__A_DATA__A_REC;

  /* End of data storage */


  /* Fields */

  /* PROGRAM-ID : test1 */
  private AbstractCobolField f_B;	/* B */
  private AbstractCobolField f_C;	/* C */
  private AbstractCobolField f_D;	/* D */
  private AbstractCobolField f_RE;	/* RE */
  private AbstractCobolField f_N;	/* N */

  /* End of fields */


  private static AbstractCobolField f_native;

  /* Constants */

  private AbstractCobolField c_1_1;

  /* Attributes */

  private CobolFieldAttribute a_3_NumericDisplay_Digits1_Scale0;
  private CobolFieldAttribute a_2_NumericDisplay_Digits3_Scale0;
  private CobolFieldAttribute a_1_NumericEdited_Digits11_Scale0;



  /* String literals */
  public static final byte[] str_2_001 = CobolUtil.stringToBytes("001");
  public static final byte[] str_1_001 = CobolUtil.stringToBytes("001");
  public static final byte[] str_0_001 = CobolUtil.stringToBytes("001");

  /* Sections and Labels */
  private final static int l_test1 = 1;
  private final static int l_MAIN_SECTION = 2;
  private final static int l_MAIN_SECTION__MAIN = 3;
  private final static int l_Default_Error_Handler = 4;

}
