/* Generated by opensource COBOL 4J 1.1.16 */
import java.io.UnsupportedEncodingException;
import jp.osscons.opensourcecobol.libcobj.*;
import jp.osscons.opensourcecobol.libcobj.common.*;
import jp.osscons.opensourcecobol.libcobj.data.*;
import jp.osscons.opensourcecobol.libcobj.exceptions.*;
import jp.osscons.opensourcecobol.libcobj.termio.*;
import jp.osscons.opensourcecobol.libcobj.call.*;
import jp.osscons.opensourcecobol.libcobj.file.*;
import jp.osscons.opensourcecobol.libcobj.ui.*;
import java.util.Optional;

public class PROGRAM_ID implements CobolRunnable {

  private boolean initialized = false;
  private CobolModule module;
  private int entry;

  private CobolRunnable cob_unifunc;


  @Override
  public int run(CobolDataStorage... argStorages) {
    return PROGRAM_ID_(0, argStorages);
  }

  @Override
  public void cancel() {
    PROGRAM_ID_(-1);
  }

  @Override
  public boolean isActive() {
    return false;
  }

  public CobolResultSet execute () {
    int returnCode = run_module(0);
    return new CobolResultSet(returnCode);
  }

  public int PROGRAM_ID_ (int entry, CobolDataStorage ...argStorages) {
    this.entry = entry;
    return this.run_module(entry);
  }

  int run_module (int entry) {
    this.module = new CobolModule(null, null, null, null, 0, '.', '$', ',', 1, 1, 1, 0, null );

    /* Start of function code */

    /* CANCEL callback handling */
    if (entry < 0) {
    	if (!this.initialized) {
    		CobolDecimal.cobInitNumeric();
    		return 0;
    	}
    	this.initialized = false;
    	return 0;
    }

    /* Push module stack */
    CobolModule.push (module);
    CobolResolve.pushCallStackList ("PROGRAM_ID");

    /* Initialize program */
    if (!this.initialized) {
      module.setProgramId("PROGRAM_ID");

      b_RETURN_CODE.set((int)0);
      b_len.setBytes (str_0_0000000003, 10);
      b_S.fillBytes(' ', 3);
      b_T.fillBytes(' ', 3);
      b_i.fillBytes (0, 8);
      b_ans.fillBytes('0', 10);
      f_zs.moveFrom (CobolConstant.zero);
      this.initialized = true;
    }
    /* PROCEDURE DIVISION */
    try{
      /* Entry dispatch */
      execEntry(l_PROGRAM_ID);

    } catch(CobolStopRunException e) {
      CobolStopRunException.stopRun();
      System.exit(e.getReturnCode());
    }
    /* Pop module stack */
    CobolResolve.popCallStackList();
    CobolModule.pop();

    /* Program return */
    return b_RETURN_CODE.intValue();
  }
  public CobolControl[] contList = {
    new CobolControl(0, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_PROGRAM_ID]);
      }
    },
    /* Entry PROGRAM_ID */
    new CobolControl(l_PROGRAM_ID, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN]);
      }
    },
    /* MAIN SECTION */
    new CobolControl(l_MAIN, CobolControl.LabelType.section) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION__DEFAULT_PARAGRAPH]);
      }
    },
    /* MAIN_SECTION__DEFAULT_PARAGRAPH */
    new CobolControl(l_MAIN_SECTION__DEFAULT_PARAGRAPH, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* /content/temp_cobol/PROGRAM_ID_fixed.cob:14: ACCEPT */
        {
          CobolTerminal.accept (f_S);
        }
        /* /content/temp_cobol/PROGRAM_ID_fixed.cob:15: ACCEPT */
        {
          CobolTerminal.accept (f_T);
        }
        /* /content/temp_cobol/PROGRAM_ID_fixed.cob:16: PERFORM */
        b_i.setSwpU64Binary (1);
        for(;;b_i.addSwpU64Binary (1))
        {
          if (((long)f_len.compareTo (f_i) <  0L))
            break;
          {
            /* /content/temp_cobol/PROGRAM_ID_fixed.cob:17: IF */
            {
              if (((long)(Byte.toUnsignedInt(b_S.getSubDataStorage((b_i.bswap_64() - 1)).getByte(0)) - Byte.toUnsignedInt(b_T.getSubDataStorage((b_i.bswap_64() - 1)).getByte(0))) == 0L))
                {
                  /* /content/temp_cobol/PROGRAM_ID_fixed.cob:18: ADD */
                  {
                    f_ans.add (c_1_1, 4);
                  }
                }
            }
          }
        }
        /* /content/temp_cobol/PROGRAM_ID_fixed.cob:21: MOVE */
        {
          f_zs.moveFrom (f_ans);
        }
        /* /content/temp_cobol/PROGRAM_ID_fixed.cob:22: DISPLAY */
        {
          CobolTerminal.display (0, 1, 1, CobolIntrinsic.funcTrim (0, 0, f_zs, 0));
        }
        /* /content/temp_cobol/PROGRAM_ID_fixed.cob:23: STOP */
        {
          CobolStopRunException.throwException (b_RETURN_CODE.intValue());
        }
        return Optional.of(CobolControl.pure());
      }
    },
    CobolControl.pure()
  };
  public void execEntry(int start) throws CobolRuntimeException, CobolStopRunException {
    Optional<CobolControl> nextLabel = Optional.of(contList[start]);
    while(nextLabel.isPresent()) {
      CobolControl section = nextLabel.get();
      nextLabel = section.run();
    }
  }

  public static void main(String[] args)
  {
    CobolUtil.cob_init(args, false);
    CobolDecimal.cobInitNumeric();
    new PROGRAM_ID().PROGRAM_ID_(0);
    CobolStopRunException.stopRun();
  }

  public PROGRAM_ID()
  {
    init();
  }

  public void init() 
  {
    /* Data storage */

    cob_unifunc = null;

    /* PROGRAM-ID : PROGRAM_ID */
    b_RETURN_CODE = new CobolDataStorage(4);	/* RETURN-CODE */
    b_len = new CobolDataStorage(10);	/* len */
    b_S = new CobolDataStorage(3);	/* S */
    b_T = new CobolDataStorage(3);	/* T */
    b_i = new CobolDataStorage(8);	/* i */
    b_ans = new CobolDataStorage(10);	/* ans */
    b_zs = new CobolDataStorage(10);	/* zs */

    /* End of data storage */


    initAttr();

    /* Fields */

    /* PROGRAM-ID : PROGRAM_ID */
    f_len	= CobolFieldFactory.makeCobolField(10, b_len, a_3_NumericDisplay_Digits10_Scale0);	/* len */
    f_S	= CobolFieldFactory.makeCobolField(3, b_S, a_2_Alphanumeric);	/* S */
    f_T	= CobolFieldFactory.makeCobolField(3, b_T, a_2_Alphanumeric);	/* T */
    f_i	= CobolFieldFactory.makeCobolField(8, b_i, a_4_NumericBinary_Digits10_Scale0_BinarySwap);	/* i */
    f_ans	= CobolFieldFactory.makeCobolField(10, b_ans, a_3_NumericDisplay_Digits10_Scale0);	/* ans */
    f_zs	= CobolFieldFactory.makeCobolField(10, b_zs, a_1_NumericEdited_Digits10_Scale0);	/* zs */

    /* End of fields */


    /* Constants */

    c_1_1	= CobolFieldFactory.makeCobolField(1, "1", a_5_NumericDisplay_Digits1_Scale0);

  }

  private void initAttr() {
    /* Attributes */

    a_1_NumericEdited_Digits10_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_EDITED,
      /* digits= */ 10,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ "Z\011\000\000\0009\001\000\000\000");
    a_2_Alphanumeric = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_ALPHANUMERIC,
      /* digits= */ 0,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_3_NumericDisplay_Digits10_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 10,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_4_NumericBinary_Digits10_Scale0_BinarySwap = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_BINARY,
      /* digits= */ 10,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_BINARY_SWAP,
      /* pic= */ null);
    a_5_NumericDisplay_Digits1_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 1,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);

  }

  /* Data storage */

  /* PROGRAM-ID : PROGRAM_ID */
  public CobolDataStorage b_RETURN_CODE;	/* RETURN-CODE */
  private CobolDataStorage b_len;	/* len */
  private CobolDataStorage b_S;	/* S */
  private CobolDataStorage b_T;	/* T */
  private CobolDataStorage b_i;	/* i */
  private CobolDataStorage b_ans;	/* ans */
  private CobolDataStorage b_zs;	/* zs */

  /* End of data storage */


  /* Fields */

  /* PROGRAM-ID : PROGRAM_ID */
  private AbstractCobolField f_len;	/* len */
  private AbstractCobolField f_S;	/* S */
  private AbstractCobolField f_T;	/* T */
  private AbstractCobolField f_i;	/* i */
  private AbstractCobolField f_ans;	/* ans */
  private AbstractCobolField f_zs;	/* zs */

  /* End of fields */


  private static AbstractCobolField f_native;

  /* Constants */

  private AbstractCobolField c_1_1;

  /* Attributes */

  private CobolFieldAttribute a_5_NumericDisplay_Digits1_Scale0;
  private CobolFieldAttribute a_4_NumericBinary_Digits10_Scale0_BinarySwap;
  private CobolFieldAttribute a_3_NumericDisplay_Digits10_Scale0;
  private CobolFieldAttribute a_2_Alphanumeric;
  private CobolFieldAttribute a_1_NumericEdited_Digits10_Scale0;



  /* String literals */
  public static final byte[] str_0_0000000003 = CobolUtil.stringToBytes("0000000003");

  /* Sections and Labels */
  private final static int l_PROGRAM_ID = 1;
  private final static int l_MAIN = 2;
  private final static int l_MAIN_SECTION__DEFAULT_PARAGRAPH = 3;
  private final static int l_Default_Error_Handler = 4;

}
