/* Generated by opensource COBOL 4J 1.1.16 */
import java.io.UnsupportedEncodingException;
import jp.osscons.opensourcecobol.libcobj.*;
import jp.osscons.opensourcecobol.libcobj.common.*;
import jp.osscons.opensourcecobol.libcobj.data.*;
import jp.osscons.opensourcecobol.libcobj.exceptions.*;
import jp.osscons.opensourcecobol.libcobj.termio.*;
import jp.osscons.opensourcecobol.libcobj.call.*;
import jp.osscons.opensourcecobol.libcobj.file.*;
import jp.osscons.opensourcecobol.libcobj.ui.*;
import java.util.Optional;

public class _3138B implements CobolRunnable {

  private boolean initialized = false;
  private CobolModule module;
  private int entry;

  private CobolRunnable cob_unifunc;


  @Override
  public int run(CobolDataStorage... argStorages) {
    return _3138B_(0, argStorages);
  }

  @Override
  public void cancel() {
    _3138B_(-1);
  }

  @Override
  public boolean isActive() {
    return false;
  }

  public CobolResultSet execute () {
    int returnCode = run_module(0);
    return new CobolResultSet(returnCode);
  }

  public int _3138B_ (int entry, CobolDataStorage ...argStorages) {
    this.entry = entry;
    return this.run_module(entry);
  }

  int run_module (int entry) {
    this.module = new CobolModule(null, null, null, null, 0, '.', '$', ',', 1, 1, 1, 0, null );

    /* Start of function code */

    /* CANCEL callback handling */
    if (entry < 0) {
    	if (!this.initialized) {
    		CobolDecimal.cobInitNumeric();
    		return 0;
    	}
    	d0.clear();
    	d0.setScale(0);
    	d1.clear();
    	d1.setScale(0);
    	d2.clear();
    	d2.setScale(0);
    	this.initialized = false;
    	return 0;
    }

    /* Push module stack */
    CobolModule.push (module);
    CobolResolve.pushCallStackList ("_3138B");

    /* Initialize program */
    if (!this.initialized) {
      module.setProgramId("_3138B");

      /* Initialize decimal numbers */
      d0.decimalInit();
      d1.decimalInit();
      d2.decimalInit();

      b_RETURN_CODE.set((int)0);
      b_INP.fillBytes(' ', 500);
      b_N.fillBytes('0', 3);
      b_TBL.fillBytes('0', 400);
      b_I.fillBytes('0', 2);
      b_P1.fillBytes('0', 3);
      b_P2.fillBytes('0', 3);
      b_WA.fillBytes('0', 14);
      f_OUT.moveFrom (CobolConstant.zero);
      this.initialized = true;
    }
    /* PROCEDURE DIVISION */
    try{
      /* Entry dispatch */
      execEntry(l__3138B);

    } catch(CobolStopRunException e) {
      CobolStopRunException.stopRun();
      System.exit(e.getReturnCode());
    }
    /* Pop module stack */
    CobolResolve.popCallStackList();
    CobolModule.pop();

    /* Program return */
    return b_RETURN_CODE.intValue();
  }
  public CobolControl[] contList = {
    new CobolControl(0, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l__3138B]);
      }
    },
    /* Entry 138B */
    new CobolControl(l__3138B, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN]);
      }
    },
    /* MAIN SECTION */
    new CobolControl(l_MAIN, CobolControl.LabelType.section) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION__DEFAULT_PARAGRAPH]);
      }
    },
    /* MAIN_SECTION__DEFAULT_PARAGRAPH */
    new CobolControl(l_MAIN_SECTION__DEFAULT_PARAGRAPH, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* /content/temp_cobol/138B_fixed.cob:19: ACCEPT */
        {
          CobolTerminal.accept (f_N);
        }
        /* /content/temp_cobol/138B_fixed.cob:21: ACCEPT */
        {
          CobolTerminal.accept (f_INP);
        }
        /* /content/temp_cobol/138B_fixed.cob:22: MOVE */
        {
          b_P1.setBytes (str_0_001, 3);
        }
        /* /content/temp_cobol/138B_fixed.cob:23: PERFORM */
        b_I.setBytes (str_1_01, 2);
        for(;;f_I.addInt (1))
        {
          if (((long)b_I.cmpNumdisp (2, b_N.getNumdisp(3)) >  0L))
            break;
          {
            /* /content/temp_cobol/138B_fixed.cob:24: PERFORM */
            b_P2.setBytes (b_P1, 3);
            for(;;f_P2.addInt (1))
            {
              if (((long)(Byte.toUnsignedInt(b_INP.getSubDataStorage((b_P2.getNumdisp(3) - 1)).getByte(0)) - (int)32) == 0L))
                break;
              ;
            }
            /* /content/temp_cobol/138B_fixed.cob:26: MOVE */
            {
              CobolFieldFactory.makeCobolField(4, b_A__TBL.getSubDataStorage(4 * (b_I.getNumdisp(2) - 1)), a_5_NumericDisplay_Digits4_Scale0).moveFrom (CobolFieldFactory.makeCobolField((b_P2.getNumdisp(3) - b_P1.getNumdisp(3)), b_INP.getSubDataStorage((b_P1.getNumdisp(3) - 1)), a_3_Alphanumeric));
            }
            /* /content/temp_cobol/138B_fixed.cob:27: COMPUTE */
            {
              {
                {
                  d0.set (b_P2.getNumdisp(3));
                  d1.set (1);
                  d0.add (d1);
                  d0.getField (f_P1, 4);
                }
              }
            }
          }
        }
        /* /content/temp_cobol/138B_fixed.cob:30: MOVE */
        {
          f_WA.moveFrom (c_1_0);
        }
        /* /content/temp_cobol/138B_fixed.cob:31: PERFORM */
        b_I.setBytes (str_2_01, 2);
        for(;;f_I.addInt (1))
        {
          if (((long)b_I.cmpNumdisp (2, b_N.getNumdisp(3)) >  0L))
            break;
          {
            /* /content/temp_cobol/138B_fixed.cob:32: COMPUTE */
            {
              {
                {
                  d0.setField (f_WA);
                  d1.set (1);
                  d2.set (b_A__TBL.getSubDataStorage(4 * (b_I.getNumdisp(2) - 1)).getNumdisp(4));
                  d1.div (d2);
                  d0.add (d1);
                  d0.getField (f_WA, 4);
                }
              }
            }
          }
        }
        /* /content/temp_cobol/138B_fixed.cob:35: COMPUTE */
        {
          {
            {
              d0.set (1);
              d1.setField (f_WA);
              d0.div (d1);
              d0.getField (f_OUT, 4);
            }
          }
        }
        /* /content/temp_cobol/138B_fixed.cob:36: PERFORM */
        b_I.setBytes (str_3_10, 2);
        for(;;f_I.addInt (-1))
        {
          if (((long)(Byte.toUnsignedInt(b_OUT.getSubDataStorage((b_I.getNumdisp(2) - 1)).getByte(0)) - (int)48) != 0L))
            break;
          {
            /* /content/temp_cobol/138B_fixed.cob:37: MOVE */
            {
              b_OUT.getSubDataStorage((b_I.getNumdisp(2) - 1)).fillBytes (32, 1);
            }
          }
        }
        /* /content/temp_cobol/138B_fixed.cob:39: IF */
        {
          if (((long)b_I.cmpNumdisp (2, 5) == 0L))
            {
              /* /content/temp_cobol/138B_fixed.cob:40: MOVE */
              {
                b_OUT.getSubDataStorage((b_I.getNumdisp(2) - 1)).fillBytes (32, 1);
              }
            }
        }
        /* /content/temp_cobol/138B_fixed.cob:43: DISPLAY */
        {
          CobolTerminal.display (0, 1, 1, CobolIntrinsic.funcTrim (0, 0, f_ANS__OUT_R, 0));
        }
        /* /content/temp_cobol/138B_fixed.cob:45: STOP */
        {
          CobolStopRunException.throwException (b_RETURN_CODE.intValue());
        }
        return Optional.of(CobolControl.pure());
      }
    },
    CobolControl.pure()
  };
  public void execEntry(int start) throws CobolRuntimeException, CobolStopRunException {
    Optional<CobolControl> nextLabel = Optional.of(contList[start]);
    while(nextLabel.isPresent()) {
      CobolControl section = nextLabel.get();
      nextLabel = section.run();
    }
  }

  public static void main(String[] args)
  {
    CobolUtil.cob_init(args, false);
    CobolDecimal.cobInitNumeric();
    new _3138B()._3138B_(0);
    CobolStopRunException.stopRun();
  }

  public _3138B()
  {
    init();
  }

  public void init() 
  {
    /* Decimal structures */

    d0 = new CobolDecimal();
    d1 = new CobolDecimal();
    d2 = new CobolDecimal();

    /* Data storage */

    cob_unifunc = null;

    /* PROGRAM-ID : 138B */
    b_RETURN_CODE = new CobolDataStorage(4);	/* RETURN-CODE */
    b_INP = new CobolDataStorage(500);	/* INP */
    b_N = new CobolDataStorage(3);	/* N */
    b_TBL = new CobolDataStorage(400);	/* TBL */
    b_I = new CobolDataStorage(2);	/* I */
    b_P1 = new CobolDataStorage(3);	/* P1 */
    b_P2 = new CobolDataStorage(3);	/* P2 */
    b_WA = new CobolDataStorage(14);	/* WA */
    b_OUT = new CobolDataStorage(15);	/* OUT */
    b_ANS__OUT_R = b_OUT;
    b_A__TBL = b_TBL;

    /* End of data storage */


    initAttr();

    /* Fields */

    /* PROGRAM-ID : 138B */
    f_INP	= CobolFieldFactory.makeCobolField(500, b_INP, a_3_Alphanumeric);	/* INP */
    f_N	= CobolFieldFactory.makeCobolField(3, b_N, a_2_NumericDisplay_Digits3_Scale0);	/* N */
    f_I	= CobolFieldFactory.makeCobolField(2, b_I, a_4_NumericDisplay_Digits2_Scale0);	/* I */
    f_P1	= CobolFieldFactory.makeCobolField(3, b_P1, a_2_NumericDisplay_Digits3_Scale0);	/* P1 */
    f_P2	= CobolFieldFactory.makeCobolField(3, b_P2, a_2_NumericDisplay_Digits3_Scale0);	/* P2 */
    f_WA	= CobolFieldFactory.makeCobolField(14, b_WA, a_6_NumericDisplay_Digits14_Scale10);	/* WA */
    f_OUT	= CobolFieldFactory.makeCobolField(15, b_OUT, a_1_NumericEdited_Digits14_Scale10);	/* OUT */
    f_ANS__OUT_R	= CobolFieldFactory.makeCobolField(10, b_ANS__OUT_R, a_7_NumericEdited_Digits9_Scale5);	/* ANS */

    /* End of fields */


    /* Constants */

    c_1_0	= CobolFieldFactory.makeCobolField(1, "0", a_8_NumericDisplay_Digits1_Scale0);

  }

  private void initAttr() {
    /* Attributes */

    a_1_NumericEdited_Digits14_Scale10 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_EDITED,
      /* digits= */ 14,
      /* scale= */ 10,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ "Z\004\000\000\000.\001\000\000\0009\012\000\000\000");
    a_2_NumericDisplay_Digits3_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 3,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_3_Alphanumeric = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_ALPHANUMERIC,
      /* digits= */ 0,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_4_NumericDisplay_Digits2_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 2,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_5_NumericDisplay_Digits4_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 4,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_6_NumericDisplay_Digits14_Scale10 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 14,
      /* scale= */ 10,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_7_NumericEdited_Digits9_Scale5 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_EDITED,
      /* digits= */ 9,
      /* scale= */ 5,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ "Z\004\000\000\000.\001\000\000\0009\005\000\000\000");
    a_8_NumericDisplay_Digits1_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 1,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);

  }

  /* Decimal structures */

  private CobolDecimal d0;
  private CobolDecimal d1;
  private CobolDecimal d2;

  /* Data storage */

  /* PROGRAM-ID : 138B */
  public CobolDataStorage b_RETURN_CODE;	/* RETURN-CODE */
  private CobolDataStorage b_INP;	/* INP */
  private CobolDataStorage b_N;	/* N */
  private CobolDataStorage b_TBL;	/* TBL */
  private CobolDataStorage b_I;	/* I */
  private CobolDataStorage b_P1;	/* P1 */
  private CobolDataStorage b_P2;	/* P2 */
  private CobolDataStorage b_WA;	/* WA */
  private CobolDataStorage b_OUT;	/* OUT */
  private CobolDataStorage b_ANS__OUT_R;
  private CobolDataStorage b_A__TBL;

  /* End of data storage */


  /* Fields */

  /* PROGRAM-ID : 138B */
  private AbstractCobolField f_INP;	/* INP */
  private AbstractCobolField f_N;	/* N */
  private AbstractCobolField f_I;	/* I */
  private AbstractCobolField f_P1;	/* P1 */
  private AbstractCobolField f_P2;	/* P2 */
  private AbstractCobolField f_WA;	/* WA */
  private AbstractCobolField f_OUT;	/* OUT */
  private AbstractCobolField f_ANS__OUT_R;	/* ANS */

  /* End of fields */


  private static AbstractCobolField f_native;

  /* Constants */

  private AbstractCobolField c_1_0;

  /* Attributes */

  private CobolFieldAttribute a_8_NumericDisplay_Digits1_Scale0;
  private CobolFieldAttribute a_7_NumericEdited_Digits9_Scale5;
  private CobolFieldAttribute a_6_NumericDisplay_Digits14_Scale10;
  private CobolFieldAttribute a_5_NumericDisplay_Digits4_Scale0;
  private CobolFieldAttribute a_4_NumericDisplay_Digits2_Scale0;
  private CobolFieldAttribute a_3_Alphanumeric;
  private CobolFieldAttribute a_2_NumericDisplay_Digits3_Scale0;
  private CobolFieldAttribute a_1_NumericEdited_Digits14_Scale10;



  /* String literals */
  public static final byte[] str_3_10 = CobolUtil.stringToBytes("10");
  public static final byte[] str_2_01 = CobolUtil.stringToBytes("01");
  public static final byte[] str_1_01 = CobolUtil.stringToBytes("01");
  public static final byte[] str_0_001 = CobolUtil.stringToBytes("001");

  /* Sections and Labels */
  private final static int l__3138B = 1;
  private final static int l_MAIN = 2;
  private final static int l_MAIN_SECTION__DEFAULT_PARAGRAPH = 3;
  private final static int l_Default_Error_Handler = 4;

}
