/* Generated by opensource COBOL 4J 1.1.16 */
import java.io.UnsupportedEncodingException;
import jp.osscons.opensourcecobol.libcobj.*;
import jp.osscons.opensourcecobol.libcobj.common.*;
import jp.osscons.opensourcecobol.libcobj.data.*;
import jp.osscons.opensourcecobol.libcobj.exceptions.*;
import jp.osscons.opensourcecobol.libcobj.termio.*;
import jp.osscons.opensourcecobol.libcobj.call.*;
import jp.osscons.opensourcecobol.libcobj.file.*;
import jp.osscons.opensourcecobol.libcobj.ui.*;
import java.util.Optional;

public class PROGRAM_ID implements CobolRunnable {

  private boolean initialized = false;
  private CobolModule module;
  private int entry;

  private CobolRunnable cob_unifunc;


  @Override
  public int run(CobolDataStorage... argStorages) {
    return PROGRAM_ID_(0, argStorages);
  }

  @Override
  public void cancel() {
    PROGRAM_ID_(-1);
  }

  @Override
  public boolean isActive() {
    return false;
  }

  public CobolResultSet execute () {
    int returnCode = run_module(0);
    return new CobolResultSet(returnCode);
  }

  public int PROGRAM_ID_ (int entry, CobolDataStorage ...argStorages) {
    this.entry = entry;
    return this.run_module(entry);
  }

  int run_module (int entry) {
    this.module = new CobolModule(null, null, null, null, 0, '.', '$', ',', 1, 1, 1, 0, null );

    /* Start of function code */

    /* CANCEL callback handling */
    if (entry < 0) {
    	if (!this.initialized) {
    		CobolDecimal.cobInitNumeric();
    		return 0;
    	}
    	d0.clear();
    	d0.setScale(0);
    	d1.clear();
    	d1.setScale(0);
    	d2.clear();
    	d2.setScale(0);
    	d3.clear();
    	d3.setScale(0);
    	d4.clear();
    	d4.setScale(0);
    	d5.clear();
    	d5.setScale(0);
    	this.initialized = false;
    	return 0;
    }

    /* Push module stack */
    CobolModule.push (module);
    CobolResolve.pushCallStackList ("PROGRAM_ID");

    /* Initialize program */
    if (!this.initialized) {
      module.setProgramId("PROGRAM_ID");

      /* Initialize decimal numbers */
      d0.decimalInit();
      d1.decimalInit();
      d2.decimalInit();
      d3.decimalInit();
      d4.decimalInit();
      d5.decimalInit();

      b_RETURN_CODE.set((int)0);
      b_ln.fillBytes(' ', 30);
      b_NX.fillBytes(' ', 30);
      b_LX.fillBytes(' ', 30);
      b_N.fillBytes('0', 10);
      b_L.fillBytes('0', 10);
      b_ans.fillBytes('0', 10);
      f_zs.moveFrom (CobolConstant.zero);
      this.initialized = true;
    }
    /* PROCEDURE DIVISION */
    try{
      /* Entry dispatch */
      execEntry(l_PROGRAM_ID);

    } catch(CobolStopRunException e) {
      CobolStopRunException.stopRun();
      System.exit(e.getReturnCode());
    }
    /* Pop module stack */
    CobolResolve.popCallStackList();
    CobolModule.pop();

    /* Program return */
    return b_RETURN_CODE.intValue();
  }
  public CobolControl[] contList = {
    new CobolControl(0, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_PROGRAM_ID]);
      }
    },
    /* Entry PROGRAM_ID */
    new CobolControl(l_PROGRAM_ID, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN]);
      }
    },
    /* MAIN SECTION */
    new CobolControl(l_MAIN, CobolControl.LabelType.section) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION__DEFAULT_PARAGRAPH]);
      }
    },
    /* MAIN_SECTION__DEFAULT_PARAGRAPH */
    new CobolControl(l_MAIN_SECTION__DEFAULT_PARAGRAPH, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* /content/temp_cobol/PROGRAM_ID_fixed.cob:17: ACCEPT */
        {
          CobolTerminal.accept (f_ln);
        }
        /* /content/temp_cobol/PROGRAM_ID_fixed.cob:18: UNSTRING */
        {
          CobolString.unstringInit (f_ln, 0, 1);
          CobolString.unstringDelimited (CobolConstant.space, 0);
          CobolString.unstringInto (f_NX, 0, 0);
          CobolString.unstringInto (f_LX, 0, 0);
          CobolString.unstringFinish ();
        }
        /* /content/temp_cobol/PROGRAM_ID_fixed.cob:19: IF */
        {
          if (((long)(Byte.toUnsignedInt(b_NX.getSubDataStorage(0).getByte(0)) - (int)45) == 0L))
            {
              /* /content/temp_cobol/PROGRAM_ID_fixed.cob:20: MOVE */
              {
                f_N.moveFrom (CobolFieldFactory.makeCobolField((CobolIntrinsic.funcStoredCharLength (f_NX).getInt() - 1), b_NX.getSubDataStorage(1), a_2_Alphanumeric));
              }
              /* /content/temp_cobol/PROGRAM_ID_fixed.cob:21: COMPUTE */
              {
                {
                  {
                    d0.set (0);
                    d1.setField (f_N);
                    d0.sub (d1);
                    d0.getField (f_N, 4);
                  }
                }
              }
            }
          else
            {
              /* /content/temp_cobol/PROGRAM_ID_fixed.cob:23: MOVE */
              {
                f_N.moveFrom (CobolFieldFactory.makeCobolField(CobolIntrinsic.funcStoredCharLength (f_NX).getInt(), b_NX.getSubDataStorage(0), a_2_Alphanumeric));
              }
            }
        }
        /* /content/temp_cobol/PROGRAM_ID_fixed.cob:25: IF */
        {
          if (((long)(Byte.toUnsignedInt(b_LX.getSubDataStorage(0).getByte(0)) - (int)45) == 0L))
            {
              /* /content/temp_cobol/PROGRAM_ID_fixed.cob:26: MOVE */
              {
                f_L.moveFrom (CobolFieldFactory.makeCobolField((CobolIntrinsic.funcStoredCharLength (f_LX).getInt() - 1), b_LX.getSubDataStorage(1), a_2_Alphanumeric));
              }
              /* /content/temp_cobol/PROGRAM_ID_fixed.cob:27: COMPUTE */
              {
                {
                  {
                    d0.set (0);
                    d1.setField (f_L);
                    d0.sub (d1);
                    d0.getField (f_L, 4);
                  }
                }
              }
            }
          else
            {
              /* /content/temp_cobol/PROGRAM_ID_fixed.cob:29: MOVE */
              {
                f_L.moveFrom (CobolFieldFactory.makeCobolField(CobolIntrinsic.funcStoredCharLength (f_LX).getInt(), b_LX.getSubDataStorage(0), a_2_Alphanumeric));
              }
            }
        }
        /* /content/temp_cobol/PROGRAM_ID_fixed.cob:31: COMPUTE */
        {
          {
            {
              d0.setField (f_N);
              d2.set (2);
              d5.setField (f_L);
              d2.mul (d5);
              d4.setField (f_N);
              d2.add (d4);
              d3.set (1);
              d2.sub (d3);
              d0.mul (d2);
              d1.set (2);
              d0.div (d1);
              d0.getField (f_ans, 4);
            }
          }
        }
        /* /content/temp_cobol/PROGRAM_ID_fixed.cob:32: IF */
        {
          if (((long)CobolConstant.zero.compareTo (f_L) <  0L))
            {
              /* /content/temp_cobol/PROGRAM_ID_fixed.cob:33: COMPUTE */
              {
                {
                  {
                    d0.setField (f_ans);
                    d1.setField (f_L);
                    d0.sub (d1);
                    d0.getField (f_ans, 4);
                  }
                }
              }
            }
          else
            {
              /* /content/temp_cobol/PROGRAM_ID_fixed.cob:35: IF */
              {
                if (((long)                (new GetInt() {
                  public int run() throws CobolStopRunException {
                    d0.setField (f_L);
                    d3.setField (f_N);
                    d0.add (d3);
                    d2.set (1);
                    d0.sub (d2);
                    d1.set (0);
                    return 
                    d0.compareTo (d1);
                }
              }).run() <  0L))
                {
                  /* /content/temp_cobol/PROGRAM_ID_fixed.cob:36: COMPUTE */
                  {
                    {
                      {
                        d0.setField (f_ans);
                        d1.setField (f_L);
                        d3.setField (f_N);
                        d1.add (d3);
                        d2.set (1);
                        d1.sub (d2);
                        d0.sub (d1);
                        d0.getField (f_ans, 4);
                      }
                    }
                  }
                }
            }
          }
      }
      /* /content/temp_cobol/PROGRAM_ID_fixed.cob:39: IF */
      {
        if (((long)CobolConstant.zero.compareTo (f_ans) == 0L))
          {
            /* /content/temp_cobol/PROGRAM_ID_fixed.cob:40: DISPLAY */
            {
              CobolTerminal.display (0, 1, 1, c_1_0);
            }
          }
        else
          {
            /* /content/temp_cobol/PROGRAM_ID_fixed.cob:42: MOVE */
            {
              f_zs.moveFrom (f_ans);
            }
            /* /content/temp_cobol/PROGRAM_ID_fixed.cob:43: DISPLAY */
            {
              CobolTerminal.display (0, 1, 1, CobolIntrinsic.funcTrim (0, 0, f_zs, 0));
            }
          }
      }
      /* /content/temp_cobol/PROGRAM_ID_fixed.cob:45: STOP */
      {
        CobolStopRunException.throwException (b_RETURN_CODE.intValue());
      }
      return Optional.of(CobolControl.pure());
    }
  },
  CobolControl.pure()
};
public void execEntry(int start) throws CobolRuntimeException, CobolStopRunException {
  Optional<CobolControl> nextLabel = Optional.of(contList[start]);
  while(nextLabel.isPresent()) {
    CobolControl section = nextLabel.get();
    nextLabel = section.run();
  }
}

public static void main(String[] args)
{
  CobolUtil.cob_init(args, false);
  CobolDecimal.cobInitNumeric();
  new PROGRAM_ID().PROGRAM_ID_(0);
  CobolStopRunException.stopRun();
}

public PROGRAM_ID()
{
  init();
}

public void init() 
{
  /* Decimal structures */

  d0 = new CobolDecimal();
  d1 = new CobolDecimal();
  d2 = new CobolDecimal();
  d3 = new CobolDecimal();
  d4 = new CobolDecimal();
  d5 = new CobolDecimal();

  /* Data storage */

  cob_unifunc = null;

  /* PROGRAM-ID : PROGRAM_ID */
  b_RETURN_CODE = new CobolDataStorage(4);	/* RETURN-CODE */
  b_ln = new CobolDataStorage(30);	/* ln */
  b_NX = new CobolDataStorage(30);	/* NX */
  b_LX = new CobolDataStorage(30);	/* LX */
  b_N = new CobolDataStorage(10);	/* N */
  b_L = new CobolDataStorage(10);	/* L */
  b_ans = new CobolDataStorage(10);	/* ans */
  b_zs = new CobolDataStorage(11);	/* zs */

  /* End of data storage */


  initAttr();

  /* Fields */

  /* PROGRAM-ID : PROGRAM_ID */
  f_ln	= CobolFieldFactory.makeCobolField(30, b_ln, a_2_Alphanumeric);	/* ln */
  f_NX	= CobolFieldFactory.makeCobolField(30, b_NX, a_2_Alphanumeric);	/* NX */
  f_LX	= CobolFieldFactory.makeCobolField(30, b_LX, a_2_Alphanumeric);	/* LX */
  f_N	= CobolFieldFactory.makeCobolField(10, b_N, a_3_NumericDisplay_Digits10_Scale0_HaveSign);	/* N */
  f_L	= CobolFieldFactory.makeCobolField(10, b_L, a_3_NumericDisplay_Digits10_Scale0_HaveSign);	/* L */
  f_ans	= CobolFieldFactory.makeCobolField(10, b_ans, a_3_NumericDisplay_Digits10_Scale0_HaveSign);	/* ans */
  f_zs	= CobolFieldFactory.makeCobolField(11, b_zs, a_1_NumericEdited_Digits10_Scale0_HaveSign);	/* zs */

  /* End of fields */


  /* Constants */

  c_1_0	= CobolFieldFactory.makeCobolField(1, "0", a_4_NumericDisplay_Digits1_Scale0);

}

private void initAttr() {
  /* Attributes */

  a_1_NumericEdited_Digits10_Scale0_HaveSign = new CobolFieldAttribute(
    CobolFieldAttribute.COB_TYPE_NUMERIC_EDITED,
    /* digits= */ 10,
    /* scale= */ 0,
    CobolFieldAttribute.COB_FLAG_HAVE_SIGN,
    /* pic= */ "-\001\000\000\000Z\011\000\000\0009\001\000\000\000");
  a_2_Alphanumeric = new CobolFieldAttribute(
    CobolFieldAttribute.COB_TYPE_ALPHANUMERIC,
    /* digits= */ 0,
    /* scale= */ 0,
    CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
    /* pic= */ null);
  a_3_NumericDisplay_Digits10_Scale0_HaveSign = new CobolFieldAttribute(
    CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
    /* digits= */ 10,
    /* scale= */ 0,
    CobolFieldAttribute.COB_FLAG_HAVE_SIGN,
    /* pic= */ null);
  a_4_NumericDisplay_Digits1_Scale0 = new CobolFieldAttribute(
    CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
    /* digits= */ 1,
    /* scale= */ 0,
    CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
    /* pic= */ null);

}

/* Decimal structures */

private CobolDecimal d0;
private CobolDecimal d1;
private CobolDecimal d2;
private CobolDecimal d3;
private CobolDecimal d4;
private CobolDecimal d5;

/* Data storage */

/* PROGRAM-ID : PROGRAM_ID */
public CobolDataStorage b_RETURN_CODE;	/* RETURN-CODE */
private CobolDataStorage b_ln;	/* ln */
private CobolDataStorage b_NX;	/* NX */
private CobolDataStorage b_LX;	/* LX */
private CobolDataStorage b_N;	/* N */
private CobolDataStorage b_L;	/* L */
private CobolDataStorage b_ans;	/* ans */
private CobolDataStorage b_zs;	/* zs */

/* End of data storage */


/* Fields */

/* PROGRAM-ID : PROGRAM_ID */
private AbstractCobolField f_ln;	/* ln */
private AbstractCobolField f_NX;	/* NX */
private AbstractCobolField f_LX;	/* LX */
private AbstractCobolField f_N;	/* N */
private AbstractCobolField f_L;	/* L */
private AbstractCobolField f_ans;	/* ans */
private AbstractCobolField f_zs;	/* zs */

/* End of fields */


private static AbstractCobolField f_native;

/* Constants */

private AbstractCobolField c_1_0;

/* Attributes */

private CobolFieldAttribute a_4_NumericDisplay_Digits1_Scale0;
private CobolFieldAttribute a_3_NumericDisplay_Digits10_Scale0_HaveSign;
private CobolFieldAttribute a_2_Alphanumeric;
private CobolFieldAttribute a_1_NumericEdited_Digits10_Scale0_HaveSign;




/* Sections and Labels */
private final static int l_PROGRAM_ID = 1;
private final static int l_MAIN = 2;
private final static int l_MAIN_SECTION__DEFAULT_PARAGRAPH = 3;
private final static int l_Default_Error_Handler = 4;

}
