/* Generated by opensource COBOL 4J 1.1.16 */
import java.io.UnsupportedEncodingException;
import jp.osscons.opensourcecobol.libcobj.*;
import jp.osscons.opensourcecobol.libcobj.common.*;
import jp.osscons.opensourcecobol.libcobj.data.*;
import jp.osscons.opensourcecobol.libcobj.exceptions.*;
import jp.osscons.opensourcecobol.libcobj.termio.*;
import jp.osscons.opensourcecobol.libcobj.call.*;
import jp.osscons.opensourcecobol.libcobj.file.*;
import jp.osscons.opensourcecobol.libcobj.ui.*;
import java.util.Optional;

public class ABC_043_B implements CobolRunnable {

  private boolean initialized = false;
  private CobolModule module;
  private int entry;

  private CobolRunnable cob_unifunc;


  @Override
  public int run(CobolDataStorage... argStorages) {
    return ABC_043_B_(0, argStorages);
  }

  @Override
  public void cancel() {
    ABC_043_B_(-1);
  }

  @Override
  public boolean isActive() {
    return false;
  }

  public CobolResultSet execute () {
    int returnCode = run_module(0);
    return new CobolResultSet(returnCode);
  }

  public int ABC_043_B_ (int entry, CobolDataStorage ...argStorages) {
    this.entry = entry;
    return this.run_module(entry);
  }

  int run_module (int entry) {
    this.module = new CobolModule(null, null, null, null, 0, '.', '$', ',', 1, 1, 1, 0, null );

    /* Start of function code */

    /* CANCEL callback handling */
    if (entry < 0) {
    	if (!this.initialized) {
    		CobolDecimal.cobInitNumeric();
    		return 0;
    	}
    	d0.clear();
    	d0.setScale(0);
    	this.initialized = false;
    	return 0;
    }

    /* Push module stack */
    CobolModule.push (module);
    CobolResolve.pushCallStackList ("ABC_043_B");

    /* Initialize program */
    if (!this.initialized) {
      module.setProgramId("ABC_043_B");

      /* Initialize decimal numbers */
      d0.decimalInit();

      b_RETURN_CODE.set((int)0);
      b_s1.fillBytes(' ', 10);
      b_ans1.fillBytes(' ', 10);
      b_i.fillBytes('0', 2);
      b_len.fillBytes('0', 2);
      b_now.fillBytes('0', 2);
      this.initialized = true;
    }
    /* PROCEDURE DIVISION */
    try{
      /* Entry dispatch */
      execEntry(l_ABC_043_B);

    } catch(CobolStopRunException e) {
      CobolStopRunException.stopRun();
      System.exit(e.getReturnCode());
    }
    /* Pop module stack */
    CobolResolve.popCallStackList();
    CobolModule.pop();

    /* Program return */
    return b_RETURN_CODE.intValue();
  }
  public CobolControl[] contList = {
    new CobolControl(0, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_ABC_043_B]);
      }
    },
    /* Entry ABC_043_B */
    new CobolControl(l_ABC_043_B, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN]);
      }
    },
    /* MAIN SECTION */
    new CobolControl(l_MAIN, CobolControl.LabelType.section) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION__DEFAULT_PARAGRAPH]);
      }
    },
    /* MAIN_SECTION__DEFAULT_PARAGRAPH */
    new CobolControl(l_MAIN_SECTION__DEFAULT_PARAGRAPH, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* /content/temp_cobol/ABC_043_B_fixed.cob:18: ACCEPT */
        {
          CobolTerminal.accept (f_s1);
        }
        /* /content/temp_cobol/ABC_043_B_fixed.cob:20: COMPUTE */
        {
          {
            {
              d0.setField (CobolIntrinsic.funcStoredCharLength (f_s1));
              d0.getField (f_len, 4);
            }
          }
        }
        /* /content/temp_cobol/ABC_043_B_fixed.cob:22: MOVE */
        {
          b_now.fillBytes (48, 2);
        }
        /* /content/temp_cobol/ABC_043_B_fixed.cob:24: PERFORM */
        b_i.setBytes (str_0_01, 2);
        for(;;f_i.addInt (1))
        {
          if (((long)b_len.memcmp (b_i, 2) <  0L))
            break;
          {
            /* /content/temp_cobol/ABC_043_B_fixed.cob:25: IF */
            {
              if (((long)(Byte.toUnsignedInt(b_s__s11__s1.getSubDataStorage((b_i.getNumdisp(2) - 1)).getByte(0)) - (int)66) == 0L))
                {
                  /* /content/temp_cobol/ABC_043_B_fixed.cob:26: IF */
                  {
                    if (((long)b_now.cmpNumdisp (2, 0) != 0L))
                      {
                        /* /content/temp_cobol/ABC_043_B_fixed.cob:27: MOVE */
                        {
                          b_ans__ans11__ans1.getSubDataStorage((b_now.getNumdisp(2) - 1)).setByte(32);
                        }
                        /* /content/temp_cobol/ABC_043_B_fixed.cob:28: SUBTRACT */
                        {
                          f_now.sub (c_1_1, 4);
                        }
                      }
                  }
                }
              else
                {
                  /* /content/temp_cobol/ABC_043_B_fixed.cob:31: ADD */
                  {
                    f_now.add (c_1_1, 4);
                  }
                  /* /content/temp_cobol/ABC_043_B_fixed.cob:32: MOVE */
                  {
                    b_ans__ans11__ans1.getSubDataStorage((b_now.getNumdisp(2) - 1)).setByte(b_s__s11__s1.getSubDataStorage((b_i.getNumdisp(2) - 1)).getByte(0));
                  }
                }
            }
          }
        }
        /* /content/temp_cobol/ABC_043_B_fixed.cob:36: DISPLAY */
        {
          CobolTerminal.display (0, 1, 1, CobolFieldFactory.makeCobolField(CobolIntrinsic.funcStoredCharLength (f_ans1).getInt(), b_ans1.getSubDataStorage(0), a_3_Alphanumeric));
        }
        /* /content/temp_cobol/ABC_043_B_fixed.cob:37: STOP */
        {
          CobolStopRunException.throwException (b_RETURN_CODE.intValue());
        }
        return Optional.of(CobolControl.pure());
      }
    },
    CobolControl.pure()
  };
  public void execEntry(int start) throws CobolRuntimeException, CobolStopRunException {
    Optional<CobolControl> nextLabel = Optional.of(contList[start]);
    while(nextLabel.isPresent()) {
      CobolControl section = nextLabel.get();
      nextLabel = section.run();
    }
  }

  public static void main(String[] args)
  {
    CobolUtil.cob_init(args, false);
    CobolDecimal.cobInitNumeric();
    new ABC_043_B().ABC_043_B_(0);
    CobolStopRunException.stopRun();
  }

  public ABC_043_B()
  {
    init();
  }

  public void init() 
  {
    /* Decimal structures */

    d0 = new CobolDecimal();

    /* Data storage */

    cob_unifunc = null;

    /* PROGRAM-ID : ABC_043_B */
    b_RETURN_CODE = new CobolDataStorage(4);	/* RETURN-CODE */
    b_s1 = new CobolDataStorage(10);	/* s1 */
    b_ans1 = new CobolDataStorage(10);	/* ans1 */
    b_i = new CobolDataStorage(2);	/* i */
    b_len = new CobolDataStorage(2);	/* len */
    b_now = new CobolDataStorage(2);	/* now */
    b_ans__ans11__ans1 = b_ans1;
    b_s__s11__s1 = b_s1;

    /* End of data storage */


    initAttr();

    /* Fields */

    /* PROGRAM-ID : ABC_043_B */
    f_s1	= CobolFieldFactory.makeCobolField(10, b_s1, a_1_Group);	/* s1 */
    f_ans1	= CobolFieldFactory.makeCobolField(10, b_ans1, a_1_Group);	/* ans1 */
    f_i	= CobolFieldFactory.makeCobolField(2, b_i, a_2_NumericDisplay_Digits2_Scale0);	/* i */
    f_len	= CobolFieldFactory.makeCobolField(2, b_len, a_2_NumericDisplay_Digits2_Scale0);	/* len */
    f_now	= CobolFieldFactory.makeCobolField(2, b_now, a_2_NumericDisplay_Digits2_Scale0);	/* now */

    /* End of fields */


    /* Constants */

    c_1_1	= CobolFieldFactory.makeCobolField(1, "1", a_4_NumericDisplay_Digits1_Scale0);

  }

  private void initAttr() {
    /* Attributes */

    a_1_Group = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_GROUP,
      /* digits= */ 0,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_2_NumericDisplay_Digits2_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 2,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_3_Alphanumeric = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_ALPHANUMERIC,
      /* digits= */ 0,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_4_NumericDisplay_Digits1_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 1,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);

  }

  /* Decimal structures */

  private CobolDecimal d0;

  /* Data storage */

  /* PROGRAM-ID : ABC_043_B */
  public CobolDataStorage b_RETURN_CODE;	/* RETURN-CODE */
  private CobolDataStorage b_s1;	/* s1 */
  private CobolDataStorage b_ans1;	/* ans1 */
  private CobolDataStorage b_i;	/* i */
  private CobolDataStorage b_len;	/* len */
  private CobolDataStorage b_now;	/* now */
  private CobolDataStorage b_ans__ans11__ans1;
  private CobolDataStorage b_s__s11__s1;

  /* End of data storage */


  /* Fields */

  /* PROGRAM-ID : ABC_043_B */
  private AbstractCobolField f_s1;	/* s1 */
  private AbstractCobolField f_ans1;	/* ans1 */
  private AbstractCobolField f_i;	/* i */
  private AbstractCobolField f_len;	/* len */
  private AbstractCobolField f_now;	/* now */

  /* End of fields */


  private static AbstractCobolField f_native;

  /* Constants */

  private AbstractCobolField c_1_1;

  /* Attributes */

  private CobolFieldAttribute a_4_NumericDisplay_Digits1_Scale0;
  private CobolFieldAttribute a_3_Alphanumeric;
  private CobolFieldAttribute a_2_NumericDisplay_Digits2_Scale0;
  private CobolFieldAttribute a_1_Group;



  /* String literals */
  public static final byte[] str_0_01 = CobolUtil.stringToBytes("01");

  /* Sections and Labels */
  private final static int l_ABC_043_B = 1;
  private final static int l_MAIN = 2;
  private final static int l_MAIN_SECTION__DEFAULT_PARAGRAPH = 3;
  private final static int l_Default_Error_Handler = 4;

}
