/* Generated by opensource COBOL 4J 1.1.16 */
import java.io.UnsupportedEncodingException;
import jp.osscons.opensourcecobol.libcobj.*;
import jp.osscons.opensourcecobol.libcobj.common.*;
import jp.osscons.opensourcecobol.libcobj.data.*;
import jp.osscons.opensourcecobol.libcobj.exceptions.*;
import jp.osscons.opensourcecobol.libcobj.termio.*;
import jp.osscons.opensourcecobol.libcobj.call.*;
import jp.osscons.opensourcecobol.libcobj.file.*;
import jp.osscons.opensourcecobol.libcobj.ui.*;
import java.util.Optional;

public class AtCoder implements CobolRunnable {

  private boolean initialized = false;
  private CobolModule module;
  private int entry;

  private CobolRunnable cob_unifunc;


  @Override
  public int run(CobolDataStorage... argStorages) {
    return AtCoder_(0, argStorages);
  }

  @Override
  public void cancel() {
    AtCoder_(-1);
  }

  @Override
  public boolean isActive() {
    return false;
  }

  public CobolResultSet execute () {
    int returnCode = run_module(0);
    return new CobolResultSet(returnCode);
  }

  public int AtCoder_ (int entry, CobolDataStorage ...argStorages) {
    this.entry = entry;
    return this.run_module(entry);
  }

  int run_module (int entry) {
    this.module = new CobolModule(null, null, null, null, 0, '.', '$', ',', 1, 1, 1, 0, null );

    /* Start of function code */

    /* CANCEL callback handling */
    if (entry < 0) {
    	if (!this.initialized) {
    		CobolDecimal.cobInitNumeric();
    		return 0;
    	}
    	this.initialized = false;
    	return 0;
    }

    /* Push module stack */
    CobolModule.push (module);
    CobolResolve.pushCallStackList ("AtCoder");

    /* Initialize program */
    if (!this.initialized) {
      module.setProgramId("AtCoder");

      b_RETURN_CODE.set((int)0);
      b_INP.fillBytes(' ', 100);
      b_A.fillBytes('0', 15);
      b_B.fillBytes('0', 15);
      b_C.fillBytes('0', 15);
      b_D.fillBytes('0', 15);
      b_E.fillBytes('0', 15);
      b_F.fillBytes('0', 15);
      b_t.fillBytes('0', 15);
      b_temp1.fillBytes('0', 15);
      b_temp2.fillBytes('0', 15);
      b_N.fillBytes('0', 15);
      this.initialized = true;
    }
    /* PROCEDURE DIVISION */
    try{
      /* Entry dispatch */
      execEntry(l_AtCoder);

    } catch(CobolStopRunException e) {
      CobolStopRunException.stopRun();
      System.exit(e.getReturnCode());
    }
    /* Pop module stack */
    CobolResolve.popCallStackList();
    CobolModule.pop();

    /* Program return */
    return b_RETURN_CODE.intValue();
  }
  public CobolControl[] contList = {
    new CobolControl(0, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_AtCoder]);
      }
    },
    /* Entry AtCoder */
    new CobolControl(l_AtCoder, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION]);
      }
    },
    /* MAIN SECTION */
    new CobolControl(l_MAIN_SECTION, CobolControl.LabelType.section) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION__MAIN]);
      }
    },
    /* MAIN */
    new CobolControl(l_MAIN_SECTION__MAIN, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* /content/temp_cobol/AtCoder_fixed.cob:22: ACCEPT */
        {
          CobolTerminal.accept (f_INP);
        }
        /* /content/temp_cobol/AtCoder_fixed.cob:23: IF */
        {
          if (((long)b_INP.getSubDataStorage(0).memcmp (str_0_SUN, 3) == 0L))
            {
              /* /content/temp_cobol/AtCoder_fixed.cob:24: DISPLAY */
              {
                CobolTerminal.display (0, 1, 1, c_1_7);
              }
            }
        }
        /* /content/temp_cobol/AtCoder_fixed.cob:26: IF */
        {
          if (((long)b_INP.getSubDataStorage(0).memcmp (str_1_MON, 3) == 0L))
            {
              /* /content/temp_cobol/AtCoder_fixed.cob:27: DISPLAY */
              {
                CobolTerminal.display (0, 1, 1, c_2_6);
              }
            }
        }
        /* /content/temp_cobol/AtCoder_fixed.cob:29: IF */
        {
          if (((long)b_INP.getSubDataStorage(0).memcmp (str_2_TUE, 3) == 0L))
            {
              /* /content/temp_cobol/AtCoder_fixed.cob:30: DISPLAY */
              {
                CobolTerminal.display (0, 1, 1, c_3_5);
              }
            }
        }
        /* /content/temp_cobol/AtCoder_fixed.cob:32: IF */
        {
          if (((long)b_INP.getSubDataStorage(0).memcmp (str_3_WED, 3) == 0L))
            {
              /* /content/temp_cobol/AtCoder_fixed.cob:33: DISPLAY */
              {
                CobolTerminal.display (0, 1, 1, c_4_4);
              }
            }
        }
        /* /content/temp_cobol/AtCoder_fixed.cob:35: IF */
        {
          if (((long)b_INP.getSubDataStorage(0).memcmp (str_4_THU, 3) == 0L))
            {
              /* /content/temp_cobol/AtCoder_fixed.cob:36: DISPLAY */
              {
                CobolTerminal.display (0, 1, 1, c_5_3);
              }
            }
        }
        /* /content/temp_cobol/AtCoder_fixed.cob:38: IF */
        {
          if (((long)b_INP.getSubDataStorage(0).memcmp (str_5_FRI, 3) == 0L))
            {
              /* /content/temp_cobol/AtCoder_fixed.cob:39: DISPLAY */
              {
                CobolTerminal.display (0, 1, 1, c_6_2);
              }
            }
        }
        /* /content/temp_cobol/AtCoder_fixed.cob:41: IF */
        {
          if (((long)b_INP.getSubDataStorage(0).memcmp (str_6_SAT, 3) == 0L))
            {
              /* /content/temp_cobol/AtCoder_fixed.cob:42: DISPLAY */
              {
                CobolTerminal.display (0, 1, 1, c_7_1);
              }
            }
        }
        /* /content/temp_cobol/AtCoder_fixed.cob:44: STOP */
        {
          CobolStopRunException.throwException (b_RETURN_CODE.intValue());
        }
        return Optional.of(CobolControl.pure());
      }
    },
    CobolControl.pure()
  };
  public void execEntry(int start) throws CobolRuntimeException, CobolStopRunException {
    Optional<CobolControl> nextLabel = Optional.of(contList[start]);
    while(nextLabel.isPresent()) {
      CobolControl section = nextLabel.get();
      nextLabel = section.run();
    }
  }

  public static void main(String[] args)
  {
    CobolUtil.cob_init(args, false);
    CobolDecimal.cobInitNumeric();
    new AtCoder().AtCoder_(0);
    CobolStopRunException.stopRun();
  }

  public AtCoder()
  {
    init();
  }

  public void init() 
  {
    /* Data storage */

    cob_unifunc = null;

    /* PROGRAM-ID : AtCoder */
    b_RETURN_CODE = new CobolDataStorage(4);	/* RETURN-CODE */
    b_INP = new CobolDataStorage(100);	/* INP */
    b_A = new CobolDataStorage(15);	/* A */
    b_B = new CobolDataStorage(15);	/* B */
    b_C = new CobolDataStorage(15);	/* C */
    b_D = new CobolDataStorage(15);	/* D */
    b_E = new CobolDataStorage(15);	/* E */
    b_F = new CobolDataStorage(15);	/* F */
    b_t = new CobolDataStorage(15);	/* t */
    b_temp1 = new CobolDataStorage(15);	/* temp1 */
    b_temp2 = new CobolDataStorage(15);	/* temp2 */
    b_N = new CobolDataStorage(15);	/* N */

    /* End of data storage */


    initAttr();

    /* Fields */

    /* PROGRAM-ID : AtCoder */
    f_INP	= CobolFieldFactory.makeCobolField(100, b_INP, a_1_Alphanumeric);	/* INP */

    /* End of fields */


    /* Constants */

    c_1_7	= CobolFieldFactory.makeCobolField(str_7_7, a_1_Alphanumeric);
    c_2_6	= CobolFieldFactory.makeCobolField(str_8_6, a_1_Alphanumeric);
    c_3_5	= CobolFieldFactory.makeCobolField(str_9_5, a_1_Alphanumeric);
    c_4_4	= CobolFieldFactory.makeCobolField(str_10_4, a_1_Alphanumeric);
    c_5_3	= CobolFieldFactory.makeCobolField(str_11_3, a_1_Alphanumeric);
    c_6_2	= CobolFieldFactory.makeCobolField(str_12_2, a_1_Alphanumeric);
    c_7_1	= CobolFieldFactory.makeCobolField(str_13_1, a_1_Alphanumeric);

  }

  private void initAttr() {
    /* Attributes */

    a_1_Alphanumeric = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_ALPHANUMERIC,
      /* digits= */ 0,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);

  }

  /* Data storage */

  /* PROGRAM-ID : AtCoder */
  public CobolDataStorage b_RETURN_CODE;	/* RETURN-CODE */
  private CobolDataStorage b_INP;	/* INP */
  private CobolDataStorage b_A;	/* A */
  private CobolDataStorage b_B;	/* B */
  private CobolDataStorage b_C;	/* C */
  private CobolDataStorage b_D;	/* D */
  private CobolDataStorage b_E;	/* E */
  private CobolDataStorage b_F;	/* F */
  private CobolDataStorage b_t;	/* t */
  private CobolDataStorage b_temp1;	/* temp1 */
  private CobolDataStorage b_temp2;	/* temp2 */
  private CobolDataStorage b_N;	/* N */

  /* End of data storage */


  /* Fields */

  /* PROGRAM-ID : AtCoder */
  private AbstractCobolField f_INP;	/* INP */

  /* End of fields */


  private static AbstractCobolField f_native;

  /* Constants */

  private AbstractCobolField c_7_1;
  private AbstractCobolField c_6_2;
  private AbstractCobolField c_5_3;
  private AbstractCobolField c_4_4;
  private AbstractCobolField c_3_5;
  private AbstractCobolField c_2_6;
  private AbstractCobolField c_1_7;

  /* Attributes */

  private CobolFieldAttribute a_1_Alphanumeric;



  /* String literals */
  public static final byte[] str_13_1 = CobolUtil.stringToBytes("1");
  public static final byte[] str_12_2 = CobolUtil.stringToBytes("2");
  public static final byte[] str_11_3 = CobolUtil.stringToBytes("3");
  public static final byte[] str_10_4 = CobolUtil.stringToBytes("4");
  public static final byte[] str_9_5 = CobolUtil.stringToBytes("5");
  public static final byte[] str_8_6 = CobolUtil.stringToBytes("6");
  public static final byte[] str_7_7 = CobolUtil.stringToBytes("7");
  public static final byte[] str_6_SAT = CobolUtil.stringToBytes("SAT");
  public static final byte[] str_5_FRI = CobolUtil.stringToBytes("FRI");
  public static final byte[] str_4_THU = CobolUtil.stringToBytes("THU");
  public static final byte[] str_3_WED = CobolUtil.stringToBytes("WED");
  public static final byte[] str_2_TUE = CobolUtil.stringToBytes("TUE");
  public static final byte[] str_1_MON = CobolUtil.stringToBytes("MON");
  public static final byte[] str_0_SUN = CobolUtil.stringToBytes("SUN");

  /* Sections and Labels */
  private final static int l_AtCoder = 1;
  private final static int l_MAIN_SECTION = 2;
  private final static int l_MAIN_SECTION__MAIN = 3;
  private final static int l_Default_Error_Handler = 4;

}
