/* Generated by opensource COBOL 4J 1.1.16 */
import java.io.UnsupportedEncodingException;
import jp.osscons.opensourcecobol.libcobj.*;
import jp.osscons.opensourcecobol.libcobj.common.*;
import jp.osscons.opensourcecobol.libcobj.data.*;
import jp.osscons.opensourcecobol.libcobj.exceptions.*;
import jp.osscons.opensourcecobol.libcobj.termio.*;
import jp.osscons.opensourcecobol.libcobj.call.*;
import jp.osscons.opensourcecobol.libcobj.file.*;
import jp.osscons.opensourcecobol.libcobj.ui.*;
import java.util.Optional;

public class ABC_044_A implements CobolRunnable {

  private boolean initialized = false;
  private CobolModule module;
  private int entry;

  private CobolRunnable cob_unifunc;


  @Override
  public int run(CobolDataStorage... argStorages) {
    return ABC_044_A_(0, argStorages);
  }

  @Override
  public void cancel() {
    ABC_044_A_(-1);
  }

  @Override
  public boolean isActive() {
    return false;
  }

  public CobolResultSet execute () {
    int returnCode = run_module(0);
    return new CobolResultSet(returnCode);
  }

  public int ABC_044_A_ (int entry, CobolDataStorage ...argStorages) {
    this.entry = entry;
    return this.run_module(entry);
  }

  int run_module (int entry) {
    this.module = new CobolModule(null, null, null, null, 0, '.', '$', ',', 1, 1, 1, 0, null );

    /* Start of function code */

    /* CANCEL callback handling */
    if (entry < 0) {
    	if (!this.initialized) {
    		CobolDecimal.cobInitNumeric();
    		return 0;
    	}
    	d0.clear();
    	d0.setScale(0);
    	this.initialized = false;
    	return 0;
    }

    /* Push module stack */
    CobolModule.push (module);
    CobolResolve.pushCallStackList ("ABC_044_A");

    /* Initialize program */
    if (!this.initialized) {
      module.setProgramId("ABC_044_A");

      /* Initialize decimal numbers */
      d0.decimalInit();

      b_RETURN_CODE.set((int)0);
      b_a.setByte(0);
      b_chr.setByte(0);
      b_w.fillBytes(' ', 100);
      b_len.fillBytes('0', 3);
      b_i.fillBytes('0', 3);
      for (int i1 = 1; i1 <= 26; i1++)
      {
        b_cnt__cnt11__cnt1.getSubDataStorage(3 * (i1 - 1)).fillBytes (48, 3);


      }
      b_tmp.setByte('0');
      b_flg.setByte(0, '0');
      this.initialized = true;
    }
    /* PROCEDURE DIVISION */
    try{
      /* Entry dispatch */
      execEntry(l_ABC_044_A);

    } catch(CobolStopRunException e) {
      CobolStopRunException.stopRun();
      System.exit(e.getReturnCode());
    }
    /* Pop module stack */
    CobolResolve.popCallStackList();
    CobolModule.pop();

    /* Program return */
    return b_RETURN_CODE.intValue();
  }
  public CobolControl[] contList = {
    new CobolControl(0, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_ABC_044_A]);
      }
    },
    /* Entry ABC_044_A */
    new CobolControl(l_ABC_044_A, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN]);
      }
    },
    /* MAIN SECTION */
    new CobolControl(l_MAIN, CobolControl.LabelType.section) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION__DEFAULT_PARAGRAPH]);
      }
    },
    /* MAIN_SECTION__DEFAULT_PARAGRAPH */
    new CobolControl(l_MAIN_SECTION__DEFAULT_PARAGRAPH, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* /content/temp_cobol/ABC_044_A_fixed.cob:25: ACCEPT */
        {
          CobolTerminal.accept (f_w);
        }
        /* /content/temp_cobol/ABC_044_A_fixed.cob:27: COMPUTE */
        {
          {
            {
              d0.setField (CobolIntrinsic.funcStoredCharLength (f_w));
              d0.getField (f_len, 4);
            }
          }
        }
        /* /content/temp_cobol/ABC_044_A_fixed.cob:29: MOVE */
        {
          b_a.setByte(97);
        }
        /* /content/temp_cobol/ABC_044_A_fixed.cob:31: PERFORM */
        b_i.setBytes (str_0_001, 3);
        for(;;f_i.addInt (1))
        {
          if (((long)b_len.memcmp (b_i, 3) <  0L))
            break;
          {
            /* /content/temp_cobol/ABC_044_A_fixed.cob:32: MOVE */
            {
              b_chr.setByte(b_w.getSubDataStorage((b_i.getNumdisp(3) - 1)).getByte(0));
            }
            /* /content/temp_cobol/ABC_044_A_fixed.cob:33: ADD */
            {
              CobolFieldFactory.makeCobolField(3, b_cnt__cnt11__cnt1.getSubDataStorage(3 * (((b_num__chr.getByte(0) - b_anum__a.getByte(0)) + 1) - 1)), a_2_NumericDisplay_Digits3_Scale0).add (c_1_1, 4);
            }
          }
        }
        /* /content/temp_cobol/ABC_044_A_fixed.cob:36: PERFORM */
        b_i.setBytes (str_1_001, 3);
        for(;;f_i.addInt (1))
        {
          if (((long)c_2_26.cmpInteger (b_i.getNumdisp(3)) <  0L))
            break;
          {
            /* /content/temp_cobol/ABC_044_A_fixed.cob:37: COMPUTE */
            {
              {
                {
                  d0.setField (CobolIntrinsic.funcMod (CobolFieldFactory.makeCobolField(3, b_cnt__cnt11__cnt1.getSubDataStorage(3 * (b_i.getNumdisp(3) - 1)), a_2_NumericDisplay_Digits3_Scale0), c_3_2));
                  d0.getField (f_tmp, 4);
                }
              }
            }
            /* /content/temp_cobol/ABC_044_A_fixed.cob:38: IF */
            {
              if (((long)CobolConstant.zero.cmpInteger (b_tmp.getNumdisp(1)) <  0L))
                {
                  /* /content/temp_cobol/ABC_044_A_fixed.cob:39: MOVE */
                  {
                    b_flg.setByte(49);
                  }
                  /* /content/temp_cobol/ABC_044_A_fixed.cob:40: EXIT */
                  {
                    if(true) break;
                  }
                }
            }
          }
        }
        /* /content/temp_cobol/ABC_044_A_fixed.cob:44: IF */
        {
          if (((long)(Byte.toUnsignedInt(b_flg.getByte(0)) - (int)'0') == 0L))
            {
              /* /content/temp_cobol/ABC_044_A_fixed.cob:45: DISPLAY */
              {
                CobolTerminal.display (0, 1, 1, c_4_Yes);
              }
            }
          else
            {
              /* /content/temp_cobol/ABC_044_A_fixed.cob:47: DISPLAY */
              {
                CobolTerminal.display (0, 1, 1, c_5_No);
              }
            }
        }
        /* /content/temp_cobol/ABC_044_A_fixed.cob:50: STOP */
        {
          CobolStopRunException.throwException (b_RETURN_CODE.intValue());
        }
        return Optional.of(CobolControl.pure());
      }
    },
    CobolControl.pure()
  };
  public void execEntry(int start) throws CobolRuntimeException, CobolStopRunException {
    Optional<CobolControl> nextLabel = Optional.of(contList[start]);
    while(nextLabel.isPresent()) {
      CobolControl section = nextLabel.get();
      nextLabel = section.run();
    }
  }

  public static void main(String[] args)
  {
    CobolUtil.cob_init(args, false);
    CobolDecimal.cobInitNumeric();
    new ABC_044_A().ABC_044_A_(0);
    CobolStopRunException.stopRun();
  }

  public ABC_044_A()
  {
    init();
  }

  public void init() 
  {
    /* Decimal structures */

    d0 = new CobolDecimal();

    /* Data storage */

    cob_unifunc = null;

    /* PROGRAM-ID : ABC_044_A */
    b_RETURN_CODE = new CobolDataStorage(4);	/* RETURN-CODE */
    b_a = new CobolDataStorage(1);	/* a */
    b_chr = new CobolDataStorage(1);	/* chr */
    b_w = new CobolDataStorage(100);	/* w */
    b_len = new CobolDataStorage(3);	/* len */
    b_i = new CobolDataStorage(3);	/* i */
    b_cnt1 = new CobolDataStorage(78);	/* cnt1 */
    b_tmp = new CobolDataStorage(1);	/* tmp */
    b_flg = new CobolDataStorage(1);	/* flg */
    b_anum__a = b_a;
    b_num__chr = b_chr;
    b_cnt__cnt11__cnt1 = b_cnt1;

    /* End of data storage */


    initAttr();

    /* Fields */

    /* PROGRAM-ID : ABC_044_A */
    f_w	= CobolFieldFactory.makeCobolField(100, b_w, a_1_Alphanumeric);	/* w */
    f_len	= CobolFieldFactory.makeCobolField(3, b_len, a_2_NumericDisplay_Digits3_Scale0);	/* len */
    f_i	= CobolFieldFactory.makeCobolField(3, b_i, a_2_NumericDisplay_Digits3_Scale0);	/* i */
    f_tmp	= CobolFieldFactory.makeCobolField(1, b_tmp, a_3_NumericDisplay_Digits1_Scale0);	/* tmp */

    /* End of fields */


    /* Constants */

    c_1_1	= CobolFieldFactory.makeCobolField(1, "1", a_3_NumericDisplay_Digits1_Scale0);
    c_2_26	= CobolFieldFactory.makeCobolField(2, "26", a_4_NumericDisplay_Digits2_Scale0);
    c_3_2	= CobolFieldFactory.makeCobolField(1, "2", a_3_NumericDisplay_Digits1_Scale0);
    c_4_Yes	= CobolFieldFactory.makeCobolField(str_2_Yes, a_1_Alphanumeric);
    c_5_No	= CobolFieldFactory.makeCobolField(str_3_No, a_1_Alphanumeric);

  }

  private void initAttr() {
    /* Attributes */

    a_1_Alphanumeric = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_ALPHANUMERIC,
      /* digits= */ 0,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_2_NumericDisplay_Digits3_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 3,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_3_NumericDisplay_Digits1_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 1,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_4_NumericDisplay_Digits2_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 2,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);

  }

  /* Decimal structures */

  private CobolDecimal d0;

  /* Data storage */

  /* PROGRAM-ID : ABC_044_A */
  public CobolDataStorage b_RETURN_CODE;	/* RETURN-CODE */
  private CobolDataStorage b_a;	/* a */
  private CobolDataStorage b_chr;	/* chr */
  private CobolDataStorage b_w;	/* w */
  private CobolDataStorage b_len;	/* len */
  private CobolDataStorage b_i;	/* i */
  private CobolDataStorage b_cnt1;	/* cnt1 */
  private CobolDataStorage b_tmp;	/* tmp */
  private CobolDataStorage b_flg;	/* flg */
  private CobolDataStorage b_anum__a;
  private CobolDataStorage b_num__chr;
  private CobolDataStorage b_cnt__cnt11__cnt1;

  /* End of data storage */


  /* Fields */

  /* PROGRAM-ID : ABC_044_A */
  private AbstractCobolField f_w;	/* w */
  private AbstractCobolField f_len;	/* len */
  private AbstractCobolField f_i;	/* i */
  private AbstractCobolField f_tmp;	/* tmp */

  /* End of fields */


  private static AbstractCobolField f_native;

  /* Constants */

  private AbstractCobolField c_5_No;
  private AbstractCobolField c_4_Yes;
  private AbstractCobolField c_3_2;
  private AbstractCobolField c_2_26;
  private AbstractCobolField c_1_1;

  /* Attributes */

  private CobolFieldAttribute a_4_NumericDisplay_Digits2_Scale0;
  private CobolFieldAttribute a_3_NumericDisplay_Digits1_Scale0;
  private CobolFieldAttribute a_2_NumericDisplay_Digits3_Scale0;
  private CobolFieldAttribute a_1_Alphanumeric;



  /* String literals */
  public static final byte[] str_3_No = CobolUtil.stringToBytes("No");
  public static final byte[] str_2_Yes = CobolUtil.stringToBytes("Yes");
  public static final byte[] str_1_001 = CobolUtil.stringToBytes("001");
  public static final byte[] str_0_001 = CobolUtil.stringToBytes("001");

  /* Sections and Labels */
  private final static int l_ABC_044_A = 1;
  private final static int l_MAIN = 2;
  private final static int l_MAIN_SECTION__DEFAULT_PARAGRAPH = 3;
  private final static int l_Default_Error_Handler = 4;

}
