/* Generated by opensource COBOL 4J 1.1.16 */
import java.io.UnsupportedEncodingException;
import jp.osscons.opensourcecobol.libcobj.*;
import jp.osscons.opensourcecobol.libcobj.common.*;
import jp.osscons.opensourcecobol.libcobj.data.*;
import jp.osscons.opensourcecobol.libcobj.exceptions.*;
import jp.osscons.opensourcecobol.libcobj.termio.*;
import jp.osscons.opensourcecobol.libcobj.call.*;
import jp.osscons.opensourcecobol.libcobj.file.*;
import jp.osscons.opensourcecobol.libcobj.ui.*;
import java.util.Optional;

public class ATCODER implements CobolRunnable {

  private boolean initialized = false;
  private CobolModule module;
  private int entry;

  private CobolRunnable cob_unifunc;


  @Override
  public int run(CobolDataStorage... argStorages) {
    return ATCODER_(0, argStorages);
  }

  @Override
  public void cancel() {
    ATCODER_(-1);
  }

  @Override
  public boolean isActive() {
    return false;
  }

  public CobolResultSet execute () {
    int returnCode = run_module(0);
    return new CobolResultSet(returnCode);
  }

  public int ATCODER_ (int entry, CobolDataStorage ...argStorages) {
    this.entry = entry;
    return this.run_module(entry);
  }

  int run_module (int entry) {
    this.module = new CobolModule(null, null, null, null, 0, '.', '$', ',', 1, 1, 1, 0, null );

    /* Start of function code */

    /* CANCEL callback handling */
    if (entry < 0) {
    	if (!this.initialized) {
    		CobolDecimal.cobInitNumeric();
    		return 0;
    	}
    	d0.clear();
    	d0.setScale(0);
    	d1.clear();
    	d1.setScale(0);
    	this.initialized = false;
    	return 0;
    }

    /* Push module stack */
    CobolModule.push (module);
    CobolResolve.pushCallStackList ("ATCODER");

    /* Initialize program */
    if (!this.initialized) {
      module.setProgramId("ATCODER");

      /* Initialize decimal numbers */
      d0.decimalInit();
      d1.decimalInit();

      b_RETURN_CODE.set((int)0);
      b_INP.fillBytes(' ', 1000);
      b_A.fillBytes('0', 35);
      b_B.fillBytes('0', 35);
      b_C.fillBytes('0', 35);
      b_LEF.fillBytes('0', 35);
      b_RIG.fillBytes('0', 35);
      this.initialized = true;
    }
    /* PROCEDURE DIVISION */
    try{
      /* Entry dispatch */
      execEntry(l_ATCODER);

    } catch(CobolStopRunException e) {
      CobolStopRunException.stopRun();
      System.exit(e.getReturnCode());
    }
    /* Pop module stack */
    CobolResolve.popCallStackList();
    CobolModule.pop();

    /* Program return */
    return b_RETURN_CODE.intValue();
  }
  public CobolControl[] contList = {
    new CobolControl(0, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_ATCODER]);
      }
    },
    /* Entry ATCODER */
    new CobolControl(l_ATCODER, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN]);
      }
    },
    /* MAIN SECTION */
    new CobolControl(l_MAIN, CobolControl.LabelType.section) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION__DEFAULT_PARAGRAPH]);
      }
    },
    /* MAIN_SECTION__DEFAULT_PARAGRAPH */
    new CobolControl(l_MAIN_SECTION__DEFAULT_PARAGRAPH, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* /content/temp_cobol/ATCODER_fixed.cob:13: ACCEPT */
        {
          CobolTerminal.accept (f_INP);
        }
        /* /content/temp_cobol/ATCODER_fixed.cob:14: UNSTRING */
        {
          CobolString.unstringInit (f_INP, 0, 1);
          CobolString.unstringDelimited (CobolConstant.space, 0);
          CobolString.unstringInto (f_A, 0, 0);
          CobolString.unstringInto (f_B, 0, 0);
          CobolString.unstringInto (f_C, 0, 0);
          CobolString.unstringFinish ();
        }
        /* /content/temp_cobol/ATCODER_fixed.cob:17: COMPUTE */
        {
          {
            {
              d0.setField (f_A);
              d1.setField (c_1_5);
              d0.pow (d1);
              d0.getField (f_A, 4);
            }
          }
        }
        /* /content/temp_cobol/ATCODER_fixed.cob:18: COMPUTE */
        {
          {
            {
              d0.setField (f_B);
              d1.setField (c_1_5);
              d0.pow (d1);
              d0.getField (f_B, 4);
            }
          }
        }
        /* /content/temp_cobol/ATCODER_fixed.cob:19: COMPUTE */
        {
          {
            {
              d0.setField (f_C);
              d1.setField (c_1_5);
              d0.pow (d1);
              d0.getField (f_C, 4);
            }
          }
        }
        /* /content/temp_cobol/ATCODER_fixed.cob:20: COMPUTE */
        {
          {
            {
              d0.setField (f_A);
              d1.setField (f_B);
              d0.add (d1);
              d0.getField (f_LEF, 4);
            }
          }
        }
        /* /content/temp_cobol/ATCODER_fixed.cob:21: COMPUTE */
        {
          {
            {
              d0.setField (f_C);
              d0.getField (f_RIG, 4);
            }
          }
        }
        /* /content/temp_cobol/ATCODER_fixed.cob:23: IF */
        {
          if (((long)b_LEF.memcmp (b_RIG, 35) <  0L))
            {
              /* /content/temp_cobol/ATCODER_fixed.cob:24: DISPLAY */
              {
                CobolTerminal.display (0, 1, 1, c_2_Yes);
              }
            }
          else
            {
              /* /content/temp_cobol/ATCODER_fixed.cob:26: DISPLAY */
              {
                CobolTerminal.display (0, 1, 1, c_3_No);
              }
            }
        }
        /* /content/temp_cobol/ATCODER_fixed.cob:31: STOP */
        {
          CobolStopRunException.throwException (b_RETURN_CODE.intValue());
        }
        return Optional.of(CobolControl.pure());
      }
    },
    CobolControl.pure()
  };
  public void execEntry(int start) throws CobolRuntimeException, CobolStopRunException {
    Optional<CobolControl> nextLabel = Optional.of(contList[start]);
    while(nextLabel.isPresent()) {
      CobolControl section = nextLabel.get();
      nextLabel = section.run();
    }
  }

  public static void main(String[] args)
  {
    CobolUtil.cob_init(args, false);
    CobolDecimal.cobInitNumeric();
    new ATCODER().ATCODER_(0);
    CobolStopRunException.stopRun();
  }

  public ATCODER()
  {
    init();
  }

  public void init() 
  {
    /* Decimal structures */

    d0 = new CobolDecimal();
    d1 = new CobolDecimal();

    /* Data storage */

    cob_unifunc = null;

    /* PROGRAM-ID : ATCODER */
    b_RETURN_CODE = new CobolDataStorage(4);	/* RETURN-CODE */
    b_INP = new CobolDataStorage(1000);	/* INP */
    b_A = new CobolDataStorage(35);	/* A */
    b_B = new CobolDataStorage(35);	/* B */
    b_C = new CobolDataStorage(35);	/* C */
    b_LEF = new CobolDataStorage(35);	/* LEF */
    b_RIG = new CobolDataStorage(35);	/* RIG */

    /* End of data storage */


    initAttr();

    /* Fields */

    /* PROGRAM-ID : ATCODER */
    f_INP	= CobolFieldFactory.makeCobolField(1000, b_INP, a_1_Alphanumeric);	/* INP */
    f_A	= CobolFieldFactory.makeCobolField(35, b_A, a_2_NumericDisplay_Digits35_Scale20);	/* A */
    f_B	= CobolFieldFactory.makeCobolField(35, b_B, a_2_NumericDisplay_Digits35_Scale20);	/* B */
    f_C	= CobolFieldFactory.makeCobolField(35, b_C, a_2_NumericDisplay_Digits35_Scale20);	/* C */
    f_LEF	= CobolFieldFactory.makeCobolField(35, b_LEF, a_2_NumericDisplay_Digits35_Scale20);	/* LEF */
    f_RIG	= CobolFieldFactory.makeCobolField(35, b_RIG, a_2_NumericDisplay_Digits35_Scale20);	/* RIG */

    /* End of fields */


    /* Constants */

    c_1_5	= CobolFieldFactory.makeCobolField(1, "5", a_3_NumericDisplay_Digits1_Scale1);
    c_2_Yes	= CobolFieldFactory.makeCobolField(str_0_Yes, a_1_Alphanumeric);
    c_3_No	= CobolFieldFactory.makeCobolField(str_1_No, a_1_Alphanumeric);

  }

  private void initAttr() {
    /* Attributes */

    a_1_Alphanumeric = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_ALPHANUMERIC,
      /* digits= */ 0,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_2_NumericDisplay_Digits35_Scale20 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 35,
      /* scale= */ 20,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_3_NumericDisplay_Digits1_Scale1 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 1,
      /* scale= */ 1,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);

  }

  /* Decimal structures */

  private CobolDecimal d0;
  private CobolDecimal d1;

  /* Data storage */

  /* PROGRAM-ID : ATCODER */
  public CobolDataStorage b_RETURN_CODE;	/* RETURN-CODE */
  private CobolDataStorage b_INP;	/* INP */
  private CobolDataStorage b_A;	/* A */
  private CobolDataStorage b_B;	/* B */
  private CobolDataStorage b_C;	/* C */
  private CobolDataStorage b_LEF;	/* LEF */
  private CobolDataStorage b_RIG;	/* RIG */

  /* End of data storage */


  /* Fields */

  /* PROGRAM-ID : ATCODER */
  private AbstractCobolField f_INP;	/* INP */
  private AbstractCobolField f_A;	/* A */
  private AbstractCobolField f_B;	/* B */
  private AbstractCobolField f_C;	/* C */
  private AbstractCobolField f_LEF;	/* LEF */
  private AbstractCobolField f_RIG;	/* RIG */

  /* End of fields */


  private static AbstractCobolField f_native;

  /* Constants */

  private AbstractCobolField c_3_No;
  private AbstractCobolField c_2_Yes;
  private AbstractCobolField c_1_5;

  /* Attributes */

  private CobolFieldAttribute a_3_NumericDisplay_Digits1_Scale1;
  private CobolFieldAttribute a_2_NumericDisplay_Digits35_Scale20;
  private CobolFieldAttribute a_1_Alphanumeric;



  /* String literals */
  public static final byte[] str_1_No = CobolUtil.stringToBytes("No");
  public static final byte[] str_0_Yes = CobolUtil.stringToBytes("Yes");

  /* Sections and Labels */
  private final static int l_ATCODER = 1;
  private final static int l_MAIN = 2;
  private final static int l_MAIN_SECTION__DEFAULT_PARAGRAPH = 3;
  private final static int l_Default_Error_Handler = 4;

}
