/* Generated by opensource COBOL 4J 1.1.16 */
import java.io.UnsupportedEncodingException;
import jp.osscons.opensourcecobol.libcobj.*;
import jp.osscons.opensourcecobol.libcobj.common.*;
import jp.osscons.opensourcecobol.libcobj.data.*;
import jp.osscons.opensourcecobol.libcobj.exceptions.*;
import jp.osscons.opensourcecobol.libcobj.termio.*;
import jp.osscons.opensourcecobol.libcobj.call.*;
import jp.osscons.opensourcecobol.libcobj.file.*;
import jp.osscons.opensourcecobol.libcobj.ui.*;
import java.util.Optional;

public class ABC_057_B implements CobolRunnable {

  private boolean initialized = false;
  private CobolModule module;
  private int entry;

  private CobolRunnable cob_unifunc;


  @Override
  public int run(CobolDataStorage... argStorages) {
    return ABC_057_B_(0, argStorages);
  }

  @Override
  public void cancel() {
    ABC_057_B_(-1);
  }

  @Override
  public boolean isActive() {
    return false;
  }

  public CobolResultSet execute () {
    int returnCode = run_module(0);
    return new CobolResultSet(returnCode);
  }

  public int ABC_057_B_ (int entry, CobolDataStorage ...argStorages) {
    this.entry = entry;
    return this.run_module(entry);
  }

  int run_module (int entry) {
    this.module = new CobolModule(null, null, null, null, 0, '.', '$', ',', 1, 1, 1, 0, null );

    /* Start of function code */

    /* CANCEL callback handling */
    if (entry < 0) {
    	if (!this.initialized) {
    		CobolDecimal.cobInitNumeric();
    		return 0;
    	}
    	d0.clear();
    	d0.setScale(0);
    	d1.clear();
    	d1.setScale(0);
    	this.initialized = false;
    	return 0;
    }

    /* Push module stack */
    CobolModule.push (module);
    CobolResolve.pushCallStackList ("ABC_057_B");

    /* Initialize program */
    if (!this.initialized) {
      module.setProgramId("ABC_057_B");

      /* Initialize decimal numbers */
      d0.decimalInit();
      d1.decimalInit();

      b_RETURN_CODE.set((int)0);
      b_i.fillBytes('0', 2);
      b_j.fillBytes('0', 2);
      b_INP.fillBytes(' ', 5);
      b_INP2.fillBytes(' ', 21);
      b_N.fillBytes('0', 2);
      b_M.fillBytes('0', 2);
      b_st1.fillBytes('0', 900);
      b_pt1.fillBytes('0', 900);
      b_dt.fillBytes('0', 9);
      b_dtx.fillBytes('0', 9);
      b_dty.fillBytes('0', 9);
      b_mn.fillBytes('0', 9);
      b_p.fillBytes('0', 2);
      b_ans.fillBytes(' ', 2);
      f_ZS.moveFrom (CobolConstant.zero);
      b_DUMMY.setByte(' ');
      this.initialized = true;
    }
    /* PROCEDURE DIVISION */
    try{
      /* Entry dispatch */
      execEntry(l_ABC_057_B);

    } catch(CobolStopRunException e) {
      CobolStopRunException.stopRun();
      System.exit(e.getReturnCode());
    }
    /* Pop module stack */
    CobolResolve.popCallStackList();
    CobolModule.pop();

    /* Program return */
    return b_RETURN_CODE.intValue();
  }
  public CobolControl[] contList = {
    new CobolControl(0, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_ABC_057_B]);
      }
    },
    /* Entry ABC_057_B */
    new CobolControl(l_ABC_057_B, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION]);
      }
    },
    /* MAIN SECTION */
    new CobolControl(l_MAIN_SECTION, CobolControl.LabelType.section) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION__MAIN]);
      }
    },
    /* MAIN */
    new CobolControl(l_MAIN_SECTION__MAIN, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* /content/temp_cobol/ABC_057_B_fixed.cob:39: ACCEPT */
        {
          CobolTerminal.accept (f_INP);
        }
        /* /content/temp_cobol/ABC_057_B_fixed.cob:41: UNSTRING */
        {
          CobolString.unstringInit (f_INP, 0, 1);
          CobolString.unstringDelimited (CobolConstant.space, 0);
          CobolString.unstringInto (f_N, 0, 0);
          CobolString.unstringInto (f_M, 0, 0);
          CobolString.unstringFinish ();
        }
        /* /content/temp_cobol/ABC_057_B_fixed.cob:45: PERFORM */
        b_i.setBytes (str_0_01, 2);
        for(;;f_i.addInt (1))
        {
          if (((long)b_N.memcmp (b_i, 2) <  0L))
            break;
          {
            /* /content/temp_cobol/ABC_057_B_fixed.cob:46: ACCEPT */
            {
              CobolTerminal.accept (f_INP2);
            }
            /* /content/temp_cobol/ABC_057_B_fixed.cob:48: UNSTRING */
            {
              CobolString.unstringInit (f_INP2, 0, 1);
              CobolString.unstringDelimited (CobolConstant.space, 0);
              CobolString.unstringInto (CobolFieldFactory.makeCobolField(9, b_stx__st11__st1.getSubDataStorage(18 * (b_i.getNumdisp(2) - 1)), a_4_NumericDisplay_Digits9_Scale0_HaveSign), 0, 0);
              CobolString.unstringInto (CobolFieldFactory.makeCobolField(9, b_sty__st11__st1.getSubDataStorage(18 * (b_i.getNumdisp(2) - 1)), a_4_NumericDisplay_Digits9_Scale0_HaveSign), 0, 0);
              CobolString.unstringFinish ();
            }
          }
        }
        /* /content/temp_cobol/ABC_057_B_fixed.cob:53: PERFORM */
        b_i.setBytes (str_1_01, 2);
        for(;;f_i.addInt (1))
        {
          if (((long)b_M.memcmp (b_i, 2) <  0L))
            break;
          {
            /* /content/temp_cobol/ABC_057_B_fixed.cob:54: ACCEPT */
            {
              CobolTerminal.accept (f_INP2);
            }
            /* /content/temp_cobol/ABC_057_B_fixed.cob:56: UNSTRING */
            {
              CobolString.unstringInit (f_INP2, 0, 1);
              CobolString.unstringDelimited (CobolConstant.space, 0);
              CobolString.unstringInto (CobolFieldFactory.makeCobolField(9, b_ptx__pt11__pt1.getSubDataStorage(18 * (b_i.getNumdisp(2) - 1)), a_4_NumericDisplay_Digits9_Scale0_HaveSign), 0, 0);
              CobolString.unstringInto (CobolFieldFactory.makeCobolField(9, b_pty__pt11__pt1.getSubDataStorage(18 * (b_i.getNumdisp(2) - 1)), a_4_NumericDisplay_Digits9_Scale0_HaveSign), 0, 0);
              CobolString.unstringFinish ();
            }
          }
        }
        /* /content/temp_cobol/ABC_057_B_fixed.cob:61: PERFORM */
        b_i.setBytes (str_2_01, 2);
        for(;;f_i.addInt (1))
        {
          if (((long)b_N.memcmp (b_i, 2) <  0L))
            break;
          {
            /* /content/temp_cobol/ABC_057_B_fixed.cob:63: MOVE */
            {
              b_mn.setBytes (str_3_200000001, 9);
            }
            /* /content/temp_cobol/ABC_057_B_fixed.cob:65: PERFORM */
            b_j.setBytes (str_4_01, 2);
            for(;;f_j.addInt (1))
            {
              if (((long)b_M.memcmp (b_j, 2) <  0L))
                break;
              {
                /* /content/temp_cobol/ABC_057_B_fixed.cob:66: SUBTRACT */
                {
                  {
                    {
                      d0.set (CobolFieldFactory.makeCobolField(9, b_stx__st11__st1.getSubDataStorage(18 * (b_i.getNumdisp(2) - 1)), a_4_NumericDisplay_Digits9_Scale0_HaveSign).getInt());
                      d1.set (CobolFieldFactory.makeCobolField(9, b_ptx__pt11__pt1.getSubDataStorage(18 * (b_j.getNumdisp(2) - 1)), a_4_NumericDisplay_Digits9_Scale0_HaveSign).getInt());
                      d0.sub (d1);
                      d0.getField (f_dtx, 4);
                    }
                  }
                }
                /* /content/temp_cobol/ABC_057_B_fixed.cob:67: SUBTRACT */
                {
                  {
                    {
                      d0.set (CobolFieldFactory.makeCobolField(9, b_sty__st11__st1.getSubDataStorage(18 * (b_i.getNumdisp(2) - 1)), a_4_NumericDisplay_Digits9_Scale0_HaveSign).getInt());
                      d1.set (CobolFieldFactory.makeCobolField(9, b_pty__pt11__pt1.getSubDataStorage(18 * (b_j.getNumdisp(2) - 1)), a_4_NumericDisplay_Digits9_Scale0_HaveSign).getInt());
                      d0.sub (d1);
                      d0.getField (f_dty, 4);
                    }
                  }
                }
                /* /content/temp_cobol/ABC_057_B_fixed.cob:68: ADD */
                {
                  {
                    {
                      d0.set (b_dtx.getNumdisp(9));
                      d1.set (b_dty.getNumdisp(9));
                      d0.add (d1);
                      d0.getField (f_dt, 4);
                    }
                  }
                }
                /* /content/temp_cobol/ABC_057_B_fixed.cob:69: IF */
                {
                  if (((long)b_dt.memcmp (b_mn, 9) <  0L))
                    {
                      /* /content/temp_cobol/ABC_057_B_fixed.cob:70: MOVE */
                      {
                        b_mn.setBytes (b_dt, 9);
                      }
                      /* /content/temp_cobol/ABC_057_B_fixed.cob:71: MOVE */
                      {
                        b_p.setBytes (b_j, 2);
                      }
                    }
                }
              }
            }
            /* /content/temp_cobol/ABC_057_B_fixed.cob:75: MOVE */
            {
              f_ZS.moveFrom (f_p);
            }
            /* /content/temp_cobol/ABC_057_B_fixed.cob:77: PERFORM */
            /* PERFORM UNANS */
            CobolControl.perform(contList, l_UNANS).run();
            /* /content/temp_cobol/ABC_057_B_fixed.cob:79: DISPLAY */
            {
              CobolTerminal.display (0, 1, 1, CobolFieldFactory.makeCobolField(CobolIntrinsic.funcStoredCharLength (f_ans).getInt(), b_ans.getSubDataStorage(0), a_2_Alphanumeric));
            }
          }
        }
        /* /content/temp_cobol/ABC_057_B_fixed.cob:83: STOP */
        {
          CobolStopRunException.throwException (b_RETURN_CODE.intValue());
        }

        return Optional.of(contList[l_UNANS]);
      }
    },
    /* UNANS SECTION */
    new CobolControl(l_UNANS, CobolControl.LabelType.section) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_UNANS_SECTION__DEFAULT_PARAGRAPH]);
      }
    },
    /* UNANS_SECTION__DEFAULT_PARAGRAPH */
    new CobolControl(l_UNANS_SECTION__DEFAULT_PARAGRAPH, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* /content/temp_cobol/ABC_057_B_fixed.cob:86: UNSTRING */
        {
          CobolString.unstringInit (f_ZS, 0, 1);
          CobolString.unstringDelimited (CobolConstant.space, 1);
          CobolString.unstringInto (f_DUMMY, 0, 0);
          CobolString.unstringInto (f_ans, 0, 0);
          CobolString.unstringFinish ();
        }
        return Optional.of(CobolControl.pure());
      }
    },
    CobolControl.pure()
  };
  public void execEntry(int start) throws CobolRuntimeException, CobolStopRunException {
    Optional<CobolControl> nextLabel = Optional.of(contList[start]);
    while(nextLabel.isPresent()) {
      CobolControl section = nextLabel.get();
      nextLabel = section.run();
    }
  }

  public static void main(String[] args)
  {
    CobolUtil.cob_init(args, false);
    CobolDecimal.cobInitNumeric();
    new ABC_057_B().ABC_057_B_(0);
    CobolStopRunException.stopRun();
  }

  public ABC_057_B()
  {
    init();
  }

  public void init() 
  {
    /* Decimal structures */

    d0 = new CobolDecimal();
    d1 = new CobolDecimal();

    /* Data storage */

    cob_unifunc = null;

    /* PROGRAM-ID : ABC_057_B */
    b_RETURN_CODE = new CobolDataStorage(4);	/* RETURN-CODE */
    b_i = new CobolDataStorage(2);	/* i */
    b_j = new CobolDataStorage(2);	/* j */
    b_INP = new CobolDataStorage(5);	/* INP */
    b_INP2 = new CobolDataStorage(21);	/* INP2 */
    b_N = new CobolDataStorage(2);	/* N */
    b_M = new CobolDataStorage(2);	/* M */
    b_st1 = new CobolDataStorage(900);	/* st1 */
    b_pt1 = new CobolDataStorage(900);	/* pt1 */
    b_dt = new CobolDataStorage(9);	/* dt */
    b_dtx = new CobolDataStorage(9);	/* dtx */
    b_dty = new CobolDataStorage(9);	/* dty */
    b_mn = new CobolDataStorage(9);	/* mn */
    b_p = new CobolDataStorage(2);	/* p */
    b_ans = new CobolDataStorage(2);	/* ans */
    b_ZS = new CobolDataStorage(3);	/* ZS */
    b_DUMMY = new CobolDataStorage(1);	/* DUMMY */
    b_ptx__pt11__pt1 = b_pt1;
    b_pty__pt11__pt1 = b_pt1.getSubDataStorage(9);
    b_stx__st11__st1 = b_st1;
    b_sty__st11__st1 = b_st1.getSubDataStorage(9);

    /* End of data storage */


    initAttr();

    /* Fields */

    /* PROGRAM-ID : ABC_057_B */
    f_i	= CobolFieldFactory.makeCobolField(2, b_i, a_3_NumericDisplay_Digits2_Scale0);	/* i */
    f_j	= CobolFieldFactory.makeCobolField(2, b_j, a_3_NumericDisplay_Digits2_Scale0);	/* j */
    f_INP	= CobolFieldFactory.makeCobolField(5, b_INP, a_2_Alphanumeric);	/* INP */
    f_INP2	= CobolFieldFactory.makeCobolField(21, b_INP2, a_2_Alphanumeric);	/* INP2 */
    f_N	= CobolFieldFactory.makeCobolField(2, b_N, a_3_NumericDisplay_Digits2_Scale0);	/* N */
    f_M	= CobolFieldFactory.makeCobolField(2, b_M, a_3_NumericDisplay_Digits2_Scale0);	/* M */
    f_dt	= CobolFieldFactory.makeCobolField(9, b_dt, a_5_NumericDisplay_Digits9_Scale0);	/* dt */
    f_dtx	= CobolFieldFactory.makeCobolField(9, b_dtx, a_5_NumericDisplay_Digits9_Scale0);	/* dtx */
    f_dty	= CobolFieldFactory.makeCobolField(9, b_dty, a_5_NumericDisplay_Digits9_Scale0);	/* dty */
    f_p	= CobolFieldFactory.makeCobolField(2, b_p, a_3_NumericDisplay_Digits2_Scale0);	/* p */
    f_ans	= CobolFieldFactory.makeCobolField(2, b_ans, a_2_Alphanumeric);	/* ans */
    f_ZS	= CobolFieldFactory.makeCobolField(3, b_ZS, a_1_NumericEdited_Digits3_Scale0);	/* ZS */
    f_DUMMY	= CobolFieldFactory.makeCobolField(1, b_DUMMY, a_2_Alphanumeric);	/* DUMMY */

    /* End of fields */


  }

  private void initAttr() {
    /* Attributes */

    a_1_NumericEdited_Digits3_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_EDITED,
      /* digits= */ 3,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ "Z\002\000\000\0009\001\000\000\000");
    a_2_Alphanumeric = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_ALPHANUMERIC,
      /* digits= */ 0,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_3_NumericDisplay_Digits2_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 2,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_4_NumericDisplay_Digits9_Scale0_HaveSign = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 9,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_HAVE_SIGN,
      /* pic= */ null);
    a_5_NumericDisplay_Digits9_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 9,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);

  }

  /* Decimal structures */

  private CobolDecimal d0;
  private CobolDecimal d1;

  /* Data storage */

  /* PROGRAM-ID : ABC_057_B */
  public CobolDataStorage b_RETURN_CODE;	/* RETURN-CODE */
  private CobolDataStorage b_i;	/* i */
  private CobolDataStorage b_j;	/* j */
  private CobolDataStorage b_INP;	/* INP */
  private CobolDataStorage b_INP2;	/* INP2 */
  private CobolDataStorage b_N;	/* N */
  private CobolDataStorage b_M;	/* M */
  private CobolDataStorage b_st1;	/* st1 */
  private CobolDataStorage b_pt1;	/* pt1 */
  private CobolDataStorage b_dt;	/* dt */
  private CobolDataStorage b_dtx;	/* dtx */
  private CobolDataStorage b_dty;	/* dty */
  private CobolDataStorage b_mn;	/* mn */
  private CobolDataStorage b_p;	/* p */
  private CobolDataStorage b_ans;	/* ans */
  private CobolDataStorage b_ZS;	/* ZS */
  private CobolDataStorage b_DUMMY;	/* DUMMY */
  private CobolDataStorage b_ptx__pt11__pt1;
  private CobolDataStorage b_pty__pt11__pt1;
  private CobolDataStorage b_stx__st11__st1;
  private CobolDataStorage b_sty__st11__st1;

  /* End of data storage */


  /* Fields */

  /* PROGRAM-ID : ABC_057_B */
  private AbstractCobolField f_i;	/* i */
  private AbstractCobolField f_j;	/* j */
  private AbstractCobolField f_INP;	/* INP */
  private AbstractCobolField f_INP2;	/* INP2 */
  private AbstractCobolField f_N;	/* N */
  private AbstractCobolField f_M;	/* M */
  private AbstractCobolField f_dt;	/* dt */
  private AbstractCobolField f_dtx;	/* dtx */
  private AbstractCobolField f_dty;	/* dty */
  private AbstractCobolField f_p;	/* p */
  private AbstractCobolField f_ans;	/* ans */
  private AbstractCobolField f_ZS;	/* ZS */
  private AbstractCobolField f_DUMMY;	/* DUMMY */

  /* End of fields */


  private static AbstractCobolField f_native;

  /* Attributes */

  private CobolFieldAttribute a_5_NumericDisplay_Digits9_Scale0;
  private CobolFieldAttribute a_4_NumericDisplay_Digits9_Scale0_HaveSign;
  private CobolFieldAttribute a_3_NumericDisplay_Digits2_Scale0;
  private CobolFieldAttribute a_2_Alphanumeric;
  private CobolFieldAttribute a_1_NumericEdited_Digits3_Scale0;



  /* String literals */
  public static final byte[] str_4_01 = CobolUtil.stringToBytes("01");
  public static final byte[] str_3_200000001 = CobolUtil.stringToBytes("200000001");
  public static final byte[] str_2_01 = CobolUtil.stringToBytes("01");
  public static final byte[] str_1_01 = CobolUtil.stringToBytes("01");
  public static final byte[] str_0_01 = CobolUtil.stringToBytes("01");

  /* Sections and Labels */
  private final static int l_ABC_057_B = 1;
  private final static int l_MAIN_SECTION = 2;
  private final static int l_MAIN_SECTION__MAIN = 3;
  private final static int l_UNANS = 4;
  private final static int l_UNANS_SECTION__DEFAULT_PARAGRAPH = 5;
  private final static int l_Default_Error_Handler = 6;

}
