/* Generated by opensource COBOL 4J 1.1.16 */
import java.io.UnsupportedEncodingException;
import jp.osscons.opensourcecobol.libcobj.*;
import jp.osscons.opensourcecobol.libcobj.common.*;
import jp.osscons.opensourcecobol.libcobj.data.*;
import jp.osscons.opensourcecobol.libcobj.exceptions.*;
import jp.osscons.opensourcecobol.libcobj.termio.*;
import jp.osscons.opensourcecobol.libcobj.call.*;
import jp.osscons.opensourcecobol.libcobj.file.*;
import jp.osscons.opensourcecobol.libcobj.ui.*;
import java.util.Optional;

public class SORTNUM implements CobolRunnable {

  private boolean initialized = false;
  private CobolModule module;
  private int entry;

  private CobolRunnable cob_unifunc;


  @Override
  public int run(CobolDataStorage... argStorages) {
    return SORTNUM_(0, argStorages);
  }

  @Override
  public void cancel() {
    SORTNUM_(-1);
  }

  @Override
  public boolean isActive() {
    return false;
  }

  public CobolResultSet execute () {
    int returnCode = run_module(0);
    return new CobolResultSet(returnCode);
  }

  public int SORTNUM_ (int entry, CobolDataStorage ...argStorages) {
    this.entry = entry;
    return this.run_module(entry);
  }

  int run_module (int entry) {
    this.module = new CobolModule(null, null, null, null, 0, '.', '$', ',', 1, 1, 1, 0, null );

    /* Start of function code */

    /* CANCEL callback handling */
    if (entry < 0) {
    	if (!this.initialized) {
    		CobolDecimal.cobInitNumeric();
    		return 0;
    	}
    	d0.clear();
    	d0.setScale(0);
    	d1.clear();
    	d1.setScale(0);
    	d2.clear();
    	d2.setScale(0);
    	this.initialized = false;
    	return 0;
    }

    /* Push module stack */
    CobolModule.push (module);
    CobolResolve.pushCallStackList ("SORTNUM");

    /* Initialize program */
    if (!this.initialized) {
      module.setProgramId("SORTNUM");

      /* Initialize decimal numbers */
      d0.decimalInit();
      d1.decimalInit();
      d2.decimalInit();

      b_RETURN_CODE.set((int)0);
      b_N.fillBytes('0', 6);
      b_POIN.setBytes (str_0_FALS, 4);
      b_A.setBytes (str_1_000001, 6);
      b_B.setBytes (str_2_000001, 6);
      b_C.setBytes (str_3_000001, 6);
      b_RES.fillBytes('0', 6);
      b_CNT.fillBytes('0', 6);
      f_OUT.moveFrom (CobolConstant.zero);
      this.initialized = true;
    }
    /* PROCEDURE DIVISION */
    try{
      /* Entry dispatch */
      execEntry(l_SORTNUM);

    } catch(CobolStopRunException e) {
      CobolStopRunException.stopRun();
      System.exit(e.getReturnCode());
    }
    /* Pop module stack */
    CobolResolve.popCallStackList();
    CobolModule.pop();

    /* Program return */
    return b_RETURN_CODE.intValue();
  }
  public CobolControl[] contList = {
    new CobolControl(0, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_SORTNUM]);
      }
    },
    /* Entry SORTNUM */
    new CobolControl(l_SORTNUM, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN]);
      }
    },
    /* MAIN SECTION */
    new CobolControl(l_MAIN, CobolControl.LabelType.section) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION__DEFAULT_PARAGRAPH]);
      }
    },
    /* MAIN_SECTION__DEFAULT_PARAGRAPH */
    new CobolControl(l_MAIN_SECTION__DEFAULT_PARAGRAPH, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* /content/temp_translate/s996086821.cob:26: ACCEPT */
        {
          CobolTerminal.accept (f_N);
        }
        /* /content/temp_translate/s996086821.cob:28: PERFORM */
        b_A.setBytes (str_4_000001, 6);
        for(;;f_A.addInt (1))
        {
          if (((long)b_A.memcmp (b_N, 6) == 0L))
            break;
          {
            /* /content/temp_translate/s996086821.cob:31: PERFORM */
            b_B.setBytes (str_5_000001, 6);
            for(;;f_B.addInt (1))
            {
              if (((long)b_B.memcmp (b_N, 6) == 0L))
                break;
              {
                /* /content/temp_translate/s996086821.cob:34: PERFORM */
                b_C.setBytes (str_6_000001, 6);
                for(;;f_C.addInt (1))
                {
                  if (((long)b_C.memcmp (b_N, 6) == 0L))
                    break;
                  {
                    /* /content/temp_translate/s996086821.cob:37: COMPUTE */
                    {
                      {
                        {
                          d0.set (b_A.getNumdisp(6));
                          d2.set (b_B.getNumdisp(6));
                          d0.mul (d2);
                          d1.set (b_C.getNumdisp(6));
                          d0.add (d1);
                          d0.getField (f_RES, 4);
                        }
                      }
                    }
                    /* /content/temp_translate/s996086821.cob:39: IF */
                    {
                      if (((long)b_RES.memcmp (b_N, 6) >  0L))
                        {
                          /* /content/temp_translate/s996086821.cob:40: EXIT */
                          {
                            if(true) break;
                          }
                        }
                    }
                    /* /content/temp_translate/s996086821.cob:43: IF */
                    {
                      if (((long)b_RES.memcmp (b_N, 6) == 0L))
                        {
                          /* /content/temp_translate/s996086821.cob:45: ADD */
                          {
                            f_CNT.add (c_1_1, 4);
                          }
                          /* /content/temp_translate/s996086821.cob:46: EXIT */
                          {
                            if(true) break;
                          }
                        }
                    }
                  }
                }
              }
            }
          }
        }
        /* /content/temp_translate/s996086821.cob:52: MOVE */
        {
          f_OUT.moveFrom (f_CNT);
        }
        /* /content/temp_translate/s996086821.cob:53: DISPLAY */
        {
          CobolTerminal.display (0, 1, 1, CobolIntrinsic.funcTrim (0, 0, f_OUT, 0));
        }
        /* /content/temp_translate/s996086821.cob:56: STOP */
        {
          CobolStopRunException.throwException (b_RETURN_CODE.intValue());
        }
        return Optional.of(CobolControl.pure());
      }
    },
    CobolControl.pure()
  };
  public void execEntry(int start) throws CobolRuntimeException, CobolStopRunException {
    Optional<CobolControl> nextLabel = Optional.of(contList[start]);
    while(nextLabel.isPresent()) {
      CobolControl section = nextLabel.get();
      nextLabel = section.run();
    }
  }

  public static void main(String[] args)
  {
    CobolUtil.cob_init(args, false);
    CobolDecimal.cobInitNumeric();
    new SORTNUM().SORTNUM_(0);
    CobolStopRunException.stopRun();
  }

  public SORTNUM()
  {
    init();
  }

  public void init() 
  {
    /* Decimal structures */

    d0 = new CobolDecimal();
    d1 = new CobolDecimal();
    d2 = new CobolDecimal();

    /* Data storage */

    cob_unifunc = null;

    /* PROGRAM-ID : SORTNUM */
    b_RETURN_CODE = new CobolDataStorage(4);	/* RETURN-CODE */
    b_N = new CobolDataStorage(6);	/* N */
    b_POIN = new CobolDataStorage(4);	/* POIN */
    b_A = new CobolDataStorage(6);	/* A */
    b_B = new CobolDataStorage(6);	/* B */
    b_C = new CobolDataStorage(6);	/* C */
    b_RES = new CobolDataStorage(6);	/* RES */
    b_CNT = new CobolDataStorage(6);	/* CNT */
    b_OUT = new CobolDataStorage(6);	/* OUT */

    /* End of data storage */


    initAttr();

    /* Fields */

    /* PROGRAM-ID : SORTNUM */
    f_N	= CobolFieldFactory.makeCobolField(6, b_N, a_2_NumericDisplay_Digits6_Scale0);	/* N */
    f_A	= CobolFieldFactory.makeCobolField(6, b_A, a_2_NumericDisplay_Digits6_Scale0);	/* A */
    f_B	= CobolFieldFactory.makeCobolField(6, b_B, a_2_NumericDisplay_Digits6_Scale0);	/* B */
    f_C	= CobolFieldFactory.makeCobolField(6, b_C, a_2_NumericDisplay_Digits6_Scale0);	/* C */
    f_RES	= CobolFieldFactory.makeCobolField(6, b_RES, a_2_NumericDisplay_Digits6_Scale0);	/* RES */
    f_CNT	= CobolFieldFactory.makeCobolField(6, b_CNT, a_2_NumericDisplay_Digits6_Scale0);	/* CNT */
    f_OUT	= CobolFieldFactory.makeCobolField(6, b_OUT, a_1_NumericEdited_Digits6_Scale0);	/* OUT */

    /* End of fields */


    /* Constants */

    c_1_1	= CobolFieldFactory.makeCobolField(1, "1", a_3_NumericDisplay_Digits1_Scale0);

  }

  private void initAttr() {
    /* Attributes */

    a_1_NumericEdited_Digits6_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_EDITED,
      /* digits= */ 6,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ "Z\005\000\000\0009\001\000\000\000");
    a_2_NumericDisplay_Digits6_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 6,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_3_NumericDisplay_Digits1_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 1,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);

  }

  /* Decimal structures */

  private CobolDecimal d0;
  private CobolDecimal d1;
  private CobolDecimal d2;

  /* Data storage */

  /* PROGRAM-ID : SORTNUM */
  public CobolDataStorage b_RETURN_CODE;	/* RETURN-CODE */
  private CobolDataStorage b_N;	/* N */
  private CobolDataStorage b_POIN;	/* POIN */
  private CobolDataStorage b_A;	/* A */
  private CobolDataStorage b_B;	/* B */
  private CobolDataStorage b_C;	/* C */
  private CobolDataStorage b_RES;	/* RES */
  private CobolDataStorage b_CNT;	/* CNT */
  private CobolDataStorage b_OUT;	/* OUT */

  /* End of data storage */


  /* Fields */

  /* PROGRAM-ID : SORTNUM */
  private AbstractCobolField f_N;	/* N */
  private AbstractCobolField f_A;	/* A */
  private AbstractCobolField f_B;	/* B */
  private AbstractCobolField f_C;	/* C */
  private AbstractCobolField f_RES;	/* RES */
  private AbstractCobolField f_CNT;	/* CNT */
  private AbstractCobolField f_OUT;	/* OUT */

  /* End of fields */


  private static AbstractCobolField f_native;

  /* Constants */

  private AbstractCobolField c_1_1;

  /* Attributes */

  private CobolFieldAttribute a_3_NumericDisplay_Digits1_Scale0;
  private CobolFieldAttribute a_2_NumericDisplay_Digits6_Scale0;
  private CobolFieldAttribute a_1_NumericEdited_Digits6_Scale0;



  /* String literals */
  public static final byte[] str_6_000001 = CobolUtil.stringToBytes("000001");
  public static final byte[] str_5_000001 = CobolUtil.stringToBytes("000001");
  public static final byte[] str_4_000001 = CobolUtil.stringToBytes("000001");
  public static final byte[] str_3_000001 = CobolUtil.stringToBytes("000001");
  public static final byte[] str_2_000001 = CobolUtil.stringToBytes("000001");
  public static final byte[] str_1_000001 = CobolUtil.stringToBytes("000001");
  public static final byte[] str_0_FALS = CobolUtil.stringToBytes("FALS");

  /* Sections and Labels */
  private final static int l_SORTNUM = 1;
  private final static int l_MAIN = 2;
  private final static int l_MAIN_SECTION__DEFAULT_PARAGRAPH = 3;
  private final static int l_Default_Error_Handler = 4;

}
