/* Generated by opensource COBOL 4J 1.1.16 */
import java.io.UnsupportedEncodingException;
import jp.osscons.opensourcecobol.libcobj.*;
import jp.osscons.opensourcecobol.libcobj.common.*;
import jp.osscons.opensourcecobol.libcobj.data.*;
import jp.osscons.opensourcecobol.libcobj.exceptions.*;
import jp.osscons.opensourcecobol.libcobj.termio.*;
import jp.osscons.opensourcecobol.libcobj.call.*;
import jp.osscons.opensourcecobol.libcobj.file.*;
import jp.osscons.opensourcecobol.libcobj.ui.*;
import java.util.Optional;

public class PROGRAM_ID implements CobolRunnable {

  private boolean initialized = false;
  private CobolModule module;
  private int entry;

  private CobolRunnable cob_unifunc;


  @Override
  public int run(CobolDataStorage... argStorages) {
    return PROGRAM_ID_(0, argStorages);
  }

  @Override
  public void cancel() {
    PROGRAM_ID_(-1);
  }

  @Override
  public boolean isActive() {
    return false;
  }

  public CobolResultSet execute () {
    int returnCode = run_module(0);
    return new CobolResultSet(returnCode);
  }

  public int PROGRAM_ID_ (int entry, CobolDataStorage ...argStorages) {
    this.entry = entry;
    return this.run_module(entry);
  }

  int run_module (int entry) {
    this.module = new CobolModule(null, null, null, null, 0, '.', '$', ',', 1, 1, 1, 0, null );

    /* Start of function code */

    /* CANCEL callback handling */
    if (entry < 0) {
    	if (!this.initialized) {
    		CobolDecimal.cobInitNumeric();
    		return 0;
    	}
    	this.initialized = false;
    	return 0;
    }

    /* Push module stack */
    CobolModule.push (module);
    CobolResolve.pushCallStackList ("PROGRAM_ID");

    /* Initialize program */
    if (!this.initialized) {
      module.setProgramId("PROGRAM_ID");

      b_RETURN_CODE.set((int)0);
      b_S.fillBytes(' ', 11);
      b_T.fillBytes(' ', 11);
      this.initialized = true;
    }
    /* PROCEDURE DIVISION */
    try{
      /* Entry dispatch */
      execEntry(l_PROGRAM_ID);

    } catch(CobolStopRunException e) {
      CobolStopRunException.stopRun();
      System.exit(e.getReturnCode());
    }
    /* Pop module stack */
    CobolResolve.popCallStackList();
    CobolModule.pop();

    /* Program return */
    return b_RETURN_CODE.intValue();
  }
  public CobolControl[] contList = {
    new CobolControl(0, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_PROGRAM_ID]);
      }
    },
    /* Entry PROGRAM_ID */
    new CobolControl(l_PROGRAM_ID, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN]);
      }
    },
    /* MAIN SECTION */
    new CobolControl(l_MAIN, CobolControl.LabelType.section) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION__DEFAULT_PARAGRAPH]);
      }
    },
    /* MAIN_SECTION__DEFAULT_PARAGRAPH */
    new CobolControl(l_MAIN_SECTION__DEFAULT_PARAGRAPH, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* /content/temp_cobol/PROGRAM_ID_fixed.cob:10: ACCEPT */
        {
          CobolTerminal.accept (f_S);
        }
        /* /content/temp_cobol/PROGRAM_ID_fixed.cob:11: ACCEPT */
        {
          CobolTerminal.accept (f_T);
        }
        /* /content/temp_cobol/PROGRAM_ID_fixed.cob:13: IF */
        {
          if (((long)f_S.compareTo (CobolFieldFactory.makeCobolField((CobolIntrinsic.funcStoredCharLength (f_T).getInt() - 1), b_T.getSubDataStorage(0), a_1_Alphanumeric)) == 0L))
            {
              /* /content/temp_cobol/PROGRAM_ID_fixed.cob:14: DISPLAY */
              {
                CobolTerminal.display (0, 1, 1, c_1_Yes);
              }
            }
          else
            {
              /* /content/temp_cobol/PROGRAM_ID_fixed.cob:16: DISPLAY */
              {
                CobolTerminal.display (0, 1, 1, c_2_No);
              }
            }
        }
        /* /content/temp_cobol/PROGRAM_ID_fixed.cob:18: STOP */
        {
          CobolStopRunException.throwException (b_RETURN_CODE.intValue());
        }
        return Optional.of(CobolControl.pure());
      }
    },
    CobolControl.pure()
  };
  public void execEntry(int start) throws CobolRuntimeException, CobolStopRunException {
    Optional<CobolControl> nextLabel = Optional.of(contList[start]);
    while(nextLabel.isPresent()) {
      CobolControl section = nextLabel.get();
      nextLabel = section.run();
    }
  }

  public static void main(String[] args)
  {
    CobolUtil.cob_init(args, false);
    CobolDecimal.cobInitNumeric();
    new PROGRAM_ID().PROGRAM_ID_(0);
    CobolStopRunException.stopRun();
  }

  public PROGRAM_ID()
  {
    init();
  }

  public void init() 
  {
    /* Data storage */

    cob_unifunc = null;

    /* PROGRAM-ID : PROGRAM_ID */
    b_RETURN_CODE = new CobolDataStorage(4);	/* RETURN-CODE */
    b_S = new CobolDataStorage(11);	/* S */
    b_T = new CobolDataStorage(11);	/* T */

    /* End of data storage */


    initAttr();

    /* Fields */

    /* PROGRAM-ID : PROGRAM_ID */
    f_S	= CobolFieldFactory.makeCobolField(11, b_S, a_1_Alphanumeric);	/* S */
    f_T	= CobolFieldFactory.makeCobolField(11, b_T, a_1_Alphanumeric);	/* T */

    /* End of fields */


    /* Constants */

    c_1_Yes	= CobolFieldFactory.makeCobolField(str_0_Yes, a_1_Alphanumeric);
    c_2_No	= CobolFieldFactory.makeCobolField(str_1_No, a_1_Alphanumeric);

  }

  private void initAttr() {
    /* Attributes */

    a_1_Alphanumeric = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_ALPHANUMERIC,
      /* digits= */ 0,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);

  }

  /* Data storage */

  /* PROGRAM-ID : PROGRAM_ID */
  public CobolDataStorage b_RETURN_CODE;	/* RETURN-CODE */
  private CobolDataStorage b_S;	/* S */
  private CobolDataStorage b_T;	/* T */

  /* End of data storage */


  /* Fields */

  /* PROGRAM-ID : PROGRAM_ID */
  private AbstractCobolField f_S;	/* S */
  private AbstractCobolField f_T;	/* T */

  /* End of fields */


  private static AbstractCobolField f_native;

  /* Constants */

  private AbstractCobolField c_2_No;
  private AbstractCobolField c_1_Yes;

  /* Attributes */

  private CobolFieldAttribute a_1_Alphanumeric;



  /* String literals */
  public static final byte[] str_1_No = CobolUtil.stringToBytes("No");
  public static final byte[] str_0_Yes = CobolUtil.stringToBytes("Yes");

  /* Sections and Labels */
  private final static int l_PROGRAM_ID = 1;
  private final static int l_MAIN = 2;
  private final static int l_MAIN_SECTION__DEFAULT_PARAGRAPH = 3;
  private final static int l_Default_Error_Handler = 4;

}
