/* Generated by opensource COBOL 4J 1.1.16 */
import java.io.UnsupportedEncodingException;
import jp.osscons.opensourcecobol.libcobj.*;
import jp.osscons.opensourcecobol.libcobj.common.*;
import jp.osscons.opensourcecobol.libcobj.data.*;
import jp.osscons.opensourcecobol.libcobj.exceptions.*;
import jp.osscons.opensourcecobol.libcobj.termio.*;
import jp.osscons.opensourcecobol.libcobj.call.*;
import jp.osscons.opensourcecobol.libcobj.file.*;
import jp.osscons.opensourcecobol.libcobj.ui.*;
import java.util.Optional;

public class Answer implements CobolRunnable {

  private boolean initialized = false;
  private CobolModule module;
  private int entry;

  private CobolRunnable cob_unifunc;


  @Override
  public int run(CobolDataStorage... argStorages) {
    return Answer_(0, argStorages);
  }

  @Override
  public void cancel() {
    Answer_(-1);
  }

  @Override
  public boolean isActive() {
    return false;
  }

  public CobolResultSet execute () {
    int returnCode = run_module(0);
    return new CobolResultSet(returnCode);
  }

  public int Answer_ (int entry, CobolDataStorage ...argStorages) {
    this.entry = entry;
    return this.run_module(entry);
  }

  int run_module (int entry) {
    this.module = new CobolModule(null, null, null, null, 0, '.', '$', ',', 1, 1, 1, 0, null );

    /* Start of function code */

    /* CANCEL callback handling */
    if (entry < 0) {
    	if (!this.initialized) {
    		CobolDecimal.cobInitNumeric();
    		return 0;
    	}
    	d0.clear();
    	d0.setScale(0);
    	d1.clear();
    	d1.setScale(0);
    	this.initialized = false;
    	return 0;
    }

    /* Push module stack */
    CobolModule.push (module);
    CobolResolve.pushCallStackList ("Answer");

    /* Initialize program */
    if (!this.initialized) {
      module.setProgramId("Answer");

      /* Initialize decimal numbers */
      d0.decimalInit();
      d1.decimalInit();

      b_RETURN_CODE.set((int)0);
      b_n__Input_Values.fillBytes(0, 2);
      b_arare__Input_Values.fillBytes(' ', 200);
      b_Calc_Values.fillBytes(' ', 5);
      this.initialized = true;
    }
    /* PROCEDURE DIVISION */
    try{
      /* Entry dispatch */
      execEntry(l_Answer);

    } catch(CobolStopRunException e) {
      CobolStopRunException.stopRun();
      System.exit(e.getReturnCode());
    }
    /* Pop module stack */
    CobolResolve.popCallStackList();
    CobolModule.pop();

    /* Program return */
    return b_RETURN_CODE.intValue();
  }
  public CobolControl[] contList = {
    new CobolControl(0, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_Answer]);
      }
    },
    /* Entry Answer */
    new CobolControl(l_Answer, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_AnswerMain]);
      }
    },
    /* AnswerMain SECTION */
    new CobolControl(l_AnswerMain, CobolControl.LabelType.section) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_AnswerMain__000_Start]);
      }
    },
    /* 000-Start */
    new CobolControl(l_AnswerMain__000_Start, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* /content/temp_cobol/Answer_fixed.cob:21: ACCEPT */
        {
          CobolTerminal.accept (f_n__Input_Values);
        }
        /* /content/temp_cobol/Answer_fixed.cob:22: ACCEPT */
        {
          CobolTerminal.accept (f_arare__Input_Values);
        }
        /* /content/temp_cobol/Answer_fixed.cob:24: MOVE */
        {
          b_ans__Calc_Values.setBytes (str_0_Three, 5);
        }
        /* /content/temp_cobol/Answer_fixed.cob:25: MULTIPLY */
        {
          {
            {
              d0.set (2);
              d1.set (b_n__Input_Values.shortValue());
              d1.mul (d0);
              d1.getField (f_n__Input_Values, 0);
            }
          }
        }
        /* /content/temp_cobol/Answer_fixed.cob:26: SUBTRACT */
        {
          b_n__Input_Values.set((short)(b_n__Input_Values.shortValue() - 1));
        }

        return Optional.of(contList[l_AnswerMain__001_LoopHead]);
      }
    },
    /* 001-LoopHead */
    new CobolControl(l_AnswerMain__001_LoopHead, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* /content/temp_cobol/Answer_fixed.cob:28: IF */
        {
          if (((long)(Byte.toUnsignedInt(b_arare__Input_Values.getSubDataStorage((b_n__Input_Values.shortValue() - 1)).getByte(0)) - (int)89) == 0L))
            {
              /* /content/temp_cobol/Answer_fixed.cob:29: MOVE */
              {
                b_ans__Calc_Values.setBytes (str_1_Four, 5);
              }
              /* /content/temp_cobol/Answer_fixed.cob:30: GO TO */
              {
                if(true) return Optional.of(contList[l_AnswerMain__002_Output]);
              }
            }
        }
        /* /content/temp_cobol/Answer_fixed.cob:32: SUBTRACT */
        {
          b_n__Input_Values.set((short)(b_n__Input_Values.shortValue() - 1));
        }
        /* /content/temp_cobol/Answer_fixed.cob:33: IF */
        {
          if (((long)f_n__Input_Values.cmpInteger (0) <  0L))
            {
              /* /content/temp_cobol/Answer_fixed.cob:34: GO TO */
              {
                if(true) return Optional.of(contList[l_AnswerMain__002_Output]);
              }
            }
        }
        /* /content/temp_cobol/Answer_fixed.cob:36: GO TO */
        {
          if(true) return Optional.of(contList[l_AnswerMain__001_LoopHead]);
        }

        return Optional.of(contList[l_AnswerMain__002_Output]);
      }
    },
    /* 002-Output */
    new CobolControl(l_AnswerMain__002_Output, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* /content/temp_cobol/Answer_fixed.cob:38: DISPLAY */
        {
          CobolTerminal.display (0, 1, 1, CobolIntrinsic.funcTrim (0, 0, f_ans__Calc_Values, 0));
        }
        return Optional.of(CobolControl.pure());
      }
    },
    CobolControl.pure()
  };
  public void execEntry(int start) throws CobolRuntimeException, CobolStopRunException {
    Optional<CobolControl> nextLabel = Optional.of(contList[start]);
    while(nextLabel.isPresent()) {
      CobolControl section = nextLabel.get();
      nextLabel = section.run();
    }
  }

  public static void main(String[] args)
  {
    CobolUtil.cob_init(args, false);
    CobolDecimal.cobInitNumeric();
    new Answer().Answer_(0);
    CobolStopRunException.stopRun();
  }

  public Answer()
  {
    init();
  }

  public void init() 
  {
    /* Decimal structures */

    d0 = new CobolDecimal();
    d1 = new CobolDecimal();

    /* Data storage */

    cob_unifunc = null;

    /* PROGRAM-ID : Answer */
    b_RETURN_CODE = new CobolDataStorage(4);	/* RETURN-CODE */
    b_Input_Values = new CobolDataStorage(202);	/* Input-Values */
    b_Calc_Values = new CobolDataStorage(5);	/* Calc-Values */
    b_ans__Calc_Values = b_Calc_Values;
    b_arare__Input_Values = b_Input_Values.getSubDataStorage(2);
    b_n__Input_Values = b_Input_Values;

    /* End of data storage */


    initAttr();

    /* Fields */

    /* PROGRAM-ID : Answer */
    f_n__Input_Values	= CobolFieldFactory.makeCobolField(2, b_n__Input_Values, a_1_NumericBinary_Digits4_Scale0_HaveSign_RealBinary);	/* n */
    f_arare__Input_Values	= CobolFieldFactory.makeCobolField(200, b_arare__Input_Values, a_2_Alphanumeric);	/* arare */
    f_ans__Calc_Values	= CobolFieldFactory.makeCobolField(5, b_ans__Calc_Values, a_2_Alphanumeric);	/* ans */

    /* End of fields */


  }

  private void initAttr() {
    /* Attributes */

    a_1_NumericBinary_Digits4_Scale0_HaveSign_RealBinary = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_BINARY,
      /* digits= */ 4,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_HAVE_SIGN
        | CobolFieldAttribute.COB_FLAG_REAL_BINARY,
      /* pic= */ null);
    a_2_Alphanumeric = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_ALPHANUMERIC,
      /* digits= */ 0,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);

  }

  /* Decimal structures */

  private CobolDecimal d0;
  private CobolDecimal d1;

  /* Data storage */

  /* PROGRAM-ID : Answer */
  public CobolDataStorage b_RETURN_CODE;	/* RETURN-CODE */
  private CobolDataStorage b_Input_Values;	/* Input-Values */
  private CobolDataStorage b_Calc_Values;	/* Calc-Values */
  private CobolDataStorage b_ans__Calc_Values;
  private CobolDataStorage b_arare__Input_Values;
  private CobolDataStorage b_n__Input_Values;

  /* End of data storage */


  /* Fields */

  /* PROGRAM-ID : Answer */
  private AbstractCobolField f_n__Input_Values;	/* n */
  private AbstractCobolField f_arare__Input_Values;	/* arare */
  private AbstractCobolField f_ans__Calc_Values;	/* ans */

  /* End of fields */


  private static AbstractCobolField f_native;

  /* Attributes */

  private CobolFieldAttribute a_2_Alphanumeric;
  private CobolFieldAttribute a_1_NumericBinary_Digits4_Scale0_HaveSign_RealBinary;



  /* String literals */
  public static final byte[] str_1_Four = CobolUtil.stringToBytes("Four ");
  public static final byte[] str_0_Three = CobolUtil.stringToBytes("Three");

  /* Sections and Labels */
  private final static int l_Answer = 1;
  private final static int l_AnswerMain = 2;
  private final static int l_AnswerMain__000_Start = 3;
  private final static int l_AnswerMain__001_LoopHead = 4;
  private final static int l_AnswerMain__002_Output = 5;
  private final static int l_Default_Error_Handler = 6;

}
