/* Generated by opensource COBOL 4J 1.1.16 */
import java.io.UnsupportedEncodingException;
import jp.osscons.opensourcecobol.libcobj.*;
import jp.osscons.opensourcecobol.libcobj.common.*;
import jp.osscons.opensourcecobol.libcobj.data.*;
import jp.osscons.opensourcecobol.libcobj.exceptions.*;
import jp.osscons.opensourcecobol.libcobj.termio.*;
import jp.osscons.opensourcecobol.libcobj.call.*;
import jp.osscons.opensourcecobol.libcobj.file.*;
import jp.osscons.opensourcecobol.libcobj.ui.*;
import java.util.Optional;

public class _3152B implements CobolRunnable {

  private boolean initialized = false;
  private CobolModule module;
  private int entry;

  private CobolRunnable cob_unifunc;


  @Override
  public int run(CobolDataStorage... argStorages) {
    return _3152B_(0, argStorages);
  }

  @Override
  public void cancel() {
    _3152B_(-1);
  }

  @Override
  public boolean isActive() {
    return false;
  }

  public CobolResultSet execute () {
    int returnCode = run_module(0);
    return new CobolResultSet(returnCode);
  }

  public int _3152B_ (int entry, CobolDataStorage ...argStorages) {
    this.entry = entry;
    return this.run_module(entry);
  }

  int run_module (int entry) {
    this.module = new CobolModule(null, null, null, null, 0, '.', '$', ',', 1, 1, 1, 0, null );

    /* Start of function code */

    /* CANCEL callback handling */
    if (entry < 0) {
    	if (!this.initialized) {
    		CobolDecimal.cobInitNumeric();
    		return 0;
    	}
    	this.initialized = false;
    	return 0;
    }

    /* Push module stack */
    CobolModule.push (module);
    CobolResolve.pushCallStackList ("_3152B");

    /* Initialize program */
    if (!this.initialized) {
      module.setProgramId("_3152B");

      b_RETURN_CODE.set((int)0);
      b_INP.fillBytes(' ', 10);
      b_A.setByte('0');
      b_B.setByte('0');
      b_N.setByte('0');
      b_I.fillBytes('0', 2);
      b_OUT.fillBytes(' ', 10);
      this.initialized = true;
    }
    /* PROCEDURE DIVISION */
    try{
      /* Entry dispatch */
      execEntry(l__3152B);

    } catch(CobolStopRunException e) {
      CobolStopRunException.stopRun();
      System.exit(e.getReturnCode());
    }
    /* Pop module stack */
    CobolResolve.popCallStackList();
    CobolModule.pop();

    /* Program return */
    return b_RETURN_CODE.intValue();
  }
  public CobolControl[] contList = {
    new CobolControl(0, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l__3152B]);
      }
    },
    /* Entry 152B */
    new CobolControl(l__3152B, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN]);
      }
    },
    /* MAIN SECTION */
    new CobolControl(l_MAIN, CobolControl.LabelType.section) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION__DEFAULT_PARAGRAPH]);
      }
    },
    /* MAIN_SECTION__DEFAULT_PARAGRAPH */
    new CobolControl(l_MAIN_SECTION__DEFAULT_PARAGRAPH, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* /content/temp_cobol/152B_fixed.cob:13: ACCEPT */
        {
          CobolTerminal.accept (f_INP);
        }
        /* /content/temp_cobol/152B_fixed.cob:14: UNSTRING */
        {
          CobolString.unstringInit (f_INP, 0, 1);
          CobolString.unstringDelimited (c_1, 0);
          CobolString.unstringInto (f_A, 0, 0);
          CobolString.unstringInto (f_B, 0, 0);
          CobolString.unstringFinish ();
        }
        /* /content/temp_cobol/152B_fixed.cob:16: IF */
        {
          if (((long)b_A.memcmp (b_B, 1) <= 0L))
            {
              /* /content/temp_cobol/152B_fixed.cob:17: MOVE */
              {
                b_N.setByte(b_B.getByte(0));
              }
            }
          else
            {
              /* /content/temp_cobol/152B_fixed.cob:19: MOVE */
              {
                b_N.setByte(b_A.getByte(0));
              }
              /* /content/temp_cobol/152B_fixed.cob:20: MOVE */
              {
                b_A.setByte(b_B.getByte(0));
              }
            }
        }
        /* /content/temp_cobol/152B_fixed.cob:23: PERFORM */
        b_I.setBytes (str_0_01, 2);
        for(;;f_I.addInt (1))
        {
          if (((long)b_I.cmpNumdisp (2, b_N.getNumdisp(1)) >  0L))
            break;
          {
            /* /content/temp_cobol/152B_fixed.cob:24: MOVE */
            {
              b_OUT.getSubDataStorage((b_I.getNumdisp(2) - 1)).setByte(b_A.getByte(0));
            }
          }
        }
        /* /content/temp_cobol/152B_fixed.cob:27: DISPLAY */
        {
          CobolTerminal.display (0, 1, 1, CobolFieldFactory.makeCobolField(b_N.getNumdisp(1), b_OUT.getSubDataStorage(0), a_1_Alphanumeric));
        }
        /* /content/temp_cobol/152B_fixed.cob:29: STOP */
        {
          CobolStopRunException.throwException (b_RETURN_CODE.intValue());
        }
        return Optional.of(CobolControl.pure());
      }
    },
    CobolControl.pure()
  };
  public void execEntry(int start) throws CobolRuntimeException, CobolStopRunException {
    Optional<CobolControl> nextLabel = Optional.of(contList[start]);
    while(nextLabel.isPresent()) {
      CobolControl section = nextLabel.get();
      nextLabel = section.run();
    }
  }

  public static void main(String[] args)
  {
    CobolUtil.cob_init(args, false);
    CobolDecimal.cobInitNumeric();
    new _3152B()._3152B_(0);
    CobolStopRunException.stopRun();
  }

  public _3152B()
  {
    init();
  }

  public void init() 
  {
    /* Data storage */

    cob_unifunc = null;

    /* PROGRAM-ID : 152B */
    b_RETURN_CODE = new CobolDataStorage(4);	/* RETURN-CODE */
    b_INP = new CobolDataStorage(10);	/* INP */
    b_A = new CobolDataStorage(1);	/* A */
    b_B = new CobolDataStorage(1);	/* B */
    b_N = new CobolDataStorage(1);	/* N */
    b_I = new CobolDataStorage(2);	/* I */
    b_OUT = new CobolDataStorage(10);	/* OUT */

    /* End of data storage */


    initAttr();

    /* Fields */

    /* PROGRAM-ID : 152B */
    f_INP	= CobolFieldFactory.makeCobolField(10, b_INP, a_1_Alphanumeric);	/* INP */
    f_A	= CobolFieldFactory.makeCobolField(1, b_A, a_2_NumericDisplay_Digits1_Scale0);	/* A */
    f_B	= CobolFieldFactory.makeCobolField(1, b_B, a_2_NumericDisplay_Digits1_Scale0);	/* B */
    f_I	= CobolFieldFactory.makeCobolField(2, b_I, a_3_NumericDisplay_Digits2_Scale0);	/* I */

    /* End of fields */


    /* Constants */

    c_1	= CobolFieldFactory.makeCobolField(str_1, a_1_Alphanumeric);

  }

  private void initAttr() {
    /* Attributes */

    a_1_Alphanumeric = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_ALPHANUMERIC,
      /* digits= */ 0,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_2_NumericDisplay_Digits1_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 1,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_3_NumericDisplay_Digits2_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 2,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);

  }

  /* Data storage */

  /* PROGRAM-ID : 152B */
  public CobolDataStorage b_RETURN_CODE;	/* RETURN-CODE */
  private CobolDataStorage b_INP;	/* INP */
  private CobolDataStorage b_A;	/* A */
  private CobolDataStorage b_B;	/* B */
  private CobolDataStorage b_N;	/* N */
  private CobolDataStorage b_I;	/* I */
  private CobolDataStorage b_OUT;	/* OUT */

  /* End of data storage */


  /* Fields */

  /* PROGRAM-ID : 152B */
  private AbstractCobolField f_INP;	/* INP */
  private AbstractCobolField f_A;	/* A */
  private AbstractCobolField f_B;	/* B */
  private AbstractCobolField f_I;	/* I */

  /* End of fields */


  private static AbstractCobolField f_native;

  /* Constants */

  private AbstractCobolField c_1;

  /* Attributes */

  private CobolFieldAttribute a_3_NumericDisplay_Digits2_Scale0;
  private CobolFieldAttribute a_2_NumericDisplay_Digits1_Scale0;
  private CobolFieldAttribute a_1_Alphanumeric;



  /* String literals */
  public static final byte[] str_1 = CobolUtil.stringToBytes(" ");
  public static final byte[] str_0_01 = CobolUtil.stringToBytes("01");

  /* Sections and Labels */
  private final static int l__3152B = 1;
  private final static int l_MAIN = 2;
  private final static int l_MAIN_SECTION__DEFAULT_PARAGRAPH = 3;
  private final static int l_Default_Error_Handler = 4;

}
