/* Generated by opensource COBOL 4J 1.1.16 */
import java.io.UnsupportedEncodingException;
import jp.osscons.opensourcecobol.libcobj.*;
import jp.osscons.opensourcecobol.libcobj.common.*;
import jp.osscons.opensourcecobol.libcobj.data.*;
import jp.osscons.opensourcecobol.libcobj.exceptions.*;
import jp.osscons.opensourcecobol.libcobj.termio.*;
import jp.osscons.opensourcecobol.libcobj.call.*;
import jp.osscons.opensourcecobol.libcobj.file.*;
import jp.osscons.opensourcecobol.libcobj.ui.*;
import java.util.Optional;

public class ABC_105_C implements CobolRunnable {

  private boolean initialized = false;
  private CobolModule module;
  private int entry;

  private CobolRunnable cob_unifunc;


  @Override
  public int run(CobolDataStorage... argStorages) {
    return ABC_105_C_(0, argStorages);
  }

  @Override
  public void cancel() {
    ABC_105_C_(-1);
  }

  @Override
  public boolean isActive() {
    return false;
  }

  public CobolResultSet execute () {
    int returnCode = run_module(0);
    return new CobolResultSet(returnCode);
  }

  public int ABC_105_C_ (int entry, CobolDataStorage ...argStorages) {
    this.entry = entry;
    return this.run_module(entry);
  }

  int run_module (int entry) {
    this.module = new CobolModule(null, null, null, null, 0, '.', '$', ',', 1, 1, 1, 0, null );

    /* Start of function code */

    /* CANCEL callback handling */
    if (entry < 0) {
    	if (!this.initialized) {
    		CobolDecimal.cobInitNumeric();
    		return 0;
    	}
    	d0.clear();
    	d0.setScale(0);
    	d1.clear();
    	d1.setScale(0);
    	this.initialized = false;
    	return 0;
    }

    /* Push module stack */
    CobolModule.push (module);
    CobolResolve.pushCallStackList ("ABC_105_C");

    /* Initialize program */
    if (!this.initialized) {
      module.setProgramId("ABC_105_C");

      /* Initialize decimal numbers */
      d0.decimalInit();
      d1.decimalInit();

      b_RETURN_CODE.set((int)0);
      b_N.fillBytes('0', 11);
      b_str.fillBytes(' ', 128);
      b_ans.fillBytes(' ', 128);
      b_R.setByte('0');
      b_p.fillBytes('0', 3);
      b_len.fillBytes('0', 3);
      b_i.fillBytes('0', 3);
      this.initialized = true;
    }
    /* PROCEDURE DIVISION */
    try{
      /* Entry dispatch */
      execEntry(l_ABC_105_C);

    } catch(CobolStopRunException e) {
      CobolStopRunException.stopRun();
      System.exit(e.getReturnCode());
    }
    /* Pop module stack */
    CobolResolve.popCallStackList();
    CobolModule.pop();

    /* Program return */
    return b_RETURN_CODE.intValue();
  }
  public CobolControl[] contList = {
    new CobolControl(0, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_ABC_105_C]);
      }
    },
    /* Entry ABC_105_C */
    new CobolControl(l_ABC_105_C, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN]);
      }
    },
    /* MAIN SECTION */
    new CobolControl(l_MAIN, CobolControl.LabelType.section) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION__DEFAULT_PARAGRAPH]);
      }
    },
    /* MAIN_SECTION__DEFAULT_PARAGRAPH */
    new CobolControl(l_MAIN_SECTION__DEFAULT_PARAGRAPH, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* /content/temp_cobol/ABC_105_C_fixed.cob:13: ACCEPT */
        {
          CobolTerminal.accept (f_N);
        }
        /* /content/temp_cobol/ABC_105_C_fixed.cob:15: MOVE */
        {
          b_p.setBytes (str_0_001, 3);
        }
        /* /content/temp_cobol/ABC_105_C_fixed.cob:17: PERFORM */
        for (;;)
        {
          if (((long)b_N.cmpLongSignNumdisp (11, 0) == 0L))
            break;
          {
            /* /content/temp_cobol/ABC_105_C_fixed.cob:18: IF */
            {
              if (((long)CobolIntrinsic.funcMod (f_N, c_1_2).cmpInteger (1) == 0L))
                {
                  /* /content/temp_cobol/ABC_105_C_fixed.cob:19: SUBTRACT */
                  {
                    f_N.sub (c_2_1, 4);
                  }
                  /* /content/temp_cobol/ABC_105_C_fixed.cob:20: STRING */
                  {
                    CobolString.stringInit (f_str, f_p);
                    CobolString.stringDelimited (0);
                    CobolString.stringAppend (c_3_1);
                    CobolString.stringFinish ();
                  }
                }
              else
                {
                  /* /content/temp_cobol/ABC_105_C_fixed.cob:25: STRING */
                  {
                    CobolString.stringInit (f_str, f_p);
                    CobolString.stringDelimited (0);
                    CobolString.stringAppend (CobolConstant.zero);
                    CobolString.stringFinish ();
                  }
                }
            }
            /* /content/temp_cobol/ABC_105_C_fixed.cob:30: DIVIDE */
            {
              {
                {
                  d0.set (-2);
                  d1.setField (f_N);
                  d1.div (d0);
                  d1.getField (f_N, 4);
                }
              }
            }
          }
        }
        /* /content/temp_cobol/ABC_105_C_fixed.cob:33: COMPUTE */
        {
          {
            {
              d0.setField (CobolIntrinsic.funcStoredCharLength (f_str));
              d0.getField (f_len, 4);
            }
          }
        }
        /* /content/temp_cobol/ABC_105_C_fixed.cob:35: MOVE */
        {
          b_p.setBytes (str_1_001, 3);
        }
        /* /content/temp_cobol/ABC_105_C_fixed.cob:37: PERFORM */
        b_i.setBytes (b_len, 3);
        for(;;f_i.addInt (-1))
        {
          if (((long)b_i.cmpNumdisp (3, 0) <= 0L))
            break;
          {
            /* /content/temp_cobol/ABC_105_C_fixed.cob:38: STRING */
            {
              CobolString.stringInit (f_ans, f_p);
              CobolString.stringDelimited (0);
              CobolString.stringAppend (CobolFieldFactory.makeCobolField(1, b_str.getSubDataStorage((b_i.getNumdisp(3) - 1)), a_2_Alphanumeric));
              CobolString.stringFinish ();
            }
          }
        }
        /* /content/temp_cobol/ABC_105_C_fixed.cob:44: IF */
        {
          if (((long)CobolConstant.zero.cmpInteger (b_len.getNumdisp(3)) == 0L))
            {
              /* /content/temp_cobol/ABC_105_C_fixed.cob:45: DISPLAY */
              {
                CobolTerminal.display (0, 1, 1, CobolConstant.zero);
              }
            }
          else
            {
              /* /content/temp_cobol/ABC_105_C_fixed.cob:47: DISPLAY */
              {
                CobolTerminal.display (0, 1, 1, CobolFieldFactory.makeCobolField(b_len.getNumdisp(3), b_ans.getSubDataStorage(0), a_2_Alphanumeric));
              }
              /* /content/temp_cobol/ABC_105_C_fixed.cob:48: STOP */
              {
                CobolStopRunException.throwException (b_RETURN_CODE.intValue());
              }
            }
        }
        return Optional.of(CobolControl.pure());
      }
    },
    CobolControl.pure()
  };
  public void execEntry(int start) throws CobolRuntimeException, CobolStopRunException {
    Optional<CobolControl> nextLabel = Optional.of(contList[start]);
    while(nextLabel.isPresent()) {
      CobolControl section = nextLabel.get();
      nextLabel = section.run();
    }
  }

  public static void main(String[] args)
  {
    CobolUtil.cob_init(args, false);
    CobolDecimal.cobInitNumeric();
    new ABC_105_C().ABC_105_C_(0);
    CobolStopRunException.stopRun();
  }

  public ABC_105_C()
  {
    init();
  }

  public void init() 
  {
    /* Decimal structures */

    d0 = new CobolDecimal();
    d1 = new CobolDecimal();

    /* Data storage */

    cob_unifunc = null;

    /* PROGRAM-ID : ABC_105_C */
    b_RETURN_CODE = new CobolDataStorage(4);	/* RETURN-CODE */
    b_N = new CobolDataStorage(11);	/* N */
    b_str = new CobolDataStorage(128);	/* str */
    b_ans = new CobolDataStorage(128);	/* ans */
    b_R = new CobolDataStorage(1);	/* R */
    b_p = new CobolDataStorage(3);	/* p */
    b_len = new CobolDataStorage(3);	/* len */
    b_i = new CobolDataStorage(3);	/* i */

    /* End of data storage */


    initAttr();

    /* Fields */

    /* PROGRAM-ID : ABC_105_C */
    f_N	= CobolFieldFactory.makeCobolField(11, b_N, a_1_NumericDisplay_Digits11_Scale0_HaveSign);	/* N */
    f_str	= CobolFieldFactory.makeCobolField(128, b_str, a_2_Alphanumeric);	/* str */
    f_ans	= CobolFieldFactory.makeCobolField(128, b_ans, a_2_Alphanumeric);	/* ans */
    f_p	= CobolFieldFactory.makeCobolField(3, b_p, a_3_NumericDisplay_Digits3_Scale0);	/* p */
    f_len	= CobolFieldFactory.makeCobolField(3, b_len, a_3_NumericDisplay_Digits3_Scale0);	/* len */
    f_i	= CobolFieldFactory.makeCobolField(3, b_i, a_3_NumericDisplay_Digits3_Scale0);	/* i */

    /* End of fields */


    /* Constants */

    c_1_2	= CobolFieldFactory.makeCobolField(1, "2", a_4_NumericDisplay_Digits1_Scale0);
    c_2_1	= CobolFieldFactory.makeCobolField(1, "1", a_4_NumericDisplay_Digits1_Scale0);
    c_3_1	= CobolFieldFactory.makeCobolField(str_2_1, a_2_Alphanumeric);

  }

  private void initAttr() {
    /* Attributes */

    a_1_NumericDisplay_Digits11_Scale0_HaveSign = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 11,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_HAVE_SIGN,
      /* pic= */ null);
    a_2_Alphanumeric = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_ALPHANUMERIC,
      /* digits= */ 0,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_3_NumericDisplay_Digits3_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 3,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_4_NumericDisplay_Digits1_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 1,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);

  }

  /* Decimal structures */

  private CobolDecimal d0;
  private CobolDecimal d1;

  /* Data storage */

  /* PROGRAM-ID : ABC_105_C */
  public CobolDataStorage b_RETURN_CODE;	/* RETURN-CODE */
  private CobolDataStorage b_N;	/* N */
  private CobolDataStorage b_str;	/* str */
  private CobolDataStorage b_ans;	/* ans */
  private CobolDataStorage b_R;	/* R */
  private CobolDataStorage b_p;	/* p */
  private CobolDataStorage b_len;	/* len */
  private CobolDataStorage b_i;	/* i */

  /* End of data storage */


  /* Fields */

  /* PROGRAM-ID : ABC_105_C */
  private AbstractCobolField f_N;	/* N */
  private AbstractCobolField f_str;	/* str */
  private AbstractCobolField f_ans;	/* ans */
  private AbstractCobolField f_p;	/* p */
  private AbstractCobolField f_len;	/* len */
  private AbstractCobolField f_i;	/* i */

  /* End of fields */


  private static AbstractCobolField f_native;

  /* Constants */

  private AbstractCobolField c_3_1;
  private AbstractCobolField c_2_1;
  private AbstractCobolField c_1_2;

  /* Attributes */

  private CobolFieldAttribute a_4_NumericDisplay_Digits1_Scale0;
  private CobolFieldAttribute a_3_NumericDisplay_Digits3_Scale0;
  private CobolFieldAttribute a_2_Alphanumeric;
  private CobolFieldAttribute a_1_NumericDisplay_Digits11_Scale0_HaveSign;



  /* String literals */
  public static final byte[] str_2_1 = CobolUtil.stringToBytes("1");
  public static final byte[] str_1_001 = CobolUtil.stringToBytes("001");
  public static final byte[] str_0_001 = CobolUtil.stringToBytes("001");

  /* Sections and Labels */
  private final static int l_ABC_105_C = 1;
  private final static int l_MAIN = 2;
  private final static int l_MAIN_SECTION__DEFAULT_PARAGRAPH = 3;
  private final static int l_Default_Error_Handler = 4;

}
