/* Generated by opensource COBOL 4J 1.1.16 */
import java.io.UnsupportedEncodingException;
import jp.osscons.opensourcecobol.libcobj.*;
import jp.osscons.opensourcecobol.libcobj.common.*;
import jp.osscons.opensourcecobol.libcobj.data.*;
import jp.osscons.opensourcecobol.libcobj.exceptions.*;
import jp.osscons.opensourcecobol.libcobj.termio.*;
import jp.osscons.opensourcecobol.libcobj.call.*;
import jp.osscons.opensourcecobol.libcobj.file.*;
import jp.osscons.opensourcecobol.libcobj.ui.*;
import java.util.Optional;

public class _3172A implements CobolRunnable {

  private boolean initialized = false;
  private CobolModule module;
  private int entry;

  private CobolRunnable cob_unifunc;


  @Override
  public int run(CobolDataStorage... argStorages) {
    return _3172A_(0, argStorages);
  }

  @Override
  public void cancel() {
    _3172A_(-1);
  }

  @Override
  public boolean isActive() {
    return false;
  }

  public CobolResultSet execute () {
    int returnCode = run_module(0);
    return new CobolResultSet(returnCode);
  }

  public int _3172A_ (int entry, CobolDataStorage ...argStorages) {
    this.entry = entry;
    return this.run_module(entry);
  }

  int run_module (int entry) {
    this.module = new CobolModule(null, null, null, null, 0, '.', '$', ',', 1, 1, 1, 0, null );

    /* Start of function code */

    /* CANCEL callback handling */
    if (entry < 0) {
    	if (!this.initialized) {
    		CobolDecimal.cobInitNumeric();
    		return 0;
    	}
    	d0.clear();
    	d0.setScale(0);
    	d1.clear();
    	d1.setScale(0);
    	d2.clear();
    	d2.setScale(0);
    	d3.clear();
    	d3.setScale(0);
    	this.initialized = false;
    	return 0;
    }

    /* Push module stack */
    CobolModule.push (module);
    CobolResolve.pushCallStackList ("_3172A");

    /* Initialize program */
    if (!this.initialized) {
      module.setProgramId("_3172A");

      /* Initialize decimal numbers */
      d0.decimalInit();
      d1.decimalInit();
      d2.decimalInit();
      d3.decimalInit();

      b_RETURN_CODE.set((int)0);
      b_A.fillBytes('0', 2);
      f_OUT.moveFrom (CobolConstant.zero);
      this.initialized = true;
    }
    /* PROCEDURE DIVISION */
    try{
      /* Entry dispatch */
      execEntry(l__3172A);

    } catch(CobolStopRunException e) {
      CobolStopRunException.stopRun();
      System.exit(e.getReturnCode());
    }
    /* Pop module stack */
    CobolResolve.popCallStackList();
    CobolModule.pop();

    /* Program return */
    return b_RETURN_CODE.intValue();
  }
  public CobolControl[] contList = {
    new CobolControl(0, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l__3172A]);
      }
    },
    /* Entry 172A */
    new CobolControl(l__3172A, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN]);
      }
    },
    /* MAIN SECTION */
    new CobolControl(l_MAIN, CobolControl.LabelType.section) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION__DEFAULT_PARAGRAPH]);
      }
    },
    /* MAIN_SECTION__DEFAULT_PARAGRAPH */
    new CobolControl(l_MAIN_SECTION__DEFAULT_PARAGRAPH, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* /content/temp_cobol/172A_fixed.cob:9: ACCEPT */
        {
          CobolTerminal.accept (f_A);
        }
        /* /content/temp_cobol/172A_fixed.cob:11: COMPUTE */
        {
          {
            {
              d0.set (b_A.getNumdisp(2));
              d2.set (b_A.getNumdisp(2));
              d3.set (2);
              d2.pow (d3);
              d0.add (d2);
              d1.set (b_A.getNumdisp(2));
              d2.set (3);
              d1.pow (d2);
              d0.add (d1);
              d0.getField (f_OUT, 4);
            }
          }
        }
        /* /content/temp_cobol/172A_fixed.cob:12: DISPLAY */
        {
          CobolTerminal.display (0, 1, 1, CobolIntrinsic.funcTrim (0, 0, f_OUT, 0));
        }
        /* /content/temp_cobol/172A_fixed.cob:14: STOP */
        {
          CobolStopRunException.throwException (b_RETURN_CODE.intValue());
        }
        return Optional.of(CobolControl.pure());
      }
    },
    CobolControl.pure()
  };
  public void execEntry(int start) throws CobolRuntimeException, CobolStopRunException {
    Optional<CobolControl> nextLabel = Optional.of(contList[start]);
    while(nextLabel.isPresent()) {
      CobolControl section = nextLabel.get();
      nextLabel = section.run();
    }
  }

  public static void main(String[] args)
  {
    CobolUtil.cob_init(args, false);
    CobolDecimal.cobInitNumeric();
    new _3172A()._3172A_(0);
    CobolStopRunException.stopRun();
  }

  public _3172A()
  {
    init();
  }

  public void init() 
  {
    /* Decimal structures */

    d0 = new CobolDecimal();
    d1 = new CobolDecimal();
    d2 = new CobolDecimal();
    d3 = new CobolDecimal();

    /* Data storage */

    cob_unifunc = null;

    /* PROGRAM-ID : 172A */
    b_RETURN_CODE = new CobolDataStorage(4);	/* RETURN-CODE */
    b_A = new CobolDataStorage(2);	/* A */
    b_OUT = new CobolDataStorage(4);	/* OUT */

    /* End of data storage */


    initAttr();

    /* Fields */

    /* PROGRAM-ID : 172A */
    f_A	= CobolFieldFactory.makeCobolField(2, b_A, a_2_NumericDisplay_Digits2_Scale0);	/* A */
    f_OUT	= CobolFieldFactory.makeCobolField(4, b_OUT, a_1_NumericEdited_Digits4_Scale0);	/* OUT */

    /* End of fields */


  }

  private void initAttr() {
    /* Attributes */

    a_1_NumericEdited_Digits4_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_EDITED,
      /* digits= */ 4,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ "Z\003\000\000\0009\001\000\000\000");
    a_2_NumericDisplay_Digits2_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 2,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);

  }

  /* Decimal structures */

  private CobolDecimal d0;
  private CobolDecimal d1;
  private CobolDecimal d2;
  private CobolDecimal d3;

  /* Data storage */

  /* PROGRAM-ID : 172A */
  public CobolDataStorage b_RETURN_CODE;	/* RETURN-CODE */
  private CobolDataStorage b_A;	/* A */
  private CobolDataStorage b_OUT;	/* OUT */

  /* End of data storage */


  /* Fields */

  /* PROGRAM-ID : 172A */
  private AbstractCobolField f_A;	/* A */
  private AbstractCobolField f_OUT;	/* OUT */

  /* End of fields */


  private static AbstractCobolField f_native;

  /* Attributes */

  private CobolFieldAttribute a_2_NumericDisplay_Digits2_Scale0;
  private CobolFieldAttribute a_1_NumericEdited_Digits4_Scale0;




  /* Sections and Labels */
  private final static int l__3172A = 1;
  private final static int l_MAIN = 2;
  private final static int l_MAIN_SECTION__DEFAULT_PARAGRAPH = 3;
  private final static int l_Default_Error_Handler = 4;

}
