/* Generated by opensource COBOL 4J 1.1.16 */
import java.io.UnsupportedEncodingException;
import jp.osscons.opensourcecobol.libcobj.*;
import jp.osscons.opensourcecobol.libcobj.common.*;
import jp.osscons.opensourcecobol.libcobj.data.*;
import jp.osscons.opensourcecobol.libcobj.exceptions.*;
import jp.osscons.opensourcecobol.libcobj.termio.*;
import jp.osscons.opensourcecobol.libcobj.call.*;
import jp.osscons.opensourcecobol.libcobj.file.*;
import jp.osscons.opensourcecobol.libcobj.ui.*;
import java.util.Optional;

public class ABC_060_B implements CobolRunnable {

  private boolean initialized = false;
  private CobolModule module;
  private int entry;

  private CobolRunnable cob_unifunc;


  @Override
  public int run(CobolDataStorage... argStorages) {
    return ABC_060_B_(0, argStorages);
  }

  @Override
  public void cancel() {
    ABC_060_B_(-1);
  }

  @Override
  public boolean isActive() {
    return false;
  }

  public CobolResultSet execute () {
    int returnCode = run_module(0);
    return new CobolResultSet(returnCode);
  }

  public int ABC_060_B_ (int entry, CobolDataStorage ...argStorages) {
    this.entry = entry;
    return this.run_module(entry);
  }

  int run_module (int entry) {
    this.module = new CobolModule(null, null, null, null, 0, '.', '$', ',', 1, 1, 1, 0, null );

    /* Start of function code */

    /* CANCEL callback handling */
    if (entry < 0) {
    	if (!this.initialized) {
    		CobolDecimal.cobInitNumeric();
    		return 0;
    	}
    	d0.clear();
    	d0.setScale(0);
    	d1.clear();
    	d1.setScale(0);
    	d2.clear();
    	d2.setScale(0);
    	this.initialized = false;
    	return 0;
    }

    /* Push module stack */
    CobolModule.push (module);
    CobolResolve.pushCallStackList ("ABC_060_B");

    /* Initialize program */
    if (!this.initialized) {
      module.setProgramId("ABC_060_B");

      /* Initialize decimal numbers */
      d0.decimalInit();
      d1.decimalInit();
      d2.decimalInit();

      b_RETURN_CODE.set((int)0);
      b_i.fillBytes('0', 5);
      b_INP.fillBytes(' ', 10);
      b_A.fillBytes('0', 3);
      b_B.fillBytes('0', 3);
      b_C.fillBytes('0', 2);
      b_num.fillBytes('0', 5);
      b_flg.setByte(48);
      b_pi.fillBytes('0', 5);
      this.initialized = true;
    }
    /* PROCEDURE DIVISION */
    try{
      /* Entry dispatch */
      execEntry(l_ABC_060_B);

    } catch(CobolStopRunException e) {
      CobolStopRunException.stopRun();
      System.exit(e.getReturnCode());
    }
    /* Pop module stack */
    CobolResolve.popCallStackList();
    CobolModule.pop();

    /* Program return */
    return b_RETURN_CODE.intValue();
  }
  public CobolControl[] contList = {
    new CobolControl(0, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_ABC_060_B]);
      }
    },
    /* Entry ABC_060_B */
    new CobolControl(l_ABC_060_B, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION]);
      }
    },
    /* MAIN SECTION */
    new CobolControl(l_MAIN_SECTION, CobolControl.LabelType.section) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION__MAIN]);
      }
    },
    /* MAIN */
    new CobolControl(l_MAIN_SECTION__MAIN, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* /content/temp_cobol/ABC_060_B_fixed.cob:16: ACCEPT */
        {
          CobolTerminal.accept (f_INP);
        }
        /* /content/temp_cobol/ABC_060_B_fixed.cob:18: UNSTRING */
        {
          CobolString.unstringInit (f_INP, 0, 1);
          CobolString.unstringDelimited (CobolConstant.space, 0);
          CobolString.unstringInto (f_A, 0, 0);
          CobolString.unstringInto (f_B, 0, 0);
          CobolString.unstringInto (f_C, 0, 0);
          CobolString.unstringFinish ();
        }
        /* /content/temp_cobol/ABC_060_B_fixed.cob:22: MOVE */
        {
          f_num.moveFrom (f_A);
        }
        /* /content/temp_cobol/ABC_060_B_fixed.cob:24: PERFORM */
        b_i.setBytes (str_0_00001, 5);
        for(;;f_i.addInt (1))
        {
          if (((long)          (new GetInt() {
            public int run() throws CobolStopRunException {
              d0.set (b_A.getNumdisp(3));
              d2.set (b_B.getNumdisp(3));
              d0.mul (d2);
              d1.set (b_num.getNumdisp(5));
              return 
              d0.compareTo (d1);
          }
        }).run() <  0L))
          break;
        {
          /* /content/temp_cobol/ABC_060_B_fixed.cob:25: IF */
          {
            if (((long)CobolIntrinsic.funcMod (f_num, f_B).cmpInteger (b_C.getNumdisp(2)) == 0L))
              {
                /* /content/temp_cobol/ABC_060_B_fixed.cob:26: MOVE */
                {
                  b_flg.setByte(49);
                }
                /* /content/temp_cobol/ABC_060_B_fixed.cob:27: EXIT */
                {
                  if(true) break;
                }
              }
            else
              {
                /* /content/temp_cobol/ABC_060_B_fixed.cob:29: ADD */
                {
                  {
                    {
                      d0.set (1);
                      d1.set (b_i.getNumdisp(5));
                      d0.add (d1);
                      d0.getField (f_pi, 4);
                    }
                  }
                }
                /* /content/temp_cobol/ABC_060_B_fixed.cob:30: MULTIPLY */
                {
                  {
                    {
                      d0.set (b_pi.getNumdisp(5));
                      d1.set (b_A.getNumdisp(3));
                      d0.mul (d1);
                      d0.getField (f_num, 4);
                    }
                  }
                }
              }
          }
        }
      }
      /* /content/temp_cobol/ABC_060_B_fixed.cob:34: IF */
      {
        if (((long)b_flg.cmpNumdisp (1, 1) == 0L))
          {
            /* /content/temp_cobol/ABC_060_B_fixed.cob:35: DISPLAY */
            {
              CobolTerminal.display (0, 1, 1, c_1_YES);
            }
          }
        else
          {
            /* /content/temp_cobol/ABC_060_B_fixed.cob:37: DISPLAY */
            {
              CobolTerminal.display (0, 1, 1, c_2_NO);
            }
          }
      }
      /* /content/temp_cobol/ABC_060_B_fixed.cob:40: STOP */
      {
        CobolStopRunException.throwException (b_RETURN_CODE.intValue());
      }
      return Optional.of(CobolControl.pure());
    }
  },
  CobolControl.pure()
};
public void execEntry(int start) throws CobolRuntimeException, CobolStopRunException {
  Optional<CobolControl> nextLabel = Optional.of(contList[start]);
  while(nextLabel.isPresent()) {
    CobolControl section = nextLabel.get();
    nextLabel = section.run();
  }
}

public static void main(String[] args)
{
  CobolUtil.cob_init(args, false);
  CobolDecimal.cobInitNumeric();
  new ABC_060_B().ABC_060_B_(0);
  CobolStopRunException.stopRun();
}

public ABC_060_B()
{
  init();
}

public void init() 
{
  /* Decimal structures */

  d0 = new CobolDecimal();
  d1 = new CobolDecimal();
  d2 = new CobolDecimal();

  /* Data storage */

  cob_unifunc = null;

  /* PROGRAM-ID : ABC_060_B */
  b_RETURN_CODE = new CobolDataStorage(4);	/* RETURN-CODE */
  b_i = new CobolDataStorage(5);	/* i */
  b_INP = new CobolDataStorage(10);	/* INP */
  b_A = new CobolDataStorage(3);	/* A */
  b_B = new CobolDataStorage(3);	/* B */
  b_C = new CobolDataStorage(2);	/* C */
  b_num = new CobolDataStorage(5);	/* num */
  b_flg = new CobolDataStorage(1);	/* flg */
  b_pi = new CobolDataStorage(5);	/* pi */

  /* End of data storage */


  initAttr();

  /* Fields */

  /* PROGRAM-ID : ABC_060_B */
  f_i	= CobolFieldFactory.makeCobolField(5, b_i, a_4_NumericDisplay_Digits5_Scale0);	/* i */
  f_INP	= CobolFieldFactory.makeCobolField(10, b_INP, a_1_Alphanumeric);	/* INP */
  f_A	= CobolFieldFactory.makeCobolField(3, b_A, a_2_NumericDisplay_Digits3_Scale0);	/* A */
  f_B	= CobolFieldFactory.makeCobolField(3, b_B, a_2_NumericDisplay_Digits3_Scale0);	/* B */
  f_C	= CobolFieldFactory.makeCobolField(2, b_C, a_3_NumericDisplay_Digits2_Scale0);	/* C */
  f_num	= CobolFieldFactory.makeCobolField(5, b_num, a_4_NumericDisplay_Digits5_Scale0);	/* num */
  f_pi	= CobolFieldFactory.makeCobolField(5, b_pi, a_4_NumericDisplay_Digits5_Scale0);	/* pi */

  /* End of fields */


  /* Constants */

  c_1_YES	= CobolFieldFactory.makeCobolField(str_1_YES, a_1_Alphanumeric);
  c_2_NO	= CobolFieldFactory.makeCobolField(str_2_NO, a_1_Alphanumeric);

}

private void initAttr() {
  /* Attributes */

  a_1_Alphanumeric = new CobolFieldAttribute(
    CobolFieldAttribute.COB_TYPE_ALPHANUMERIC,
    /* digits= */ 0,
    /* scale= */ 0,
    CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
    /* pic= */ null);
  a_2_NumericDisplay_Digits3_Scale0 = new CobolFieldAttribute(
    CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
    /* digits= */ 3,
    /* scale= */ 0,
    CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
    /* pic= */ null);
  a_3_NumericDisplay_Digits2_Scale0 = new CobolFieldAttribute(
    CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
    /* digits= */ 2,
    /* scale= */ 0,
    CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
    /* pic= */ null);
  a_4_NumericDisplay_Digits5_Scale0 = new CobolFieldAttribute(
    CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
    /* digits= */ 5,
    /* scale= */ 0,
    CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
    /* pic= */ null);

}

/* Decimal structures */

private CobolDecimal d0;
private CobolDecimal d1;
private CobolDecimal d2;

/* Data storage */

/* PROGRAM-ID : ABC_060_B */
public CobolDataStorage b_RETURN_CODE;	/* RETURN-CODE */
private CobolDataStorage b_i;	/* i */
private CobolDataStorage b_INP;	/* INP */
private CobolDataStorage b_A;	/* A */
private CobolDataStorage b_B;	/* B */
private CobolDataStorage b_C;	/* C */
private CobolDataStorage b_num;	/* num */
private CobolDataStorage b_flg;	/* flg */
private CobolDataStorage b_pi;	/* pi */

/* End of data storage */


/* Fields */

/* PROGRAM-ID : ABC_060_B */
private AbstractCobolField f_i;	/* i */
private AbstractCobolField f_INP;	/* INP */
private AbstractCobolField f_A;	/* A */
private AbstractCobolField f_B;	/* B */
private AbstractCobolField f_C;	/* C */
private AbstractCobolField f_num;	/* num */
private AbstractCobolField f_pi;	/* pi */

/* End of fields */


private static AbstractCobolField f_native;

/* Constants */

private AbstractCobolField c_2_NO;
private AbstractCobolField c_1_YES;

/* Attributes */

private CobolFieldAttribute a_4_NumericDisplay_Digits5_Scale0;
private CobolFieldAttribute a_3_NumericDisplay_Digits2_Scale0;
private CobolFieldAttribute a_2_NumericDisplay_Digits3_Scale0;
private CobolFieldAttribute a_1_Alphanumeric;



/* String literals */
public static final byte[] str_2_NO = CobolUtil.stringToBytes("NO");
public static final byte[] str_1_YES = CobolUtil.stringToBytes("YES");
public static final byte[] str_0_00001 = CobolUtil.stringToBytes("00001");

/* Sections and Labels */
private final static int l_ABC_060_B = 1;
private final static int l_MAIN_SECTION = 2;
private final static int l_MAIN_SECTION__MAIN = 3;
private final static int l_Default_Error_Handler = 4;

}
